### ISSUE TITLE
Crash in RasterBucket::drawRaster

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1001]
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/54281077

In headless tests:

```
[ RUN      ] Headless/HeadlessTest.render/71
- ["INFO", "General", -1, "test fixture text-size"]
./scripts/run_tests.sh: line 28: 13015 Segmentation fault      (core dumped) ${CMD} "$@"
The program crashed with exit code 139. We're now trying to output the core dump.
[New LWP 13015]
[New LWP 13022]
[New LWP 13039]
[New LWP 13023]
[New LWP 13042]
[New LWP 14229]
[New LWP 13038]
[New LWP 13024]
[New LWP 13021]
[New LWP 13043]
[New LWP 13044]
[New LWP 14228]
[New LWP 14230]
[New LWP 13037]
[New LWP 13040]
[New LWP 13041]
[New LWP 14231]
[New LWP 14227]
warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff3b7b8000
Core was generated by `build/linux/Release/test --gtest_filter=*'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002aee72673980 in llvm::SelectionDAG::getNode(unsigned int, llvm::DebugLoc, llvm::EVT, llvm::SDValue, llvm::SDValue, llvm::SDValue) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
Thread 18 (Thread 0x2aee746f9700 (LWP 14227)):
#0  0x00002aee5e8de6d9 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000064b5e7 in uv__epoll_wait (epfd=60, events=0x2aee746f5e00, nevents=1024, timeout=-1) at src/unix/linux-syscalls.c:282
#2  0x0000000000647f85 in uv__io_poll (loop=0x2e53f40, timeout=-1) at src/unix/linux-core.c:187
#3  0x0000000000630d0d in uv_run (loop=0x2e53f40, mode=UV_RUN_DEFAULT) at src/unix/core.c:317
#4  0x00002aee5e37fb10 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
Thread 17 (Thread 0x2aee7503f700 (LWP 14231)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0x26578a8, mutex=0x2657880) at src/unix/thread.c:322
#2  0x000000000059152b in uv_chan_receive ()
#3  0x0000000000591019 in uv__worker_thread_loop ()
#4  0x00000000006467c7 in uv__thread_start (ctx_v=0x320e980) at src/uv-common.c:322
#5  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
Thread 16 (Thread 0x2aee73d93700 (LWP 13041)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 15 (Thread 0x2aee73b92700 (LWP 13040)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 14 (Thread 0x2aee70602700 (LWP 13037)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 13 (Thread 0x2aee74c3d700 (LWP 14230)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0x26578a8, mutex=0x2657880) at src/unix/thread.c:322
#2  0x000000000059152b in uv_chan_receive ()
#3  0x0000000000591019 in uv__worker_thread_loop ()
#4  0x00000000006467c7 in uv__thread_start (ctx_v=0x2866de0) at src/uv-common.c:322
#5  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
Thread 12 (Thread 0x2aee74a3c700 (LWP 14228)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0x26578a8, mutex=0x2657880) at src/unix/thread.c:322
#2  0x000000000059152b in uv_chan_receive ()
#3  0x0000000000591019 in uv__worker_thread_loop ()
#4  0x00000000006467c7 in uv__thread_start (ctx_v=0x2b474d0) at src/uv-common.c:322
#5  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
Thread 11 (Thread 0x2aee74396700 (LWP 13044)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 10 (Thread 0x2aee74195700 (LWP 13043)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 9 (Thread 0x2aee64cd8700 (LWP 13021)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0xa5c338, mutex=0xa5c310) at src/unix/thread.c:322
#2  0x000000000064090f in worker (arg=0x0) at src/unix/threadpool.c:56
#3  0x00000000006467c7 in uv__thread_start (ctx_v=0x23d99c0) at src/uv-common.c:322
#4  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x0000000000000000 in ?? ()
Thread 8 (Thread 0x2aee70401700 (LWP 13024)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0xa5c338, mutex=0xa5c310) at src/unix/thread.c:322
#2  0x000000000064090f in worker (arg=0x0) at src/unix/threadpool.c:56
#3  0x00000000006467c7 in uv__thread_start (ctx_v=0x23dab60) at src/uv-common.c:322
#4  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x0000000000000000 in ?? ()
Thread 7 (Thread 0x2aee73790700 (LWP 13038)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 6 (Thread 0x2aee74e3e700 (LWP 14229)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0x26578a8, mutex=0x2657880) at src/unix/thread.c:322
#2  0x000000000059152b in uv_chan_receive ()
#3  0x0000000000591019 in uv__worker_thread_loop ()
#4  0x00000000006467c7 in uv__thread_start (ctx_v=0x344b5b0) at src/uv-common.c:322
#5  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
Thread 5 (Thread 0x2aee73f94700 (LWP 13042)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 4 (Thread 0x2aee70200700 (LWP 13023)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0xa5c338, mutex=0xa5c310) at src/unix/thread.c:322
#2  0x000000000064090f in worker (arg=0x0) at src/unix/threadpool.c:56
#3  0x00000000006467c7 in uv__thread_start (ctx_v=0x23d99c0) at src/uv-common.c:322
#4  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x0000000000000000 in ?? ()
Thread 3 (Thread 0x2aee73991700 (LWP 13039)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aee70676a43 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000000000 in ?? ()
Thread 2 (Thread 0x2aee64ed9700 (LWP 13022)):
#0  0x00002aee5d2cbd84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000000000063fd5d in uv_cond_wait (cond=0xa5c338, mutex=0xa5c310) at src/unix/thread.c:322
#2  0x000000000064090f in worker (arg=0x0) at src/unix/threadpool.c:56
#3  0x00000000006467c7 in uv__thread_start (ctx_v=0x23dab60) at src/uv-common.c:322
#4  0x00002aee5d2c7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00002aee5e8e24bd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x0000000000000000 in ?? ()
Thread 1 (Thread 0x2aee64ad5600 (LWP 13015)):
#0  0x00002aee72673980 in llvm::SelectionDAG::getNode(unsigned int, llvm::DebugLoc, llvm::EVT, llvm::SDValue, llvm::SDValue, llvm::SDValue) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#1  0x00002aee726af740 in llvm::SelectionDAGBuilder::visitInsertElement(llvm::User const&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#2  0x00002aee7269070d in llvm::SelectionDAGBuilder::visit(unsigned int, llvm::User const&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#3  0x00002aee726b8fe2 in llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#4  0x00002aee726c6c21 in llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::Instruction const>, llvm::ilist_iterator<llvm::Instruction const>, bool&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#5  0x00002aee726c7649 in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#6  0x00002aee726c8e72 in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#7  0x00002aee7226ca69 in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#8  0x00002aee7226cbb1 in llvm::FunctionPassManagerImpl::run(llvm::Function&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#9  0x00002aee7226cc91 in llvm::FunctionPassManager::run(llvm::Function&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#10 0x00002aee72361ffe in llvm::JIT::jitTheFunction(llvm::Function*, llvm::MutexGuard const&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#11 0x00002aee7236239f in llvm::JIT::runJITOnFunctionUnlocked(llvm::Function*, llvm::MutexGuard const&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#12 0x00002aee72362594 in llvm::JIT::getPointerToFunction(llvm::Function*) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#13 0x00002aee722acc96 in llvm::ExecutionEngine::getPointerToGlobal(llvm::GlobalValue const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.0.so.1
#14 0x00002aee70683cbd in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#15 0x00002aee70684825 in llvmpipe_update_fs () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#16 0x00002aee70682410 in llvmpipe_update_derived () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#17 0x00002aee70675cc1 in ?? () from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#18 0x00002aee7143584b in st_draw_vbo () from /usr/lib/x86_64-linux-gnu/dri/libgallium.so
#19 0x00002aee70d7f0d4 in ?? () from /usr/lib/x86_64-linux-gnu/dri/libdricore.so
#20 0x00000000005bab78 in mbgl::RasterBucket::drawRaster (this=<optimized out>, shader=..., vertices=..., array=...) at ../../src/mbgl/renderer/raster_bucket.cpp:24
#21 0x00000000005dcc02 in mbgl::Painter::renderRaster (this=<optimized out>, bucket=..., layer_desc=..., matrix=...) at ../../src/mbgl/renderer/painter_raster.cpp:29
#22 0x000000000059501a in mbgl::Painter::renderTileLayer (this=0x2f5b3b0, tile=..., layer_desc=..., matrix=...) at ../../src/mbgl/renderer/painter.cpp:369
#23 0x00000000005a0344 in mbgl::Source::render (this=<optimized out>, painter=..., layer_desc=...) at ../../src/mbgl/map/source.cpp:104
#24 0x000000000059423f in mbgl::Painter::renderLayers (this=0x2f5b3b0, group=...) at ../../src/mbgl/renderer/painter.cpp:284
Python Exception <type 'exceptions.IndexError'> list index out of range: 
#25 0x0000000000593e27 in mbgl::Painter::render (this=0x2f5b3b0, style=..., sources=std::set with 1 elements, state_=..., time=...) at ../../src/mbgl/renderer/painter.cpp:240
#26 0x0000000000552ae2 in render (this=0x7fff3b680360) at ../../src/mbgl/map/map.cpp:627
#27 mbgl::Map::run (this=0x7fff3b680360) at ../../src/mbgl/map/map.cpp:259
#28 0x00000000004222c2 in HeadlessTest_render_Test::TestBody (this=<optimized out>) at ../../test/headless/headless.cpp:153
#29 0x00000000006284d3 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#30 0x0000000000617fb1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#31 0x00000000005fde47 in testing::Test::Run() ()
#32 0x00000000005fec9c in testing::TestInfo::Run() ()
#33 0x00000000005ff4c5 in testing::TestCase::Run() ()
#34 0x000000000060754b in testing::internal::UnitTestImpl::RunAllTests() ()
#35 0x0000000000624a33 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#36 0x000000000061a6a1 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#37 0x00000000006071f7 in testing::UnitTest::Run() ()
#38 0x000000000041d88c in RUN_ALL_TESTS () at ../../deps/gtest/gtest/gtest.h:20058
#39 main (argc=1, argv=0x0) at ../../test/fixtures/main.cpp:5
```

**Comment by jfirebaugh** [comment]
Given the stack trace, my guess is this is a bug in llvm or mesa, not our code.

**Comment by jfirebaugh** [comment]
Nope, probably memory corruption in our code. Backed out some changes in 0c985c024b4db6c8063648d493830c67ebff50bc.
