### ISSUE TITLE
Fatal Exception: java.lang.Error: eglMakeCurrent() failed

### ISSUE THREAD

**Issue by notHide** [mapbox/mapbox-gl-native#10040]
I have a problem that causes a lot of users to crash, but I don't know what caused it, and I can't reproduce.
MapBox SDK Version: 4.2.2

```
Fatal Exception: java.lang.Error: eglMakeCurrent() failed
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:131)
       at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:1521)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:641)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:169)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2366)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
       at android.view.Choreographer.doCallbacks(Choreographer.java:735)
       at android.view.Choreographer.doFrame(Choreographer.java:667)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6577)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by fabian-guerra** [comment]
Hi @notHide. Thank you for using Mapbox. I am sorry to hear you have issues. Our current SDK version is [5.1.3](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v5.1.3) is it possible for you update your app with the latest version?

**Comment by notHide** [comment]
@fabian-guerra sry for that, may not be able to upgrade in a short time, there are other ways?

**Comment by tobrun** [comment]
Closing as the reported issue is with 4.2.2, please update you app to a newer version. Happy to look into any crashes/issues you have with that version
