### ISSUE TITLE
[Android][ANR] when adding multiple Annotations in 5.2.0-beta.1

### ISSUE THREAD

**Issue by schachi5000** [mapbox/mapbox-gl-native#10207]
Hi there,
 
I switch from 5.1.3 to the 5.2.0-beta.1 and experiencing a lot of ANRs when adding Annotations to the map. Sadly this happens very randomly, which maybe points to some form of deadlock.

Heres a stacktrace where the application starts to hang:

	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:460)
	at com.mapbox.mapboxsdk.maps.MarkerContainer.obtainViewsIn(MarkerContainer.java:178)
	at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(AnnotationManager.java:218)
	at com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(MapboxMap.java:1278)
	at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:485)
	at com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(MarkerViewManager.java:471)
	at com.mapbox.mapboxsdk.maps.AnnotationManager.update(AnnotationManager.java:91)
	at com.mapbox.mapboxsdk.maps.MapboxMap.onUpdateRegionChange(MapboxMap.java:192)
	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:939)
	at com.mapbox.mapboxsdk.maps.MapView.onMapChange(MapView.java:527)
	at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:826)
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddPolylines(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.addPolyline(NativeMapView.java:393)
	at com.mapbox.mapboxsdk.maps.PolylineContainer.addBy(PolylineContainer.java:31)
	at com.mapbox.mapboxsdk.maps.AnnotationManager.addPolyline(AnnotationManager.java:260)
	at com.mapbox.mapboxsdk.maps.MapboxMap.addPolyline(MapboxMap.java:1316)

**Comment by tobrun** [comment]
@schachi5000 
could you elaborate on the amount of annoations you are adding? 
and what kind of annotations?

**Comment by schachi5000** [comment]
Roughly 10 annotations at any given time (polylines and polygons).
About every second half of them are being updated (removed and replaced with new ones).
The ANR only seems to happen while the camera is being moved, either manually or programmatically.

All calls are being made off the Main thread.

**Comment by tobrun** [comment]
@schachi5000 all invocations on MapboxMap should occur from the main thread (this is both covered in the javadoc as with the `@UiThread` annotation on the class). I will look into reproducing your issue though a possible cult print could be doing the calls from a different thread.

**Comment by schachi5000** [comment]
Sorry...my bad. Of course, all calls are being made from the UI thread.

**Comment by tobrun** [comment]
@schachi5000 no problem! just trying to figure out what is going wrong for you.

I have been trying to reproduce this by adding a random point to 6 polyline every 500ms:

![ezgif com-video-to-gif 46](https://user-images.githubusercontent.com/2151639/31716918-386363b8-b40a-11e7-9d66-b69fc76c3ffd.gif)

As seen above, this isn't resulting in a deadlock as you mentioned. Would you be able provide a minimal reproducible testcase so we can get to the bottom of this issue? Thank you.

**Comment by schachi5000** [comment]
@tobrun Thanks for getting back so quickly. I will try to build a test case app to reproduce the ANR.

**Comment by lilykaiser** [comment]
Was this bug resolved? Are we still waiting for more info?

**Comment by schachi5000** [comment]
The problem was solved with the newest MapBox version. Didn't have to change anything on my end 👍

**Comment by rm3dbeckers** [comment]
I am experiencing the same problem on version v5.3.0.
When I add a a few Polylines (in my case it's roughly 50-100 Polylines) and when I enter the MapView activity I get the following stacktrace, when I pause the execution after nothing seems to happen:

"main@7587" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(NativeMapView.java:-1)
	  at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:471)
	  at com.mapbox.mapboxsdk.maps.MarkerContainer.obtainViewsIn(MarkerContainer.java:171)
	  at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(AnnotationManager.java:208)
	  at com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(MapboxMap.java:1289)
	  at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:485)
	  at com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(MarkerViewManager.java:471)
	  at com.mapbox.mapboxsdk.maps.AnnotationManager.update(AnnotationManager.java:90)
	  at com.mapbox.mapboxsdk.maps.MapboxMap.onUpdateRegionChange(MapboxMap.java:192)
	  at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1056)
	  at com.mapbox.mapboxsdk.maps.MapView.onMapChange(MapView.java:588)
	  at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:862)
	  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeJumpTo(NativeMapView.java:-1)
	  at com.mapbox.mapboxsdk.maps.NativeMapView.jumpTo(NativeMapView.java:593)
	  at com.mapbox.mapboxsdk.maps.Transform.moveCamera(Transform.java:108)
	  at com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:715)
	  at com.mapbox.mapboxsdk.maps.MapboxMap.setCameraPosition(MapboxMap.java:692)

Seems to be exactly the same problem.
