### ISSUE TITLE
[android crash] Clear map causes app to crash

### ISSUE THREAD

**Issue by joaopedro1520** [mapbox/mapbox-gl-native#10386]
Hello, I'm using the new plugin for cluster and also the latest beta version, when performing a map clear to update the data on map it causes the crash below on the 5.2.0 betas, however in the 5.1.x versions that doesn't happen but the clusters don't have the correct behaviour.

Thanks

`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.mapbox.mapboxsdk.maps.IconManager.iconCleanup(IconManager.java:146)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.removeAnnotation(AnnotationManager.java:122)
       at com.mapbox.mapboxsdk.maps.MapboxMap.removeAnnotation(MapboxMap.java:1428)
       at com.mapbox.mapboxsdk.annotations.Annotation.remove(Annotation.java:53)
       at com.mapbox.mapboxsdk.plugins.cluster.MarkerManager$Collection.remove(MarkerManager.java:122)
       at com.mapbox.mapboxsdk.plugins.cluster.MarkerManager.remove(MarkerManager.java:99)
       at com.mapbox.mapboxsdk.plugins.cluster.clustering.view.DefaultClusterRenderer$MarkerModifier.removeMarker(DefaultClusterRenderer.java:650)
       at com.mapbox.mapboxsdk.plugins.cluster.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:633)
       at com.mapbox.mapboxsdk.plugins.cluster.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:608)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Platform:*Android*
**Mapbox SDK version:*5.2.0 - beta*

### Steps to trigger behavior

 1. Add clusters
 2.Clear map to re add new map info
 3.App crash

**Comment by tobrun** [comment]
done with #10388
