### ISSUE TITLE
[android] MapView crash resuming Activity

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-gl-native#10417]
**Platform:** Android 6.0.1 API 23 - Motorola Moto G Play
**Mapbox SDK version:** `5.2.0-beta4`

Got this crash when resuming an `Activity` with a `MapView` in the navigation test app.  Have not been able to reproduce more than once. 

```
E/FileSource: Failed to read the storage key:    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference  at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:71)
   at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:50)
   at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:364)
   at com.mapbox.services.android.navigation.testapp.activity.navigationui.NavigationViewActivity.onStart(NavigationViewActivity.java:101)  
   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1260)  
   at android.app.Activity.performStart(Activity.java:6276)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2392)  
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)  
   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)  
   at android.app.ActivityThread.main(ActivityThread.java:5459)  
   at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)  
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

cc @tobrun

**Comment by danesfeder** [comment]
This is a caught exception and the crash I was experiencing was from another issue in the Navigation SDK.
