### ISSUE TITLE
Crash on Android `SupportMapFragment` during early fragment destroy.

### ISSUE THREAD

**Issue by Diederikjh** [mapbox/mapbox-gl-native#10603]
**Platform:**
Android. Reproduced on Android 4.4 and 8.1
**Mapbox SDK version:**
5.2.0 (doesn't crash on 5.1.5)
### Steps to trigger behavior

 1. Add a `SupportMapFragment` to a layout, and commit transaction.
 2. Immediately add another transaction to add another instance of `SupportMapFragment` to the same view.

### Expected behavior
Map shows as expected.

### Actual behavior
Crashes with NullPointerException:

```
11-30 16:49:34.653 4928-4928/? E/AndroidRuntime: FATAL EXCEPTION: main
     Process: com.honeybeeapp.mapboxplay.mapboxplay, PID: 4928
     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.honeybeeapp.mapboxplay.mapboxplay/com.honeybeeapp.mapboxplay.mapboxplay.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.destroy()' on a null object reference
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
         at android.app.ActivityThread.-wrap11(Unknown Source:0)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
         at android.os.Handler.dispatchMessage(Handler.java:106)
         at android.os.Looper.loop(Looper.java:164)
         at android.app.ActivityThread.main(ActivityThread.java:6494)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.destroy()' on a null object reference
         at com.mapbox.mapboxsdk.maps.MapView.onDestroy(MapView.java:410)
         at com.mapbox.mapboxsdk.maps.SupportMapFragment.onDestroyView(SupportMapFragment.java:146)
         at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2497)
         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1503)
         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
         at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
         at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
         at android.app.Activity.performStart(Activity.java:7020)
         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
         at android.app.ActivityThread.-wrap11(Unknown Source:0) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
         at android.os.Handler.dispatchMessage(Handler.java:106) 
         at android.os.Looper.loop(Looper.java:164) 
         at android.app.ActivityThread.main(ActivityThread.java:6494) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

Code snippet to trigger crash:

```
final SupportMapFragment mapFragment1 = new SupportMapFragment();
getSupportFragmentManager().beginTransaction().replace(R.id.map_frame_layout, mapFragment1).commit();

// Contrived example of mapFragment1 being destroyed before surface view added.

final SupportMapFragment mapFragment2 = new SupportMapFragment();
getSupportFragmentManager().beginTransaction().replace(R.id.map_frame_layout, mapFragment2).commit();
```
This code is obviously contrived, but we have seen this behavior when the map fragment is part of a [ViewPager](https://developer.android.com/reference/android/support/v4/view/ViewPager.html).  

Scanning quickly through the Mapbox code, it seems that the native map view is only initialized when the surface view is created.  This doesn't seem to happen for the first fragment, as its view is probably never even created. Then when `onDestroy` is called on the fragment, the native map is still null.  As far as I can tell, the native map was initialized earlier in Mapbox 5.1.5

[Github project](https://github.com/Diederikjh/Mapboxplay) with example code.

**Comment by tobrun** [comment]
Fixed with https://github.com/mapbox/mapbox-gl-native/pull/10589, thank you for reaching out and reporting this issue.
