### ISSUE TITLE
Android - Crash in UiSettings.decode

### ISSUE THREAD

**Issue by snijsure** [mapbox/mapbox-gl-native#10636]
**Platform:**
Android
**Mapbox SDK version:**
5.2.0-beta4

### Steps to trigger behavior

I have not been able to reproduce following error, but we are getting lot of crashlytics reports with following stack trace.

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at com.mapbox.mapboxsdk.maps.UiSettings.decode(SourceFile:194)
       at com.mapbox.mapboxsdk.maps.UiSettings.restoreCompass(SourceFile:190)
       at com.mapbox.mapboxsdk.maps.UiSettings.onRestoreInstanceState(SourceFile:101)
       at com.mapbox.mapboxsdk.maps.MapboxMap.onRestoreInstanceState(SourceFile:148)
       at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(SourceFile:220)
       at com.mapbox.mapboxsdk.maps.MapView.access$800(SourceFile:69)
       at com.mapbox.mapboxsdk.maps.MapView$5$1.run(SourceFile:305)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6134)
       at java.lang.reflect.Method.invoke(Method.java)
```

**Comment by lilykaiser** [comment]
Can this issue be closed?
