### ISSUE TITLE
[Android] 5.3.0-SNAPSHOT (5.3.0-20171214.184944-28.aar) crash when load map

### ISSUE THREAD

**Issue by cmxyzx** [mapbox/mapbox-gl-native#10705]
**Platform:Android**
**Mapbox SDK version:5.3.0-SNAPSHOT (5.3.0-20171214.184944-28.aar)**

### Steps to trigger behavior

 1.Create new hello word project with android studio 3.0.1, android gradle build plugin 3.0.1, gradle 4.1, intergrate mapbox android sdk
```groovy
allprojects {
    repositories {
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
        google()
        jcenter()
    }
}
 implementation 'com.android.support:support-v4:26.1.0'
 implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.0-SNAPSHOT@aar'){
        exclude group: 'com.android.support'
    }

```
 2. Write demo code in activity
```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_fullscreen);

        Mapbox.getInstance(this,"REAL_TOKEN");

        FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
        SupportMapFragment mapFragment = SupportMapFragment.newInstance();
        transaction.add(R.id.fullscreen_content, mapFragment);
        transaction.commitAllowingStateLoss();
        mapFragment.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

            }
        });
    }
```
 3. App crash when start activity

### Expected behavior
not crash

### Actual behavior
crash log on art
```
 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.location.LocationSource>
 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.location.LocationSource>
 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.EmptyLocationSource>
 I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.EmptyLocationSource>
 D/AndroidRuntime: Shutting down VM
 E/AndroidRuntime: FATAL EXCEPTION: main
            Process: com.example.diduan.mapboxdemo, PID: 19578
            java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LocationEngineProvider;
                at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54)
                at com.example.diduan.mapboxdemo.FullscreenActivity.onCreate(FullscreenActivity.java:20)
                at android.app.Activity.performCreate(Activity.java:6357)
                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543)
                at android.app.ActivityThread.access$1000(ActivityThread.java:156)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5653)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.services.android.telemetry.location.LocationEngineProvider" on path: DexPathList[[zip file "/data/app/com.example.diduan.mapboxdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.diduan.mapboxdemo-1/lib/arm, /data/app/com.example.diduan.mapboxdemo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
                at com.example.diduan.mapboxdemo.FullscreenActivity.onCreate(FullscreenActivity.java:20) 
                at android.app.Activity.performCreate(Activity.java:6357) 
                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436) 
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
                at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
                at android.os.Handler.dispatchMessage(Handler.java:102) 
                at android.os.Looper.loop(Looper.java:157) 
                at android.app.ActivityThread.main(ActivityThread.java:5653) 
                at java.lang.reflect.Method.invoke(Native Method) 
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
            	Suppressed: java.lang.ClassNotFoundException: com.mapbox.services.android.telemetry.location.LocationEngineProvider
                at java.lang.Class.classForName(Native Method)
                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                		... 15 more
             Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
W/ActivityManager:   Force finishing activity com.example.diduan.mapboxdemo/.FullscreenActivity
```

crash log on dalvik
```
W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/mapbox/services/android/telemetry/location/LocationEngine;)
E/dalvikvm: Could not find class 'com.mapbox.services.android.telemetry.location.LocationEngineProvider', referenced from method com.mapbox.mapboxsdk.Mapbox.getInstance
W/dalvikvm: VFY: unable to resolve new-instance 1957 (Lcom/mapbox/services/android/telemetry/location/LocationEngineProvider;) in Lcom/mapbox/mapboxsdk/Mapbox;
W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/mapbox/services/android/telemetry/location/LocationEngine;)
W/dalvikvm: Unable to resolve superclass of Lcom/mapbox/mapboxsdk/location/LocationSource; (1955)
W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/location/LocationSource;' failed
W/dalvikvm: Unable to resolve superclass of Lcom/mapbox/mapboxsdk/EmptyLocationSource; (1691)
W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/EmptyLocationSource;' failed
E/dalvikvm: Could not find class 'com.mapbox.mapboxsdk.EmptyLocationSource', referenced from method com.mapbox.mapboxsdk.Mapbox.getLocationSource
W/dalvikvm: VFY: unable to resolve new-instance 1592 (Lcom/mapbox/mapboxsdk/EmptyLocationSource;) in Lcom/mapbox/mapboxsdk/Mapbox;
W/dalvikvm: Unable to resolve superclass of Lcom/mapbox/mapboxsdk/location/LocationSource; (1955)
W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/location/LocationSource;' failed
W/dalvikvm: Unable to resolve superclass of Lcom/mapbox/mapboxsdk/EmptyLocationSource; (1691)
W/dalvikvm: Link of class 'Lcom/mapbox/mapboxsdk/EmptyLocationSource;' failed
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41e16c50)
```

**Comment by Guardiola31337** [comment]
Hey @cmxyzx 👋 
Thanks for reaching out and report your problem.

The reason why you're getting that crash is that the Mapbox Maps SDK dependency is not properly set up.
You have two options here:

1. Remove the `@aar` suffix
```groovy
implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.0-SNAPSHOT') {
    exclude group: 'com.android.support'
}
```

2. Keeping the `@aar` suffix add `transitive = true`
```groovy
implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.0-SNAPSHOT@aar') {
    transitive = true
    exclude group: 'com.android.support'
}
```
The reason is that if you don't add `@aar` Gradle takes the transitive dependencies automatically but if you do, you need to tell explicitly `transitive = true` so that it knows that you're going to use them.
I recommend you to choose the first one, it's the standard solution and also you need to write less code 😉

Closing as answered, let us know if this doesn't work for you.

**Comment by cmxyzx** [comment]
Thanks for the help
```groovy
implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.0-SNAPSHOT') {
    exclude group: 'com.android.support'
}
```
works fine now
