### ISSUE TITLE
[Android] IllegalStateException: setRenderer has already been called for this instance

### ISSUE THREAD

**Issue by sictiru** [mapbox/mapbox-gl-native#10711]
Mapbox Android SDK version: 5.2.0 and 5.2.1.
Tested on Nexus 5X with 8.0 and 8.1
Issue not present in 5.1.5

Using FragmentStatePagerAdapter containing 7 fragments. Frag 2 and 7 contain MapView

`java.lang.IllegalStateException: setRenderer has already been called for this instance. 
at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1893)
at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:473)
at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:27)
at com.mapbox.mapboxsdk.maps.MapView$6.<init>(MapView.java:318)
at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:318)
at com.mapbox.mapboxsdk.maps.MapView.access$100(MapView.java:70)
at com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout(MapView.java:143)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2250)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by tobrun** [comment]
Thank you for reaching out and reporting this issue, I'm currently not able to reproduce with code as:

```java
/**
 * Test activity showcasing using the Android SDK ViewPager API to show MapFragments.
 */
public class ViewPagerActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_viewpager);

    ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
    if (viewPager != null) {
      MapFragmentAdapter adapter = new MapFragmentAdapter(getSupportFragmentManager());
      viewPager.setAdapter(adapter);
    }
  }

  static class MapFragmentAdapter extends FragmentPagerAdapter {

    private static int NUM_ITEMS = 6;

    MapFragmentAdapter(FragmentManager fragmentManager) {
      super(fragmentManager);
    }

    @Override
    public int getCount() {
      return NUM_ITEMS;
    }

    @Override
    public Fragment getItem(int position) {
      SupportMapFragment fragment = null;
      MapboxMapOptions options = new MapboxMapOptions();

      switch (position) {
        case 0:
          options.styleUrl(Style.MAPBOX_STREETS);
          options.camera(new CameraPosition.Builder().target(new LatLng(34.920526, 102.634774)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
        case 1:
          options.styleUrl(Style.DARK);
          options.camera(new CameraPosition.Builder().target(new LatLng(62.326440, 92.764913)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
        case 2:
          options.styleUrl(Style.SATELLITE);
          options.camera(new CameraPosition.Builder().target(new LatLng(-25.007786, 133.623852)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
        case 3:
          options.styleUrl(Style.TRAFFIC_NIGHT);
          options.camera(new CameraPosition.Builder().target(new LatLng(-25.007786, 133.623852)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
        case 4:
          options.styleUrl(Style.TRAFFIC_DAY);
          options.camera(new CameraPosition.Builder().target(new LatLng(-25.007786, 133.623852)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
        case 5:
          options.styleUrl(Style.OUTDOORS);
          options.camera(new CameraPosition.Builder().target(new LatLng(-25.007786, 133.623852)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
        case 6:
          options.styleUrl(Style.LIGHT);
          options.camera(new CameraPosition.Builder().target(new LatLng(-25.007786, 133.623852)).zoom(3).build());
          fragment = SupportMapFragment.newInstance(options);
          break;
      }
      return fragment;
    }

    @Override
    public CharSequence getPageTitle(int position) {
      return "Page " + position;
    }
  }
}


```

Would you be able look into the difference between this snippet and your code?

**Comment by sictiru** [comment]
I made a small test app with a similar situation as in my main project and couldn't reproduce the issue. I'll investigate further

**Comment by tobrun** [comment]
Root cause for this issue was identified and will ship as part of the 5.3.2 release.

**Comment by Nols1000** [comment]
We tried version 5.3.2 and for us the problem is not solved. We still get this error message:
```bash
java.lang.IllegalStateException: setRenderer has already been called for this instance.
    at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1873)
    at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:473)
    at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:27)
    at com.mapbox.mapboxsdk.maps.MapView$6.<init>(MapView.java:308)
    at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:308)
    at com.mapbox.mapboxsdk.maps.MapView.access$100(MapView.java:70)
    at com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout(MapView.java:143)
    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2142)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6469)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1000)
    at android.view.Choreographer.doCallbacks(Choreographer.java:796)
    at android.view.Choreographer.doFrame(Choreographer.java:716)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:986)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Our Application is just using 1 Activity and transition to different Fragments. First we transition to a Fragment that contains a MapView and go back to a Fragment without a MapView. If we then try to transition to a Fragment that contains a MapView the Exception occures.

Device: One Plus 5t
Android API: 25
Mapbox-API: 5.3.2

**Comment by LukasPaczos** [comment]
Thanks for reporting your issue @Nols1000. Unfortunately, I wasn't able to reproduce the crash following your pointers. If that is still an issue for you, could you open a new ticket and provide simplified code for reproduction?

**Comment by skienzl** [comment]
I saw the same crash in out fabric logs. Also for a One Plus device: 
Device: ONEPLUS A5010
Android API: 8.0.0
Mapbox-API: 5.3.2

**Comment by michaelbird1155** [comment]
I'm seeing the same crash as well. Was getting it a lot more frequently before 5.3.2 though. I am unable to reproduce on my own device but this is being reported by users.

Device: Samsung Galaxy S8
Android API: 8.0.0
Mapbox: 5.3.2

**Comment by LukasPaczos** [comment]
Hey @michaelbird1155, would you be able to retest using one of the more recent releases? It's not actionable for us to provide patches for such an old version.

You can follow below migration guides:
[v5.x -> v6.x](https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide)
[v6.x -> v7.x](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide)

**Comment by michaelbird1155** [comment]
I can do that. Thanks for the quick response.
