### ISSUE TITLE
Android Crash Within AndroidLocationEngine.java

### ISSUE THREAD

**Issue by simon-the-canadian** [mapbox/mapbox-gl-native#10785]
**Platform: Android**
**Mapbox SDK version: 5.2.1**

I am getting a crash on production on a Pixel C tablet running Android Oreo. 

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.busyllc.equipment/com.busyllc.equipment.app.dashboard.DashboardActivity}: java.lang.IllegalArgumentException: provider doesn't exist: gps
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by java.lang.IllegalArgumentException: provider doesn't exist: gps
       at android.os.Parcel.readException(Parcel.java:2008)
       at android.os.Parcel.readException(Parcel.java:1950)
       at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:691)
       at android.location.LocationManager.requestLocationUpdates(LocationManager.java:888)
       at android.location.LocationManager.requestLocationUpdates(LocationManager.java:470)
       at com.mapbox.services.android.telemetry.location.AndroidLocationEngine.requestLocationUpdates(AndroidLocationEngine.java:85)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.onConnected(MapboxTelemetry.java:492)
       at com.mapbox.services.android.telemetry.location.AndroidLocationEngine.activate(AndroidLocationEngine.java:56)
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:549)
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:525)
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.onStart(MyLocationView.java:419)
       at com.mapbox.mapboxsdk.maps.TrackingSettings.onStart(TrackingSettings.java:409)
       at com.mapbox.mapboxsdk.maps.MapboxMap.onStart(MapboxMap.java:114)
       at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:366)
       at com.busybusy.library.busy_maps.MapsFragment.onStart(MapsFragment.kt:119)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2369)
       at android.support.v4.app.l.a(FragmentManager.java:1458)
       at android.support.v4.app.l.b(FragmentManager.java:1740)
       at android.support.v4.app.l.a(FragmentManager.java:1809)
       at android.support.v4.app.l.c(FragmentManager.java:3217)
       at android.support.v4.app.l.p(FragmentManager.java:3176)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2375)
       at android.support.v4.app.l.a(FragmentManager.java:1458)
       at android.support.v4.app.l.b(FragmentManager.java:1740)
       at android.support.v4.app.l.a(FragmentManager.java:1809)
       at android.support.v4.app.l.c(FragmentManager.java:3217)
       at android.support.v4.app.l.p(FragmentManager.java:3176)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:16203)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at com.busyllc.equipment.app.dashboard.DashboardActivity.onStart(DashboardActivity.java:147)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
       at android.app.Activity.performStart(Activity.java:7019)
       at android.app.Activity.performRestart(Activity.java:7094)
       at android.app.Activity.performResume(Activity.java:7099)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tobrun** [comment]
cc @Guardiola31337

**Comment by electrostat** [comment]
@simon-the-canadian the Pixel C tablet does not have a gps unit. It looks like you are specifically requesting 'gps' as the provider for the AndroidLocationEngine. One thing you can do before setting the provider using 'setPriority', is to check for the gps hardware (via PackageManager [LINK](https://stackoverflow.com/questions/2584867/programmatically-find-device-support-gps-or-not)) and set priority to passive or wifi, if GPS is unavailable.

I'll add this to a list of things to look into automating or making more developer friendly in future releases.

**Comment by tobrun** [comment]
stale
