### ISSUE TITLE
Requested zoom higher than maxZoom: 15

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10816]
Steps to reproduce:
- open map with:
  - maxZoom = 14
  - camera zoom = 14
- add Polygon to map
- set maxZoom = 20
- double tap to zoom the map -> crash

```
01-02 16:59:54.207 27024-27078/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: GLThread 3756
Process: com.mapbox.mapboxsdk.testapp, PID: 27024
java.lang.Error: Requested zoom higher than maxZoom: 15
at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:90)
at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:55)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)                                                                                  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

Without the Polygon code, the interaction works as expected.

![ezgif com-video-to-gif 8](https://user-images.githubusercontent.com/2151639/34490191-5dd63452-efdf-11e7-8b4c-3d2edc5e3dca.gif)

**Comment by jfirebaugh** [comment]
Probably the same issue as #10177, and fixed by #10791.

**Comment by siavashabdoli** [comment]
why this is closed? is it fixed? I can't find milestone or pr related to this :)
