### ISSUE TITLE
CRASH: setRenderer has already been called for this instance.

### ISSUE THREAD

**Issue by okku** [mapbox/mapbox-gl-native#10935]
Platform: Android
Mapbox SDK version: 5.2.0-beta.5 to 5.3.0 of mapbox

### Steps to trigger behavior

This crash is top 1 for our app, about 1.5% of the users get this. This seems to started when we switched from 5.2.0-beta.3 to beta.5 and present in 5.3.0. We can't reproduce this. 

Stack trace:

```
Fatal Exception: java.lang.IllegalStateException: setRenderer has already been called for this instance.
       at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1878)
       at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:473)
       at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.(SourceFile)
       at com.mapbox.mapboxsdk.maps.MapView$6.(SourceFile)
       at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(SourceFile:318)
       at com.mapbox.mapboxsdk.maps.MapView.access$100(SourceFile:70)
       at com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout(SourceFile:143)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2107)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6325)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6111)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

Any clues?

**Comment by tobrun** [comment]
Thank you for reaching out @okku, we recently fixed this issue with https://github.com/mapbox/mapbox-gl-native/pull/10890. This crash occurs when you destroy/rotate the activity before the render surface was created. We are aiming to release a 5.3.2 version this week containing that fix!
