### ISSUE TITLE
[Android] IllegalStateException: setRenderer has already been called for this instance

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-gl-native#10997]
Hitta has been seeing this stacktrace in their crash stats using the navigation drop-in UI.  I have not been able to reproduce on my test devices and am unsure of any steps to reproduce.  

**Platform:** Android
**Mapbox SDK version:** 5.2.0-beta.5 to 5.3.0 

```
 Fatal Exception: java.lang.IllegalStateException: setRenderer has already been called for this instance.
           at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1878)
           at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:473)
           at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.(SourceFile)
           at com.mapbox.mapboxsdk.maps.MapView$6.(SourceFile)
           at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(SourceFile:318)
           at com.mapbox.mapboxsdk.maps.MapView.access$100(SourceFile:70)
           at com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout(SourceFile:143)
           at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2107)
           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6325)
           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
           at android.view.Choreographer.doCallbacks(Choreographer.java:683)
           at android.view.Choreographer.doFrame(Choreographer.java:619)
           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
           at android.os.Handler.handleCallback(Handler.java:751)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:154)
           at android.app.ActivityThread.main(ActivityThread.java:6111)
           at java.lang.reflect.Method.invoke(Method.java)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

cc @tobrun

**Comment by LukasPaczos** [comment]
@danesfeder might be fixed with https://github.com/mapbox/mapbox-gl-native/pull/10890. Will they be able to re-test this one with `5.3.2`?

Closing for now, feel free to reopen if still present on `5.3.2`.

**Comment by mf-mindcrewtech** [comment]
@LukasPaczos still crashing in 5.3.2

**Comment by LukasPaczos** [comment]
Continuing in https://github.com/mapbox/mapbox-gl-native/issues/11181.
