### ISSUE TITLE
Crash on galaxy note 8

### ISSUE THREAD

**Issue by asalliou** [mapbox/mapbox-gl-native#11089]
**Platform:** Android (Galaxy note 8)
**Mapbox SDK version:** 5.3.2

### Steps to trigger behavior

Unknown (log collected via Crashlytics)

### Actual behavior

Crash

### Log

`
Android: 7.1.1
Android Build: NMF26X.N950FXXU3BRA2
Manufacturer: samsung
Model: SM-N950F
Thread: GLThread 626-626
java.lang.Error: map::at:  key not found
	at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
	at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:90)
	at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:55)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)`

**Comment by tobrun** [comment]
Could you give an indication about the impact of this crash? Are you only seeing this on a galaxy note 8? Are you seeing this crash with the latest release 5.4.1?

**Comment by tobrun** [comment]
Let us know if you can reproduce this with the latest stable version 5.5.0. 
Closing as non-actionable for now.

**Comment by kingfisherphuoc** [comment]
I had the same issue with 5.5.0 SDK. I don't know why it's so randomly.

```
 FATAL EXCEPTION: GLThread 15483
                                                                  Process: com.map.goong.v2, PID: 28860
                                                                  java.lang.Error: unordered_map::at: key not found
                                                                      at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
                                                                      at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:90)
                                                                      at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:55)
                                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
                                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

**Comment by jfirebaugh** [comment]
→ #11788 (which has a C++ stack trace)
