### ISSUE TITLE
Crash in MapView.java:309: java.lang.IllegalStateException: setRenderer has already been called for this instance.

### ISSUE THREAD

**Issue by michaelfomin** [mapbox/mapbox-gl-native#11195]
Receiving this crash report

java.lang.IllegalStateException: setRenderer has already been called for this instance.
	at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1882)
	at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:482)
	at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:27)
	at com.mapbox.mapboxsdk.maps.MapView$6.<init>(MapView.java:309)
	at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:309)
	at com.mapbox.mapboxsdk.maps.MapView.access$100(MapView.java:70)
	at com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout(MapView.java:144)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:981)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2475)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Platform: Android 7.1.1**
**Mapbox SDK version: mapbox-android-sdk:5.4.0**

### Steps to trigger behavior

Unknown, this crash was reported by HockeyApp and the stack trace does not provide any clues to what exactly the map is rendering.

### Expected behavior
No crash

### Actual behavior
Crash

**Comment by michaelfomin** [comment]
Sorry guys, this looks like a duplicate.
I got no search results when searching "setRenderer has already been called for this instance"
But after creating the bug I tried just searching "setRenderer" and got hits

**Comment by michaelfomin** [comment]
Looks like a dup of #11181

**Comment by tobrun** [comment]
Thank you for reaching out and using our products, this should be fixed with https://github.com/mapbox/mapbox-gl-native/pull/11124 and fix is available in v5.4.1.
