### ISSUE TITLE
android.view.WindowManager$BadTokenException at com.mapbox.mapboxsdk.maps.AttributionDialogManager.showAttributionDialog(AttributionDialogManager.java:60)

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#11238]
Platform: Android
Mapbox SDK version: 5.3.3

### Steps to trigger behavior

 1. Unfortunately I did never (re)produce this error myself, but it showed up on 4 of 10 of the Pre-Launch Reports of my last apk.

The stack trace always looks like this:

FATAL EXCEPTION: ControllerMessenger
Process: de.realitymaps.dolomitisuperski, PID: 7413
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:683)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.app.Dialog.show(Dialog.java:322)
	at android.app.AlertDialog$Builder.show(AlertDialog.java:1112)
	at com.mapbox.mapboxsdk.maps.AttributionDialogManager.showAttributionDialog(AttributionDialogManager.java:60)
	at com.mapbox.mapboxsdk.maps.AttributionDialogManager.onClick(AttributionDialogManager.java:52)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:465)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:421)
	at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:235)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:140)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:123)
	at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at android.support.test.espresso.action.Tap.access$100(Tap.java:31)
	at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:47)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:136)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:355)
	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:242)
	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

In the end, it might be, that the test triggers an onClick event on a view belonging to an activity that no longer is shown (which sounds pretty wrong to me), but maybe there is something wrong/dangerous happening in the MapBox SDK as well.
Generally showing a dialog on Android is always a dangerous procedure as the developer has to make sure that, when calling show(), the app is still being visible. This is one of the things I hate most about Android. That shouldn't be the dev's responsibility (or at least it should offer the dev a showDontThrow() in the cases, where he/she doesn't care if the dialog could be shown successfully), but simply surrounding it with a try-catch should do the trick.

### Expected behavior
Don't crash or ignore this report because that scenario is not realistic.

### Actual behavior
Crashes.

**Comment by tobrun** [comment]
@rm3dbeckers thank you for reaching out, the mentioned version 3.5.1 is already pretty outdated. Would you be able to update to a more recent version 5.4.1 and retest? Closing as this is with an older version of the sdk.

**Comment by rm3dbeckers** [comment]
I am very, very sorry. I completely botched the SDK version number (apparently my memory completely betrayed me). The real SDK version is/was 5.3.3.

**Comment by rm3dbeckers** [comment]
Perfect. Thanks for the fix.
