### ISSUE TITLE
Offline downloading blocking return of mapboxMap object

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#11461]
Using the Map SDK 5.5.0 if you download a region, leave the activity and return to the same activity with the mapView, the OnMapReady callback gets held up by what I assume is an attempt to read the "file source".

```
03-15 14:29:11.505 5222-5222/com.mapbox.mapboxsdk.plugins.testapp E/FileSource: Failed to read the storage key: 
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
                                                                                    at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
                                                                                    at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
                                                                                    at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:349)
                                                                                    at com.mapbox.mapboxsdk.plugins.offline.ui.RegionSelectionFragment.onStart(RegionSelectionFragment.java:97)
                                                                                    at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3186)
                                                                                    at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:203)
                                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:582)
                                                                                    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
                                                                                    at android.app.Activity.performStart(Activity.java:7019)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                    at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
```

Eventually, the callback is invoked, a MapboxMap object is available but no map style is loaded (only the background). 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5652865/37485994-86c6f664-2863-11e8-8b86-d4fc2f2136fa.gif)

cc: @mapbox/maps-android

**Comment by LukasPaczos** [comment]
@cammace could you ensure that there is no other native stack trace before the one you posted? I've seen a situation when `NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference` was thrown just after a native crash.

**Comment by cammace** [comment]
Can confirm that i'm not seeing any native crashes, @tobrun mentioned this could be related to https://github.com/mapbox/mapbox-gl-native/issues/11147.

**Comment by dylan-chong** [comment]
Sorry to bug you all but is this bug still being worked on?

Also did anyone find any workarounds while this bug is still being fixed?

**Comment by neslihanturan** [comment]
We also get very similar error on another project which uses mapbox. Is it a bug that is caused from mapbox-android or do we misinterpret logs? If so, did you find a solution for this?

**Comment by tobrun** [comment]
OnMapReady invocation is linked to style loading which is blocked as the queue in filesource is filled up with offline resources that will be handled first. In https://github.com/mapbox/mapbox-gl-native/issues/12219 we have a solution outlined that decouples OnMapReady invocation from style loading.

**Comment by tobrun** [comment]
@neslihanturan @dylan-chong 
would you be able to retest with a more recent version? eg 6.3.0 (6.4.0 will be released later today) In gif below I'm downloading a large region on application start (clean install), while the map takes a couple seconds to load, it shows as expected:

![ezgif com-video-to-gif 29](https://user-images.githubusercontent.com/2151639/44159283-39900800-a0b7-11e8-814a-1b46b4df5fe7.gif)

**Comment by tobrun** [comment]
While in 6.4.0 this issue seems less apparant, it is still there. Fixing this issue at core level is ticketed in #12655. Closing this issue as the solution for this issue is outlined in #12655.
