### ISSUE TITLE
nativeQueryPointAnnotations crash

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11634]
User reported a random crash:

```
#0. Crashed: main
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:481)
       at com.mapbox.mapboxsdk.maps.MarkerContainer.obtainAllIn(MarkerContainer.java:102)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkersInRect(AnnotationManager.java:194)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerHitFromTouchArea(AnnotationManager.java:423)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:388)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:336)
       at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

--

Fatal Exception: java.lang.Error: The associated promise has been destructed prior to the associated state becoming ready.
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:481)
       at com.mapbox.mapboxsdk.maps.MarkerContainer.obtainAllIn(MarkerContainer.java:102)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkersInRect(AnnotationManager.java:194)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerHitFromTouchArea(AnnotationManager.java:423)
       at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:388)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:336)
       at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:341)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tobrun** [comment]
Not reproducible anymore
