### ISSUE TITLE
java.lang.Error: vector crash

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11633]
A user reported a random crash with the following output:

```
Fatal Exception: java.lang.Error: vector
       at com.mapbox.mapboxsdk.maps.renderer.MapRendererRunnable.run(MapRendererRunnable.java)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1471)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

**Comment by tobrun** [comment]
thanks for chiming in @mb12, I will follow you lead that this is a user bug since I haven't been able to reproduce myself. Closing for now.
