### ISSUE TITLE
TelemetryService crashing while handling onTaskRemoved()

### ISSUE THREAD

**Issue by masterjefferson** [mapbox/mapbox-gl-native#11673]
**Platform:**

So far, this issue seems to be affecting Samsung devices running Android 7.0. There may be other affected versions

**Mapbox SDK version:**

SDK: `6.0.0-beta.6`
Location Layer Plugin: `0.5.0-beta.2`

### Steps to trigger behavior

 1. Launch an activity with a map view.
 2. Ensure telemetry is enabled (i.e. attribution control)
 3. Close the app from recents screen. You should see a crash.

### Expected behavior

The app closes normally.

### Actual behavior

The app crashes with the following stack trace:
```
04-12 14:29:27.905 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.beartooth, PID: 27070
    java.lang.RuntimeException: Unable to start service com.mapbox.android.telemetry.TelemetryService@3e01558 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.beartooth/com.beartooth.presentation.launch.LaunchActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }: java.lang.IllegalArgumentException: Receiver not registered: com.mapbox.android.telemetry.AlarmReceiver@952556c
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3746)
        at android.app.ActivityThread.-wrap23(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6688)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.mapbox.android.telemetry.AlarmReceiver@952556c
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1047)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1359)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:651)
        at com.mapbox.android.telemetry.AlarmSchedulerFlusher.unregister(AlarmSchedulerFlusher.java:47)
        at com.mapbox.android.telemetry.MapboxTelemetry.stopAlarm(MapboxTelemetry.java:428)
        at com.mapbox.android.telemetry.MapboxTelemetry.unregisterTelemetry(MapboxTelemetry.java:422)
        at com.mapbox.android.telemetry.MapboxTelemetry.onTaskRemoved(MapboxTelemetry.java:108)
        at com.mapbox.android.telemetry.TelemetryService.onTaskRemoved(TelemetryService.java:71)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3731)
        at android.app.ActivityThread.-wrap23(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6688) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

**Comment by tobrun** [comment]
@masterjefferson thank you for reporting, could you retest this with 6.0.0-beta.7?

cc @electrostat @Guardiola31337 @zugaldia

**Comment by Guardiola31337** [comment]
Hey @masterjefferson 👋 Thanks for reaching out and report the crash.

We also noticed that weird crash in some Samsung devices and fixed it via https://github.com/mapbox/mapbox-events-android/pull/110

This is included in `6.0.0-beta.7` as @tobrun mentioned. Could you please retest this with the latest beta and report back if it's still an issue?

**Comment by masterjefferson** [comment]
Testing now. Just a heads up, I had to specify Java 8 compatibility in my `compileOptions` after switching to beta 7:
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by masterjefferson** [comment]
I'm now seeing a different crash, indicating the service is not registered in any manifest:
```
04-13 12:55:39.145 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.beartooth.bronco_beta, PID: 12110
    java.lang.RuntimeException: Unable to start service com.mapbox.android.telemetry.TelemetryService@a2e7e82 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.beartooth.bronco_beta/com.beartooth.bronco.presentation.launch.LaunchActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }: java.lang.IllegalArgumentException: Service not registered: com.mapbox.android.telemetry.MapboxTelemetry$3@b9d7735
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3746)
        at android.app.ActivityThread.-wrap23(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6688)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
     Caused by: java.lang.IllegalArgumentException: Service not registered: com.mapbox.android.telemetry.MapboxTelemetry$3@b9d7735
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1345)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1536)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:700)
        at com.mapbox.android.telemetry.MapboxTelemetry.unbindTelemetryService(MapboxTelemetry.java:434)
        at com.mapbox.android.telemetry.MapboxTelemetry.unregisterTelemetry(MapboxTelemetry.java:423)
        at com.mapbox.android.telemetry.MapboxTelemetry.onTaskRemoved(MapboxTelemetry.java:108)
        at com.mapbox.android.telemetry.TelemetryService.onTaskRemoved(TelemetryService.java:71)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3731)
        at android.app.ActivityThread.-wrap23(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6688) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

I tried declaring the service in our own manifest as `<service android:name="com.mapbox.android.telemetry.TelemetryService" />` , but saw no change.

This is being tested on a Samsung G930A (AT&T S7) running Android 7.0.

**Comment by masterjefferson** [comment]
This seems to be caused by the handling of `onTaskRemoved` specifically. 

Our app runs a foreground service that incorporates a 'close' button in its notification view. When pressed, our service sends out a broadcast that effectively finishes all activities, and then invokes `stopSelf()`. If the app is closed using this method there is no crash.

**Comment by masterjefferson** [comment]
We will work around this for now by disabling telemetry using:
`TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED)`

@tobrun @Guardiola31337 let me know if there is anything else I can do to assist.

**Comment by Guardiola31337** [comment]
Hey @masterjefferson 👋 mapbox/mapbox-events-android#117 landed and `mapbox-android-telemetry:4.0.0-SNAPSHOT` is available in Maven Central https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-telemetry/4.0.0-SNAPSHOT/ 

It'd be awesome if you could retest this as explained above https://github.com/mapbox/mapbox-gl-native/issues/11673#issuecomment-381534829 and report back if it's still an issue (hopefully not 🤞).

Thanks a lot!

**Comment by LukasPaczos** [comment]
Fix landed with https://github.com/mapbox/mapbox-gl-native/pull/11700. Please feel free to reopen if seen again.

**Comment by masterjefferson** [comment]
Great, will confirm later today. Thanks all!

**Comment by Guardiola31337** [comment]
@masterjefferson 
> Great, will confirm later today.

`mapboxsdk:mapbox-android-sdk:6.0.1` should do the trick. Thanks for 👀
