### ISSUE TITLE
Sometimes ANR when SSL handshake time out in Android 8.0 

### ISSUE THREAD

**Issue by xfans** [mapbox/mapbox-gl-native#11707]
Sometimes ANR when SSL handshake time out in Android 8.0 

**Platform:*android, HUAWEI mate10*
**Mapbox SDK version:*5.2.0*

### Steps

 1.Happend SSL handshake time out like [this](https://github.com/mapbox/mapbox-gl-native/issues/4090)
 2.open fragment (has Mapbox)
 3.Sometimes ANR

### LOG
Application Not Responding
                                                                                   Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
                                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeSetReachability(Native Method)
                                                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.setReachability(NativeMapView.java:541)
                                                                                       at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:216)
                                                                                       at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:70)
                                                                                       at com.mapbox.mapboxsdk.maps.MapView$5$1.run(MapView.java:304)
                                                                                       at android.os.Handler.handleCallback(Handler.java:808)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                       at android.os.Looper.loop(Looper.java:166)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AdditionalHandlerThread (state = RUNNABLE)
                                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                       at android.os.MessageQueue.next(MessageQueue.java:379)
                                                                                       at android.os.Looper.loop(Looper.java:144)
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AsyncTask #1 (state = TIMED_WAITING)
                                                                                       at java.lang.Object.wait(Native Method)
                                                                                       at java.lang.Thread.parkFor$(Thread.java:2161)
                                                                                       at sun.misc.Unsafe.park(Unsafe.java:358)
                                                                                       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
                                                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
                                                                                       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                       at java.lang.Thread.run(Thread.java:784)
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AsyncTask #2 (state = TIMED_WAITING)
                                                                                       at java.lang.Object.wait(Native Method) 
                                                                                       at java.lang.Thread.parkFor$(Thread.java:2161) 
                                                                                       at sun.misc.Unsafe.park(Unsafe.java:358) 
                                                                                       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 
                                                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 
                                                                                       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                       at java.lang.Thread.run(Thread.java:784) 
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AsyncTask #3 (state = TIMED_WAITING)
                                                                                       at java.lang.Object.wait(Native Method) 
                                                                                       at java.lang.Thread.parkFor$(Thread.java:2161) 
                                                                                       at sun.misc.Unsafe.park(Unsafe.java:358) 
                                                                                       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 
                                                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 
                                                                                       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                       at java.lang.Thread.run(Thread.java:784) 
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: AsyncTask #4 (state = TIMED_WAITING)
                                                                                       at java.lang.Object.wait(Native Method) 
                                                                                       at java.lang.Thread.parkFor$(Thread.java:2161) 
                                                                                       at sun.misc.Unsafe.park(Unsafe.java:358) 
                                                                                       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 
                                                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 
                                                                                       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                       at java.lang.Thread.run(Thread.java:784) 
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: BUGLY_THREAD (state = WAITING)
                                                                                       at java.lang.Object.wait(Native Method)
                                                                                       at java.lang.Thread.parkFor$(Thread.java:2161)
                                                                                       at sun.misc.Unsafe.park(Unsafe.java:358)
                                                                                       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
                                                                                       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
                                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1127)
                                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                       at java.lang.Thread.run(Thread.java:784) 
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: CodelessViewCrawler (state = RUNNABLE)
                                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                       at android.os.MessageQueue.next(MessageQueue.java:379)
                                                                                       at android.os.Looper.loop(Looper.java:144)
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                    Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ConnectivityThread (state = RUNNABLE)
                                                                                       at android.os.MessageQueue.nativePollOnce(Native Method) 
                                                                                       at android.os.MessageQueue.next(MessageQueue.java:379) 
                                                                                       at android.os.Looper.loop(Looper.java:144) 
                                                                                       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by xfans** [comment]
5.5.1 ok
