### ISSUE TITLE
Crash when changing map style after adding polyline

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#11889]
**Platform: Android**
**Mapbox SDK version: 6.1.1**

### Steps to trigger behavior

 1. Load a map style after opening activity.
 2. Draw Polyline on the map as below:

```
// store to make navigation
        PolylineOptions polylineOptions = new PolylineOptions()
                .add(points)
                .color(mainColor ? routeColor : routeSecondColor)
                .alpha(alpha)
                .width(routeWidth);

        mapboxMap.addPolyline(polylineOptions);
        mPolylineOptions.add(polylineOptions);
        mPoints.add(points);
```

 3. Change map style --> app crash.

When I did not change map style or change it before adding polyline, there's no crash. Below logs are crash log:

```
JNI DETECTED ERROR IN APPLICATION: thread Thread[1,tid=28138,Native,Thread*=0x7f8fec7a00,peer=0x773e4530,"main"] using JNIEnv* from thread Thread[1,tid=28138,Native,Thread*=0x7f8fec7a00,peer=0x773e4530,"main"]
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]     in call to DeleteGlobalRef
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]     from void android.os.MessageQueue.nativePollOnce(long, int)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470] "main" prio=5 tid=1 Runnable
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x773e4530 self=0x7f8fec7a00
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   | sysTid=28138 nice=0 cgrp=default sched=0/0 handle=0x7f94344ab0
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 3855972541 524354885 4662 ) utm=343 stm=42 core=0 HZ=100
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   | stack=0x7fc644f000-0x7fc6451000 stackSize=8MB
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #00 pc 0000000000478f74  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #01 pc 0000000000478f70  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #02 pc 000000000044d11c  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+472)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #03 pc 00000000002ed898  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1128)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #04 pc 00000000002edf80  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+120)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #05 pc 0000000000101c00  /system/lib64/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+156)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #06 pc 000000000010149c  /system/lib64/libart.so (_ZN3art11ScopedCheck11CheckThreadEP7_JNIEnv+172)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #07 pc 00000000000ff148  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+1120)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #08 pc 00000000001032b8  /system/lib64/libart.so (_ZN3art8CheckJNI9DeleteRefEPKcP7_JNIEnvP8_jobjectNS_15IndirectRefKindE+640)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #09 pc 000000000006ae10  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #10 pc 000000000006aee4  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #11 pc 000000000006b858  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #12 pc 0000000000246efc  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #13 pc 000000000034d508  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #14 pc 000000000024823c  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #15 pc 0000000000247bd8  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #16 pc 0000000000249fb0  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #17 pc 00000000000f4170  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #18 pc 000000000021b9ac  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #19 pc 000000000021bb48  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #20 pc 000000000037bfc8  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #21 pc 000000000037b3e8  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #22 pc 000000000037a9ac  /data/app/com.map.goong.v2-2/lib/arm64/libmapbox-gl.so (???)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #23 pc 0000000000018338  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+852)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #24 pc 0000000000017f34  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #25 pc 00000000000f6f70  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   native: #26 pc 00000000009fba20  /system/framework/arm64/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+140)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at android.os.MessageQueue.nativePollOnce(Native method)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at android.os.MessageQueue.next(MessageQueue.java:323)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at android.os.Looper.loop(Looper.java:136)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at android.app.ActivityThread.main(ActivityThread.java:6776)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at java.lang.reflect.Method.invoke!(Native method)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
05-11 15:28:11.274 28138-28138/com.map.goong.v2 A/art: art/runtime/java_vm_ext.cc:470]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by tobrun** [comment]
Thank you for reaching out!
Could you add a minimal reproducible example?
Not able to reproduce with provided context:

![ezgif com-video-to-gif 66](https://user-images.githubusercontent.com/2151639/39920231-a63e643e-5516-11e8-93a2-3358a949733e.gif)
