### ISSUE TITLE
Fatal Exception: com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException

### ISSUE THREAD

**Issue by waar19** [mapbox/mapbox-gl-native#11998]
This error ocurred sometimes but is not ever

The token is configured and ocurred in some devices

Fatal Exception: com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one. 
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
       at com.mapbox.mapboxsdk.Mapbox.validateMapbox(Unknown Source)
       at com.mapbox.mapboxsdk.Mapbox.getAccessToken(Unknown Source)
       at com.mapbox.mapboxsdk.storage.FileSource.<init>(Unknown Source)
       at com.mapbox.mapboxsdk.storage.FileSource.getInstance(Unknown Source)
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.<init>(Unknown Source)
       at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(Unknown Source)
       at com.mapbox.mapboxsdk.maps.MapView$5.<init>(Unknown Source)
       at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(Unknown Source)
       at com.mapbox.mapboxsdk.maps.MapView.access$1000(Unknown Source)
       at com.mapbox.mapboxsdk.maps.MapView$MapViewLayoutListener.onGlobalLayout(Unknown Source)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2168)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1286)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6551)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6312)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

![image](https://user-images.githubusercontent.com/4492064/40461922-37c221a0-5ed3-11e8-9707-f045c75ac857.png)

**Comment by tobrun** [comment]
@waar19 this is very strange as we haven't heard about any reports like this. Are you calling into `Mapbox.getInstance(context, accessToken)`? In any case, I'm removing the thrown exception in https://github.com/mapbox/mapbox-gl-native/pull/12001 to resolve https://github.com/mapbox/mapbox-gl-native/issues/4972 so this shouldn't be an issue moving forward. Any steps to reproduce this issue is highly appreciated, closing this issue as it is obsolete with changes from #12001.

**Comment by ameerhamza6733** [comment]
My use mapbox sdk and some off user getting same error i am thinking  to switch google map

**Comment by ActuallyGSM** [comment]
Set Mapbox.getInstance(this,getString(R.string.access_token)); method before the setContentView(R.layout.activity_map); Method. If you having this exception change code structure as follows.

i.e:

protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Mapbox.getInstance(this,getString(R.string.access_token));
    setContentView(R.layout.activity_map);

    mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);
    mapView.getMapAsync(mapboxMap -> mapboxMap.setStyle(
            new Style.Builder().fromUrl(Style.MAPBOX_STREETS)
    ));
}

**Comment by KaberereG** [comment]
> My use mapbox sdk and some off user getting same error i am thinking to switch google map

Me too

**Comment by Mr-Ramzan** [comment]
Hi Did the same as described in an above comment but getting this crash while typing anything inside autocomplete search fragment
below is the code for it: 
           

       `    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Mapbox.getInstance(this, getString(R.string.map_box_access_token))
        setContentView(R.layout.activity_main)

        mBinding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(mBinding.root)

        initMapView(savedInstanceState)
        initPermissions()
        button_start_navigation.setOnClickListener {
            val navigationLauncherOptions = NavigationLauncherOptions.builder()
                .directionsRoute(currentRoute)
                .shouldSimulateRoute(true)
                .build()
            NavigationLauncher.startNavigation(this, navigationLauncherOptions)
        }

        val autocompleteFragment: PlaceAutocompleteFragment?

        if (savedInstanceState == null) {
            autocompleteFragment = PlaceAutocompleteFragment.newInstance("<access_token>")
            val transaction: FragmentTransaction = supportFragmentManager.beginTransaction()
            transaction.add(R.id.fragment_container, autocompleteFragment, "AutoComplete")
            transaction.commit()
        } else {
            autocompleteFragment =
                supportFragmentManager.findFragmentByTag("AutoComplete") as PlaceAutocompleteFragment?
        }
        }`

**Comment by jxian725** [comment]
I have the same issued and found out that you need to do
Mapbox.getInstance
first before 
setContentView

It solved the problem
