### ISSUE TITLE
Not allowed to start service Intent, Android Oreo.

### ISSUE THREAD

**Issue by cbedoy** [mapbox/mapbox-gl-native#12033]
**Platform:** Android
**Mapbox SDK version:** 6.1.1

### Expected behavior

I'm already know you have been tried to fixed this problem but seems still happens. 
It's crashing as randomly way :/

### Actual behavior

```
05-30 09:49:41.389 14373-14373/com.dagm8.dagdev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dagm8.dagdev, PID: 14373
    java.lang.ExceptionInInitializerError
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
        at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
        at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
        at com.dagm8.DagM8Application.onCreate(DagM8Application.kt:63)
        ......
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.dagm8.dagdev/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{33fddfb u0a120 SVC  idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
        at android.app.ContextImpl.startService(ContextImpl.java:1461)
        at android.content.ContextWrapper.startService(ContextWrapper.java:644)
        at com.mapbox.android.telemetry.MapboxTelemetry.startLocation(MapboxTelemetry.java:490)
        at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService(MapboxTelemetry.java:226)
        at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn(MapboxTelemetry.java:197)
        at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:461)
        at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:136)
        at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:25)
        at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:10)
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit>(Telemetry.java:42)
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41) 
        at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46) 
        at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49) 
        at com.dagm8.DagM8Application.onCreate(DagM8Application.kt:63) 

```

**Comment by LukasPaczos** [comment]
Thanks for reaching out @cbedoy. Would you mind retrying with `v6.1.3`?

/cc @electrostat

**Comment by electrostat** [comment]
@cbedoy handling this issue through this PR: https://github.com/mapbox/mapbox-events-android/pull/157

**Comment by LukasPaczos** [comment]
@cbedoy, https://github.com/mapbox/mapbox-gl-native/pull/12156 landed and should resolve this issue. Would you mind retesting with `6.2.0-beta.3`? Thanks!

Closing for now, let us know if you are still seeing this crashes.
