### ISSUE TITLE
Crash when building Expression.match() in 6.2.0-beta.2

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-gl-native#12101]
**Platform: Android**
**Mapbox SDK version: 6.2.0-beta.2**

I'm giving 6.2.0-beta.2 a try and have a crash when initializing the LocationLayerPlugin:
```
java.lang.RuntimeException: Can't convert an expression to a literal
    at com.mapbox.mapboxsdk.style.expressions.Expression.literal(Expression.java:183)
    at com.mapbox.mapboxsdk.style.expressions.Expression.match(Expression.java:1023)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.addSymbolLayer(LocationLayer.java:207)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.addLayers(LocationLayer.java:187)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.initializeComponents(LocationLayer.java:108)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.<init>(LocationLayer.java:101)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initialize(LocationLayerPlugin.java:496)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:148)
    at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:112)  
```

I first thought of reporting this on the plugins repository but after having a look at the source code it seems to be building the expression properly (`LocationLayer.java` line 207):
```
match(literal(layerId), literal(0f),
  stop(FOREGROUND_LAYER, get(PROPERTY_GPS_BEARING)),
  stop(BACKGROUND_LAYER, get(PROPERTY_GPS_BEARING)),
  stop(SHADOW_LAYER, get(PROPERTY_GPS_BEARING)),
  stop(BEARING_LAYER, get(PROPERTY_COMPASS_BEARING))
)
```

I believe it's due to the changes in #12022 that were made after I reported #12021

**Comment by tobrun** [comment]
Thank you for flagging @Jukurrpa! this should have been picked up by tests but went unnoticed!
