### ISSUE TITLE
[ANDROID] NullPointerException on MapGestureDetector

### ISSUE THREAD

**Issue by slm** [mapbox/mapbox-gl-native#12149]
**Platform: 7 - 24**
**Mapbox SDK version: 5.5.0**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.VelocityTracker.getYVelocity()' on a null object reference
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$RotateGestureListener.calculateVelocityVector(MapGestureDetector.java:796)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$RotateGestureListener.onRotateEnd(MapGestureDetector.java:769)
       at com.almeros.android.multitouch.gesturedetectors.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:132)
       at com.almeros.android.multitouch.gesturedetectors.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:73)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:182)
       at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:425)
       at android.view.View.dispatchTouchEvent(View.java:10062)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2776)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3063)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
       at android.view.View.dispatchPointerEvent(View.java:10293)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by LukasPaczos** [comment]
Thanks for reaching out @slm! With versions `6.x` of the Maps SDK we've migrated to [`Mapbox Gestures for Android`](https://github.com/mapbox/mapbox-gestures-android) library for gestures handling and I'm recommending to bump your dependency to the most recent `v6.1.3`, as we won't be supporting versions `5.x` anymore.

Closing as not actionable.
