### ISSUE TITLE
NullPointerException on getting zoom

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-gl-native#12288]
**Platform:Android**
**Mapbox SDK version:6.1.2**
the below crash is happened to lots of our user. Did you see this before:

Android versions: from 4 to 7
Device Company: HUAWEI and SAMSUNG
App in background: 9%
rooted: 5%

Fatal Exception: java.lang.NullPointerException
       at com.mapbox.mapboxsdk.maps.Transform.getZoom(Transform.java:222)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.isZoomValid(MapGestureDetector.java:901)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.sendTelemetryEvent(MapGestureDetector.java:888)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.access$700(MapGestureDetector.java:42)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$MoveGestureListener.onMoveBegin(MapGestureDetector.java:442)
       at com.mapbox.android.gestures.MoveGestureDetector.analyzeMovement(MoveGestureDetector.java:154)
       at com.mapbox.android.gestures.MultiFingerGesture.analyzeEvent(MultiFingerGesture.java:98)
       at com.mapbox.android.gestures.ProgressiveGesture.analyzeEvent(ProgressiveGesture.java:46)
       at com.mapbox.android.gestures.MoveGestureDetector.analyzeEvent(MoveGestureDetector.java:135)
       at com.mapbox.android.gestures.BaseGesture.analyze(BaseGesture.java:56)
       at com.mapbox.android.gestures.BaseGesture.onTouchEvent(BaseGesture.java:34)
       at com.mapbox.android.gestures.AndroidGesturesManager.onTouchEvent(AndroidGesturesManager.java:186)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:216)
       at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:436)
       at android.view.View.dispatchTouchEvent(View.java:8112)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2414)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2138)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2252)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1587)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2507)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2200)
       at android.view.View.dispatchPointerEvent(View.java:8320)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4558)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4430)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4042)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4011)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4122)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4019)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4179)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4042)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4011)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4019)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3988)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6333)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6249)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6220)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6185)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6413)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5335)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by tobrun** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/12042 and released with 6.2.0, latest patched version is 6.2.1 and there is an 6.3.0-alpha available as well. Thank you for reporting this issue!
