### ISSUE TITLE
JNI Error: java.lang.NoSuchMethodError GeometryCollection.getGeometries()

### ISSUE THREAD

**Issue by themics** [mapbox/mapbox-gl-native#12343]
### Steps to reproduce

 1. Create a `CustomGeometrySource` with a `GeometryTileProvider` which returns a `GeometryCollection`
```java
class CustomProvider implements GeometryTileProvider {
    @Override
    public FeatureCollection getFeaturesForBounds(LatLngBounds bounds, int zoom) {
        return FeatureCollection.fromFeatures(
            Collections.singletonList(
                Feature.fromGeometry(
                    GeometryCollection.fromGeometries(
                        Collections.emptyList()))));
    }
}
```
2. Add it to a map
```java
map.addSource(new CustomGeometrySource("custom-source", new CustomProvider()));
```

### Expected behavior

- No crash

### Actual behavior

- Application crashes via `NoSuchMethodError`
```
java.lang.NoSuchMethodError: no non-static method "Lcom/mapbox/geojson/GeometryCollection;.getGeometries()Ljava/util/List;"
    at com.mapbox.mapboxsdk.style.sources.CustomGeometrySource.nativeSetTileData(Native Method)
    at com.mapbox.mapboxsdk.style.sources.CustomGeometrySource.setTileData(CustomGeometrySource.java:121)
    at com.mapbox.mapboxsdk.style.sources.CustomGeometrySource.access$000(CustomGeometrySource.java:28)
    at com.mapbox.mapboxsdk.style.sources.CustomGeometrySource$GeometryTileRequest.run(CustomGeometrySource.java:195)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

### Configuration
 
**Mapbox SDK versions: 6.2.1** 

---

There's a typo in geometry_collection.cpp. The method name should be `"geometries"`, not `"getGeometry"`.

https://github.com/mapbox/mapbox-gl-native/blob/c5625f988a37b6876c4ef5fc8d9de295ee28ed44/platform/android/src/geojson/geometry_collection.cpp#L33

**Comment by tobrun** [comment]
Thanks for catching this @themics! @LukasPaczos  we need to improve our testcoverage more on jni-geojson integration. This has regressed before and these issues go unnoticed until you perform reflection to execute the method on the java side.
