### ISSUE TITLE
Problem with ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission

### ISSUE THREAD

**Issue by ufocom** [mapbox/mapbox-gl-native#12424]
### Steps to reproduce

 1. Add:
```
public class MyApplication extends MultiDexApplication {

   @Override
    public void onCreate() {
        super.onCreate();
      
        try {
            Mapbox.getInstance(this, getString(R.string.def_mapbox_key));
        } catch (Exception e) {
            e.printStackTrace();
        }
```
 2.
Somewhere in your main activity add method and call them
```
public void callPermissionRequest() {
        if (Build.VERSION.SDK_INT >= 23)
            this.requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSION_REQUEST_ID);

    }
```
 3. Allow to use Location
4. When application is running and you already allowed to using location go to app settings in android and disable location permission for your app
5. Go back to your app. You should see again dialog with question about allowing access to location. Don't do anything - just wait. 
6. After few seconds I have
```
Process: com.tripbucket.utah, PID: 27361
    java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
        at android.os.Parcel.readException(Parcel.java:1943)
        at android.os.Parcel.readException(Parcel.java:1889)
        at com.google.android.gms.internal.location.zza.transactAndReadExceptionReturnVoid(Unknown Source:10)
        at com.google.android.gms.internal.location.zzap.zza(Unknown Source:9)
        at com.google.android.gms.internal.location.zzas.zza(Unknown Source:44)
        at com.google.android.gms.internal.location.zzaz.zza(Unknown Source:5)
        at com.google.android.gms.internal.location.zzr.doExecute(Unknown Source:25)
        at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.run(Unknown Source:10)
        at com.google.android.gms.common.api.internal.zzag.execute(Unknown Source:71)
        at com.google.android.gms.common.api.internal.zzbd.execute(Unknown Source:5)
        at com.google.android.gms.common.api.internal.zzav.execute(Unknown Source:138)
        at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source:14)
        at com.mapbox.android.core.location.GoogleLocationEngine.requestLocationUpdates(GoogleLocationEngine.java:133)
        at com.mapbox.android.telemetry.TelemetryService.onConnected(TelemetryService.java:94)
        at com.mapbox.android.core.location.GoogleLocationEngine.onConnected(GoogleLocationEngine.java:93)
        at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source:109)
        at com.google.android.gms.common.api.internal.zzav.zzb(Unknown Source:22)
        at com.google.android.gms.common.api.internal.zzaj.zzat(Unknown Source:92)
        at com.google.android.gms.common.api.internal.zzaj.onConnected(Unknown Source:21)
        at com.google.android.gms.common.api.internal.zzbd.onConnected(Unknown Source:7)
        at com.google.android.gms.common.api.internal.zzp.onConnected(Unknown Source:5)
        at com.google.android.gms.common.internal.zzf.onConnected(Unknown Source:2)
        at com.google.android.gms.common.internal.BaseGmsClient$PostInitCallback.handleServiceSuccess(Unknown Source:131)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:62)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:2)
        at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source:51)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:270)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

I'm using mapbox only on one fragment which is not opened before crash(actually, for now is not opening at all). And I'm preaty sure this is problem with mapbox because if I remove this code from step one i don't have crash. I'm using in app google map and mapbox(google maps works fine).

### Configuration

**Android versions:** 8.0
**Device models:** Motoroal g6 plus
**Mapbox SDK versions:** 6.2.1

**Comment by tobrun** [comment]
@ufocom thank you for the report, this is an issue with the mapbox-events-android and I reticketed this issue in https://github.com/mapbox/mapbox-events-android/issues/182. Thank you for reaching out, we will handle your request upstream.
