### ISSUE TITLE
Loading mapbox crashes app with android software renderer

### ISSUE THREAD

**Issue by 94b42c29dd** [mapbox/mapbox-gl-native#12567]
The mapbox-gl-native implementation crashes on devices that use the android software renderer instead of native gpu rendering. Replicant (completely free android distribution) uses the android software renderer since using the gpu for rendering requires non-free software.

### Steps to reproduce

 1. Open mapbox android demo app or any other app that uses the mapbox-gl-native library
 2. Click on any map (In this case: A simple map view)
 3. The app crashes

### Expected behavior
Show the map

### Actual behavior
The app crashes with this log:
```
08-07 17:26:12.394 D/libEGL  ( 4618): loaded /system/lib/egl/libGLES_android.so
08-07 17:26:12.404 I/ActivityManager( 9464): Displayed com.mapbox.mapboxandroiddemo/.examples.basics.SimpleMapViewActivity: +759ms
08-07 17:26:12.474 E/UncaughtException( 4618): 
08-07 17:26:12.474 E/UncaughtException( 4618): com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed
08-07 17:26:12.474 E/UncaughtException( 4618): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(Unknown Source)
08-07 17:26:12.474 E/UncaughtException( 4618): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
08-07 17:26:12.474 E/UncaughtException( 4618): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
08-07 17:26:12.474 E/UncaughtException( 4618): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-07 17:26:12.479 E/AndroidRuntime( 4618): FATAL EXCEPTION: GLThread 934
08-07 17:26:12.479 E/AndroidRuntime( 4618): Process: com.mapbox.mapboxandroiddemo, PID: 4618
08-07 17:26:12.479 E/AndroidRuntime( 4618): Theme: themes:{}
08-07 17:26:12.479 E/AndroidRuntime( 4618): com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(Unknown Source)
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-07 17:26:12.489 W/ActivityManager( 9464):   Force finishing activity com.mapbox.mapboxandroiddemo/.examples.basics.SimpleMapViewActivity
08-07 17:26:12.489 W/ActivityManager( 9464):   Force finishing activity com.mapbox.mapboxandroiddemo/.MainActivity
```

### Configuration

Android Version: Replicant 6.0003 (android 6)
Device models: Galaxy Note 2
Mapbox SDK versions: tested it with 5.5.0 (in Transportr) and 6.3.0 in mapbox demo for android, the log is from mapbox demo for android 6.3.0-4.

**Comment by Altonss** [comment]
Is this bug not happening anymore?
