### ISSUE TITLE
Android - "Cannot add layer twice" error (but layer is not existing)

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12885]
My MapView is within a Fragment which is part of a tab bar that the user can click. Each fragment is shown using the FragmentTransaction.replace(...) method. When I click tab A (mapview tab), switch to tab B and then to tab A again, mapbox crashes. First internally and as soon as I try to scroll, the app itself.

```
09-13 21:23:08.146 29587-29587/com.domesticcat.mte.android.dev E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Cannot add layer twice
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addLayer(NativeMapView.java:715)
        at com.mapbox.mapboxsdk.maps.MapboxMap.addLayer(MapboxMap.java:314)
        at au.gov.vic.dewlp.ffmv.moretoexplore.mapbox.view.CustomMapView$addLayersToMapBox$1.onMapReady(CustomMapView.kt:133)
        at com.mapbox.mapboxsdk.maps.MapView.getMapAsync(MapView.java:708)
        at au.gov.vic.dewlp.ffmv.moretoexplore.mapbox.view.CustomMapView.addLayersToMapBox(CustomMapView.kt:129)
        at au.gov.vic.dewlp.ffmv.moretoexplore.mapbox.view.CustomMapView.access$addLayersToMapBox(CustomMapView.kt:19)
        at au.gov.vic.dewlp.ffmv.moretoexplore.mapbox.view.CustomMapView$addTrackStartSiteSource$1.onMapReady(CustomMapView.kt:112)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1235)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1220)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:911)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

But it gets more interesting. :) This exception should not happen. The layer is not existing inside the MapboxMap which I checked with getLayer(layerId) (it returns null and therefore I assume mapbox does not have this layer yet). Is it possible that mapbox is not saving the layerid correctly, but compares the object that I parse via addLayer(layer)?

The app actually crashes with:

`09-13 21:30:29.210 29587-29587/com.domesticcat.mte.android.dev A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x656877c7 in tid 29587 (mte.android.dev)`

This issue seems to be related to https://github.com/mapbox/mapbox-gl-native/issues/12614 which I opened a while ago.

My current workaround: 
I have to use a separate fragment view container for the mapview fragment.

### Configuration

**Android versions:** All
**Device models:** All
**Mapbox SDK versions:** 6.5.0

**Comment by tobrun** [comment]
@Mordag thank you for reaching out, I performed the steps you mention but not able to see this crash:

![ezgif com-video-to-gif 43](https://user-images.githubusercontent.com/2151639/45489440-7efe2e80-b764-11e8-9b18-24fcca1cbea2.gif)

Full code that I used in above gif is below, it uses the replace fragment transaction as you did:

```java
package com.mapbox.mapboxsdk.testapp.activity.fragment;

import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.design.widget.BottomNavigationView;
import android.support.v4.app.Fragment;
import android.support.v7.app.AppCompatActivity;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.TextView;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.mapbox.geojson.Feature;
import com.mapbox.geojson.FeatureCollection;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.maps.SupportMapFragment;
import com.mapbox.mapboxsdk.style.layers.Property;
import com.mapbox.mapboxsdk.style.layers.SymbolLayer;
import com.mapbox.mapboxsdk.style.sources.GeoJsonSource;
import com.mapbox.mapboxsdk.testapp.R;
import timber.log.Timber;

import java.util.ArrayList;
import java.util.List;

import static com.mapbox.mapboxsdk.style.expressions.Expression.get;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconAllowOverlap;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconAnchor;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconColor;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconIgnorePlacement;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.iconImage;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.textAllowOverlap;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.textAnchor;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.textColor;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.textField;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.textIgnorePlacement;
import static com.mapbox.mapboxsdk.style.layers.PropertyFactory.textSize;

public class BottomNavActivity extends AppCompatActivity {

  private final List<Fragment> fragments = new ArrayList<>(5);
  private Fragment currentFragment;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_bottom_nav);

    BottomNavigationView navigation = findViewById(R.id.navigation);

    fragments.add(CustomFragment.newInstance(1));
    fragments.add(new CustomMapFragment());
    fragments.add(CustomFragment.newInstance(3));
    fragments.add(SupportMapFragment.newInstance());
    fragments.add(CustomFragment.newInstance(5));

    // add initial fragment
    currentFragment = fragments.get(0);
    getSupportFragmentManager().beginTransaction().add(R.id.fragment_container, currentFragment).commit();

    // add tab listener to change fragments
    navigation.setOnNavigationItemSelectedListener(item -> {
      switch (item.getItemId()) {
        case R.id.navigation_home:
          currentFragment = fragments.get(0);
          break;
        case R.id.navigation_map_one:
          currentFragment = fragments.get(1);
          break;
        case R.id.navigation_notifications:
          currentFragment = fragments.get(2);
          break;
        case R.id.navigation_map_two:
          currentFragment = fragments.get(3);
          break;
        case R.id.navigation_car:
          currentFragment = fragments.get(4);
          break;
      }
      // replace current fragment with tab selected one
      getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, currentFragment).commit();
      return true;
    });
  }

  @Override
  public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.menu_bottom, menu);
    return true;
  }

  @Override
  public boolean onOptionsItemSelected(MenuItem item) {
    int itemId = item.getItemId();
    if (itemId == R.id.menu_action_show) {
      getSupportFragmentManager().beginTransaction().show(currentFragment).commit();
      return true;
    } else if (itemId == R.id.menu_action_hide) {
      getSupportFragmentManager().beginTransaction().hide(currentFragment).commit();
      return true;
    } else if (itemId == R.id.menu_action_detach) {
      getSupportFragmentManager().beginTransaction().detach(currentFragment).commit();
      return true;
    } else if (itemId == R.id.menu_action_attach) {
      getSupportFragmentManager().beginTransaction().attach(currentFragment).commit();
      return true;
    }
    return super.onOptionsItemSelected(item);
  }

  public static class CustomFragment extends Fragment {

    public static final String COUNTER = "counter";

    public static CustomFragment newInstance(int counter) {
      Bundle args = new Bundle();
      args.putInt(COUNTER, counter);
      CustomFragment fragment = new CustomFragment();
      fragment.setArguments(args);
      return fragment;
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
      TextView textView = new TextView(inflater.getContext());
      textView.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, Gravity.CENTER));
      textView.setTextSize(20);
      textView.setText(String.format("Fragment number: %s", getArguments().getInt("counter")));
      return textView;
    }
  }

  public static class CustomMapFragment extends Fragment {

    private MapView mapView;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
      Timber.e("OnCreateView Map");
      return mapView = new MapView(inflater.getContext());
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
      super.onViewCreated(view, savedInstanceState);
      mapView.getMapAsync(new OnMapReadyCallback() {
        @Override
        public void onMapReady(MapboxMap mapboxMap) {
          // Add a source
          FeatureCollection markers = FeatureCollection.fromFeatures(new Feature[] {
            Feature.fromGeometry(Point.fromLngLat(4.91638, 52.35673), featureProperties("Marker 1")),
            Feature.fromGeometry(Point.fromLngLat(4.91638, 52.34673), featureProperties("Marker 2"))
          });
          mapboxMap.addSource(new GeoJsonSource("source-id", markers));

          // Add the symbol-layer
          mapboxMap.addLayer(
            new SymbolLayer("layer-id", "source-id")
              .withProperties(
                iconImage("car-15"),
                iconIgnorePlacement(true),
                iconAllowOverlap(true),
                iconAnchor(Property.ICON_ANCHOR_BOTTOM),
                iconColor(Color.RED),
                textField(get("title")),
                textColor(Color.RED),
                textAllowOverlap(true),
                textIgnorePlacement(true),
                textAnchor(Property.TEXT_ANCHOR_TOP),
                textSize(10f)
              )
          );
        }
      });
    }

    private JsonObject featureProperties(String title) {
      JsonObject object = new JsonObject();
      object.add("title", new JsonPrimitive(title));
      return object;
    }

    @Override
    public void onStart() {
      super.onStart();
      Timber.e("OnStart Map");
      mapView.onStart();
    }

    @Override
    public void onResume() {
      super.onResume();
      Timber.e("OnResume Map");
      mapView.onResume();
    }

    @Override
    public void onPause() {
      super.onPause();
      Timber.e("OnPause Map");
      mapView.onPause();
    }

    @Override
    public void onStop() {
      super.onStop();
      Timber.e("OnStop Map");
      mapView.onStop();
    }

    @Override
    public void onDestroyView() {
      super.onDestroyView();
      Timber.e("OnDestroy Map");
      mapView.onDestroy();
    }

    @Override
    public void onSaveInstanceState(@NonNull Bundle outState) {
      super.onSaveInstanceState(outState);
      Timber.e("OnSaveInstanceState Map");
      mapView.onSaveInstanceState(outState);
    }

    @Override
    public void onLowMemory() {
      super.onLowMemory();
      Timber.e("OnLowMemory Map");
      mapView.onLowMemory();
    }
  }
}
```

Would  you be able to either provide a minimal reproducible code example? 
or point out where my code differs from your setup? 

Thanks again for reaching out and using our products

**Comment by Mordag** [comment]
I will try to create an example tomorrow.

Can you try to change your example in using a layout which is using databinding? I also add layers and the source to the mapbox using observer objects. The observer pass their data into the mapboxmap using custom bindingadapters. And instead of holding a list of fragments can you retrieve the fragment using the supportedFragmentManager (and the fragment tag)?

When I change the tabs, the whole mapview turns black for a very short while.

**Comment by Mordag** [comment]
I was still not able to find some time to build a demo project. But I was able to fix it in my current project by using fragmentManager.add(...)/.hide(...) instead of .replace(...).
