### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found: com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13045]
We are getting crash with error

```
 FATAL EXCEPTION: main
    Process: com.fersmart.maps.nav.nativemapnavtestapp, PID: 2492
    java.lang.UnsatisfiedLinkError: Native method not found: com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize:()V
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:40)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
```

**Comment by tobrun** [comment]
Thank you for reaching out @Xgamefactory, 
which version of the SDK  were you using? 
could you provide a minimal reproducible example?

**Comment by florianPOLARSTEPS** [comment]
@tobrun I am seeing this one now as well in our production app for a limited set of users quite frequently. Please reopen.

Mapbox SDK Version: 6.7.1
Distribution: .aab

[Device distribution](https://imgur.com/OHOOLg3)

**Comment by LukasPaczos** [comment]
Most likely not related to #13448 as it's targeting a different architecture. Are you able to reproduce locally by any chance @florianPOLARSTEPS? You can have the `.so` library load failure re-thrown by enabling strict mode with `MapStrictMode.setStrictModeEnabled(true)` or just search for a "Failed to load native shared library." log.

**Comment by florianPOLARSTEPS** [comment]
I tried your suggestions but unfortunately could not reproduce on one of the devices I saw that issue happening in production. It also only happens to a very limited set of users ( 50 distinct users for the screenshot above ) upon app startup whereas on the same devices a huge number of users have no problem at all. Unfortunately Google play does not have any more valuable information available for diagnostics. It could very well be an issue in google play's dynamic delivery system.

**Comment by LukasPaczos** [comment]
Thanks for looking into this @florianPOLARSTEPS. Unfortunately, I wasn't able to reproduce locally either. Please keep us posted if you happen to find some more information.

**Comment by tobrun** [comment]
@florianPOLARSTEPS this could be an issue related to general so file loading. I would advice you to look into an external library loader as https://github.com/KeepSafe/ReLinker or https://github.com/facebook/SoLoader, you can use these libraries in conjunction with our `LibraryLoader.java` class.

**Comment by P-Zenker** [comment]
I've updated one of my apps from:
- mapbox-android-navigation-ui:0.24.1
- uploaded as APK

to

- mapbox-android-navigation-ui:0.26.0
- uploaded as Android App Bundle

There are now a few UnsatisfiedLinkError exceptions in my application:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(NativeConnectivityListener.java)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:40)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
       at myapp.CUApplication.onCreate(CUApplication.java:52)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4577)
       at android.app.ActivityThread.access$1500(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5278)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

CUApplication.java:52 is just:
`Mapbox.getInstance(this, getString(R.string.mapbox_access_token));`

Before my update I never saw this issue before and I couldn't reproduce it

**Comment by LukasPaczos** [comment]
@P-Zenker have you tried using any of the libraries mentioned by Tobrun in https://github.com/mapbox/mapbox-gl-native/issues/13045#issuecomment-442788475? The issue most likely stems from the default library failing to do its job. You can use `LibraryLoader#setLibraryLoader` to provide an alternative, see [the setup in our test app](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java#L57-L64).

**Comment by bundeeteddee** [comment]
Hi @LukasPaczos , we have also just started seeing this `UnsatisfiedLinkError` error after turning on app bundle (almost identical to @P-Zenker). We have seen very minimal crashes before that, it has jumped quite a bit since then (from ~30 to ~500 crashes in our release cycle).

I have tried using a different .so library loader, the `SOLoader` from facebook but that is not making any difference in crash rate. I havent tried using `ReLinker` though, potentially something i can test with next.

We are currently using sdk v6.6.

**Comment by tobrun** [comment]
Thank you for adding that additional information @bundeeteddee, do you have some more information on which devices this is occurring? do you have any additional configuration setup in terms of ABI exclusion?

**Comment by bundeeteddee** [comment]
No worries! There does not seem to be any patterns emerging in terms of devices and android version. Here is the snapshot of the latest release (sample size of ~900 crashes through few release cycles):

![sample](https://user-images.githubusercontent.com/570327/51617246-20c03400-1f2c-11e9-8f78-fd3c09c4fa40.png)

In this release we excluded ABI.

**Comment by bundeeteddee** [comment]
Update: we have done a few more trials and found out the library loader actually works. I had carelessly set the library *after* attempting to setup mapbox. Ugh.

Using SOLoader, before calling 'getInstance' on mapbox works well. It does not 100% remove all the 'unsatisfiedLink' crashes, but it brings it back to pre-appbundling. 

:+1

**Comment by P-Zenker** [comment]
@LukasPaczos I've followed your links, copied the test code and released a app update. But I still got some crashes on this device:
```
Gerät
Marke: TrendMicro
Modell: GI-I9500_TMMARS
Ausrichtung: Hochformat
Freier RAM: 25.04 GB
Freier Festplattenspeicher: 9.92 GB
Betriebssystem
Version: 5.1
Ausrichtung: Hochformat
Rooting durchgeführt: Ja
Absturz
Datum: 10.02.2019, 13:42:00
App-Version: 1.0.1 (5)
```

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
       at com.catchup_apps.android.med.app.CUApplication.onCreate(CUApplication.java:60)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4577)
       at android.app.ActivityThread.access$1500(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5278)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Caused by com.getkeepsafe.relinker.MissingLibraryException
libmapbox-gl.so
```
Caused by com.getkeepsafe.relinker.MissingLibraryException: libmapbox-gl.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
       at com.catchup_apps.android.med.app.CUApplication$2.load(CUApplication.java:92)
       at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:45)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
       at com.catchup_apps.android.med.app.CUApplication.onCreate(CUApplication.java:60)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4577)
       at android.app.ActivityThread.access$1500(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5278)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I'am using com.mapbox.mapboxsdk:mapbox-android-navigation-ui:**0.28.0**

**Comment by florianPOLARSTEPS** [comment]
> @florianPOLARSTEPS this could be an issue related to general so file loading. I would advice you to look into an external library loader as https://github.com/KeepSafe/ReLinker or https://github.com/facebook/SoLoader, you can use these libraries in conjunction with our `LibraryLoader.java` class.

We released an update with SoLoader as library loader and the issue seems to be fixed. Thx

**Comment by tobrun** [comment]
Adding here that starting with 7.3.0, we will ship relinker as the default library loader

**Comment by dabitdev** [comment]
@tobrun I am getting this crash on minsDK 26 and using 
   `implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.0'`

**Comment by dabitdev** [comment]
should we reopen this issue?
