### ISSUE TITLE
cmake error when building from source on macos

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13052]
```
Build command failed.

Error while executing process /Users/Xtrack/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with 
arguments {-H/Users/Xtrack/Downloads/mapbox-gl-native-master -B/Users/Xtrack/Downloads/
mapbox-gl-native-master/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/
release/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/Xtrack/Downloads/mapbox-gl-native-master/
platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release/obj/x86_64 
-DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/Users/Xtrack/Downloads/android-ndk-r18 
-DCMAKE_TOOLCHAIN_FILE=/Users/Xtrack/Downloads/android-ndk-r18/build/cmake
/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/Xtrack/Library/Android/sdk/cmake
/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang 
-DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android 
-DMASON_PLATFORM=android -DNodeJS_EXECUTABLE= -Dnpm_EXECUTABLE=}

-- Check for working CXX compiler: /Users/Xtrack/Downloads/android-ndk-r18/
toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++

-- Check for working CXX compiler: /Users/Xtrack/Downloads/android-ndk-r18/
toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Users/Xtrack/Downloads/android-ndk-r18/
toolchains/llvm/prebuilt/darwin-x86_64/bin/clang

-- Check for working C compiler: /Users/Xtrack/Downloads/android-ndk-r18/
toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works

-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at cmake/mbgl.cmake:12 (message):
-- Configuring incomplete, errors occurred!
```

**Comment by kkaefer** [comment]
NDK 18 isn't supported yet and depends on https://github.com/mapbox/mapbox-gl-native/pull/13049. Please use NDK 17 in the meantime.

**Comment by Xgamefactory** [comment]
thanks for fast response !

would be helpful if you mentioned it on instructions notes too.

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/README.md

**Comment by Xgamefactory** [comment]
we have installed latest nodejs v8.12.0

**Comment by kkaefer** [comment]
> `... -DNodeJS_EXECUTABLE= -Dnpm_EXECUTABLE=}`

it looks like it's not getting picked up in `platform/android/gradle/configuration.gradle`. can you please try removing that file, and rerunning `make aproj` again?

**Comment by Xgamefactory** [comment]
we did same error

**Comment by Xgamefactory** [comment]
we make a clean git download and now we are getting another error

`Failed to notify project evaluation listener.`

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':MapboxGLAndroidSDK'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
```

**Comment by Xgamefactory** [comment]
Android studio 3.2
gradle version 4.4
android plug 3.1.4
jdk /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home

**Comment by Xgamefactory** [comment]
after updating gradle wrapper version to 4.6 with android plugin version to 3.2.0
getting same error **Failed to notify project evaluation listener.**
