### ISSUE TITLE
.Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13069]
app crashes with resource not found exception i have checked in aar file there is resource file mapbox_info_bg_selector but in R.txt the actual id of this resource is different  see below

**R.txt** 
`int drawable mapbox_info_bg_selector **0x7f090055**`

**Error**
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable resource ID #**0x7f07011a**

```
 FATAL EXCEPTION: main
    Process: com.test.maps.nav.nativemapnavtestapp, PID: 2422
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fersm..............android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.mapboxsdk.maps.MapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2193)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
        .........................
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.mapboxsdk.maps.MapView
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       .........................................
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       ...............................................
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class ImageView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
       ................................................
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable resource ID #0x7f07011a
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at android.widget.ImageView.<init>(ImageView.java:129)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:71)
        a.......................
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFound
```

**Comment by tobrun** [comment]
have not heard any other user with this issue. You are building from source yourself, we do not provide support for this.
