### ISSUE TITLE
No implementation found for void com.mapbox.mapboxsdk.storage.FileSource.initialize(java.lang.String, java.lang.String, 

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13117]
mapbox sdk 6.5 crash when initializing mapview
```
 Process: com.xdevfactory.nothify, PID: 31412
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.storage.FileSource.initialize(java.lang.String, java.lang.String, android.content.res.AssetManager) 
(tried Java_com_mapbox_mapboxsdk_storage_FileSource_initialize
 and Java_com_mapbox_mapboxsdk_storage_FileSource_initialize__Ljava_lang_String_2Ljava_lang_String_2Landroid_content_res_AssetManager_2)
        at com.mapbox.mapboxsdk.storage.FileSource.initialize(Native Method)
        at com.mapbox.mapboxsdk.storage.FileSource.<init>(FileSource.java:228)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:66)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.<init>(MapRenderer.java:29)
        at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewMapRenderer.<init>(TextureViewMapRenderer.java:34)
        at com.mapbox.mapboxsdk.maps.MapView$4.<init>(MapView.java:300)
        at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:299)
        at com.mapbox.mapboxsdk.maps.MapView.access$1100(MapView.java:77)
        at com.mapbox.mapboxsdk.maps.MapView$MapViewLayoutListener.onGlobalLayout(MapView.java:1004)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:889)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2070)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
        at android.view.Choreographer.doCallbacks(Choreographer.java:590)
        at android.view.Choreographer.doFrame(Choreographer.java:560)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
10-17 00:15:38.066 31412-31412/com.xdevfactory.nothify I/Process: Sending signal. PID: 31412 SIG: 9

```

**Comment by Xgamefactory** [comment]
the layout mapview xml 

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:textIsSelectable="false"
        app:mapbox_cameraTargetLat="38.907192"
        app:mapbox_cameraTargetLng="-77.036871"
        app:mapbox_cameraZoom="12"
        app:mapbox_renderTextureMode="true"
        app:mapbox_styleUrl="@string/mapbox_style_mapbox_streets"/>
</RelativeLayout>
```

**Comment by Xgamefactory** [comment]
same crash with GLSurfaceViewMapRenderer too.

:```
 No implementation found for void com.mapbox.mapboxsdk.storage.FileSource.initialize(java.lang.String, java.lang.String, android.content.res.AssetManager) (tried Java_com_mapbox_mapboxsdk_storage_FileSource_initialize and Java_com_mapbox_mapboxsdk_storage_FileSource_initialize__Ljava_lang_String_2Ljava_lang_String_2Landroid_content_res_AssetManager_2)
        at com.mapbox.mapboxsdk.storage.FileSource.initialize(Native Method)
        at com.mapbox.mapboxsdk.storage.FileSource.<init>(FileSource.java:228)
        at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:66)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.<init>(MapRenderer.java:29)
        at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:27)
        at com.mapbox.mapboxsdk.maps.MapView$5.<init>(MapView.java:312)
        at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:312)
        at com.mapbox.mapboxsdk.maps.MapView.access$1100(MapView.java:77)
        at com.mapbox.mapboxsdk.maps.MapView$MapViewLayoutListener.onGlobalLayout(MapView.java:1004)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:889)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2070)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
```

**Comment by tobrun** [comment]
this isn't an issue with our ready made binaries, we don't provide support for building from source.
Please do not open any new issues. This issue stems from not being able to look up the method definition in the shared library.

**Comment by Xgamefactory** [comment]
we did exactly as you have described in build from source instructions and struggling with issues.
at least if you provide more useful errors in sdk developers could identify the problem.
