### ISSUE TITLE
    com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13156]
we are getting crash on rerouting using mapbox android navigation core. no NavigationView class

there is no autoreroting logic in core navigation so we are doing rerouting after triggering
**userOffRoute** event loading new directionsRoute and adding new route
as in reroute and mocknavigation activity.

crash happens in base case with simulation mode and not.

Are we missing something ? 

`navigationMapRoute.addRoutes(response.body().routes());`

```
com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addLayerBelow(NativeMapView.java:676)
        at com.mapbox.mapboxsdk.maps.MapboxMap.addLayerBelow(MapboxMap.java:332)
        at com.mapbox.services.android.navigation.ui.v5.utils.MapUtils.addLayerToMap(MapUtils.java:63)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addRouteShieldLayer(NavigationMapRoute.java:480)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.drawRoutes(NavigationMapRoute.java:324)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:734)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:157)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:114)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:123)
        at android.os.Handler.handleCallback(Handler.java:733)
```

**Comment by Xgamefactory** [comment]
sorry issue moved to mapbox navigation side https://github.com/mapbox/mapbox-navigation-android/issues/1448
