### ISSUE TITLE
 implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.1') Do not work with me

### ISSUE THREAD

**Issue by swadallail** [mapbox/mapbox-gl-native#13195]
Everything was working well with me
Then when I updated the Mapbox to 6.6.1 a problem happened
Give me the error:-

E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.amedbasheir.g7l/com.example.amedbasheir.g7l.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
                      at android.app.ActivityThread.access$600(ActivityThread.java:140)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4898)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                      at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at com.example.amedbasheir.g7l.MainActivity.onCreate(MainActivity.java:49)
                      at android.app.Activity.performCreate(Activity.java:5206)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4898) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                      at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at com.example.amedbasheir.g7l.MainActivity.onCreate(MainActivity.java:49) 
                      at android.app.Activity.performCreate(Activity.java:5206) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4898) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class ImageView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:459)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                      at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:138)
                      at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:108)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                      at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at com.example.amedbasheir.g7l.MainActivity.onCreate(MainActivity.java:49) 
                      at android.app.Activity.performCreate(Activity.java:5206) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4898) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable resource ID #0x7f0700c4
                      at android.content.res.Resources.loadDrawable(Resources.java:1951)
                      at android.content.res.Resources.getDrawable(Resources.java:672)
                      at android.support.v7.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:130)
                      at android.support.v7.widget.TintResources.getDrawable(TintResources.java:46)
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:465)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
                      at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
                      at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
                      at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:59)
                      at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
                      at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
                  	at android.support.v7.app.AppCompatViewInflater.createImageV

### Configuration

**Android versions:*3.1.4* 
**Mapbox SDK versions:*6.6.1*

**Comment by tobrun** [comment]
Can you try retesting with 6.6.2?

**Comment by swadallail** [comment]
You are a genius, it's works thank you
