### ISSUE TITLE
[Android] app crashes with Error inflating class com.mapbox.mapboxsdk.maps.MapView

### ISSUE THREAD

**Issue by TooLazyy** [mapbox/mapbox-gl-native#13201]
Hi, getting such exception.

**Error log:**
```
10-25 17:44:51.909 2258-2258/ru.galt.appdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.galt.appdemo, PID: 2258
    android.view.InflateException: Binary XML file line #9: Error inflating class com.mapbox.mapboxsdk.maps.MapView
        at android.view.LayoutInflater.createView(LayoutInflater.java:621)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at ru.galt.app.presentation.base.BaseFragment.onCreateView(BaseFragment.kt:34)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.setOffscreenPageLimit(ViewPager.java:850)
        at ru.galt.app.presentation.screens.contacts.fragment.ContactsMainFragment.initPager(ContactsMainFragment.kt:53)
        at ru.galt.app.presentation.screens.contacts.fragment.ContactsMainFragment.onCreateOptionsMenu(ContactsMainFragment.kt:70)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2450)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3296)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:322)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:365)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:543)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:595)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at ru.galt.app.presentation.base.BaseFragment.onCreateView(BaseFragment.kt:34) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215) 
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649) 
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167) 
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238) 
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086) 
        at android.support.v4.view.ViewPager.setOffscreenPageLimit(ViewPager.java:850) 
        at ru.galt.app.presentation.screens.contacts.fragment.ContactsMainFragment.initPager(ContactsMainFragment.kt:53) 
        at ru.galt.app.presentation.screens.contacts.fragment.ContactsMainFragment.onCreateOptionsMenu(ContactsMainFragment.kt:70) 
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2450) 
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3296) 
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:322) 
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:365) 
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93) 
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332) 
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93) 
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454) 
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:574) 
        at android.view.Choreographer.doFrame(Choreographer.java:543) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.view.InflateException: Binary XML fi
```

**Configuration**

Android versions: **4.4.4** (19 api)
Device models: **emulator Nexus S**
Mapbox SDK versions: **mapbox-android-sdk:6.6.1**

Layout firing exception contains:
```
 <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_cameraZoom="11"
        mapbox:mapbox_styleUrl="mapbox://styles/mapbox/streets-v10" />
```
This is not helping:
```
vectorDrawables {
            useSupportLibrary true
        }

```

**Comment by tobrun** [comment]
Should be resolved with 6.6.2! Could you retest?
Closing as resolved but please reach out if not!
