### ISSUE TITLE
MapRenderer : program failed to link

### ISSUE THREAD

**Issue by msh91** [mapbox/mapbox-gl-native#13215]
### Steps to reproduce
`Fatal Exception: java.lang.Error: program failed to link
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(MapRenderer.java)
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
       at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

`0. Crashed: GLThread 2856
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(MapRenderer.java)
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
       at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240`

### Configuration
Mapbox sdk : 6.4.0
Navigation sdk : 0.16.0

**Android versions:**  4.2.2
**Device models:**  Sony Xperia L
**Mapbox SDK versions:** 6.4.0

**Comment by siavashabdoli** [comment]
Seems the problem is with sony Xperia L. after a short time it will crash when user open activity with a mapbox map.

**Comment by msh91** [comment]
I can reproduce this crash with this report:
Device: Xperia L C2105
Mapbox: 6.7.0

Report:
`Program failed to link: --From Vertex Shader: Error: Symbol u_is_text defined with different precision in vertex and fragment shaders. --From Fragment Shader: Error: Symbol u_is_text defined with different precision in vertex and fragment shaders. E/AndroidRuntime: FATAL EXCEPTION: GLThread 943 java.lang.Error: program failed to link at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method) at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74) at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:58) at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516) at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

**Comment by tobrun** [comment]
cc @mapbox/gl-core

**Comment by siavashabdoli** [comment]
It has been fixed in version 7.3.2 we can't see the crash on fabric anymore

**Comment by kkaefer** [comment]
Glad to hear!
