### ISSUE TITLE
[Android] Could not find class 'android.graphics.drawable.RippleDrawable'

### ISSUE THREAD

**Issue by amir169** [mapbox/mapbox-gl-native#13344]
The application seems to work fine but this error is seen in logcat:

`Could not find class 'android.graphics.drawable.RippleDrawable'`

and the full stack trace is:

`
11-12 14:33:15.586 5617-5617/com.test.myapplication E/ActivityThread: Pause GC
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at android.app.ActivityThread.pauseGC(ActivityThread.java:5525)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
        at android.app.ActivityThread.access$900(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.UnsatisfiedLinkError: Native method not found: dalvik.system.VMRuntime.pauseGc:(Ljava/lang/String;)I
        at dalvik.system.VMRuntime.pauseGc(Native Method)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at android.app.ActivityThread.pauseGC(ActivityThread.java:5525) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2324) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
11-12 14:33:15.926 5617-5617/com.test.myapplication E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
`

Is this an important error?

### Steps to reproduce

 1. Run a simple app.
 2. See the error in logcat.

### Configuration

**Android versions:** 4.4.2
**Device models:** Samsung GT-N7100
**Mapbox SDK versions:** 6.7.0

**Comment by tobrun** [comment]
Capturing from https://stackoverflow.com/a/47643614/1281750 that this isn't actionable
