### ISSUE TITLE
compilation failure when using kapt "android.arch.persistence.room:compiler:1.1.1"

### ISSUE THREAD

**Issue by BecAbi** [mapbox/mapbox-gl-native#13377]
Hi,
Building my app I get the following failure:

**[kapt] An exception occurred: java.lang.ClassCastException: com.sun.tools.javac.code.Type$ClassType cannot be cast to com.sun.tools.javac.code.Type$ArrayType
	at com.sun.tools.javac.code.Type$AnnotatedType.getComponentType(Type.java:2018)
	at android.arch.persistence.room.solver.TypeAdapterStore.findQueryParameterAdapter(TypeAdapterStore.kt:414)
	at android.arch.persistence.room.processor.QueryParameterProcessor.process(QueryParameterProcessor.kt:32)
	at android.arch.persistence.room.processor.QueryMethodProcessor.process(QueryMethodProcessor.kt:138)
	at android.arch.persistence.room.processor.DaoProcessor.process(DaoProcessor.kt:95)
	at android.arch.persistence.room.processor.DatabaseProcessor.doProcess(DatabaseProcessor.kt:93)
	at android.arch.persistence.room.processor.DatabaseProcessor.process(DatabaseProcessor.kt:53)
	at android.arch.persistence.room.RoomProcessor$DatabaseProcessingStep.process(RoomProcessor.kt:57)**

Here I share with you part of my gradle file (dependencies): 

**def room_version = "1.1.1"
    implementation "android.arch.persistence.room:runtime:$room_version"
    kapt "android.arch.persistence.room:compiler:$room_version"
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.1.0'**

I noticed that the problem has been introduced since version 6.4.0

**Comment by tobrun** [comment]
@BecAbi without any additional context/information this is hard for us to look into.
Coul you share the output of `gradlew app:dependencies`?
