### ISSUE TITLE
java.lang.NullPointerException  TelemetryUtils

### ISSUE THREAD

**Issue by TooLazyy** [mapbox/mapbox-gl-native#13388]
Exception: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at com.mapbox.android.telemetry.TelemetryUtils.obtainApplicationState(TelemetryUtils.java:103)
       at com.mapbox.android.telemetry.LocationEvent.<init>(LocationEvent.java:44)
       at com.mapbox.android.telemetry.LocationMapper.createLocationEvent(LocationMapper.java:32)
       at com.mapbox.android.telemetry.LocationMapper.from(LocationMapper.java:18)
       at com.mapbox.android.telemetry.LocationReceiver.sendEvent(LocationReceiver.java:47)
       at com.mapbox.android.telemetry.LocationReceiver.onReceive(LocationReceiver.java:26)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Mapbox SDK** - 6.7.0
**Devices** (by Fabric report): 
 * **Samsung** - SM-N900, SM-J320F, GT-I8190 (95% of crashes)
* **Acer** - A3-A11 (5% of crashes)

**Android versions**: 4.1.2, 4.2.2, 5.0, 5.1.1.

**P.S.** Also using com.mapbox.mapboxsdk:mapbox-android-plugin-localization:0.6.0-SNAPSHOT.

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @TooLazyy. This one is fixed by https://github.com/mapbox/mapbox-events-android/pull/272 and available in the `v6.7.1` of the Maps SDK. Closing as not actionable, but please let us know if upgrading the version did not resolve the issue for you, thanks!
