### ISSUE TITLE
App crashes when run using .aar module

### ISSUE THREAD

**Issue by Mohammad-Faisal** [mapbox/mapbox-gl-native#13413]
I built .aar file from source code. Then created a new project and added that as a module. it is built successfully but as soon as the app starts it crashes . Here is the output from log 

11-20 15:33:55.764 11044-11062/com.example.faisal.dingiapi E/libc: Access denied finding property "vendor.debug.egl.profiler"
11-20 15:33:55.765 11044-11062/com.example.faisal.dingiapi E/libc: Access denied finding property "vendor.debug.prerotation.disable"
11-20 15:33:55.807 11044-11044/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.faisal.dingiapi, PID: 11044
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/telemetry/MapboxTelemetry;
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:28)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:21)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:130)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at com.example.faisal.dingiapi.MainActivity.onCreate(MainActivity.java:23)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.telemetry.MapboxTelemetry" on path: DexPathList[[zip file "/data/app/com.example.faisal.dingiapi-lM0v0jgC4fxKE43rhbkdkw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.faisal.dingiapi-lM0v0jgC4fxKE43rhbkdkw==/lib/arm64, /data/app/com.example.faisal.dingiapi-lM0v0jgC4fxKE43rhbkdkw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:28) 
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:21) 
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:130) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60) 
        at com.example.faisal.dingiapi.MainActivity.onCreate(MainActivity.java:23) 
        at android.app.Activity.performCreate(Activity.java:7149) 
        at android.app.Activity.performCreate(Activity.java:7140) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

### Steps to reproduce

 1. build .aar from source
 2. add this .aar file as module into another project
 3. run the app

### Expected behavior
The app should run and load map succesfully

### Actual behavior
It crashes in opening

**Comment by Mohammad-Faisal** [comment]
here is my manifest file 


<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.faisal.dingiapi">

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />


    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity android:name=".MainActivity">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by Mohammad-Faisal** [comment]
my  app level build.gradle file


apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.faisal.dingiapi"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':MapboxGLAndroidSDK-release')

}

**Comment by Mohammad-Faisal** [comment]
@tobrun can you help please?

**Comment by tobrun** [comment]
@Mohammad-Faisal the error message shows that it can't reference one of the dependencies. You probably need to add these to make your module compile:
```
    api(dependenciesList.mapboxAndroidTelemetry) {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
    api dependenciesList.mapboxJavaGeoJSON
    api dependenciesList.mapboxAndroidGestures
    implementation dependenciesList.mapboxJavaTurf
    implementation dependenciesList.supportAppcompatV7
    implementation dependenciesList.supportAnnotations
    implementation dependenciesList.supportFragmentV4
    implementation dependenciesList.okhttp3
```
 these come from `/gradle/dependencies.gradle` file

Closing this as answered, let us know if you have any additional issues

**Comment by Mohammad-Faisal** [comment]
I tried to add these dependencies in my app level build.gradle file but i got an error and gradle sync was unsuccesful. The error was

`Could not get unknown property 'dependenciesList' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

Sorry for my ignorance but can you please tell me exactly where in my project should i add these lines? 
@tobrun

**Comment by LukasPaczos** [comment]
Hey @Mohammad-Faisal, the `dependeciesList` is just our way to keep our `build.gradle` files clean. The dependencies are declared in one shared file [`dependencies.gradle`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/gradle/dependencies.gradle) that we reuse across the project.

**Comment by Mohammad-Faisal** [comment]
@LukasPaczos   Thank you bro. Problem solved !

**Comment by openGLnoob** [comment]
@LukasPaczos Not mapbox_gl_native, not mapbox_java has no dependencies.gradle. Where I can find that? 
@Mohammad-Faisal How did you solve this?

**Comment by openGLnoob** [comment]
For two days I'm trying to figure out which dependency lacks and what version of dependency this will work. This build.gradle works for me:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.1"

    defaultConfig {
        applicationId "com.example.navigation"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation project(':mapbox-android-sdk-9.3.0')

    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
    implementation 'com.squareup.okhttp3:okhttp:4.8.0'
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation "com.mapbox.mapboxsdk:mapbox-sdk-turf:5.4.1"
    api 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.0.0'
    api 'com.mapbox.mapboxsdk:mapbox-java-geojson:2.2.10'
    api "com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0"
}`
