### ISSUE TITLE
Telemetry Service Crashes on background even though it's disabled.

### ISSUE THREAD

**Issue by mhr9o2o** [mapbox/mapbox-gl-native#13528]
### Steps to reproduce

 1. After Initializing the map, we disable the telemetry service using: TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED);
 2. In some cases which are unfamiliar to us, on some devices, it crashes on the background.
 3. The log is as follow:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at com.mapbox.android.telemetry.TelemetryUtils.obtainApplicationState(SourceFile:103)
       at com.mapbox.android.telemetry.LocationEvent.(SourceFile:44)
       at com.mapbox.android.telemetry.LocationReceiver.com.mapbox.android.telemetry.LocationMapper.createLocationEvent(SourceFile:2032)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(SourceFile:311)
       at android.support.v4.content.LocalBroadcastManager$1.android.support.v4.content.LocalBroadcastManager.access$000(SourceFile:1047)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Expected behavior
When Telemetry is disabled, it means, we don't want any action from this service.

### Actual behavior
Seems that telemetry is not disabled, and it also crashes.

### Configuration

**Android versions: Observed on 5 and 7 ** 
**Device models: Observed on HTC_D728x100, Moto C Plus and Xperia M2 dual ** 
**Mapbox SDK versions: 6.7.0 **

**Comment by tobrun** [comment]
cc @electrostat @andrlee

**Comment by andrlee** [comment]
@mhr9o2o the crash has been fixed in the latest https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v6.7.2.  The `TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED);` fix is in works atm and you can track its progress via https://github.com/mapbox/mapbox-events-android/issues/281. Please let us know if this was helpful.

**Comment by mhr9o2o** [comment]
@andrlee Thanks a lot Andrey!

**Comment by tobrun** [comment]
Capturing from https://github.com/mapbox/mapbox-gl-native/issues/13528#issuecomment-445486079 that this issue is already adressed. Thank you @andrlee for :eyes: . Closing as resolved
