### ISSUE TITLE
Error: ProcessLifecycleOwnerInitializer on Android

### ISSUE THREAD

**Issue by albertocappellina** [mapbox/mapbox-gl-native#13586]
Hi, i just tried to add a mapview to a simple activity. when trying to run i get this error 

 java.lang.RuntimeException: Unable to get provider android.arch.lifecycle.ProcessLifecycleOwnerInitializer: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer

### Steps to reproduce

 1. add  implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.2' to gradle 
 2. press run
 3. adding 

 implementation "android.arch.lifecycle:runtime:1.1.1"
    implementation "android.arch.lifecycle:extensions:1.1.1"
    implementation "android.arch.lifecycle:viewmodel:1.1.1" // use -ktx for Kotlin
    implementation "android.arch.lifecycle:livedata:1.1.1"
    kapt "android.arch.lifecycle:compiler:1.1.1" // use kapt for Kotlin

didn't help

### Expected behavior

At least running. No problem on Nexus 6p on Android 8.1.0

### Actual behavior

Got this error

2018-12-14 16:53:53.531 7103-7103/it.intesys.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.intesys.myapplication, PID: 7103
    java.lang.RuntimeException: Unable to get provider android.arch.lifecycle.ProcessLifecycleOwnerInitializer: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/data/app/it.intesys.myapplication-Yd4Kn_vIl9MqWGQ63721MA==/base.apk"],nativeLibraryDirectories=[/data/app/it.intesys.myapplication-Yd4Kn_vIl9MqWGQ63721MA==/lib/arm64, /data/app/it.intesys.myapplication-Yd4Kn_vIl9MqWGQ63721MA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6437)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6000)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5912)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)

### Configuration

**Android versions: 8.0.0 ** 
**Device models: LG G6** 
**Mapbox SDK versions: 6.7.2** 

No problem on Nexus 6p on Android 8.1.0

**Comment by albertocappellina** [comment]
Hi and thanks for the response!

The third time i cleaned, it started working. Thanks again
