### ISSUE TITLE
Mapbox GL can't be download via npm

### ISSUE THREAD

**Issue by danger89** [mapbox/mapbox-gl-native#13656]
**Platform:** Linux
**Mapbox SDK version:** NA

### Steps to trigger behavior

 1. Installing mapbox (eg. via `npm install -g tileserver-gl`) using npm v6.4.1.

### Expected behavior
Downloading the tarball from your server:
https://mapbox-node-binary.s3.amazonaws.com/@mapbox

Finished OK.

### Actual behavior

```

> @mapbox/mapbox-gl-native@4.0.0 install /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node


WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v4.0.0/node-v59-linux-x64-Release.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/tileserver-gl/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:185:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/tileserver-gl/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:180:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:540:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:445:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:180:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:274:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:261:11)
node-pre-gyp ERR! System Linux 4.9.0-8-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/tileserver-gl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
node-pre-gyp ERR! node -v v9.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
...

npm ERR! errno 2
npm ERR! @mapbox/mapbox-gl-native@4.0.0 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @mapbox/mapbox-gl-native@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by kkaefer** [comment]
ABI version 59 was used in Node v9, which is an unstable line. We don't provide binaries for those. Please upgrade to Node 10.x or downgrade to Node 8.x.

**Comment by danger89** [comment]
V10 is indeed lts. Thanks for your reply,

**Comment by hkrutzer** [comment]
Node 10 can segfault: https://github.com/mapbox/mapbox-gl-native/issues/12252
