### ISSUE TITLE
Fatal Exception: com.mapbox.mapboxsdk.style.layers.CannotAddLayerException

### ISSUE THREAD

**Issue by viveksaruk** [mapbox/mapbox-gl-native#13848]
I am trying to add a layer named 'farmLayer' above a layer named 'plotLayer'(which is created and added) but facing a below crash while adding 'farmLayer'. Although 'farmlayer' is not added.

Fatal Exception: com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer farmsLayer already exists
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayerAbove(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.addLayerAbove(NativeMapView.java:683)
       at com.mapbox.mapboxsdk.maps.MapboxMap.addLayerAbove(MapboxMap.java:341)
       at com.kisanhub.myfarm.MapFragment.addFarmsLayerToMap(MapFragment.java:476)
       at com.kisanhub.myfarm.MapFragment.drawFarms(MapFragment.java:461)
       at com.kisanhub.myfarm.MapFragment.drawPlots(MapFragment.java:401)
       at com.kisanhub.myfarm.MapFragment.drawFields(MapFragment.java:350)
       at com.kisanhub.myfarm.MapFragment$2.run(MapFragment.java:273)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

### Configuration

**Android versions:*8.0.0* 
**Device models:*Samsung Galaxy J7* 
**Mapbox SDK versions:*5.5.0*

**Comment by LukasPaczos** [comment]
Hey @viveksaruk, thanks for reaching out!

Since `v5.5.0` we've rebuilt the layers/sources management system, so this issue isn't actionable for us at this point. Would you be able to retest using any of the `7.x.x` releases and let us know whether it still doesn't work for you?

You can find migration guides for major versions here:
[5.x -> 6.x](https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide)
[6.x -> 7x](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide)

**Comment by viveksaruk** [comment]
Thanks, @LukasPaczos for the quick reply. I will migrate to 7x and will let you know if it arises again.

**Comment by tobrun** [comment]
Closing as stale, but feel free to reach out if this is still an issue with a more recent version.
