### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13844]
When I trigger certain touch events (I haven't really figured out which one yet) on the mapview, the mapview crashes with the following exception:

2019-01-31 11:55:17.694 12672-12672/app.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.android.dev, PID: 12672
    java.lang.NoClassDefFoundError: Failed resolution of: Ltimber/log/Timber;
        at com.mapbox.android.gestures.MultiFingerGesture.analyzeEvent(MultiFingerGesture.java:83)
        at com.mapbox.android.gestures.ProgressiveGesture.analyzeEvent(ProgressiveGesture.java:46)
        at com.mapbox.android.gestures.BaseGesture.analyze(BaseGesture.java:56)
        at com.mapbox.android.gestures.BaseGesture.onTouchEvent(BaseGesture.java:34)
        at com.mapbox.android.gestures.AndroidGesturesManager.onTouchEvent(AndroidGesturesManager.java:186)
        at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:211)
        at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:467)
        at app.android.dev.mapbox.view.CustomMapView.onTouchEvent(CustomMapView.kt:137)
        at android.view.View.dispatchTouchEvent(View.java:12513)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
2019-01-31 11:55:17.697 12672-12672/com.domesticcat.mte.android.dev E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "timber.log.Timber" on path: DexPathList[[zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/base.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_dependencies_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_resources_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_0_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_1_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_2_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_3_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_4_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_5_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_6_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_7_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_8_apk.apk", zip file "/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/lib/arm64, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/base.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2019-01-31 11:55:17.699 12672-12672/app.android.dev E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 63 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/app.android.dev-gvy23D0Huz8Ot6GBeNWAeg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5798)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        		... 4 more

According to the changelog of 7.1.0, timber should not be part of mapbox anymore, correct? I had no problems with 7.0.0.

### Configuration

**Android versions:** 9.0.0
**Device models:** Pixel XL
**Mapbox SDK versions:** 7.1.0

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @Mordag. Correct, timber should not be a Maps SDK's dependency, but we excluded it prematurely. The workaround for now is to manually add a `Timber` dependency:
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.1.0'
implementation 'com.jakewharton.timber:timber:4.7.1'
```
