### ISSUE TITLE
Crash when switching style

### ISSUE THREAD

**Issue by hurrba** [mapbox/mapbox-gl-native#14138]
We see an increase in crash reports due to switching map styles. The problem occurs when trying to set `renderMode` on `LocationComponent` before the map is fully loaded. You throw an `IllegalStateException` with the message `Calling getSourceAs when a newer style is loading/has loaded`. 

We handle it by checking `map?.style?.isFullyLoaded` before setting `renderMode`, but is it really necessary to throw an exception in this scenario? What are the implications if you simply log a warning/error instead? 

### Steps to reproduce

 1. Set style to map
 2. Change style
 3. Set `locationComponent.renderMode` before the new style is fully loaded

### Configuration

**Android versions: 9** 
**Device models: OnePlus 6** 
**Mapbox SDK versions: 7.1.2** 

### Stacktrace
```
Caused by java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.
       at com.mapbox.mapboxsdk.maps.Style.validateState(Style.java:482)
       at com.mapbox.mapboxsdk.maps.Style.getSourceAs(Style.java:127)
       at com.mapbox.mapboxsdk.location.LocationLayerController.refreshSource(LocationLayerController.java:278)
       at com.mapbox.mapboxsdk.location.LocationLayerController.setBearingProperty(LocationLayerController.java:258)
       at com.mapbox.mapboxsdk.location.LocationLayerController.updateForegroundBearing(LocationLayerController.java:203)
       at com.mapbox.mapboxsdk.location.LocationComponent.updateLayerOffsets(LocationComponent.java:1145)
       at com.mapbox.mapboxsdk.location.LocationComponent.setRenderMode(LocationComponent.java:523)
       at dk.hopper.hopper.map.MapFragment$enableLocationPlugin$4.onChanged(MapFragment.kt:649)
       at dk.hopper.hopper.map.MapFragment$enableLocationPlugin$4.onChanged(MapFragment.kt:79)
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:121)
       at android.arch.lifecycle.LiveData.access$400(LiveData.java:59)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:416)
       at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
       at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
       at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
       at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
       at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2485)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1494)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3235)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:628)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
       at android.app.Activity.performStart(Activity.java:6930)
       at android.app.Activity.performRestart(Activity.java:7004)
       at android.app.Activity.performResume(Activity.java:7009)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3622)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3687)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by tobrun** [comment]
If we would just execute is this case, it would add a source to the old style and crash as we can't execute the animator on the new style as the source isn't available. To fix this issue you need to make use of the second callback parameter of setStyle. This provides you a hook for which you should be able to call setRenderMode correctly.

**Comment by cerberusv2px** [comment]
facing the same issue. How to fix this?

**Comment by JobGetabu** [comment]
@tobrun How did you fix it ?

**Comment by cerberusv2px** [comment]
Nevermind. I fixed it by overriding all the available lifecycle methods provided by mapbox

**Comment by dshazly** [comment]
How did you solve the problem?
