### ISSUE TITLE
[Android] IllegalArgumentException with EGLConfigChooser

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14152]
I have observed some crashes with mapbox related to the EGLConfigChooser. I can't really name details, but I have noticed crashes since updating to mapbox 7.x with devices running Android 7.x.

```
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:276)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:201)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:84)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1051)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1421)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)
```

And another:

```
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:274)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:199)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:84)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1051)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1421)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)
```

Is it possible if someone takes a look at this crash? Maybe it is caused by some recent changes?

If there are no changes made that should case this issue, is it possible to translate this exception into something which only creates a log? Or is that going to create even more issues?

### Configuration

**Android versions:** 7.1.1, 7.0.0
**Device models:** Galaxy Tab A 8.0
**Mapbox SDK versions:** 7.2.0

**Comment by rohitr308** [comment]
We have been seeing a lot of these errors too:

```
Fatal Exception: java.lang.IllegalArgumentException Raw Text
--
  | com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib (EGLImpl.java)
  | com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr (EGLConfigChooser.java:274)
  | com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig (EGLConfigChooser.java:199)
  | com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig (EGLConfigChooser.java:84)
  | android.opengl.GLSurfaceView$EglHelper.start (GLSurfaceView.java:1042)
  | android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1412)
  | android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1259)

```

**Mapbox SDK version** 6.7.2

**Comment by anisart** [comment]
```
java.lang.IllegalArgumentException: 
  at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib (EGLImpl.java)
  at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig (EGLConfigChooser.java)
  or                     .getConfigAttr (EGLConfigChooser.java)
  or                     .getConfigAttributes (EGLConfigChooser.java)
  or                     .getNumberOfConfigurations (EGLConfigChooser.java)
  or                     .getPossibleConfigurations (EGLConfigChooser.java)
  at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig (EGLConfigChooser.java)
  or                     .getConfigAttr (EGLConfigChooser.java)
  or                     .getConfigAttributes (EGLConfigChooser.java)
  or                     .getNumberOfConfigurations (EGLConfigChooser.java)
  or                     .getPossibleConfigurations (EGLConfigChooser.java)
  at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig (EGLConfigChooser.java)
  at android.opengl.GLSurfaceView$EglHelper.start (GLSurfaceView.java:1051)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1421)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1268)
```
Mapbox SDK 7.3.0, Android 7.1.1, Samsung Galaxy J5(2016)

**Comment by sjr** [comment]
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:276)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:201)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:84)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1036)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1416)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)

This is still happening, we have 7144 of these crashes in the last 90 days.

All crashes are on Android 6, 7, and 8, and across many versions of mapbox up to and including the latest.  Happens on many different devices and manufacturers, although a majority of these are on LGE(58%), Motorola(24%), and Samsung(12%) devices for us.
