### ISSUE TITLE
App crashing when launched

### ISSUE THREAD

**Issue by hussi1** [mapbox/mapbox-gl-native#14372]
Previously i was using version 'com.mapbox.mapboxsdk:mapbox-android-sdk:1.0.0' i changed my version to 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0' and App stated crashing and it looks like its a native mapbox crash.

Here is my Mapview :
<com.mapbox.mapboxsdk.maps.MapView
                android:id="@+id/map"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_weight="1"             
                />

My LogCat : 
No implementation found for void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeInitialize(com.mapbox.mapboxsdk.maps.renderer.MapRenderer, float, java.lang.String, java.lang.String) (tried Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize and Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize__Lcom_mapbox_mapboxsdk_maps_renderer_MapRenderer_2FLjava_lang_String_2Ljava_lang_String_2)
04-09 12:53:32.108 13854-13854/com.app.TourFly D/AndroidRuntime: Shutting down VM
04-09 12:53:32.118 13854-13854/com.app.TourFly E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.app.TourFly, PID: 13854
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.TourFly/com.app.stanley.HomeActivity}: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                  Caused by: android.view.InflateException: Binary XML file line #94: Binary XML file line #94: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
                                                                     at android.app.Activity.setContentView(Activity.java:2387)
                                                                     at com.app.stanley.HomeActivity.onCreate(HomeActivity.java:264)
                                                                     at android.app.Activity.performCreate(Activity.java:6876)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                  Caused by: android.view.InflateException: Binary XML file line #94: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                     at android.app.Activity.setContentView(Activity.java:2387) 
                                                                     at com.app.stanley.HomeActivity.onCreate(HomeActivity.java:264) 
                                                                     at android.app.Activity.performCreate(Activity.java:6876) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474) 
                                                                     at android.app.Activity.setContentView(Activity.java:2387) 
                                                                     at com.app.stanley.HomeActivity.onCreate(HomeActivity.java:264) 
                                                                     at android.app.Activity.performCreate(Activity.java:6876) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                  Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeInitialize(com.mapbox.mapboxsdk.maps.renderer.MapRenderer, float, java.lang.String, java.lang.String) (tried Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize and Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize__Lcom_mapbox_mapboxsdk_maps_renderer_MapRenderer_2FLjava_lang_String_2Ljava_lang_String_2)
                                                                     at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeInitialize(Native Method)
                                                                     at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.<init>(MapRenderer.java:38)
                                                                     at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:29)
                                                                     at com.mapbox.mapboxsdk.maps.MapView$5.<init>(MapView.java:296)
                                                                     at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:296)
                                                                     at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:139)
                                                                 	at com.mapbox.mapbox
04-09 12:53:39.053 13854-13862/com.app.mapapp E/art: No implementation found for void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.finalize() (tried Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_finalize and Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_finalize__)
04-09 12:53:39.058 13854-13862/com.app.mapapp E/System: Uncaught exception thrown by finalizer
04-09 12:53:39.073 13854-13862/com.app.mapapp E/System: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.finalize() (tried Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_finalize and Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_finalize__)
                                                             at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.finalize(Native Method)
                                                             at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
                                                             at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
                                                             at java.lang.Thread.run(Thread.java:818)

### Configuration

**Android versions:** compileSdkVersion 28, targetSdkVersion 27
**Device models:**  All Android devices
**Mapbox SDK versions:** 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0', 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.34.0'

**Comment by LukasPaczos** [comment]
Hey @hussi1, thanks for reaching out.

Your issue most likely is, that you are not calling `Mapbox#getInstance` before inflating the `MapView`.

You need to do:
```
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  
  // initialize Mapbox
  Mapbox.getInstance(this, "{token}");
  
  // inflate Views
  setContentView(R.layout.activity_map_simple);
  
  mapView = findViewById(R.id.mapView);
  mapView.onCreate(savedInstanceState);
  mapView.getMapAsync(new OnMapReadyCallback() {
    @Override
    public void onMapReady(@NonNull MapboxMap mapboxMap) {
      mapboxMap.setStyle(new Style.Builder().fromUrl(Style.MAPBOX_STREETS), new Style.OnStyleLoaded() {
        @Override
        public void onStyleLoaded(@NonNull Style style) {
          ...
        }
      });
    }
  });
}
```

The crash will print a clearer error in the `v7.4.0`, see https://github.com/mapbox/mapbox-gl-native/pull/14366.

Closing as answered, but please feel free to reach out if this did not resolve your issue.

**Comment by hussi1** [comment]
Thanks that was the solution
