### ISSUE TITLE
Crash on start app - java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by anisart** [mapbox/mapbox-gl-native#14410]
I have 4 crashes from 2 users in Crashlytics panel for last day
```
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java)
       at ru.anisart.vv.App.onCreate(App.java)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by com.b.a.b: libmapbox-gl.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.sourceDirectories(ApkLibraryInstaller.java)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java)
       at com.getkeepsafe.relinker.ReLinkerInstance.log(ReLinkerInstance.java)
       at com.getkeepsafe.relinker.ReLinkerInstance.log(ReLinkerInstance.java)
       at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$ReLinkerLibraryLoader.load(LibraryLoaderProviderImpl.java)
       at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.(Unknown Source)
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java)
       at ru.anisart.vv.App.onCreate(App.java)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

I use this code for initialization in app
```Kotlin
override fun onCreate() {
        super.onCreate()
        Mapbox.getInstance(applicationContext, PUBLIC_KEY)
    }
```

### Configuration

**Android versions:** 5.0.2, 6.0.1
**Device models:** Batmobile Defy Mini, LG Nexus 5X
**Mapbox SDK versions:** 7.3.0

**Comment by tobrun** [comment]
I believe you are allowed to discard the `Batmobile Defy Mini` crashes (see [here](https://stackoverflow.com/a/47125797/1281750) for context). That said, this crash originates from https://github.com/KeepSafe/ReLinker. Have you seen any more occurences of this on different handsets? or any more reports of this specific issue?

**Comment by anisart** [comment]
Besides the Batmobile this crash happened on LG Nexus 5X (6.0.1) and Simulator vivo X9. Second device don't view like a real. As same as Nexus 5X with 3.33 GB free RAM (2GB in stock OR available to solder 4GB chip). All of 'devices' have ROOT.

I think you can close this issue. I will put comment if I see report from real device.

**Comment by tobrun** [comment]
Thank you for providing additional information. Feel free to follow and thank you for using our products.

**Comment by Gary111** [comment]
@tobrun, fyi, I have the same issue, but none of my devices are rooted. But there is another oddity: all these failures occur within a 3-4 minutes after I deploy the build for internal testing.
