### ISSUE TITLE
CannotAddSourceException: Source mapbox-navigation-waypoint-source already exists

### ISSUE THREAD

**Issue by haroonkhan9426** [mapbox/mapbox-gl-native#14474]
### Expected behavior
Should work fine on all devices

### Actual behavior
Generates this Exception:

Fatal Exception: com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-navigation-waypoint-source already exists
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:848)
       at com.mapbox.mapboxsdk.maps.Style.addSource(Style.java:99)
       at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine.<init>(MapRouteLine.java:156)
       at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:138)
       at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:117)
       at com.tripmate.travelguidePakistan.AddMarkerAndNavigate$3.onResponse(AddMarkerAndNavigate.java:240)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteCallback.onResponse(NavigationRouteCallback.java:30)
       at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:129)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:200)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

### Configuration

**Android versions:  8.1.0** 
**Device models: OPPO A5** 
**Mapbox SDK versions: mapbox-android-sdk:7.1.2, mapbox-android-navigation-ui:0.30.0 **

**Comment by tobrun** [comment]
@haroonkhan9426 this issue is specfifc to `mapbox-android-navigation-ui:0.30.0`as indicated by `Source mapbox-navigation-waypoint-source already exists`. Please open an issue downstream at https://github.com/mapbox/mapbox-navigation-android/issues/new.
