### ISSUE TITLE
(Mapbox Android) Mapboxmap instance throws NullPointerException when closing the mapview

### ISSUE THREAD

**Issue by GeordiRugenbrink** [mapbox/mapbox-gl-native#14587]
When I close my fragment that has the mapview the app crashes and throws the following error:

``E/AndroidRuntime: FATAL EXCEPTION: main
    Process: project.name, PID: 12878
    java.lang.NullPointerException: Attempt to read from field 'com.mapbox.mapboxsdk.maps.MapboxMap project.name.fragments.MapFragment.mapboxMap' on a null object reference
        at project.name.fragments.MapFragment.access$000(MapFragment.java:53)
        at project.name.fragments.MapFragment$MapFragmentLocationCallback.onSuccess(MapFragment.java:281)
        at project.name.fragments.MapFragment$MapFragmentLocationCallback.onSuccess(MapFragment.java:263)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLocationEngineCallbackTransport.onLocationResult(GoogleLocationEngineImpl.java:114)
        at com.google.android.gms.internal.zzcff.zzu(Unknown Source:4)
        at com.google.android.gms.common.api.internal.zzci.zzb(Unknown Source:8)
        at com.google.android.gms.common.api.internal.zzcj.handleMessage(Unknown Source:16)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)``

This is the code in the fragment:

```import android.annotation.SuppressLint;
import android.app.Fragment;
import android.location.Location;
import android.os.Bundle;
import android.os.Looper;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.mapbox.android.core.location.LocationEngine;
import com.mapbox.android.core.location.LocationEngineCallback;
import com.mapbox.android.core.location.LocationEngineProvider;
import com.mapbox.android.core.location.LocationEngineRequest;
import com.mapbox.android.core.location.LocationEngineResult;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.annotations.PolylineOptions;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.geometry.LatLngBounds;
import com.mapbox.mapboxsdk.location.LocationComponent;
import com.mapbox.mapboxsdk.location.LocationComponentActivationOptions;
import com.mapbox.mapboxsdk.location.modes.CameraMode;
import com.mapbox.mapboxsdk.location.modes.RenderMode;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.maps.Style;

import java.lang.ref.WeakReference;
import java.util.ArrayList;
import java.util.List;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import project.name.R;
import project.name.network.RestClient;
import project.name.objects.Route;
import project.name.utils.DrawPointsTask;
import project.name.utils.NoConnectionUtil;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

import staticproject.name.utils.LocationUtil.hasLocationPermission;

public class MapFragment extends Fragment {
    public static final String ROUTE = "ROUTE";
    private static final int TRANSITION_DURATION = 1000;
    private static final int MAX_TRANSITION_DURATION = 5000;
    private static final int CAMERA_BOUND_PADDING = 100;
    private static final int ZOOM_LEVEL = 10;

    @BindView(R.id.container)
    public View container;
    @BindView(R.id.map_view)
    public MapView mapView;

    private MapboxMap mapboxMap;
    private Route route;
    private ArrayList<Point> points;
    private LocationComponent locationComponent;
    private LocationEngine locationEngine;

    private MapFragmentLocationCallback callback = new MapFragmentLocationCallback(this);

    public static MapFragment newInstance(Route route) {
        MapFragment fragment = new MapFragment();
        Bundle args = new Bundle();
        args.putParcelable(ROUTE, route);
        fragment.setArguments(args);
        return fragment;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_map, container, false);
        ButterKnife.bind(this, rootView);
        return rootView;
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        Mapbox.getInstance(getActivity(), getString(R.string.access_token));
        mapView.onCreate(savedInstanceState);
        route = getArguments().getParcelable(ROUTE);
        initiateMap();
    }

    private void initiateMap() {
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                MapFragment.this.mapboxMap = mapboxMap;

                mapboxMap.setStyle(Style.MAPBOX_STREETS, new Style.OnStyleLoaded() {
                    @Override
                    public void onStyleLoaded(@NonNull Style style) {
                        enableLocationPlugin(style);
                    }
                });
                if (points == null) getPoints();
            }
        });
    }

    private void getPoints() {
        RestClient.getInstance(getActivity()).noAccessTokenService.getRouteCoordinates(route.getId()).enqueue(new Callback<List<double[]>>() {
            @Override
            public void onResponse(@NonNull Call<List<double[]>> call, @NonNull Response<List<double[]>> response) {
                if (response.isSuccessful()) {
                    ArrayList<Point> coordinates = new ArrayList<>();
                    List<double[]> locationArray = response.body();
                    if (locationArray != null) {
                        for (int i = 0; i < locationArray.size(); i++) {
                            Point point = Point.fromLngLat(locationArray.get(i)[1], locationArray.get(i)[0]);
                            coordinates.add(point);
                        }
                    }
                    points = coordinates;
                    drawPoints(coordinates);
                }
            }

            @Override
            public void onFailure(@NonNull Call<List<double[]>> call, @NonNull Throwable t) {
                noConnection();
            }
        });
    }

    private void drawPoints(List<Point> points) {
        if (getActivity() != null) {
            new DrawPointsTask(mapboxMap, getActivity().getResources().getColor(R.color.route_line_color), points, new DrawPointsTask.AsyncResponse() {
                @Override
                public void done(@Nullable LatLngBounds latLngBounds, @Nullable PolylineOptions polylineOptions) {
                    if (polylineOptions != null) mapboxMap.addPolyline(polylineOptions);
                    if (latLngBounds != null)
                        mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, CAMERA_BOUND_PADDING), TRANSITION_DURATION);
                }
            }).execute();
        }
    }

    private void noConnection() {
        View.OnClickListener onClickListener = new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                getPoints();
            }
        };
        NoConnectionUtil.makeSnackbar(onClickListener, mapView);
    }

    @SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin(@NonNull Style loadedMapStyle) {
        if (hasLocationPermission(getActivity()) && locationComponent == null) {
            locationComponent = mapboxMap.getLocationComponent();

            LocationComponentActivationOptions location = LocationComponentActivationOptions
                    .builder(getContext(), loadedMapStyle)
                    .useDefaultLocationEngine(false)
                    .build();

            locationComponent.activateLocationComponent(location);
            locationComponent.setLocationComponentEnabled(true);
            locationComponent.setCameraMode(CameraMode.TRACKING);
            locationComponent.setRenderMode(RenderMode.COMPASS);

            initLocationEngine();
        }
    }

    @SuppressLint({"MissingPermission"})
    private void initLocationEngine() {
        locationEngine = LocationEngineProvider.getBestLocationEngine(getActivity());
        LocationEngineRequest locationEngineRequest = new LocationEngineRequest.Builder(TRANSITION_DURATION)
                .setPriority(LocationEngineRequest.PRIORITY_LOW_POWER)
                .setMaxWaitTime(MAX_TRANSITION_DURATION).build();

        locationEngine.requestLocationUpdates(locationEngineRequest, callback, Looper.getMainLooper());
        locationEngine.getLastLocation(callback);
    }

    @SuppressLint("MissingPermission")
    @OnClick(R.id.current)
    public void current() {
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                Location location = locationComponent.getLastKnownLocation();
                if(location != null){
                    LatLng latLng = new LatLng(location.getLatitude(), location.getLongitude());
                    mapboxMap.easeCamera(CameraUpdateFactory.newLatLng(latLng), TRANSITION_DURATION);
                }
            }
        });
    }

    @SuppressWarnings("unused")
    @OnClick(R.id.close)
    public void close() {
        try {
            MapFragmentInterface mapFragmentInterface = (MapFragmentInterface) getActivity();
            mapFragmentInterface.close();
        } catch (ClassCastException e) {
            throw new ClassCastException(getActivity().toString()
                    + " must implement MapFragmentInterface ");
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @SuppressLint("MissingPermission")
    @Override
    public void onStart() {
        super.onStart();
        mapView.onStart();
        if (locationComponent != null && getActivity() != null && hasLocationPermission(getActivity())) locationComponent.onStart();
    }

    @Override
    public void onStop() {
        super.onStop();
        mapView.onStop();
        if (locationComponent != null) locationComponent.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        mapView.onDestroy();
    }

    public interface MapFragmentInterface {
        void close();
    }

    private static class MapFragmentLocationCallback implements LocationEngineCallback<LocationEngineResult> {

        private final WeakReference<MapFragment> activityWeakReference;

        MapFragmentLocationCallback(MapFragment fragment){
            this.activityWeakReference = new WeakReference<>(fragment);
        }

        @Override
        public void onSuccess(LocationEngineResult result) {
            MapFragment fragment = activityWeakReference.get();

            if(fragment != null){
                Location location = result.getLastLocation();

                if(location == null) return;
            }

            if(fragment.mapboxMap != null && result.getLastLocation() != null){
                fragment.mapboxMap.getLocationComponent().forceLocationUpdate(result.getLastLocation());
            }
        }

        @Override
        public void onFailure(@NonNull Exception exception) {
            MapFragment fragment = activityWeakReference.get();
            if(fragment != null) {
                Toast.makeText(fragment.getContext(), exception.getLocalizedMessage(),
                        Toast.LENGTH_SHORT).show();
            }
        }
    }
}
```

I can't seem to figure out what the error is. If you need more information about the problem ask me and I'll try to answer you.

**Comment by tobrun** [comment]
```

**Comment by tobrun** [comment]
You aren't handling the null value of mapboxMap properly or aren't maintaining state correctly.  MapboxMap is iniitliasid asynchronolously. This isn't an issue with the SDK but with tyour code. Nothing to investigate or fix from our end. Closing.
