### ISSUE TITLE
Mapbox crashes with InterruptedException

### ISSUE THREAD

**Issue by TankJK** [mapbox/mapbox-gl-native#14688]
App is getting continuous crash with InterruptedException.

FATAL EXCEPTION: OkHttp events.mapbox.com Writer
java.lang.InterruptedException
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:1991)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2025)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1048)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:820)

Device is Android Samsung S5 with Android 5.0

### Steps to reproduce

 1.App was trying to place the marker and showing route
 2.App crashes randomly after some time.
 3.

### Expected behavior
App should not crash

### Actual behavior
App crashes

### Configuration

**Android versions:** 
Android 5.0
**Device models:** 
Samsung S5 
**Mapbox SDK versions:** 
com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.37.0

**Comment by LukasPaczos** [comment]
Thanks for following up from https://github.com/mapbox/mapbox-android-demo/issues/1059#issuecomment-492948859 @TankJK. Let me actually transition this one to the Navigation SDK's repository.
