### ISSUE TITLE
Error with unit test

### ISSUE THREAD

**Issue by gilromeu** [mapbox/mapbox-gl-native#14725]
Whenever I am going to perform a unit test it presents me with this error

java.lang.ExceptionInInitializerError
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
	at teste.empresa.testesmapbox.MainActivity.onCreate(MainActivity.java:20)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:702)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:102)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:396)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:102)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:107)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:39)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:231)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:190)
	at androidx.test.ext.junit.rules.ActivityScenarioRule.lambda$new$0$ActivityScenarioRule(ActivityScenarioRule.java:68)
	at androidx.test.ext.junit.rules.ActivityScenarioRule$$Lambda$0.get(Unknown Source)
	at androidx.test.ext.junit.rules.ActivityScenarioRule.before(ActivityScenarioRule.java:82)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.getkeepsafe.relinker.MissingLibraryException: mapbox-gl.dll
	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
	at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$ReLinkerLibraryLoader.load(LibraryLoaderProviderImpl.java:38)
	at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
	at teste.empresa.testesmapbox.MainActivity.onCreate(MainActivity.java:20)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7127)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnCreate(Instrumentation.java:1271)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	... 19 more

### Configuration

**Android versions: 5, 8** 
**Device models: Nexus 5x, Samsung Galaxy J7** 
**Mapbox SDK versions: 7.4.0**

**Comment by LukasPaczos** [comment]
Hey @gilromeu, because the Maps SDK is based on native components, you need to either mock all components that have `native` methods or run an instrumentation test. Feel free to check out how we build unit tests internally.
