### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_8ff85ea/Offline;

### ISSUE THREAD

**Issue by vallantain** [mapbox/mapbox-gl-native#14780]
05-28 07:35:39.642 4496-4496/com.test.handheld E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.handheld, PID: 4496
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_8ff85ea/Offline;
        at com.mapbox.mapboxsdk.Mapbox.$jacocoInit(Mapbox.java)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java)
        at com.test.handheld.ActMain.onCreate(ActMain.kt:79)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_8ff85ea.Offline" on path: DexPathList[[zip file "/data/app/com.test.handheld-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.handheld-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.mapbox.mapboxsdk.Mapbox.$jacocoInit(Mapbox.java) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java) 
        at com.test.handheld.ActMain.onCreate(ActMain.kt:79) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_8ff85ea.Offline
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 17 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
05-28 07:35:39.645 423-1692/? W/ActivityManager:   Force finishing activity 1 com.test.handheld/.ActMain
05-28 07:35:39.715 423-1328/? I/OpenGLRenderer: Initialized EGL, version 1.4

### Steps to reproduce
1.
git clone https://github.com/mapbox/mapbox-gl-native
cd mapbox-gl-native
make android-configuration
make android-lib-arm-v7
2.
Apply the MapboxGLAndroidSDK-debug.aar file to my project
3.
Occurs in the code below.
Mapbox.getInstance(applicationContext, resources.getString(R.string.mapbox_access_token))

### Configuration
**Android versions: 5.1.1
**Device models: AOSP-enabled proprietary device
**Mapbox SDK versions: 8.1.0-SNAPSHOT

project build.gradle =================================================
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.3.21'
    ext.anko_version = '0.10.5'
    //ext.googel_version = '11.8.0' //https://developers.google.com/android/guides/releases
    ext.support_version = '28.0.0'//''27.1.1'
    ext.glide_version = '4.6.1'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
module build.gradle=================================================
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'

android {
    signingConfigs {
        config {
            keyAlias 'androiddebugkey'
            keyPassword '******'
            storeFile file('D:/../../..')
            storePassword '******'
        }
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.test.handheld"
        minSdkVersion 22
        targetSdkVersion 22
        versionCode 1
        versionName "0.1.5_1"
        multiDexEnabled true
        //testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'LICENSE.txt'
    }
    lintOptions {
        baseline file("lint-baseline-local.xml")
        checkAllWarnings true
        warningsAsErrors true
        disable 'MissingTranslation', 'GoogleAppIndexingWarning', 'UnpackedNativeCode', 'IconDipSize', 'TypographyQuotes'
        abortOnError false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.config
        }
    }
    dexOptions {
        maxProcessCount 8
        javaMaxHeapSize "2g"
        preDexLibraries true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:support-v4:$support_version"
    implementation "com.android.support:appcompat-v7:$support_version"
    implementation "com.android.support:design:$support_version"
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:multidex:1.0.2'
    //kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    //anko
    implementation "org.jetbrains.anko:anko:$anko_version"
    implementation "org.jetbrains.anko:anko-constraint-layout:$anko_version"
    // retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.2.0'
    //map scaleView
    implementation 'com.github.pengrad:mapscaleview:1.4.0'
    //glide (https://medium.com/@vlonjatgashi/using-glide-with-kotlin-5e345b557547)
    implementation "com.github.bumptech.glide:glide:$glide_version"
    kapt "com.github.bumptech.glide:compiler:$glide_version"
    // lib files
    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    implementation files('libs/jdom-2.0.6.jar')
    implementation files('libs/mail.jar')
    implementation files('libs/Rhino.jar')
    // mapbox sdk
    //implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0'
    implementation project(':MapboxGLAndroidSDK-debug')
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:4.8.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.8.0'
}

**Comment by tobrun** [comment]
@vallantain if you include an .aar file locally it will not download its transitive dependencies. You will have to add the same entries as listed in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/build.gradle#L6 to make it work.

**Comment by priyankkasera** [comment]
@tobrun your given link is showing 404, can you please put it down here, it will really helpful.
