### ISSUE TITLE
[android] OutOfMemoryError when adding infowindow as bitmap 

### ISSUE THREAD

**Issue by moorthysubu** [mapbox/mapbox-gl-native#14960]
When tried to show Info window by generating a bitmap from view, Android system throws OutOfMemory when tried to loan 100+ marks in a map, Here view includes textView & Multiple Imageview with SVG source, So how to implement info window in symbol layer without using bitmaps or any other approaches to fix OutOfMemory exceptions,Thanks in advance

` java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 289988 byte allocation with 97968 free bytes and 87KB until OOM
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:56)
        at com.mapbox.mapboxsdk.maps.NativeMapView$BitmapImageConversionTask.doInBackground(NativeMapView.java:1300)
        at com.mapbox.mapboxsdk.maps.NativeMapView$BitmapImageConversionTask.doInBackground(NativeMapView.java:1273)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) `

**Comment by tobrun** [comment]
> so how to implement info window in symbol layer without using bitmaps 

You can but are limited to the style-spec properties we expose, see https://docs.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol

> any other approaches to fix OutOfMemory exceptions

Are you cleaning up your created views and bitmaps? How are you adding these images to your map?
We recently added a new functionality to lazily load images when needed (see PR in https://github.com/mapbox/mapbox-gl-native/pull/14320).

**Comment by tobrun** [comment]
since their is no follow up from your end and this is an implementation detail on your end. 
Going to close for now.
