### ISSUE TITLE
how can get my Location

### ISSUE THREAD

**Issue by swadallail** [mapbox/mapbox-gl-native#15118]
Hi guys
How can I get the current user Location in a simple way and then I get Latitude and Longitude

### Configuration

**Android versions:*3.1.4* 
**Mapbox SDK versions:*6.6.2'*

**Comment by tobrun** [comment]
https://docs.mapbox.com/android/core/overview/#requesting-location-updates

**Comment by swadallail** [comment]
When you add implementation 'com.mapbox.mapboxsdk:mapbox-android-core:1.3.0'
The app has not worked

**Comment by swadallail** [comment]
This is the error that appears to me

07-16 00:18:30.688 12289-12289/com.example.android.mapbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.mapbox, PID: 12289
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/telemetry/TelemetryService;
        at com.mapbox.android.telemetry.MapboxTelemetry.initializeTelemetryLocationState(MapboxTelemetry.java:434)
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:83)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:47)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.getInstance(TelemetryImpl.java:39)
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:24)
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:128)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
        at com.example.android.mapbox.MainActivity.onCreate(MainActivity.java:330)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.ClassNotFoundException: com.mapbox.android.telemetry.TelemetryService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.android.telemetry.MapboxTelemetry.initializeTelemetryLocationState(MapboxTelemetry.java:434) 
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:83) 
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:47) 
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.getInstance(TelemetryImpl.java:39) 
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:24) 
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:128) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58) 
        at com.example.android.mapbox.MainActivity.onCreate(MainActivity.java:330) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/core/location/LocationEngineListener;
        at com.mapbox.android.telemetry.MapboxTelemetry.initializeTelemetryLocationState(MapboxTelemetry.java:434) 
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:83) 
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:47) 
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.getInstance(TelemetryImpl.java:39) 
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:24) 
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:128) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58) 
        at com.example.android.mapbox.MainActivity.onCreate(MainActivity.java:330) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.core.location.LocationEngineListener" on path: DexPathList[[zip file "/data/app/com.example.android.mapbox-YeLI6UPTAYnh8Y5JH9gxhg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.mapbox-YeLI6UPTAYnh8Y5JH9gxhg==/lib/arm, /data/app/com.example.android.mapbox-YeLI6UPTAYnh8Y5JH9gxhg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.android.telemetry.MapboxTelemetry.initializeTelemetryLocationState(MapboxTelemetry.java:434) 
        at com.mapbox.android.telemetry.MapboxTelemetry.<init>(MapboxTelemetry.java:83) 
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:47) 
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.getInstance(TelemetryImpl.java:39) 
        at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:24) 
        at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:128) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58) 
        at com.example.android.mapbox.MainActivity.onCreate(MainActivity.java:330) 
        at android.app.Activity.performCreate(Activity.java:7258) 
        at android.app.Activity.performCreate(Activity.java:7249) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by swadallail** [comment]
> 
> 
> https://docs.mapbox.com/android/core/overview/#requesting-location-updates

When you add implementation 'com.mapbox.mapboxsdk:mapbox-android-core:1.3.0'
The app has not worked

**Comment by friedbunny** [comment]
Hi @swadallail — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
