### ISSUE TITLE
Probles Building and using Android Mapbox  SDK

### ISSUE THREAD

**Issue by glencaliba** [mapbox/mapbox-gl-native#15270]
Hello I tried to built the SDK.
Before that I have a problem with cmake/mbgl.cmake in the line 100 because it's trying to use the comand npm mapbox-gl-js. What I did is commented. After that I built and it's worked.
The problem is after add in another project the .aar that generate I have an error:
### Steps to reproduce

 1. Comment  cmake/mbgl.cmake  line 100
 2. Built the SDK using the command  BUILDTYPE=Release make apackage in the root of the repo
 3. Create another Project in Android Studio 
 4. Import the arr that I've generated
 5. Build and Run

### Expected behavior

Show a map

### Actual behavior

In the simulator it's break and gives this error : 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 21038
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/soloader/SoLoader;
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:41)
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:64)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:18)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.soloader.SoLoader" on path: DexPathList[[zip file "/data/app/com.example.myapplication-WdZiPwoewdvxYWyLl5iZiw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication-WdZiPwoewdvxYWyLl5iZiw==/lib/x86, /data/app/com.example.myapplication-WdZiPwoewdvxYWyLl5iZiw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:41) 
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43) 
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13) 
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:64) 
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:18) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
Application terminated.
```

### Configuration

**Android versions: 8.1
**Mapbox SDK versions: for android-v8.1.1

**Comment by LukasPaczos** [comment]
A raw AAR file will not include transitive dependencies, you need to add them manually. See [the dependencies list](https://github.com/mapbox/mapbox-gl-native/blob/300f0b59805c45c4d8e6a8033077ef64892f4f24/platform/android/MapboxGLAndroidSDK/build.gradle#L6-L23) to verify what's used.
