### ISSUE TITLE
[android] offline.OfflineDownloadTest is flaky

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#15324]
The `offline.OfflineDownloadTest` device test on [`android-debug-arm-v8`](https://circleci.com/gh/mapbox/mapbox-gl-native/312264) [can fail with](https://console.firebase.google.com/u/1/project/android-gl-native/testlab/histories/bh.1470d2ab45df6f1f/matrices/6359707616996693864/executions/bs.5521b57bcbc8774e/testcases/168):

```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
at java.lang.Object.wait(Native Method)
at java.lang.Thread.parkFor$(Thread.java:2135)
at sun.misc.Unsafe.park(Unsafe.java:358)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1061)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1352)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
at com.mapbox.mapboxsdk.offline.OfflineDownloadTest.offlineDownload(OfflineDownloadTest.kt:50)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:764)
```

/cc @mapbox/maps-android

**Comment by tobrun** [comment]
Looking at the logs for these tests: I'm seeing:

```
08-04 23:54:05.695: I/TestRunner(10438): started: offlineDownload(com.mapbox.mapboxsdk.offline.OfflineDownloadTest)
....
08-04 23:54:35.803: V/Mbgl-HttpRequest(10438): [HTTP] Request was successful (code = 200).
```

Which shows we were still actively downloading the region while the timeout occurred. Proposing to increase the timeout and add additional logging on the offline region status.

**Comment by tobrun** [comment]
While trying to run locally (right clicking a file and click run test):

![image](https://user-images.githubusercontent.com/2151639/63337156-c01d9c00-c340-11e9-9c72-7b3d8bf4f20d.png)


This issue stems from including an extension function in the same file as the test. 
Going to move this to separate file as well.
