### ISSUE TITLE
Fallback fonts query fails on Android 4.3

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#15378]
Typeface verification introduced in https://github.com/mapbox/mapbox-gl-native/pull/15255 throws on Galaxy S3 running Android 4.3. This is something we should investigate for alternatives before https://github.com/mapbox/mapbox-gl-native/pull/15255 is released.
```
Caused by: com.mapbox.mapboxsdk.MapStrictModeException: Map detected an error that would fail silently otherwise: Couldn't load fonts from Typeface - java.lang.NoSuchFieldException: sSystemFontMap
   at com.mapbox.mapboxsdk.MapStrictMode.strictModeViolation(MapStrictMode.java:34)
   at com.mapbox.mapboxsdk.utils.FontUtils.getAvailableFonts(FontUtils.java:60)
   at com.mapbox.mapboxsdk.utils.FontUtils.extractValidFont(FontUtils.java:37)
   at com.mapbox.mapboxsdk.maps.MapboxMapOptions.localIdeographFontFamily(MapboxMapOptions.java:647)
   at com.mapbox.mapboxsdk.maps.MapboxMapOptions.createFromAttributes(MapboxMapOptions.java:255)
   at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:100)

        at java.lang.reflect.Constructor.constructNative(Native Method) 

        at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
   at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
   at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
   at com.mapbox.mapboxsdk.testapp.activity.maplayout.SimpleMapActivity.onCreate(SimpleMapActivity.java:21) 
   at android.app.Activity.performCreate(Activity.java:5372) 
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) 
   at android.app.ActivityThread.access$700(ActivityThread.java:159) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:176) 
   at android.app.ActivityThread.main(ActivityThread.java:5419) 
   at java.lang.reflect.Method.invokeNative(Native Method) 

        at java.lang.reflect.Method.invoke(Method.java:525) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) 
   at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by tobrun** [comment]
Looking through the AOSP source code, seeing that this field was only added for Android Lolipop.
