### ISSUE TITLE
CustomGeometrySource finalize JNI crash

### ISSUE THREAD

**Issue by jheikkola** [mapbox/mapbox-gl-native#15739]
We have mapbox on a fragment using a CustomGeometrySource, and when switching multiple times quickly to another fragment and back again, we'll get a JNI crash from CustomGeometrySource.finalize()

I'll work on a sample project to reproduce this, but figured I'd submit this first, in case you have any immediate suggestions.

### Steps to reproduce

 1. Setup mapbox on a fragment, using all the required fragment lifecycle methods
 2. Switch to another non-map fragment and back, very quickly, about 20 times. It's not reliable to reproduce, maybe because related to GC and timing?

### Actual behavior
application crashes with
```
java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: can't call void com.mapbox.mapboxsdk.style.sources.CustomGeometrySource.releaseThreads() on null object
    java_vm_ext.cc:542]     in call to CallVoidMethodV
    java_vm_ext.cc:542]     from void com.mapbox.mapboxsdk.style.sources.CustomGeometrySource.finalize()
    java_vm_ext.cc:542] "FinalizerDaemon" daemon prio=5 tid=6 Runnable
    java_vm_ext.cc:542]   | group="system" sCount=0 dsCount=0 flags=0 obj=0x12f80330 self=0xe6a6ac00
    java_vm_ext.cc:542]   | sysTid=24345 nice=4 cgrp=default sched=0/0 handle=0xcdc7c970
    java_vm_ext.cc:542]   | state=R schedstat=( 909837804 361102466 717 ) utm=86 stm=4 core=0 HZ=100
    java_vm_ext.cc:542]   | stack=0xcdb79000-0xcdb7b000 stackSize=1042KB
    java_vm_ext.cc:542]   | held mutexes= "mutator lock"(shared held)
    java_vm_ext.cc:542]   native: #00 pc 002e5b0f  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+134)
    ...
    java_vm_ext.cc:542]   native: #48 pc 0001e4a5  /system/lib/libc.so (__start_thread+32)
    java_vm_ext.cc:542]   at com.mapbox.mapboxsdk.style.sources.CustomGeometrySource.finalize(Native method)
    java_vm_ext.cc:542]   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
    java_vm_ext.cc:542]   at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
    java_vm_ext.cc:542]   at java.lang.Daemons$Daemon.run(Daemons.java:103)
    java_vm_ext.cc:542]   at java.lang.Thread.run(Thread.java:764)
```

### Configuration

**Android versions:** 9
**Device models:** Samsung Galaxy XCover 4
**Mapbox SDK versions:** 8.4.0

**Comment by jheikkola** [comment]
Here's a project to reproduce with, just add mapbox token to strings.xml before running and then swap between home and dashboard fragments using the bottom nav
https://github.com/jheikkola/mapbox-fragment-testing

**Comment by jheikkola** [comment]
I found an easier way to reproduce this, just create an instance of CustomGeometrySource, but do not add it to the map as a source. When GC cleans that instance up, its finalizer will crash.

Even though thats not correct usage, I'm guessing this same thing can happen in a memory stressed environment. I'll update the github sample so it crashes at startup.
