### ISSUE TITLE
IllegalStateException when location component receives last location

### ISSUE THREAD

**Issue by jheikkola** [mapbox/mapbox-gl-native#15755]
We're using mapbox in a fragment with a style loaded from uri, a CustomGeometrySource and location component. Sometimes when creating or removing fragment we'll get the below IllegalStateException from style validation when last location is received. 

This seems strange since the location component is activated after style has loaded, in the OnStyleLoaded callback, and I would think that last location is not requested until activation?

### Steps to reproduce
No reliable steps yet.. but seems to happen either when creating or destroying the map fragment

### Actual behavior
application crash with
```
java.lang.IllegalStateException: Calling getLayer when a newer style is loading/has loaded.
        at com.mapbox.mapboxsdk.maps.Style.validateState(Style.java:599)
        at com.mapbox.mapboxsdk.maps.Style.getLayer(Style.java:238)
        at com.mapbox.mapboxsdk.location.LocationLayerController.setLayerVisibility(LocationLayerController.java:225)
        at com.mapbox.mapboxsdk.location.LocationLayerController.show(LocationLayerController.java:164)
        at com.mapbox.mapboxsdk.location.LocationComponent.showLocationLayerIfHidden(LocationComponent.java:1339)
        at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1324)
        at com.mapbox.mapboxsdk.location.LocationComponent.access$1000(LocationComponent.java:97)
        at com.mapbox.mapboxsdk.location.LocationComponent$LastLocationEngineCallback.onSuccess(LocationComponent.java:1512)
        at com.mapbox.mapboxsdk.location.LocationComponent$LastLocationEngineCallback.onSuccess(LocationComponent.java:1500)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.onSuccess(GoogleLocationEngineImpl.java:132)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLastLocationEngineCallbackTransport.onSuccess(GoogleLocationEngineImpl.java:121)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
```

### Configuration

**Android versions:** 9 sdk 28
**Device models:** Samsung Galaxy XCover 4
**Mapbox SDK versions:** 8.4.0

**Comment by LukasPaczos** [comment]
Hey @jheikkola, thanks for reporting the issue. Are you calling all required lifecycle methods? I'm especially thinking about `MapView#onStart` and `MapView`onStop`. Also, are you providing your own location engine?

**Comment by jheikkola** [comment]
Hi @LukasPaczos thanks for looking into this, yes we're calling the lifecycle methods and not providing any custom engine, I suppose its using Google engine by default?

**Comment by jheikkola** [comment]
Here's a sample thats pretty close to what we have.. I havent been able to reproduce the issue with this yet but it should give you an idea of what we have 
https://github.com/jheikkola/mapbox-fragment-testing/tree/location-component-issue
