### ISSUE TITLE
Android place picker exception : bad array lengths

### ISSUE THREAD

**Issue by manjunath-cy** [mapbox/mapbox-gl-native#15780]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lge.myapplication/com.mapbox.mapboxsdk.plugins.places.picker.ui.PlacePickerActivity}: java.lang.RuntimeException: bad array lengths
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3021)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6991)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
     Caused by: java.lang.RuntimeException: bad array lengths
        at android.os.Parcel.readDoubleArray(Parcel.java:1259)
        at com.mapbox.mapboxsdk.camera.CameraPosition$1.createFromParcel(CameraPosition.java:34)
        at com.mapbox.mapboxsdk.camera.CameraPosition$1.createFromParcel(CameraPosition.java:27)
        at android.os.Parcel.readParcelable(Parcel.java:2774)
        at com.mapbox.mapboxsdk.plugins.places.picker.model.AutoValue_PlacePickerOptions$1.createFromParcel(AutoValue_PlacePickerOptions.java:21)
        at com.mapbox.mapboxsdk.plugins.places.picker.model.AutoValue_PlacePickerOptions$1.createFromParcel(AutoValue_PlacePickerOptions.java:13)
        at android.os.Parcel.readParcelable(Parcel.java:2774)
        at android.os.Parcel.readValue(Parcel.java:2668)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3037)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.getString(BaseBundle.java:1155)
        at android.content.Intent.getStringExtra(Intent.java:7458)
        at com.mapbox.mapboxsdk.plugins.places.picker.ui.PlacePickerActivity.onCreate(PlacePickerActivity.java:76)
        at android.app.Activity.performCreate(Activity.java:7159)
        at android.app.Activity.performCreate(Activity.java:7150)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)

**Comment by langsmith** [comment]
I transferred this from https://github.com/mapbox/mapbox-plugins-android because the topic of this ticket is the Maps SDK's `CameraPosition` class.
