### ISSUE TITLE
Issue in location engine callback

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-gl-native#15789]
Hello we are currently encountering an issue with the google location engine implemented in the SDK on Circle CI. I did not find anyway to customize the callback !

### Steps to reproduce

 1. activateLocationComponent on CircleCI

### Expected behavior

Should display the user position

### Actual behavior

Crash the app :
`java.lang.IllegalArgumentException: latitude must be between -90 and 90
at com.mapbox.mapboxsdk.geometry.LatLng.setLatitude(LatLng.java:132)
at com.mapbox.mapboxsdk.geometry.LatLng.<init>(LatLng.java:79)
at com.mapbox.mapboxsdk.geometry.LatLng.<init>(LatLng.java:90)
at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.getPreviousLayerLatLng(LocationAnimatorCoordinator.java:171)
at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:82)
at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1363)
at com.mapbox.mapboxsdk.location.LocationComponent.access$1000(LocationComponent.java:97)
at com.mapbox.mapboxsdk.location.LocationComponent$CurrentLocationEngineCallback.onSuccess(LocationComponent.java:1522)
at com.mapbox.mapboxsdk.location.LocationComponent$CurrentLocationEngineCallback.onSuccess(LocationComponent.java:1510)
at com.mapbox.android.core.location.GoogleLocationEngineImpl$GoogleLocationEngineCallbackTransport.onLocationResult(GoogleLocationEngineImpl.java:114)
at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
at android.os.Handler.dispatchMessage(Handler.java:105)
at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:8)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

### Configuration

**Android versions:**  26
**Device models:** CircleCI Emulator
**Mapbox SDK versions:** 
 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.4.0'
  implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.9.0'
  implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.41.0'
  implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.41.0'

**Comment by LukasPaczos** [comment]
Hey @ben-j69, what are the actual values that the Google location engine returns? We're not hitting this issue in our instrumentation tests on device farms and I would suspect the emulator providing incorrect data.

Generally, if you want to test the `LocationComponent` integration, I wouldn't rely on data that's provided by either emulators or farm devices. You can initialize the component with a `null` engine instead and push updates with `LocationComponent#forceLocationUpdate`.

@alfwatt is it expected that the `LocationEngine` can return `NaN` or infinities as latitude/longitude?

**Comment by ben-j69** [comment]
@LukasPaczos I did not found anyway to check this values since I can not override this location engine implementation and it only occur on CI environment.

I am writing a fix like "if ci does not use location" but the sdk should not crash at this point.

**Comment by LukasPaczos** [comment]
Per docs, [`Location` should always return valid values](https://developer.android.com/reference/android/location/Location.html#getLatitude()). Transferring this to the events repository for now. Let me know if you'd like to handle it differently @alfwatt.
