### ISSUE TITLE
Unable to Create Solution File from CMake

### ISSUE THREAD

**Issue by Pranavpaharia** [mapbox/mapbox-gl-native#15870]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1. Download mapbox-gl-native master branch
 2. Open CMake and set source code to : mapbox-gl-native and build binaries to mapbox-gl-native/build
 3. Hit Configure 

### Expected behavior
Cmake should create a sln file for microsoft visual studio 2017 using  Windows SDK version 10.0.17763.0 to target Windows 10.0.18362

### Actual behavior
I'm not able to generate Visual Studio solution file: CMake gives error:
 `Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
Updating submodules...
Running 'npm install' for mapbox-gl-native...
Finished 'npm install' for mapbox-gl-native...
CMake Error at cmake/mbgl.cmake:54 (message):
  NPM install failed:

  C:\Program Files\nodejs\npm:2

  (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

          ^^^^^

  

  SyntaxError: Unexpected identifier

      at Module._compile (internal/modules/cjs/loader.js:892:18)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
      at internal/main/run_main_module.js:17:11

Call Stack (most recent call first):
  cmake/mbgl.cmake:99 (_npm_install)
  CMakeLists.txt:36 (include)

Configuring incomplete, errors occurred!
See also "E:/GithubRepo/mapbox-gl-native/build/CMakeFiles/CMakeOutput.log".`

Here is the CMakeOutput.log [link](https://gist.github.com/Pranavpaharia/82cece2c4c5d42439fbceb89c1b57251).

**Comment by Pranavpaharia** [comment]
After removing Line 100 from mbgl.cmake which is
`_npm_install("${CMAKE_SOURCE_DIR}/mapbox-gl-js/test/integration" mapbox-gl-js "${CMAKE_SOURCE_DIR}/node_modules/.mapbox-gl-native.stamp")`

Even after this the error persist
