### ISSUE TITLE
[Android] App Crash (NPE on Telemetry) when first installed.... 

### ISSUE THREAD

**Issue by jay77** [mapbox/mapbox-gl-native#15876]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonElement.isJsonArray()' on a null object reference
        at com.mapbox.android.telemetry.CertificateBlacklist.isValidContent(CertificateBlacklist.java:113)
        at com.mapbox.android.telemetry.CertificateBlacklist.saveBlackList(CertificateBlacklist.java:78)
        at com.mapbox.android.telemetry.CertificateBlacklist.onUpdate(CertificateBlacklist.java:145)
        at com.mapbox.android.telemetry.ConfigurationClient.onResponse(ConfigurationClient.java:94)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

I understand the NPE but I don't know why it happened and how to fix. 

### Steps to reproduce

 1. Make MapboxGLAndroidSDK.aar file locally.
 2. Imported as .aar to my project. 
 3. Install to device and it crashs only once. 

Maybe this will give some hint. My map activity has some other 
activities on top of that when first installed and run. 

### Expected behavior
App Not crashing

### Actual behavior
App crashing

### Configuration

**Android versions:** 8.1.0
**Device models:** LG Q6
**Mapbox SDK versions:** 8.4.0

**Comment by jay77** [comment]
I updated gson to latest and it works. Thank you for your support and really sorry.
