### ISSUE TITLE
Runtime crash: terminating with uncaught exception of type jni::PendingJavaException

### ISSUE THREAD

**Issue by vchernetsky** [mapbox/mapbox-gl-native#15928]
Hello,

We started to see these crashes on Android devices today. 
We saw it happening on Android 9, as well as few older phones, with Android 6, 7, 8. 

I tried different versions of the mapbox SDK's: 7.0.1, 7.4.1, 8.4.0, the behavior the same on all of them.

Is this a known issue? Did something happened today? Our code was working fine for a year without much changes. Any advice would be greatly appreciated.

The crash log:

E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
        at com.mapbox.mapboxsdk.maps.Style.toImage(Style.java:1026)
        at com.mapbox.mapboxsdk.maps.Style.addImage(Style.java:343)
        at com.mapbox.mapboxsdk.maps.Style.onDidFinishLoadingStyle(Style.java:570)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:850)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:212)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1268)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1037)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException

2019-11-14 12:56:02.175 15573-15573/? E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
2019-11-14 12:56:02.175 15573-15573/? A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 15573 (oud.amigomobile), pid 15573 (oud.amigomobile)
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: Build fingerprint: 'OnePlus/OnePlus5T/OnePlus5T:9/PKQ1.180716.001/1910081948:user/release-keys'
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: Revision: '0'
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: ABI: 'arm64'
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: pid: 15573, tid: 15573, name: oud.amigomobile  >>> com.amigocloud.amigomobile <<<
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG: Abort message: 'terminating with uncaught exception of type jni::PendingJavaException'
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG:     x0  0000000000000000  x1  0000000000003cd5  x2  0000000000000006  x3  0000000000000008
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG:     x4  fefeff6d6e68736f  x5  fefeff6d6e68736f  x6  fefeff6d6e68736f  x7  7f7f7f7f7f7f7f7f
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG:     x8  0000000000000083  x9  84f11382d1c257be  x10 0000000000000000  x11 fffffffc7ffffbdf
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG:     x12 0000000000000001  x13 000000005dcdbf62  x14 0009fc31565c537f  x15 000075aa11ff3f38
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG:     x16 0000007595d2c2a8  x17 0000007595c4b954  x18 0000000000000010  x19 0000000000003cd5
2019-11-14 12:56:02.262 15719-15719/? A/DEBUG:     x20 0000000000003cd5  x21 0000007fdf9862a8  x22 ffffff80ffffffc8  x23 0000007fdf986360
2019-11-14 12:56:02.263 15719-15719/? A/DEBUG:     x24 0000007fdf986240  x25 0000007fdf986280  x26 000000759684e5e0  x27 0000000000000048
2019-11-14 12:56:02.263 15719-15719/? A/DEBUG:     x28 0000000000000001  x29 0000007fdf9861b0
2019-11-14 12:56:02.263 15719-15719/? A/DEBUG:     sp  0000007fdf986170  lr  0000007595c3f084  pc  0000007595c3f0ac
2019-11-14 12:56:02.300 11645-11686/? E/bt_osi_wakelock: wakelock_acquire wakelock acquired
2019-11-14 12:56:02.301 11645-11687/? E/bt_osi_wakelock: wakelock_release wakelock released
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG: backtrace:
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #00 pc 00000000000220ac  /system/lib64/libc.so (abort+116)
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #01 pc 000000000035d13c  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #02 pc 000000000035d25c  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #03 pc 000000000035b00c  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #04 pc 000000000035a7b0  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #05 pc 000000000035a730  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #06 pc 000000000003c0e4  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #07 pc 00000000000400cc  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #08 pc 00000000000a6850  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #09 pc 0000000000125260  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #10 pc 0000000000127764  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #11 pc 00000000002a7c50  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #12 pc 000000000008dc1c  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #13 pc 0000000000059448  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.346 15719-15719/? A/DEBUG:     #14 pc 00000000000595e4  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #15 pc 0000000000057b04  /data/app/com.amigocloud.amigomobile-LDT9p9Tk9dJwGgDOWhD9tA==/lib/arm64/libmapbox-gl.so
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #16 pc 0000000000014ff8  /system/lib64/libutils.so (android::Looper::pollInner(int)+836)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #17 pc 0000000000014c18  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #18 pc 0000000000127e40  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #19 pc 00000000003ecfec  /system/framework/arm64/boot-framework.oat (offset 0x3d8000) (android.media.MediaExtractor.seekTo [DEDUPED]+140)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #20 pc 0000000000acfb20  /system/framework/arm64/boot-framework.oat (offset 0x3d8000) (android.os.MessageQueue.next+240)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #21 pc 0000000000acd4ac  /system/framework/arm64/boot-framework.oat (offset 0x3d8000) (android.os.Looper.loop+636)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #22 pc 0000000000894868  /system/framework/arm64/boot-framework.oat (offset 0x3d8000) (android.app.ActivityThread.main+664)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #23 pc 0000000000555a4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #24 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #25 pc 000000000045cd00  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #26 pc 000000000045e754  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #27 pc 00000000003ee5b0  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #28 pc 000000000011f6d4  /system/framework/arm64/boot-core-oj.oat (offset 0x115000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #29 pc 0000000000c082e8  /system/framework/arm64/boot-framework.oat (offset 0x3d8000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #30 pc 0000000000c0f4d0  /system/framework/arm64/boot-framework.oat (offset 0x3d8000) (com.android.internal.os.ZygoteInit.main+3088)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #31 pc 0000000000555a4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #32 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #33 pc 000000000045cd00  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #34 pc 000000000045c960  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #35 pc 0000000000361b64  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #36 pc 00000000000b2a2c  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #37 pc 00000000000b5514  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+948)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #38 pc 000000000000251c  /system/bin/app_process64 (main+2000)
2019-11-14 12:56:02.347 15719-15719/? A/DEBUG:     #39 pc 00000000000c8418  /system/lib64/libc.so (__libc_init+88)

Thanks,
Victor

**Comment by vchernetsky** [comment]
Never mind, it's our problem.

**Comment by dbernic** [comment]
how did you solve this problem?

**Comment by dbernic** [comment]
> Never mind, it's our problem.

how did you solve this problem?
