### ISSUE TITLE
[Android] java.lang.UnsatisfiedLinkError when initializing SDK 

### ISSUE THREAD

**Issue by schachi5000** [mapbox/mapbox-gl-native#16178]
Currently we experiencing following error when trying to initialize the Android SDK with our token.

`java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:64)`

SDK Version: 8.3.0
Android API Level: 28
Device Huawei MediaPad M5 (JDN2-L09 )

**Comment by bc67da8d** [comment]
This issue is duplicate and I solved it in #14890

**Comment by leocarona** [comment]
I'm also having this issue. It doesn't happen on some devices, but happens in some other. So far I got crash reports from Samsung Galaxy S3 (API Level 18) and Nexus 5X (API Level 23). The MapBox dependencies I'm using are the most recently released:

>     implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0-beta.1'
>     implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.1.0-beta.1'

**Comment by leocarona** [comment]
Perhaps it'll help if you paste your gradle dependencies here @schachi5000

**Comment by schachi5000** [comment]
This one is the only one we are using

> com.mapbox.mapboxsdk:mapbox-android-sdk:8.3.0

**Comment by leocarona** [comment]
Alright. Apparently we're facing the same issue. I'll also post all my gradle dependencies here as it might be useful when someone brings some idea on how to solve it. 


_dependencies {
    implementation 'com.android.support:multidex:1.0.3'

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.navigation:navigation-fragment:2.2.1'
    implementation 'androidx.navigation:navigation-ui:2.2.1'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-database:19.2.1'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    implementation 'com.google.android.gms:play-services-location:17.0.0'

    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0-beta.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:5.1.0-beta.1'

    def room_version = "2.2.3"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    // optional - RxJava support for Room
    implementation "androidx.room:room-rxjava2:$room_version"
    // optional - Guava support for Room, including Optional and ListenableFuture
    implementation "androidx.room:room-guava:$room_version"
}_

I have tried @bc67da8d suggestion, but still got the crashes.
