### ISSUE TITLE
sqlite cache database is locked

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2121]
I get a few of these errors on a HTC device, api level 21.

E/mbgl﹕ {SQLite Cache}[Database](5): database is locked

**Comment by erf** [comment]
A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 28103 (main)

**Comment by erf** [comment]
And this:

<pre>
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String android.os.SystemProperties.native_get(java.lang.String) (tried Java_android_os_SystemProperties_native_1get and Java_android_os_SystemProperties_native_1get__Ljava_lang_String_2)
at android.os.SystemProperties.native_get(Native Method)
at android.os.SystemProperties.get(SystemProperties.java:52)
at com.htc.customization.HtcCustomizationManager.<init>(HtcCustomizationManager.java:65)
at com.htc.customization.HtcCustomizationManager.<clinit>(HtcCustomizationManager.java:60)
at android.os.Environment$UserEnvironment.getCustomizationReader(Environment.java:523)
at android.os.Environment$UserEnvironment.isDynamicSwitchSupported(Environment.java:534)
at android.os.Environment$UserEnvironment.<init>(Environment.java:222)
at android.os.Environment.initForCurrentUser(Environment.java:142)
at android.os.Environment.<clinit>(Environment.java:136)
at android.os.Environment.getLegacyExternalStorageDirectory(Environment.java:726)
at android.os.Debug.<clinit>(Debug.java:96)
at android.ddm.DdmHandleHello.handleHELO(DdmHandleHello.java:164)
at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:91)
at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
java.lang.UnsatisfiedLinkError: android.os.Debug
at android.ddm.DdmHandleHello.handleFEAT(DdmHandleHello.java:176)
at android.ddm.DdmHandleHello.handleChunk(DdmHandleHello.java:93)
at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
java.lang.UnsatisfiedLinkError: android.os.Debug
at android.ddm.DdmHandleProfiling.handleMPRQ(DdmHandleProfiling.java:215)
at android.ddm.DdmHandleProfiling.handleChunk(DdmHandleProfiling.java:106)
at org.apache.harmony.dalvik.ddmc.DdmServer.dispatch(DdmServer.java:171)
Ab
</pre>

**Comment by ljbade** [comment]
That last one is a bug in the HTC Android customisations.

But I have seen that sqlite error today.

**Comment by erf** [comment]
I have seen a few of the following errors now:
<pre>
Build fingerprint: 'google/hammerhead/hammerhead:5.1.1/LMY48I/2074855:user/release-keys'
Revision: '11'
ABI: 'arm'
pid: 15131, tid: 15131, name: com.isea.embark >>> com.isea.embark <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: obj == null'
r0 00000000 r1 00003b1b r2 00000006 r3 00000000
r4 b6f37e38 r5 00000006 r6 0000000b r7 0000010c
r8 00000000 r9 b486f520 sl b4827800 fp 00000001
ip 00003b1b sp beff6bc0 lr b6db53c5 pc b6dd7f4c cpsr 60070010

backtrace:
#00 pc 00039f4c /system/lib/libc.so (tgkill+12)
#01 pc 000173c1 /system/lib/libc.so (pthread_kill+52)
#02 pc 00017fd3 /system/lib/libc.so (raise+10)
#03 pc 00014795 /system/lib/libc.so (__libc_android_abort+36)
#04 pc 00012f44 /system/lib/libc.so (abort+4)
#05 pc 00228cd7 /system/lib/libart.so (art::Runtime::Abort()+170)
#06 pc 000a7371 /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
#07 pc 000b1b17 /system/lib/libart.so (art::JniAbort(char const*, char const*)+1118)
#08 pc 000b2055 /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
#09 pc 001b4925 /system/lib/libart.so (art::JNI::GetDoubleField(_JNIEnv*, _jobject*, _jfieldID*)+608)
#10 pc 000d94fc /data/app/com.isea.embark-2/lib/arm/libmapbox-gl.so
#11 pc 0026bd3d /data/dalvik-cache/arm/data@app@com.isea.embark-2@base.apk@classes.dex
</pre>

**Comment by ljbade** [comment]
Hmm I seen that one in another ticket...

**Comment by ljbade** [comment]
I hit his today.

**Comment by ljbade** [comment]
This should be fixed in #2345
