### ISSUE TITLE
Disable "Toggle Point Annotations" In TestApp Causes Crash

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2414]
While testing in the `release-android-0.1.0` branch this morning I discovered the following crash.  It's unclear at this time if it's in `master`

Steps to reproduce:

1. Open Navigation Drawer
1. Select "Toggle Point Annotations" to enable
1. Select "Toggle Point Annotations" to disable.  Crash occurs.

```java
09-24 09:46:58.662    2832-2832/com.mapbox.mapboxgl.testapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mapbox.mapboxgl.testapp, PID: 2832
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxgl.annotations.InfoWindow com.mapbox.mapboxgl.annotations.InfoWindow.close()' on a null object reference
            at com.mapbox.mapboxgl.annotations.Marker.hideInfoWindow(Marker.java:81)
            at com.mapbox.mapboxgl.views.MapView.removeAnnotations(MapView.java:590)
            at com.mapbox.mapboxgl.testapp.MainActivity.removeAnnotations(MainActivity.java:457)
            at com.mapbox.mapboxgl.testapp.MainActivity.toggleAnnotations(MainActivity.java:396)
            at com.mapbox.mapboxgl.testapp.MainActivity.access$600(MainActivity.java:40)
            at com.mapbox.mapboxgl.testapp.MainActivity$4.onNavigationItemSelected(MainActivity.java:277)
            at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:146)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.design.internal.NavigationMenuPresenter.onItemClick(NavigationMenuPresenter.java:196)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1247)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3215)
            at android.widget.AbsListView.onTouchUp(AbsListView.java:4021)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3793)
            at android.view.View.dispatchTouchEvent(View.java:8444)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2386)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1727)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2767)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2335)
            at android.view.View.dispatchPointerEvent(View.java:8655)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4261)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4117)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3717)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3683)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3796)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3691)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.
```

**Comment by bleege** [comment]
Tried testing on `master` but ran into same issue as #2401 and the recent fix via e5ff4638b38c497cf37cffde30b46d9af54cc60d didn't work.

Will disable Crashlytics NDK locally to get things working so that I can test.  Depending on results will look to disable Crashlytics NDK in `master` so that it is also usable to developers.

/cc @ljbade

**Comment by bleege** [comment]
Yep, after removing the Crashlytics NDK support I was able to compile and run the TestApp.  It failed at the exact same spot as `release-android-0.1.0`.  Will need to fix.

```java
09-24 10:08:33.372  11522-11522/com.mapbox.mapboxgl.testapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mapbox.mapboxgl.testapp, PID: 11522
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxgl.annotations.InfoWindow com.mapbox.mapboxgl.annotations.InfoWindow.close()' on a null object reference
            at com.mapbox.mapboxgl.annotations.Marker.hideInfoWindow(Marker.java:81)
            at com.mapbox.mapboxgl.views.MapView.removeAnnotations(MapView.java:601)
            at com.mapbox.mapboxgl.testapp.MainActivity.removeAnnotations(MainActivity.java:462)
            at com.mapbox.mapboxgl.testapp.MainActivity.toggleAnnotations(MainActivity.java:401)
            at com.mapbox.mapboxgl.testapp.MainActivity.access$600(MainActivity.java:41)
            at com.mapbox.mapboxgl.testapp.MainActivity$4.onNavigationItemSelected(MainActivity.java:278)
            at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:146)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.design.internal.NavigationMenuPresenter.onItemClick(NavigationMenuPresenter.java:196)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1247)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3215)
            at android.widget.AbsListView$3.run(AbsListView.java:4009)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5721)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by bleege** [comment]
Cherry picking https://github.com/mapbox/mapbox-gl-native/commit/c3fe83f709839b3faf4900eb67f52053234ea363 into `release-android-0.1.0`.

**Comment by incanus** [comment]
Shouldn't we instead avoid calling `hideInfoWindow()` unnecessarily, perhaps on a `null` marker? 

e.g. https://github.com/mapbox/mapbox-gl-native/blob/85ec3eb0a5739c4f7b160d82715d3be51e10a02b/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L568-L578

This calls `hideInfoWindow` on every marker in the set, when we can only have one info window shown.
