### ISSUE TITLE
Orientation crash on Android 4.1.2

### ISSUE THREAD

**Issue by cablegunmaster** [mapbox/mapbox-gl-native#2970]
Mapbox Version 2.2.0 
Api 16
Android 4.1.2

- Keep moving the orientation until this happens. 5-6 times. or just early as the map is not loaded yet.
````LOGCAT
11-07 12:36:15.828 23074-23074/? E/SensorManager: thread start
11-07 12:36:48.058 23074-23945/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:36:50.588 23074-24214/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:36:52.173 23074-24371/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:36:53.623 23074-24483/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:36:55.298 23074-24585/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:36:56.773 23074-24709/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:36:58.893 23074-24830/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:37:00.363 23074-24950/scrumbag.meldploegapp E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime: FATAL EXCEPTION: main
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime: java.lang.NullPointerException
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.mapbox.mapboxsdk.views.MapView.getTopOffsetPixelsForSprite(MapView.java:1931)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.mapbox.mapboxsdk.views.MapView.prepareMarker(MapView.java:1661)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.mapbox.mapboxsdk.views.MapView.addMarker(MapView.java:1681)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at scrumbag.meldploegapp.activities.MapActivity.onResult(MapActivity.java:171)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at scrumbag.meldploegapp.extensions.HttpRequest$1.onResponse(HttpRequest.java:40)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at scrumbag.meldploegapp.extensions.HttpRequest$1.onResponse(HttpRequest.java:36)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:615)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4898)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
11-07 12:37:00.613 23074-23074/scrumbag.meldploegapp E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
````

**Comment by tobrun** [comment]
By looking at stacktrace I'm guessing you are calling addMarker from onResult callback in your MapActivity implementation. Could you verify this? If not could you add the code where you are adding the marker?

**Comment by ljbade** [comment]
I believe the issue here is that via a thread race condition you are calling a `MapView` method before you have called `MapView.onCreate`

You need to cancel any outstanding async `JsonRequest`s in your activties' `onDestroy`. 

@cablegunmaster Can you implement the request cancelling and test if this fixes the issue?

**Comment by cablegunmaster** [comment]
@ljbade You are right! I didn't quit my volley calls on my queue line. 
Which made calls to a context, the context didn't exist anymore.
