### ISSUE TITLE
Unfortunately, mapbox has stopped - android.os.DeadObjectException

### ISSUE THREAD

**Issue by parulshukla** [mapbox/mapbox-gl-native#3494]
Following steps for here to set up simple app - https://www.mapbox.com/help/first-steps-android-sdk/

The app crashes as soon as I open it with following error:
(Please note - I am testing the app on Genymotion)

```java
I/mbgl    ( 2552): {Main}[OpenGL]: EGL Client Extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_image_base EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer
E/mbgl    ( 2552): {Main}[OpenGL]: eglChooseConfig(NULL) returned error 12288
F/libc    ( 2552): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 2552 (a.myapplication)
I/DEBUG   (  142): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  142): Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.buildbot.20150610.102145:userdebug/test-keys'
I/DEBUG   (  142): Revision: '0'
I/DEBUG   (  142): pid: 2552, tid: 2552, name: a.myapplication  >>> com.example.parulshukla.myapplication <<<
I/DEBUG   (  142): signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
I/DEBUG   (  142):     eax b8263c98  ebx 952e0b14  ecx 0000000b  edx 00000001
I/DEBUG   (  142):     esi 00003000  edi 9525bad8
I/DEBUG   (  142):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   (  142):     eip 951b5c2b  ebp bfc3b0c8  esp bfc3b0b0  flags 00210282
E/Corkscrew(  142): unrecognized dwarf lower part encoding: 0x2f
I/DEBUG   (  142):
I/DEBUG   (  142): backtrace:
I/DEBUG   (  142):     #00  pc 0036cc2b  /data/app-lib/com.example.parulshukla.myapplication-1/libmapbox-gl.so
I/BootReceiver(  515): Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
W/ActivityManager(  515):   Force finishing activity com.example.parulshukla.myapplication/.MainActivity
D/Zygote  (  145): Process 2552 terminated by signal (11)
I/WindowManager(  515): Screenshot max retries 4 of Token{52b08720 ActivityRecord{529b34fc u0 com.example.parulshukla.myapplication/.MainActivity t3 f}} appWin=Window{52a550e8 u0 Starting com.example.parulshukla.myapplication} drawState=4
W/WindowManager(  515): Screenshot failure taking screenshot for (1080x1920) to layer 21010
W/ActivityManager(  515): Exception thrown during pause
W/ActivityManager(  515): android.os.DeadObjectException
W/ActivityManager(  515): 	at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  515): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager(  515): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:761)
W/ActivityManager(  515): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2443)
W/ActivityManager(  515): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2320)
W/ActivityManager(  515): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2050)
W/ActivityManager(  515): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9548)
W/ActivityManager(  515): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9441)
W/ActivityManager(  515): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10086)
W/ActivityManager(  515): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9637)
W/ActivityManager(  515): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
I/ActivityManager(  515): Process com.example.parulshukla.myapplication (pid 2552) has died.
W/EGL_genymotion(  725): eglSurfaceAttrib not implemented
```

**Comment by cammace** [comment]
I believe this has something to do with Genymotion and the use of older API levels. Not sure how it can be fixed but a simple work around for testing is to use a more modern device in Genymotion such as the Nexus 5 which doesn't produce the errors you described. Another option is of course to run it off the device itself or use the Android Virtual Device (AVD) instead of Genymotion. Just make sure "Use Host GPU" is checked within the device configuration.

**Comment by parulshukla** [comment]
Thanks @cammace - it works for Nexus 5, so it is an issue with Genymotion then. Thanks so much!
