### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI GetFieldID called with pending exception

### ISSUE THREAD

**Issue by parulshukla** [mapbox/mapbox-gl-native#3514]
Trying to set up mapbox in my app and get the error below. I have followed steps given here: https://www.mapbox.com/android-sdk/examples/

Please note I have tested on Samsung SM-G920V, Android 5.1.1 and Genymotion and I get the same error on both.

Part of build.gradle looks like this:

```gradle
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:3.0.0@aar'){
        exclude group:'com.android.support', module:'design'
        transitive=true
    }
```

The app is using 
-com.android.support:design-22.2.1
-com.android.support:support-annotations:22.2.1
-com.android.support:appcompat-v7:22.2.1

```java
JNI DETECTED ERROR IN APPLICATION: JNI GetFieldID called with pending exception 'java.lang.NoSuchFieldError' thrown in java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String):-2
D/dalvikvm(11886): Added shared lib /data/app-lib/com.tripadvisor.tripadvisor.debug-1/libmapbox-gl.so 0xa507c808
W/System.err(11886): java.lang.NoSuchFieldError: no field with name='mID' signature='Ljava/lang/String;' in class Lcom/mapbox/mapboxsdk/layers/CustomLayer;
W/System.err(11886): at java.lang.Runtime.nativeLoad(Native Method)
W/System.err(11886): at java.lang.Runtime.doLoad(Runtime.java:421)
W/System.err(11886): at java.lang.Runtime.loadLibrary(Runtime.java:362)
W/System.err(11886): at java.lang.System.loadLibrary(System.java:526)
W/System.err(11886): at com.mapbox.mapboxsdk.views.NativeMapView.<clinit>(NativeMapView.java:41)
W/System.err(11886): at com.mapbox.mapboxsdk.views.MapView.initialize(MapView.java:718)
W/System.err(11886): at com.mapbox.mapboxsdk.views.MapView.<init>(MapView.java:659)
W/System.err(11886): at java.lang.reflect.Constructor.constructNative(Native Method)
W/System.err(11886): at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
W/System.err(11886): at android.view.LayoutInflater.createView(LayoutInflater.java:594)
W/System.err(11886): at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
W/System.err(11886): at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
W/System.err(11886): at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
W/System.err(11886): at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
W/System.err(11886): at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
W/System.err(11886): at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
W/System.err(11886): at android.app.Activity.setContentView(Activity.java:1929)
W/System.err(11886): at com.tripadvisor.android.lib.tamobile.activities.MapboxActivity.onCreate(MapboxActivity.java:54)
W/System.err(11886): at android.app.Activity.performCreate(Activity.java:5231)
W/System.err(11886): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
W/System.err(11886): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
W/System.err(11886): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
W/System.err(11886): at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err(11886): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err(11886): at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(11886): at android.os.Looper.loop(Looper.java:136)
W/System.err(11886): at android.app.ActivityThread.main(ActivityThread.java:5001)
W/System.err(11886): at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(11886): at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(11886): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err(11886): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err(11886): at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm(11886): JNI WARNING: JNI function GetFieldID called with exception pending
W/dalvikvm(11886):              in Ljava/lang/Runtime;.nativeLoad:(Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/String;)Ljava/lang/String; (GetFieldID)
W/dalvikvm(11886): Pending exception is:
I/dalvikvm(11886): java.lang.NoSuchFieldError: no field with name='mID' signature='Ljava/lang/String;' in class Lcom/mapbox/mapboxsdk/layers/CustomLayer;
I/dalvikvm(11886):   (raw stack trace not found)
I/dalvikvm(11886): "main" prio=5 tid=1 NATIVE
I/dalvikvm(11886):   | group="main" sCount=0 dsCount=0 obj=0xa4cffbd8 self=0xb872eeb0
I/dalvikvm(11886):   | sysTid=11886 nice=-6 sched=0/0 cgrp=apps handle=-1216929728
I/dalvikvm(11886):   | state=R schedstat=( 5174191786 233898156 33674 ) utm=361 stm=156 core=1
I/dalvikvm(11886):   #00  pc 000bd936  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+86)
I/dalvikvm(11886):   #01  pc 00098513  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+1155)
I/dalvikvm(11886):   #02  pc 00098806  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+86)
I/dalvikvm(11886):   #03  pc 0004d217  /system/lib/libdvm.so (ScopedCheck::checkThread(int)+455)
I/dalvikvm(11886):   #04  pc 0005a1b5  /system/lib/libdvm.so
I/dalvikvm(11886):   #05  pc 000d7d82  /data/app-lib/com.tripadvisor.tripadvisor.debug-1/libmapbox-gl.so (JNI_OnLoad+3874)
I/dalvikvm(11886):   #06  pc 00176d55  /system/lib/libdvm.so (houdini::hookJniOnload(bool, void*, void*, void*)+53)
I/dalvikvm(11886):   #07  pc 0008bf78  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+1352)
I/dalvikvm(11886):   #08  pc 000ceaab  /system/lib/libdvm.so
I/dalvikvm(11886):   #09  pc 00177615  /system/lib/libdvm.so
I/dalvikvm(11886):   at java.lang.Runtime.nativeLoad(Native Method)
I/dalvikvm(11886):   at java.lang.Runtime.doLoad(Runtime.java:421)
I/dalvikvm(11886):   at java.lang.Runtime.loadLibrary(Runtime.java:362)
I/dalvikvm(11886):   at java.lang.System.loadLibrary(System.java:526)
I/dalvikvm(11886):   at com.mapbox.mapboxsdk.views.NativeMapView.<clinit>(NativeMapView.java:41)
I/dalvikvm(11886):   at com.mapbox.mapboxsdk.views.MapView.initialize(MapView.java:-1)
I/dalvikvm(11886):   at com.mapbox.mapboxsdk.views.MapView.<init>(MapView.java:659)
I/dalvikvm(11886):   at java.lang.reflect.Constructor.constructNative(Native Method)
I/dalvikvm(11886):   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
I/dalvikvm(11886):   at android.view.LayoutInflater.createView(LayoutInflater.java:594)
I/dalvikvm(11886):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
I/dalvikvm(11886):   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
I/dalvikvm(11886):   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
I/dalvikvm(11886):   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
I/dalvikvm(11886):   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
I/dalvikvm(11886):   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
I/dalvikvm(11886):   at android.app.Activity.setContentView(Activity.java:1929)
I/dalvikvm(11886):   at com.tripadvisor.android.lib.tamobile.activities.MapboxActivity.onCreate(MapboxActivity.java:54)
I/dalvikvm(11886):   at android.app.Activity.performCreate(Activity.java:5231)
I/dalvikvm(11886):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
I/dalvikvm(11886):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
I/dalvikvm(11886):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
I/dalvikvm(11886):   at android.app.ActivityThread.access$800(ActivityThread.java:135)
I/dalvikvm(11886):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
I/dalvikvm(11886):   at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm(11886):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm(11886):   at android.app.ActivityThread.main(ActivityThread.java:5001)
I/dalvikvm(11886):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(11886):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm(11886):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
I/dalvikvm(11886):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
I/dalvikvm(11886):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(11886):Runtime aborting...
```

**Comment by parulshukla** [comment]
NVM - figured out the problem - proguard was removing the unused field 'mId' in the CustomLayer class

**Comment by tobrun** [comment]
@parulshukla thank you for giving this feedback,
this is something that should be fixed at SDK level. 
Reopening for updating the proguard config.
