### ISSUE TITLE
crash in Source.RasterTileCancel test

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3784]
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/106368286

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aaab353d700 (LWP 14424)]
mbgl::decodeImage(std::string const&) () at /usr/include/c++/4.9/bits/basic_string.h:293
293	      { return  _M_dataplus._M_p; }
Thread 331 (Thread 0x2aaafbe1e700 (LWP 14428)):
#0  0x00002aaaaacdc65d in pthread_cond_broadcast@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00002aaaac5cba19 in std::condition_variable::notify_all() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000665a29 in _ZN4mbgl4util6ThreadINS_6Worker4ImplEE3runISt5tupleIJEEJEEEvNS0_13ThreadContextEOT_St16integer_sequenceImJXspT0_EEE () at /usr/include/c++/4.9/future:374
#3  0x0000000000665d59 in _ZNSt6thread5_ImplISt12_Bind_simpleIFZN4mbgl4util6ThreadINS2_6Worker4ImplEEC4IJEEERKNS3_13ThreadContextEDpOT_EUlvE_vEEE6_M_runEv () at ../../src/mbgl/util/thread.hpp:106
#4  0x00002aaaac5d0a30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00002aaaaacd7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00002aaaacb5c2ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000000000 in ?? ()
Thread 330 (Thread 0x2aab78200700 (LWP 14427)):
#0  0x00002aaaacb58509 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000086428a in uv__epoll_wait (epfd=<optimized out>, events=<optimized out>, nevents=<optimized out>, timeout=<optimized out>) at src/unix/linux-syscalls.c:321
#2  0x0000000000862972 in uv__io_poll (loop=0x2aab7c000c80, timeout=-1) at src/unix/linux-core.c:243
#3  0x0000000000859bd3 in uv_run (loop=0x2aab7c000c80, mode=UV_RUN_DEFAULT) at src/unix/core.c:341
#4  0x0000000000665a58 in _ZN4mbgl4util6ThreadINS_6Worker4ImplEE3runISt5tupleIJEEJEEEvNS0_13ThreadContextEOT_St16integer_sequenceImJXspT0_EEE () at ../../src/mbgl/util/thread.hpp:124
#5  0x0000000000665d59 in _ZNSt6thread5_ImplISt12_Bind_simpleIFZN4mbgl4util6ThreadINS2_6Worker4ImplEEC4IJEEERKNS3_13ThreadContextEDpOT_EUlvE_vEEE6_M_runEv () at ../../src/mbgl/util/thread.hpp:106
#6  0x00002aaaac5d0a30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00002aaaaacd7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00002aaaacb5c2ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x0000000000000000 in ?? ()
Thread 329 (Thread 0x2aab78401700 (LWP 14426)):
#0  0x00002aaaacb58509 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000086428a in uv__epoll_wait (epfd=<optimized out>, events=<optimized out>, nevents=<optimized out>, timeout=<optimized out>) at src/unix/linux-syscalls.c:321
#2  0x0000000000862972 in uv__io_poll (loop=0x2aab80000cd0, timeout=-1) at src/unix/linux-core.c:243
#3  0x0000000000859bd3 in uv_run (loop=0x2aab80000cd0, mode=UV_RUN_DEFAULT) at src/unix/core.c:341
#4  0x0000000000665a58 in _ZN4mbgl4util6ThreadINS_6Worker4ImplEE3runISt5tupleIJEEJEEEvNS0_13ThreadContextEOT_St16integer_sequenceImJXspT0_EEE () at ../../src/mbgl/util/thread.hpp:124
#5  0x0000000000665d59 in _ZNSt6thread5_ImplISt12_Bind_simpleIFZN4mbgl4util6ThreadINS2_6Worker4ImplEEC4IJEEERKNS3_13ThreadContextEDpOT_EUlvE_vEEE6_M_runEv () at ../../src/mbgl/util/thread.hpp:106
#6  0x00002aaaac5d0a30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00002aaaaacd7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00002aaaacb5c2ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x0000000000000000 in ?? ()
Thread 328 (Thread 0x2aab78602700 (LWP 14425)):
#0  0x00002aaaacb58509 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000086428a in uv__epoll_wait (epfd=<optimized out>, events=<optimized out>, nevents=<optimized out>, timeout=<optimized out>) at src/unix/linux-syscalls.c:321
#2  0x0000000000862972 in uv__io_poll (loop=0x2aab84000cd0, timeout=-1) at src/unix/linux-core.c:243
#3  0x0000000000859bd3 in uv_run (loop=0x2aab84000cd0, mode=UV_RUN_DEFAULT) at src/unix/core.c:341
#4  0x0000000000665a58 in _ZN4mbgl4util6ThreadINS_6Worker4ImplEE3runISt5tupleIJEEJEEEvNS0_13ThreadContextEOT_St16integer_sequenceImJXspT0_EEE () at ../../src/mbgl/util/thread.hpp:124
#5  0x0000000000665d59 in _ZNSt6thread5_ImplISt12_Bind_simpleIFZN4mbgl4util6ThreadINS2_6Worker4ImplEEC4IJEEERKNS3_13ThreadContextEDpOT_EUlvE_vEEE6_M_runEv () at ../../src/mbgl/util/thread.hpp:106
#6  0x00002aaaac5d0a30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00002aaaaacd7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00002aaaacb5c2ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x0000000000000000 in ?? ()
Thread 327 (Thread 0x2aaab353d700 (LWP 14424)):
#0  mbgl::decodeImage(std::string const&) () at /usr/include/c++/4.9/bits/basic_string.h:293
#1  0x0000000000662633 in mbgl::Worker::Impl::parseRasterTile () at ../../src/mbgl/util/worker.cpp:22
#2  0x0000000000664b83 in _ZN4mbgl4util7RunLoop7InvokerIZNS0_6ThreadINS_6Worker4ImplEE4bindIMS5_FvSt10unique_ptrINS_12RasterBucketESt14default_deleteIS9_EESt10shared_ptrIKSsESt8functionIFvN6mapbox4util7variantIJS8_INS_6BucketESA_ISK_EENSt15__exception_ptr13exception_ptrEEEEEEEEEDaT_EUlDpOT_E_St5tupleIJSC_SF_ZNS1_18invokeWithCallbackISY_RSR_JRSC_RKSF_EEES8_INS_11WorkRequestESA_IS15_EEOT_OT0_DpOT1_EUlSX_E_EEEclEv () at ../../src/mbgl/util/thread.hpp:73
#3  0x00000000006a5ae5 in mbgl::util::RunLoop::process() () at ../../include/mbgl/util/run_loop.hpp:173
#4  0x000000000085917d in uv__async_event (loop=0x2aaab85df670, w=<optimized out>, nevents=<optimized out>) at src/unix/async.c:92
#5  0x00000000008592d9 in uv__async_io (loop=0x2aaab85df670, w=0x2aaab85df838, events=<optimized out>) at src/unix/async.c:132
#6  0x0000000000862afe in uv__io_poll (loop=0x2aaab85df670, timeout=-1) at src/unix/linux-core.c:345
#7  0x0000000000859bd3 in uv_run (loop=0x2aaab85df670, mode=UV_RUN_DEFAULT) at src/unix/core.c:341
#8  0x0000000000665a58 in _ZN4mbgl4util6ThreadINS_6Worker4ImplEE3runISt5tupleIJEEJEEEvNS0_13ThreadContextEOT_St16integer_sequenceImJXspT0_EEE () at ../../src/mbgl/util/thread.hpp:124
#9  0x0000000000665d59 in _ZNSt6thread5_ImplISt12_Bind_simpleIFZN4mbgl4util6ThreadINS2_6Worker4ImplEEC4IJEEERKNS3_13ThreadContextEDpOT_EUlvE_vEEE6_M_runEv () at ../../src/mbgl/util/thread.hpp:106
#10 0x00002aaaac5d0a30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00002aaaaacd7e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00002aaaacb5c2ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x0000000000000000 in ?? ()
Thread 1 (Thread 0x2aaaaaaf2580 (LWP 14093)):
#0  0x00002aaaaacdeccd in write () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000859535 in uv__async_send (wa=<optimized out>) at src/unix/async.c:161
#2  uv_async_send (handle=<optimized out>) at src/unix/async.c:66
#3  0x000000000069e6e1 in mbgl::util::AsyncTask::send() () at ../../platform/default/async_task.cpp:42
#4  0x00000000006a0499 in mbgl::util::RunLoop::push(std::shared_ptr<mbgl::WorkTask>) () at ../../platform/default/run_loop.cpp:151
#5  0x000000000065f162 in mbgl::Worker::parseRasterTile () at ../../include/mbgl/util/run_loop.hpp:108
#6  0x0000000000689b99 in _ZNSt17_Function_handlerIFvN4mbgl8ResponseEEZNS0_14RasterTileDataC4ERKNS0_6TileIDEfRKSsRNS0_11TexturePoolERNS0_6WorkerERKSt8functionIFvNSt15__exception_ptr13exception_ptrEEEEUlS1_E_E9_M_invokeERKSt9_Any_dataS1_ () at ../../src/mbgl/map/raster_tile_data.cpp:53
#7  0x0000000000433837 in _ZNSt17_Function_handlerIFvvEZN4mbgl14StubFileSourceC4EvEUlvE_E9_M_invokeERKSt9_Any_data () at /usr/include/c++/4.9/functional:2439
#8  0x0000000000860dd8 in uv__run_timers (loop=0xba43e0) at src/unix/timer.c:165
#9  0x0000000000859b30 in uv_run (loop=0xba43e0, mode=UV_RUN_DEFAULT) at src/unix/core.c:332
#10 0x000000000057a4d2 in Source_RasterTileCancel_Test::TestBody() () at ../../test/style/source.cpp:63
#11 0x00000000006f60e3 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#12 0x00000000006e4cb1 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#13 0x00000000006cca25 in testing::Test::Run() ()
#14 0x00000000006cd6ab in testing::TestInfo::Run() ()
#15 0x00000000006cddf7 in testing::TestCase::Run() ()
#16 0x00000000006d56a2 in testing::internal::UnitTestImpl::RunAllTests() ()
#17 0x00000000006f20d3 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#18 0x00000000006e7291 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#19 0x00000000006d535b in testing::UnitTest::Run() ()
#20 0x000000000042b7ff in main () at /home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/gtest/1.7.0/include/gtest/gtest.h:20058
```

**Comment by jfirebaugh** [comment]
Probably introduced in 716997b99eed50ecf35fd1ec3124a85760a05753.
