### ISSUE TITLE
JNI Error When CameraPosition.Builder() API Used With Only zoom

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3811]
I encountered the following error earlier today.  We'll need to add some logic around the CameraPostion Builder to use the current cameraPostion (aka LatLng) if one isn't specified.  This likely impacts `bearing()` and `tilt()` when used individually as well.

```java
// JNI Error
CameraPosition cp = new CameraPosition.Builder().zoom(3).build();
mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(cp));

// Works
CameraPosition cp = new CameraPosition.Builder().zoom(3).target(new LatLng(0, 0)).build();
mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(cp));
```

```java
02-03 15:43:18.229 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: field operation on NULL object: 0x0
02-03 15:43:18.229 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]     in call to GetDoubleField
02-03 15:43:18.229 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]     from void com.mapbox.mapboxsdk.maps.NativeMapView.nativeFlyTo(long, double, com.mapbox.mapboxsdk.geometry.LatLng, long, double, double)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x739672a0 self=0xf5336500
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=19681 nice=0 cgrp=default sched=0/0 handle=0xf74d6b34
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 10158903282 2352502363 14731 ) utm=868 stm=147 core=1 HZ=100
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xff76a000-0xff76c000 stackSize=8MB
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 0035a55f  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::ArtMethod*, void*)+126)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 0033b0e7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+138)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0024dfcb  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+750)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0024e66f  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+54)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fbbfd  /system/lib/libart.so (art::ScopedCheck::AbortF(char const*, ...)+28)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 00112999  /system/lib/libart.so (art::ScopedCheck::CheckFieldAccess(art::ScopedObjectAccess&, _jobject*, _jfieldID*, bool, art::Primitive::Type)+2164)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 00113af7  /system/lib/libart.so (art::CheckJNI::GetField(char const*, _JNIEnv*, _jobject*, _jfieldID*, bool, art::Primitive::Type)+486)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 0011406d  /system/lib/libart.so (art::CheckJNI::GetDoubleField(_JNIEnv*, _jobject*, _jfieldID*)+24)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 000e1324  /data/app/com.mapbox.sirius-1/lib/arm/libmapbox-gl.so (???)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 0028f411  /data/app/com.mapbox.sirius-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.NativeMapView.nativeFlyTo(long, double, com.mapbox.mapboxsdk.geometry.LatLng, long, double, double)+196)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00292bd3  /data/app/com.mapbox.sirius-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.NativeMapView.flyTo(double, com.mapbox.mapboxsdk.geometry.LatLng, long, double, double)+214)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 0028424b  /data/app/com.mapbox.sirius-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.MapView.flyTo(double, com.mapbox.mapboxsdk.geometry.LatLng, long, double, double, com.mapbox.mapboxsdk.maps.MapboxMap$CancelableCallback)+374)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 0028b2a7  /data/app/com.mapbox.sirius-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(com.mapbox.mapboxsdk.maps.CameraUpdate, int, com.mapbox.mapboxsdk.maps.MapboxMap$CancelableCallback)+346)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 0028b09f  /data/app/com.mapbox.sirius-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(com.mapbox.mapboxsdk.maps.CameraUpdate)+90)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #14 pc 000e5fc1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #15 pc 003e8807  /system/lib/libart.so (art_quick_invoke_stub+170)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   native: #16 pc 007fc68c  [stack] (???)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.NativeMapView.nativeFlyTo(Native method)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.NativeMapView.flyTo(NativeMapView.java:475)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.MapView.flyTo(MapView.java:1386)
02-03 15:43:18.230 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(MapboxMap.java:194)
02-03 15:43:18.231 19681-19681/com.mapbox.sirius A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(MapboxMap.java:155)
```

/cc @tobrun @zugaldia

**Comment by tobrun** [comment]
Great find @bleege, will try to make this type of use-case more robust

**Comment by tobrun** [comment]
This is the code I reproduced with:
```java
mMapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(
                            new CameraPosition.Builder().zoom(16).build()));
```

Result after fix can be seen [here](https://www.dropbox.com/s/334pfiokq0imuyy/device-2016-02-04-123114.mp4?dl=0).
