### ISSUE TITLE
Test app crashes on install

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#3895]
While testing out the latest test app, I got the following error on start:

```
02-10 18:29:53.287 15513-15513/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 15513
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxsdk.testapp/com.mapbox.mapboxsdk.testapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(boolean)' on a null object reference
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(boolean)' on a null object reference
                                                                                  at com.mapbox.mapboxsdk.testapp.MainActivity.toggleGps(MainActivity.java:555)
                                                                                  at com.mapbox.mapboxsdk.testapp.MainActivity.onStart(MainActivity.java:245)
                                                                                  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                  at android.app.Activity.performStart(Activity.java:6268)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

It looks like the app is calling `toggleGps(false);` before `mMapboxMap` has finished initializing. 

cc: @tobrun @bleege

**Comment by tobrun** [comment]
the `MapboxMap` #3485  refactor is not handling this correctly, will fix

**Comment by tobrun** [comment]
the source of the problem is not handling request permissions correctly.
Following snippet in `toggelGps(false)` fixed this:

```java
     if ((ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION)
                    == PackageManager.PERMISSION_GRANTED) ||
                    (ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION)
                            == PackageManager.PERMISSION_GRANTED)){
                mMapboxMap.setMyLocationEnabled(false);
            }
```

**Comment by tobrun** [comment]
@danswick could you retest?

**Comment by bleege** [comment]
@tobrun This is likely to be an issue in `MapView` too [during the initialization process](https://github.com/mapbox/mapbox-gl-native/blob/43ed846a12d574a7a0465a54ded22507b706462a/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L282).  Can you come up with a more universal solution so that we and other developers don't need to put permissions checks around any and all calls to enable GPS?

**Comment by tobrun** [comment]
@bleege 
> Can you come up with a more universal solution?

Yes we can. Currently the SDK has made managing permissions a responsibility of the end developer. (as you has seen above, this can get messy). The only universal solution I'm seeing for the SDK to be able to manage the permission checks and result itself. This will mean we are going to add another lifecycle method: `onRequestPermissionsResult`. I'm going to base my solution on `LeakCanary`, where they are doing something similar with the write external storage permission. I'm also going to take a look at Google Maps SDK and how they are managing this. 

Going to open another ticket since this issue is not same as initial.

**Comment by tobrun** [comment]
New issue created #3921

**Comment by bleege** [comment]
I think this may be overly complicating things @tobrun.  What I was thinking was that we could leave Permissions requests to the implementing app as that's more their responsibility, but that we could simply add a Permissions Check at the beginning of `setMyLocationEnalbed()` that would ensure that it's ready to go and if not Log an error message to the developer that they need to rethink their workflow.


```java
if (!(ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION)
                    == PackageManager.PERMISSION_GRANTED) &&
                    (!ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION)
                            == PackageManager.PERMISSION_GRANTED)){
Log.w(TAG, "The app doesn't have permissions to use this yet.  Please adjust the workflow.");
return;
            }
```

**Comment by tobrun** [comment]
agreed, will pick this up in upcoming days
