### ISSUE TITLE
flyTo crashes on OnMapChangeListeners when recreating activity

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3900]
`IndexOutOfBoundsException` when returning from background with current `SNAPSHOT-4.0.0`

>FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 24656
                                                                              java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                                  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                  at java.util.ArrayList.get(ArrayList.java:308)
                                                                                  at com.mapbox.mapboxsdk.maps.MapView.onMapChanged(MapView.java:2451)
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:495)
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCancelTransitions(Native Method)
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.cancelTransitions(NativeMapView.java:242)
                                                                                  at com.mapbox.mapboxsdk.maps.MapView.flyTo(MapView.java:1404)
                                                                                  at com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(MapboxMap.java:263)
                                                                                  at com.mapbox.mapboxsdk.maps.UserLocationView.update(UserLocationView.java:307)
                                                                                  at com.mapbox.mapboxsdk.maps.MapView$SurfaceTextureListener.onSurfaceTextureUpdated(MapView.java:1526)
                                                                                  at android.view.TextureView.applyUpdate(TextureView.java:443)
                                                                                  at android.view.TextureView.getHardwareLayer(TextureView.java:388)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15151)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by tobrun** [comment]
This only occurs when you have `UserLocaitonView` enabled.

**Comment by tobrun** [comment]
Has something to do with calling `setMyLocationTrackingMode`, this will automatically call `moveCamera` on `MapboxMap`.

**Comment by tobrun** [comment]
The underlying issue is that we are iterating over our `MapChangeListeners` and at the same time removing items from it, which will lead to `IndexOutOfBoundsException` or `ConcurrentModificationException`

**Comment by tobrun** [comment]
Using a `CopyOnWriteArrayList` instead of a standard `ArrayList` resolves this (as suggested [here](http://www.javacodegeeks.com/2011/05/avoid-concurrentmodificationexception.html)). Reopen if you want to handle this differently.
