### ISSUE TITLE
UnsatisfiedLinkError on Intel Atom Processors 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4064]
I noticed that the following 3 devices: 
- Galaxy Tab 3 10.1 (WiFI) running 4.4.2
- Dell Venue 8 7840 running 5.1
- ASUS Memo Pad 7 running 5.0

Were crashing on AWS Device Farm with the following exception:
```
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: android.view.InflateException: Binary XML file line #32: Error inflating class com.mapbox.mapboxsdk.maps.MapView
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at com.mapbox.mapboxsdk.testapp.MainActivity.onCreate(MainActivity.java:103)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.Activity.performCreate(Activity.java:5990)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:534)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.os.Looper.loop(Looper.java:135)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.app.ActivityThread.main(ActivityThread.java:5258)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at java.lang.reflect.Method.invoke(Method.java:372)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: Caused by: java.lang.reflect.InvocationTargetException
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at java.lang.reflect.Constructor.newInstance(Native Method)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	... 25 more
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.mapbox.mapboxsdk.testapp.test-1/base.apk", zip file "/data/app/com.mapbox.mapboxsdk.testapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxsdk.testapp-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libmapbox-gl.so"
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at java.lang.System.loadLibrary(System.java:988)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at com.mapbox.mapboxsdk.maps.NativeMapView.<clinit>(NativeMapView.java:44)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:186)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:158)
02-19 06:41:59.073 26200 26200 E MonitoringInstrumentation: 	... 28 more
```

After looking into the specifications of these devices, I'm noticing they all use an **Intel Atom Processor**.

**Comment by tobrun** [comment]
My own fault, the apk I provided wasn't build with x86 support. closing..
