### ISSUE TITLE
DynamicMarkerActivity crashes on start

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4157]
>  Process: com.mapbox.mapboxsdk.testapp, PID: 2632
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapbox.mapboxsdk.annotations.Icon.getId()' on a null object reference
                                                                                at com.mapbox.mapboxsdk.annotations.MarkerOptions.writeToParcel(MarkerOptions.java:63)
                                                                                at android.os.Parcel.writeParcelable(Parcel.java:1416)
                                                                                at android.os.Parcel.writeValue(Parcel.java:1322)
                                                                                at android.os.Parcel.writeList(Parcel.java:738)
                                                                                at android.os.Parcel.writeValue(Parcel.java:1344)
                                                                                at android.os.Parcel.writeArrayMapInternal(Parcel.java:665)
                                                                                at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                                                at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                                                at android.os.Parcel.writeBundle(Parcel.java:690)
                                                                                at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3152)
                                                                                at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tobrun** [comment]
It seems this only occurring on Genymotion and not on a Nexus 5 device

**Comment by tobrun** [comment]
Now also not able to reproduce this anymore on Genymotion. Nevertheless we should handle this more gracefully. 

I have implemented:

```java
   @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeParcelable(getPosition(), flags);
        out.writeString(getSnippet());
        Icon icon = getIcon();
        out.writeByte((byte) (icon != null ? 1 : 0));
        if (icon != null) {
            out.writeString(getIcon().getId());
            out.writeParcelable(getIcon().getBitmap(), flags);
        }
        out.writeString(getTitle());
    }
```

and recreating this with:

```java
   private MarkerOptions(Parcel in) {
        marker = new Marker();
        position((LatLng) in.readParcelable(LatLng.class.getClassLoader()));
        snippet(in.readString());

        if(in.readByte()!=0){
            // this means we have an icon
            String iconId = in.readString();
            Bitmap iconBitmap = in.readParcelable(Bitmap.class.getClassLoader());
            Icon icon = new Icon(iconId, iconBitmap);
            icon(icon);
        }
        title(in.readString());
    }
```
