### ISSUE TITLE
No implementation Found For OfflineManager.createDefaultFileSource Error

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4175]
The following error occurred while I was trying to download a region using the Offline API.  The last call in the stack trace from Sirius was to do:

`offlineManager = OfflineManager.getInstance(this);`

```java
03-02 17:09:58.759 21556-21556/com.mapbox.sirius E/art: No implementation found for long com.mapbox.mapboxsdk.offline.OfflineManager.createDefaultFileSource(java.lang.String, java.lang.String, long) (tried Java_com_mapbox_mapboxsdk_offline_OfflineManager_createDefaultFileSource and Java_com_mapbox_mapboxsdk_offline_OfflineManager_createDefaultFileSource__Ljava_lang_String_2Ljava_lang_String_2J)
03-02 17:09:58.760 21556-21556/com.mapbox.sirius D/AndroidRuntime: Shutting down VM
03-02 17:09:58.767 21556-21556/com.mapbox.sirius E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.mapbox.sirius, PID: 21556
                                                                   java.lang.UnsatisfiedLinkError: No implementation found for long com.mapbox.mapboxsdk.offline.OfflineManager.createDefaultFileSource(java.lang.String, java.lang.String, long) (tried Java_com_mapbox_mapboxsdk_offline_OfflineManager_createDefaultFileSource and Java_com_mapbox_mapboxsdk_offline_OfflineManager_createDefaultFileSource__Ljava_lang_String_2Ljava_lang_String_2J)
                                                                       at com.mapbox.mapboxsdk.offline.OfflineManager.createDefaultFileSource(Native Method)
                                                                       at com.mapbox.mapboxsdk.offline.OfflineManager.<init>(OfflineManager.java:57)
                                                                       at com.mapbox.mapboxsdk.offline.OfflineManager.getInstance(OfflineManager.java:62)
                                                                       at com.mapbox.sirius.activity.OfflineRegionsActivity.onCreate(OfflineRegionsActivity.java:78)
                                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

/cc @zugaldia

**Comment by zugaldia** [comment]
@bleege Thanks for the feedback. I'm having difficulties reproducing this one though.

In case it helps, the error seems to indicate that the Java method

```
private native long createDefaultFileSource(
        String cachePath, String assetRoot, long maximumCacheSize);
```

used in the `OfflineManager` constructor is unable to find the corresponding JNI function which is [registered here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/jni.cpp#L2943) and [implemented here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/jni.cpp#L1737-L1744).

Could you try again with a clean build, or with the same code in the TestApp to see if the error persist?

**Comment by bleege** [comment]
Let's close this for now as the bug fixes from last week seemed to have solved this.

**Comment by NamtarR** [comment]
It seems I've just bumped into the same issue. Tried disabling ProGuard, Instant Run, clean build, using snapshot but no luck. 
    03-17 17:55:50.124 11745-11745/ru.aspirity.stolbyapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: ru.aspirity.stolbyapp, PID: 11745
                                                                       java.lang.UnsatisfiedLinkError: No implementation found for long com.mapbox.mapboxsdk.offline.OfflineManager.createDefaultFileSource(java.lang.String, java.lang.String, long) (tried Java_com_mapbox_mapboxsdk_offline_OfflineManager_createDefaultFileSource and Java_com_mapbox_mapboxsdk_offline_OfflineManager_createDefaultFileSource__Ljava_lang_String_2Ljava_lang_String_2J)
                                                                           at com.mapbox.mapboxsdk.offline.OfflineManager.createDefaultFileSource(Native Method)
                                                                           at com.mapbox.mapboxsdk.offline.OfflineManager.<init>(OfflineManager.java:57)
                                                                           at com.mapbox.mapboxsdk.offline.OfflineManager.getInstance(OfflineManager.java:62)
                                                                           at ru.aspirity.stolby.activities.MainActivity.setupOfflineRegion(MainActivity.java:210)
                                                                           at ru.aspirity.stolby.activities.MainActivity.onCreate(MainActivity.java:196)
                                                                           at android.app.Activity.performCreate(Activity.java:5975)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5253)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by zugaldia** [comment]
@NamtarR thank you for the report. Could you please try with our `4.0.0-beta.1` as described here https://www.mapbox.com/android-sdk/#gradle to see if this is still happening?

**Comment by NamtarR** [comment]
I got this exception with 4.0.0-beta1. Moving to SNAPSHOT didn't do any good, though. I had tested offline features in separate test project with SNAPSHOT two days ago and it worked just fine. Don't know where the problem lies.

**Comment by NamtarR** [comment]
Alright, I have just managed to overcome the issue. I have an activity and the offline region I need is downloaded in its ```onCreate()``` method. After setting up region download I dynamically add a fragment containing a ```MapView```. This code produced an error trying to acquire ```OfflineManager```. What I have changed is an order of actions: now the fragment is added to view at first and then in ```onMapReadyCallback()``` it asks activity to set up region download. Now it works fine, no exceptions, the region is downloading.

**Comment by zugaldia** [comment]
@NamtarR thank you for the detailed report. I'm trying to reproduce this issue, do you have any code you could share that generates the crash?

For now I've tried to move a region download before the `MapView` is even assigned, but that didn't trigger it.

**Comment by NamtarR** [comment]
Well, the code I tried to make working is pretty straightforward (here is not full version though):

```java
    @Override
    protected void onCreate(Bundle pSavedInstanceState) {
        super.onCreate(pSavedInstanceState);
        //start initialization: Window parameters, Toolbar, Nav Drawer
        //in-app SQLite database initialization routine
        setupOfflineRegion(); //this is the method where offline data is checked and downloaded
        if (pSavedInstanceState == null) {
            mLocationServiceEnabled = false;
            mMapFragment = new MapFragment(); //MapFragment is my custom fragment embedding a mapView
            mMapFragment.setArguments(bundle);
            displayFragment(mMapFragment);
            mTextItemMap.setSelected(true);
            mToolbar.setTitle(R.string.toolbar_title_map);
        }

        public void setupOfflineRegion() {
        manager = OfflineManager.getInstance(this); // and this is where exception is thrown
        manager.setAccessToken(getString(R.string.mapbox_token));
        manager.listOfflineRegions(new OfflineManager.ListOfflineRegionsCallback() {
            @Override
            public void onList(OfflineRegion[] offlineRegions) {
                if (offlineRegions.length == 0) {
                    createOfflineRegion();
                }
            }

            @Override
            public void onError(String error) {

            }
        });
    }
```

**Comment by t4keda** [comment]
I have the same crash in my app.
In my case I have the OfflineManager.getInstance(this); call in a service started from an activity without a map. The app crashes when OfflineManager.getInstance(this); is called, but only if I have not initialized a map in the app before.

**Comment by zugaldia** [comment]
@NamtarR @t4keda thank you both for your reports. We've been able to reproduce the issue exactly as you describe, `OfflineManager.getInstance(this)` will fail if no map has previously been loaded.

We've just pushed a fix in https://github.com/mapbox/mapbox-gl-native/issues/4413 that should solve this. It should be available in the next SNAPSHOT and in the next beta. Please reopen otherwise.
