### ISSUE TITLE
Subprocess Permission denied

### ISSUE THREAD

**Issue by haovn577** [mapbox/mapbox-gl-native#4177]
Hi, 

I got this errors (Ubuntu 14.04), what's wrong with my configurations?
```
root@hao-HP-Pavilion-Sleekbook-14:/home/hao/mapbox-gl-native# make android
make[1]: Entering directory `/home/hao/mapbox-gl-native'
build: linux/x86_64
host: android/arm-v7
libs: headless=none  platform=android  asset=zip  http=android  
* Recreating project...
Traceback (most recent call last):
  File "./scripts/flock.py", line 27, in <module>
    sys.exit(flock(sys.argv[1], sys.argv[2:]))
  File "./scripts/flock.py", line 20, in flock
    return subprocess.call(cmd_list)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
make[1]: *** [config/android-arm-v7.gypi] Error 1
make[1]: Leaving directory `/home/hao/mapbox-gl-native'
make: *** [android-lib] Error 2

```

Best Regards,
Hao Tran

**Comment by jfirebaugh** [comment]
This looks like an issue with your local configuration. Perhaps you have a file or subdirectory in `mapbox-gl-native` that's owned by root rather than your own user?
