### ISSUE TITLE
Show concrete exception when not implementing the required lifecycle method

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4246]
Currently if you add a `MapView` element to an xml layout without adding the required lifecycle methods. 

You will get the following exception:

>
FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 30249
                                                                              java.lang.Error: unknown native exception
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:110)

It would be more developer friendly catching this occurrence and showing a concrete exception.

**Comment by tobrun** [comment]
1593b96 resolved this, we can now show the MapView without having the lifecycle methods implemented. Nothing actionable left to do here. Closing.

**Comment by jjhesk** [comment]
this is appearing again at #4797
