### ISSUE TITLE
Closing a concurrent InfoWindow results in a ConcurrentModificationException.

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4252]
Having following configuration:

```java
mapboxMap.setAllowConcurrentMultipleOpenInfoWindows(true);
```
and having multiple of them open and than tapping the map to close them results in

```java
Process: com.mapbox.mapboxsdk.testapp, PID: 20738
java.util.ConcurrentModificationException at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at com.mapbox.mapboxsdk.maps.MapboxMap.deselectMarkers(MapboxMap.java:921)
at com.mapbox.mapboxsdk.maps.MapView$GestureListener.onSingleTapConfirmed(MapView.java:1576)
at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by tobrun** [comment]
Been testing this issue but fail to locate where this is coming from.
Will need to `git bisect` to find the source of the regression.

**Comment by tobrun** [comment]
I'm going to `git bisect` this issue in the weekend so I can do other things while building.

**Comment by tobrun** [comment]
I was able to pinpoint it to:

```
61e63b718c9a315684d4b25def76c5a1c21cb1ca is the first bad commit
commit 61e63b718c9a315684d4b25def76c5a1c21cb1ca
Author: Tobrun <tobrun@mapbox.com>
Date:   Tue Feb 9 09:52:06 2016 +0100

    [android] #3746 - InfoWindowCloseListener

:040000 040000 2dff4d65619afe8a4664beeae4909006366e9cce 4430d84ed3e5f5e6b8f0b007348e0adebb943cf5 M	platform

```

**Comment by tobrun** [comment]
I reworked the way closing works and removed the obsolete close/onClose combination.
