### ISSUE TITLE
unknown native expection

### ISSUE THREAD

**Issue by sirvon** [mapbox/mapbox-gl-native#4357]
Device info
----------------
samsung SM-G928T, running Android version 5.1.1,  version 1720 , remoteId = 000000006aa0554fffffffffd641d53f
emailAddress = xxxxx
user crash date: 2016-03-16T21:09:32.000-04:00user app start date: 2016-03-16T21:09:29.000-04:00total mem size: 26634944512avaliable mem size: 3219656704

Stacktrace
----------------
java.lang.Error: unknown native exception
    at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
    at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:110)
    at com.mapbox.mapboxsdk.maps.MapView$SurfaceTextureListener.onSurfaceTextureAvailable(MapView.java:1255)
    at android.view.TextureView.getHardwareLayer(TextureView.java:370)
    at android.view.View.updateDisplayListIfDirty(View.java:15393)
    at android.view.View.getDisplayList(View.java:15438)
    at android.view.View.draw(View.java:16208)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
    at android.view.View.draw(View.java:16489)
    at android.widget.FrameLayout.draw(FrameLayout.java:598)
    at android.view.View.updateDisplayListIfDirty(View.java:15416)
    at android.view.View.getDisplayList(View.java:15438)
    at android.view.View.draw(View.java:16208)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
    at android.view.View.draw(View.java:16489)
    at android.view.View.updateDisplayListIfDirty(View.java:15416)
    at android.view.View.getDisplayList(View.java:15438)
    at android.view.View.draw(View.java:16208)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
    at android.view.View.updateDisplayListIfDirty(View.java:15411)
    at android.view.View.getDisplayList(View.java:15438)
    at android.view.View.draw(View.java:16208)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
    at android.view.View.updateDisplayListIfDirty(View.java:15411)
    at android.view.View.getDisplayList(View.java:15438)
    at android.view.View.draw(View.java:16208)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
    at android.view.View.updateDisplayListIfDirty(View.java:15411)
    at andr…

**Comment by tobrun** [comment]
@sirvon thank you for reaching out and reporting your crash.
Could it be you are not implementing the required lifecycle methods as documented [here](https://www.mapbox.com/android-sdk/examples/)?

I created a similar issue for this crash to show a concrete exception instead of this exception in #4246.

**Comment by tobrun** [comment]
Not received any feedback on the issue, I was able to reproduce this myself in #4246. 
With  1593b96 this crash will not show anymore and will even show the Mapview without the lifecycle methods. closing.

**Comment by jjhesk** [comment]
appearing at #4797
