### ISSUE TITLE
Adding MapView programatically crashes app

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4385]
When you execute following code, the app crashes:

```java
@Override
       protected void onCreate(Bundle savedInstanceState) {
           super.onCreate(savedInstanceState);
           setContentView(R.layout.activity_main);
           ViewGroup mainLayout = (ViewGroup) findViewById(R.id.main);

           CameraPosition cameraPosition = new CameraPosition.Builder()
                   .target(new LatLng(-22.8993, -43.1208))
                   .build();

           MapboxMapOptions mapboxMapOptions = new MapboxMapOptions();
           mapboxMapOptions.camera(cameraPosition);
           mapboxMapOptions.styleUrl(Style.MAPBOX_STREETS);
           mapboxMapOptions.accessToken(getString(R.string.accessToken));

           mapView = new MapView(this, mapboxMapOptions);
           mainLayout.addView(mapView);
           mapView.onCreate(savedInstanceState);

           mapView.getMapAsync(new OnMapReadyCallback() {
               @Override
               public void onMapReady(@NonNull final MapboxMap mapboxMap) {

                   // Marker we will be animating
                   Marker marker = mapboxMap.addMarker(new MarkerOptions()
                           .position(new LatLng(-22.86992, -43.16740)));

                   // Begin animating the marker to new location
                   //animateMarker(marker, new LatLng(-22.88492, -43.06186));

               }
           });

       }
```

This is a common use-case and should be investigated for `4.0.0` release.
We used to have an example in the test app but with all the moving pieces this was removed.

**Comment by zugaldia** [comment]
Confirmed with current master. This is the stacktrace:

```java
03-18 16:30:22.887 29668-29726/com.mapbox.mapboxsdk.testapp I/OpenGLRenderer: Initialized EGL, version 1.4
03-18 16:30:22.993 29668-29668/com.mapbox.mapboxsdk.testapp E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
03-18 16:30:22.993 29668-29668/com.mapbox.mapboxsdk.testapp E/mbgl: {Main}[OpenGL]: eglCreateWindowSurface() returned error 12296
03-18 16:30:22.999 29668-29668/com.mapbox.mapboxsdk.testapp D/AndroidRuntime: Shutting down VM
03-18 16:30:23.006 29668-29668/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 29668
                                                                              java.lang.Error: unknown native exception
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:110)
                                                                                  at com.mapbox.mapboxsdk.maps.MapView$SurfaceTextureListener.onSurfaceTextureAvailable(MapView.java:1252)
                                                                                  at android.view.TextureView.getHardwareLayer(TextureView.java:368)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15157)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.draw(View.java:16187)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1077)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.draw(View.java:16187)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                                  at android.view.View.draw(View.java:15954)
                                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                                  at android.view.View.draw(View.java:16187)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                              	at android.os.Handler.handleC
03-18 16:30:23.271 29668-29725/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 2
03-18 16:30:32.758 29668-29991/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
```

**Comment by jfirebaugh** [comment]
The reason this is getting reported as "unknown native exception" is the use of `throw new std::runtime_error` [here](https://github.com/mapbox/mapbox-gl-native/blob/20c3706536ac9e927f80a50e9ec8906dfd0d2baf/platform/android/src/native_map_view.cpp#L401-L401). This is incorrect -- C++ exceptions should always be thrown by value, not by pointer. I'll make a separate PR to fix this.

**Comment by jfirebaugh** [comment]
`12296` = `0x3008` = `EGL_BAD_DISPLAY`

**Comment by tobrun** [comment]
I validated and 1593b96 resolves this crash, thank you @jfirebaugh!
Are we going to cherry pick this commit onto the release branch?

> We used to have an example in the test app but with all the moving pieces this was removed.

I'm currently committing an example of this use-case to catch regressions in the future (will be automatically found by our UI tests).

**Comment by jfirebaugh** [comment]
@tobrun 1593b962ed30c866db10e1720142bfb67a3c49c1 is not a fix for the underlying issue here, which is that `eglCreateWindowSurface()` is failing. It just corrects the error handling for that error.

**Comment by tobrun** [comment]
Strange, will do some tests tomorrow and see if I can reproduce this crash. 
@cammace any chance you still have the code locally?

**Comment by cammace** [comment]
@tobrun Yeah still in Android Studio

**Comment by tobrun** [comment]
@cammace Would you mind sharing the whole `.java` file?

**Comment by tobrun** [comment]
Did another test on the release branch with following code. Was not able to reproduce this crash:

```java
package com.mapbox.mapboxsdk.testapp;

import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.MenuItem;
import android.view.ViewGroup;

import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.constants.MapboxConstants;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.constants.Style;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.geometry.LatLngBounds;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.MapboxMapOptions;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.maps.UiSettings;
import com.mapbox.mapboxsdk.testapp.utils.ApiAccess;
import com.mapbox.mapboxsdk.maps.MapView;

public class LatLngBoundsActivity extends AppCompatActivity {

    private static final LatLng LOS_ANGELES = new LatLng(34.053940, -118.242622);
    private static final LatLng NEW_YORK = new LatLng(40.712730, -74.005953);

    private MapView mMapView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_visible_bounds);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.setDisplayHomeAsUpEnabled(true);
            actionBar.setDisplayShowHomeEnabled(true);
        }

        MapboxMapOptions options = new MapboxMapOptions();
        options.accessToken(ApiAccess.getToken(this));
        options.styleUrl(Style.DARK);
        options.scrollGesturesEnabled(false);
        options.rotateGesturesEnabled(false);
        options.tiltGesturesEnabled(false);
        options.zoomGesturesEnabled(false);

        mMapView = new MapView(this, options);
        mMapView.onCreate(savedInstanceState);
        mMapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull final MapboxMap mapboxMap) {
                mapboxMap.setStyle(Style.DARK);

                UiSettings uiSettings = mapboxMap.getUiSettings();
                uiSettings.setAllGesturesEnabled(false);

                mapboxMap.addMarker(new MarkerOptions()
                        .title("Los Angeles")
                        .snippet("City Hall")
                        .position(LOS_ANGELES));

                mapboxMap.addMarker(new MarkerOptions()
                        .title("New York")
                        .snippet("City Hall")
                        .position(NEW_YORK));

                // Create Bounds
                final LatLngBounds bounds = new LatLngBounds.Builder()
                        .include(NEW_YORK)
                        .include(LOS_ANGELES)
                        .build();

                // And padding
                int padding = (int) getResources().getDimension(R.dimen.coordinatebounds_margin);

                // Move camera to the bounds with padding
                mapboxMap.moveCamera(CameraUpdateFactory.newLatLngBounds(bounds, padding));

                // Call mapboxMap.getProjection().getVisibleRegion().latLngBounds to retrieve the bounds
                Log.v(MapboxConstants.TAG, mapboxMap.getProjection().getVisibleRegion().latLngBounds.toString());
            }
        });

        ViewGroup parent = (ViewGroup) findViewById(R.id.parent_layout);
        parent.addView(mMapView);
    }

    @Override
    protected void onStart() {
        super.onStart();
        mMapView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        mMapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mMapView.onPause();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mMapView.onStop();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mMapView.onSaveInstanceState(outState);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mMapView.onDestroy();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mMapView.onLowMemory();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                onBackPressed();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }
}
```

I'm guessing that we did not implement the required lifecycle methods as mentioned in #4246.
@cammace could you double check this?

This issue has improved the code 2 in ways, we are correctly handling the exceptions and we have a feature activity showing off this configuration. Nothing actionable to do here anymore. Closing.

**Comment by cammace** [comment]
Can confirm, just ran the same code we wrote on Friday and it works. Granted I tested it on a different device if that matters.

**Comment by nondefyde** [comment]
Similar error here : java.lang.Error: eglCreateWindowSurface() failed
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:121)
at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:1410)
at android.view.SurfaceView.updateWindow(SurfaceView.java:676)
at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:203)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)...`......

Is there any fix on this on this?.

0S : Android 6.0
com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.1@aar

**Comment by cammace** [comment]
First could you update the SDK version to 4.2.0-beta.3. This ticket was resolved after realizing I forgot to include the correct map lifecycles. Could you make sure you included all of them. If this doesn't fix this issue please contact through [our support page](mapbox.com/contact) with the full logcat error output and any additional code snippets to help troubleshoot the issue.
