### ISSUE TITLE
Unable to register for GPS updates 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4713]
I'm seeing the following exception when trying to register for location updates on an Pixel C running N.

```java
04 - 15 10: 26: 52.382 17567 - 17567 / com.mapbox.mapboxsdk.testapp E / FusionEngine: Unable to register
for GPS updates.
java.lang.IllegalArgumentException: provider doesn 't exist: gps
at android.os.Parcel.readException(Parcel.java: 1670)
at android.os.Parcel.readException(Parcel.java: 1619)
at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java: 614)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java: 881)
at android.location.LocationManager.requestLocationUpdates(LocationManager.java: 465)
at com.mapzen.android.lost.internal.FusionEngine.enableGps(FusionEngine.java: 96)
at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java: 72)
at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java: 36)
at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java: 38)
at com.mapbox.mapboxsdk.location.LocationServices.toggleGPS(LocationServices.java: 96)
at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.toggleGps(UserLocationView.java: 326)
at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.onResume(UserLocationView.java: 272)
at com.mapbox.mapboxsdk.maps.MapView.onResume(MapView.java: 539)
at com.mapbox.mapboxsdk.testapp.activity.userlocation.MyLocationCustomisationActivity.onLocationChanged(MyLocationCustomisationActivity.java: 77)
at com.mapbox.mapboxsdk.location.LocationServices.onLocationChanged(LocationServices.java: 131)
at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.reportLocation(FusedLocationProviderApiImpl.java: 96)
at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java: 137)
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java: 291)
at android.location.LocationManager$ListenerTransport. - wrap0(LocationManager.java)
at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java: 236)
at android.os.Handler.dispatchMessage(Handler.java: 102)
at android.os.Looper.loop(Looper.java: 148)
at android.app.ActivityThread.main(ActivityThread.java: 6066)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 770)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 660)
```

First look suggest an issue with mapzen (library we use as Google Play Services replacement on Android). Need to look into the details before creating an issue upstream.

**Comment by dagatsoin** [comment]
I have an equivalent problem with my cordova plugin.
Is there anything to write with the manifest or something?

```
07-21 05:46:52.629 22847-22847/io.cordova.hellocordova E/FusionEngine: Unable to register for GPS updates.
                                                                       java.lang.IllegalArgumentException: provider doesn't exist: gps
                                                                           at android.os.Parcel.readException(Parcel.java:1469)
                                                                           at android.os.Parcel.readException(Parcel.java:1419)
                                                                           at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
                                                                           at android.location.LocationManager.requestLocationUpdates(LocationManager.java:860)
                                                                           at android.location.LocationManager.requestLocationUpdates(LocationManager.java:454)
                                                                           at com.mapzen.android.lost.internal.FusionEngine.enableGps(FusionEngine.java:98)
                                                                           at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java:72)
                                                                           at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java:36)
                                                                           at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:38)
                                                                           at com.mapbox.mapboxsdk.location.LocationServices.toggleGPS(LocationServices.java:103)
                                                                           at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:388)
                                                                           at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(MyLocationView.java:341)
                                                                           at com.mapbox.mapboxsdk.maps.MapView.setMyLocationEnabled(MapView.java:2415)
                                                                           at com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(MapboxMap.java:1526)
                                                                           at com.mapbox.mapboxsdk.maps.MapView.setInitialState(MapView.java:289)
                                                                           at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:247)
                                                                           at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:182)
                                                                           at com.telerik.plugins.mapbox.MapController.<init>(MapController.java:117)
                                                                           at com.telerik.plugins.mapbox.Map.<init>(Map.java:78)
                                                                           at com.telerik.plugins.mapbox.MapsManager.createMap(MapsManager.java:36)
                                                                           at com.telerik.plugins.mapbox.CDVMapbox$1.run(CDVMapbox.java:169)
                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                           at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ahuang13** [comment]
I'm also using a Pixel C running Android N and seeing the same problem issue as @tobrun. I'm using 4.2.0-beta.2 of the MapBox SDK.

**Comment by tobrun** [comment]
@dagatsoin sorry for replying a bit late. The need to handle runtime permissions depends on the target SDK version. 

@ahuang13 thank you for confirming. 

Adding info to this issue that I'm running N on a Nexus 6P and not seeing the issue there. I believe this is issue is device dependable.

**Comment by ahuang13** [comment]
@tobrun Yep, I'm also not able to reproduce on a Nexus 5X running Android Marshmallow.

**Comment by tobrun** [comment]
Proposal to update dependency in https://github.com/mapbox/mapbox-gl-native/pull/6476. 
Will reopen if still an issue.
