### ISSUE TITLE
ConcurrentModificationException when listening to location updates

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4731]
### Steps to trigger behavior

 1. Open an activity listening to location changes with `LocationServices`.
 2. App crashes instantly

### Expected behavior

Not crashing :trollface: 

### Actual behavior

Crashing with:
```java
04 - 18 14: 27: 12.786 6652 - 6652 / com.mapbox.mapboxsdk.testapp E / AndroidRuntime: FATAL EXCEPTION: main
Process: com.mapbox.mapboxsdk.testapp, PID: 6652
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java: 831)
at com.mapbox.mapboxsdk.location.LocationServices.onLocationChanged(LocationServices.java: 130)
at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.reportLocation(FusedLocationProviderApiImpl.java: 96)
at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java: 137)
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java: 291)
at android.location.LocationManager$ListenerTransport. - wrap0(LocationManager.java)
at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java: 236)
at android.os.Handler.dispatchMessage(Handler.java: 102)
at android.os.Looper.loop(Looper.java: 148)
at android.app.ActivityThread.main(ActivityThread.java: 6066)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 770)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 660)
```

Setup code:

```java
    LocationServices locationServices = LocationServices.getLocationServices(this);
        locationServices.addLocationListener(this);
        locationServices.toggleGPS(true);
```

Callback code:
```java
  @Override
    public void onLocationChanged(Location location) {
        if (location != null) {
            if (mMapView == null) {
                findViewById(R.id.progress).setVisibility(View.GONE);

                MapboxMapOptions mapboxMapOptions = new MapboxMapOptions();
                mapboxMapOptions.accessToken(getString(R.string.mapbox_access_token));
                mapboxMapOptions.styleUrl(Style.MAPBOX_STREETS);
                mapboxMapOptions.locationEnabled(true);
                mapboxMapOptions.camera(new CameraPosition.Builder()
                        .target(new LatLng(location))
                        .zoom(11)
                        .tilt(25)
                        .build());

                mMapView = new MapView(this, mapboxMapOptions);
                ((ViewGroup) findViewById(R.id.container)).addView(mMapView);

                mMapView.onCreate(savedState);
                mMapView.getMapAsync(this);
                mMapView.onResume();
                mLocation = location;
            }
        }
    }
```

**Comment by tobrun** [comment]
Rerunning the code without any changes is not producing the same exception..

**Comment by bleege** [comment]
Is this still happening after the fix in #4829 ?

**Comment by bleege** [comment]
Bump.  Can we close this @tobrun?

**Comment by bleege** [comment]
Thanks @tobrun!

**Comment by snkashis** [comment]
I'm encountering a similar error - can this be reopened?How related are they, given the change in version from 4.1.0?Happens on multiple OS versions. 

Libraries
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.1@aar'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.9'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.9'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building:0.1.0'

```
Setup code
```
        LocationEngineProvider locationEngineProvider = new LocationEngineProvider(this);

        locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
        locationEngine.setPriority(HIGH_ACCURACY);
        locationEngine.activate();
```

Stacktrace 
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
       at java.util.HashMap$ValueIterator.next(HashMap.java:879)
       at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.e(FusedLocationProviderServiceDelegate.java:93)
       at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:191)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
       at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
       at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:249)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by tobrun** [comment]
@Nexxado with https://github.com/mapbox/mapbox-gl-native/pull/10354 we made location provider optional and you are able to use alternative providers as google play services or the default android one. The linked stacktrace above indicates an internal issue within the LOST location provider. Thank you for reporting this issue but please update to a more recent version of the library (5.5.0) and use alternative location provider.
