### ISSUE TITLE
class not found com.mapbox.mapboxsdk.location.LocationServices when using manually built mapbox sdk aar

### ISSUE THREAD

**Issue by smartkiwi** [mapbox/mapbox-gl-native#4757]
**Platform:** Android
**Mapbox SDK version:** 4.0.0

### Steps to trigger behavior

 1. checkout mapbox sdk
 2. `make android`
 3. import ./platform/android/MapboxGLAndroidSDK/build/outputs/aar/MapboxGLAndroidSDK-release.aar to android app

 4. when I use mapbox sdk from download from public repo - my application starts and work ok.
```
        compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.0@aar') {
            transitive = true
        }
```

Please note that my application is not using com.mapbox.mapboxsdk.location.LocationServices - but com.mapbox.mapboxsdk.maps.widgets.UserLocationView tries ti import it.

I've tried to add proguard rule into my app's proguard-rules.pro file - but it didn't help.
```
# Package location
-keep class com.mapbox.mapboxsdk.location.** { *; }

```
### Expected behavior
Application should be able to show map

### Actual behavior
Application crashes with exception: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.location.LocationServices" on path: DexPathList[[zip file "/data/app/com.uber.sensors.band-1/base.apk"],nativeLibraryDirectories=[/data/app/com.uber.sensors.band-1/lib/arm, /vendor/lib, /system/lib]]

>                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.location.LocationServices" on path: DexPathList[[zip file "/data/app/com.uber.sensors.band-1/base.apk"],nativeLibraryDirectories=[/data/app/com.uber.sensors.band-1/lib/arm, /vendor/lib, /system/lib]]
TraceIngest dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
 at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.toggleGps(UserLocationView.java:355) 
 at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.setEnabled(UserLocationView.java:251) 
 at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.initialize(UserLocationView.java:119) 
 at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.<init>(UserLocationView.java:109) 
 at java.lang.reflect.Constructor.newInstance(Native Method) 
 at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
 at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
 at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:179) 
 at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:158) 
 at java.lang.reflect.Constructor.newInstance(Native Method) 
 at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
 at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
 at com.uber.sensors.band.MapFragment.onCreateView(MapFragment.java:594) 
 at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962) 
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248) 
 at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) 
 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613) 
 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517) 
 at android.os.Handler.handleCallback(Handler.java:739) 
 at android.os.Handler.dispatchMessage(Handler.java:95) 
 at android.os.Looper.loop(Looper.java:135) 
 at android.app.ActivityThread.main(ActivityThread.java:5254) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at java.lang.reflect.Method.invoke(Method.java:372) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
Suppressed: java.lang.NoClassDefFoundError: com.mapbox.mapboxsdk.location.LocationServices
 at dalvik.system.DexFile.defineClassNative(Native Method)
 at dalvik.system.DexFile.defineClass(DexFile.java:226)
 at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
 at dalvik.system.DexPathList.fin

**Comment by tobrun** [comment]
@smartkiwi 
Thanks for reaching out and reporting your problem. The proposed proguard config should normally keep that class and it's a bit strange that we haven't seen this crashes during any of our proguard tests. 

Before starting to reproduce this behaviour, could you answer me the following question:
 - where are you enabling proguard in the SDK module or the app module?

**Comment by smartkiwi** [comment]
Here is part of my app/build.gradle 
And looks like it has `minifyEnabled false` - so I'm not sure is it proguard related.
Maybe it is has something with the way how I built aar or how I'm using it in my app.
I'll use mapbox example app code and will import locally build Mapbox SDK aar. Also I'll try to do the same with latest Mapbox SDK code from master.
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        def mVersionName = "git describe --dirty".execute().text.trim()

        applicationId "com.my.app"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode getVersionCode()
        versionName mVersionName
        //multiDexEnabled true
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}
```
Also I've build apk with Android Studio and loaded it with `adb install app-debug.apk` to the phone and see same exception. 
So I've uncompressed apk, converted classes.dex to .jar and uncompressed it - and I see that com.mapbox.mapboxsdk.location.LocationServices class is there.

**Comment by smartkiwi** [comment]
Ok. I've compiled mapbox android demo successfully.
But when I import locally built aar module - it fails with the same exception.
So the problem is with the way how I build package or import it.

Here are the steps I import aar into my app:
1) File/New/New Module/Select arr
2) I select aar file and give it a name: :MapboxGLAndroidSDK-release-400-vanilla
3) update build.gradle

```
dependencies {
    compile 'com.android.support:gridlayout-v7:23.1.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
//    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.0@aar'){
//        transitive=true
//    }
    compile project(':MapboxGLAndroidSDK-release-400-vanilla')
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}
```

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/location/LocationServices;
   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.toggleGps(UserLocationView.java:355)
   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.setEnabled(UserLocationView.java:251)
   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.initialize(UserLocationView.java:119)
   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.<init>(UserLocationView.java:109)
   at java.lang.reflect.Constructor.newInstance(Native Method) 
   at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
   at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
   at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:179) 
   at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:158) 
   at java.lang.reflect.Constructor.newInstance(Native Method) 
   at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
   at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
   at com.mapbox.mapboxandroiddemo.MainActivity.onCreate(MainActivity.java:41) 
   at android.app.Activity.performCreate(Activity.java:5990) 
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
   at android.app.ActivityThread.access$800(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:135) 
   at android.app.ActivityThread.main(ActivityThread.java:5254) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:372) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

```

**Comment by bleege** [comment]
@smartkiwi Can you help us understand your use case for building the library from scratch?  We produce nightly SNAPSHOTS from `master` so if there's additional functionality that you need we'd be happy to incorporate it into the project so that everyone can benefit.

**Comment by smartkiwi** [comment]
@bleege 
This is exactly my case - I'm trying to add functionality and just wanted to test it before submitting pull request with it. 
I've just created pull request with the functionality I'm suggesting to add:
https://github.com/mapbox/mapbox-gl-native/pull/4769
I would appreciate help building and publishing it

**Comment by bleege** [comment]
Noting that the issue in PR #4769 will be solved by the forthcoming Style API in the Mapbox Android SDK.  Thanks again @smartkiwi!

**Comment by Pilou44** [comment]
Hello
I have the same issue. Can we have some help with this please ?

**Comment by bleege** [comment]
@Pilou44 We have the build instructions in https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md#android .

**Comment by yuriyskulskiy** [comment]
(Error:Attribute “zoom” has already been defined, it is cause of another module in my project that uses chart framework lib that has same value with attr: zoom) so i decided to  modiffy mapbox sdk. And add it as an AAR file to new module of my app -  have got same issue :

  java.lang.NoClassDefFoundError: com.mapbox.mapboxsdk.location.LocationServices     
Guess i have done something incorrect but cant figure out what exactly...

**Comment by yuriyskulskiy** [comment]
ok. Fixed. My mistake  "...the Core GL portion needs to built first. Core GL is the common C++ based OpenGL engine that powers the maps for iOS, Android, and Qt in the project..."

**Comment by moodstubos** [comment]
I have exactly the same issue:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LocationEngine;`

I followed this instructions: 
https://github.com/peroper/pp-mapbox-gl-native/blob/master/platform/android/CONTRIBUTING_LINUX.md

compiles without any error, but if I start a new project with included generated aar file, i get this exception.

@yuriyskulskiy 
Could you explain how you fixed this problem?

Many many thanks, 
graham

**Comment by tobrun** [comment]
@moodstubos such an issue can be troubledshooted with `./gradlew dependencies`, more information about that and the issue you are facing in https://github.com/mapbox/mapbox-gl-native/issues/9408.

**Comment by greybeard1123** [comment]
@tobrun is right with saying this can be troubleshooted with  `./gradlew dependencies` .
To be clear, 
``` 
implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3@aar') {
            transitive = true
}
```

includes all the transitive dependencies needed for the sdk to run, i.e:
```
+--- com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3
|    +--- com.android.support:support-annotations:25.3.1 -> 27.1.1
|    +--- com.android.support:support-v4:25.3.1 -> 27.1.1 (*)
|    +--- com.android.support:design:25.3.1 -> 27.1.1 (*)
|    +--- com.jakewharton.timber:timber:4.5.1
|    +--- com.squareup.okhttp3:okhttp:3.8.0 -> 3.9.0 (*)
|    +--- com.mapzen.android:lost:1.1.1
|    |    +--- com.android.support:appcompat-v7:22.2.0 -> 27.1.1 (*)
|    |    \--- com.android.support:support-v4:22.2.0 -> 27.1.1 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-java-geojson:2.2.1
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-core:2.2.1
|    |    \--- com.google.code.gson:gson:2.8.0 -> 2.8.2
|    \--- com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.1
|         +--- com.android.support:appcompat-v7:25.1.0 -> 27.1.1 (*)
|         \--- com.squareup.okhttp3:okhttp:3.6.0 -> 3.9.0 (*)
```
So, to complie the sdk from source and add the aar to your application, run `./gradlew dependencies` again and see if all the above libraries are there, if not, just add the missing dependencies in your `build.gradle`, like:
```
    implementation fileTree(include: ['MapboxGLAndroidSDK-debug.aar'], dir: 'libs')
    implementation "com.mapzen.android:lost:1.1.1"
    implementation "com.squareup.okhttp3:okhttp:3.8.0"
    implementation "com.mapbox.mapboxsdk:mapbox-java-geojson:2.2.1"
    implementation "com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.1"
```
