### ISSUE TITLE
crash on start with 23.3.0 android support library

### ISSUE THREAD

**Issue by jjhesk** [mapbox/mapbox-gl-native#4797]
**Platform:** Android with support library v7 - 23.3.0, OnePlus A0001
**Mapbox SDK version:** 4.0.0 - stable
```gradle
dependencies {
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.0@aar'){
        transitive=true
    }
}
```

```java
    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        map_body = (MapView) view.findViewById(R.id.mapview);
        map_body.setAccessToken(BuildConfig.MAPBOX_API);
        map_body.getMapAsync(this);
    }
```
### Steps to trigger behavior

 1. read the instruction as normal from the [official website](https://www.mapbox.com/android-sdk/#gradle)
 2. implement all the lifecycle calls
 3. build and run the app and run on the Nexus 5 - Android 5.1.1

### Expected behavior
normal map

### Actual behavior
```
Fatal Exception: java.lang.Error: unknown native exception
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:115)
       at com.mapbox.mapboxsdk.maps.MapView$SurfaceTextureListener.onSurfaceTextureAvailable(MapView.java:1258)
       at android.view.TextureView.getHardwareLayer(TextureView.java:370)
       at android.view.View.updateDisplayListIfDirty(View.java:14144)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15234)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15234)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14162)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.View.draw(View.java:14959)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15234)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
       at android.view.View.updateDisplayListIfDirty(View.java:14167)
       at android.view.View.getDisplayList(View.java:14189)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by jjhesk** [comment]
@tobrun  i found some more related issues in here.

**Comment by jjhesk** [comment]
something was missed from the tutorial... remember to add 
`mapView.onCreate(savedInstanceState)` at onCreate.

```java
  @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        maptag = (MapView) view.findViewById(R.id.mapview);
        maptag.onCreate(savedInstanceState);
        maptag.setAccessToken(BuildConfig.MAPBOX_API);
        maptag.getMapAsync(this);
    }

```

**Comment by tobrun** [comment]
Thanks for reporting this back. Going to close this as non actionable.
