### ISSUE TITLE
User Location On / Off Test Example

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4835]
The UserLocationView was refactored last week (yay!) in #4396.  I've noticed some difficulties / sluggishness getting it to work in an internal app but it's unclear if the issue is with the implementing app or with the SDK.  There are currently 2 TestApp examples that deal with User Location (`MyLocationCustomisationActivity` and `MyLocationTrackingModeActivity`) however neither of them allow for a simple toggle on / toggle off.  Instead of overloading these two activities, the goal will be to create a simple FAB based toggle so that the issue can be sandboxed.

**Comment by tobrun** [comment]
Similar feature is being tracked in #4531 can close that one as well as this one lands.

**Comment by tobrun** [comment]
Their is currently a bug which shows the user location view only after receiving a 2 location updates. Calling `setMyLocationEnabled()` is not instantly showing the user location. Issue is documented in https://github.com/mapbox/mapbox-gl-native/issues/4850. FWIW their are also multiple smaller bugfixes in #4800.

**Comment by bleege** [comment]
Thanks for pointing out #4531 as I hadn't seen that one in the pile of tickets.  I'll close that one as I've already started the work on this ticket.

**Comment by bleege** [comment]
I finished fleshing out the initial FAB driven UI and ran into the following crash / stacktrace.  This stack trace is the same one that I've seen on the internal app and doesn't appear to be part of #4800 or #4850.  Will investigate further.

```java
:29.610 29589-29589/com.mapbox.mapboxsdk.testapp W/art: Verification of void com.mapbox.mapboxsdk.testapp.activity.userlocation.MyLocationToggleActivity.enableLocation(boolean) took 102.694ms
04-26 11:38:42.000 29589-29589/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 29589
                                                                              java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.mapboxsdk.maps.MapboxMap$OnMyLocationChangeListener.onMyLocationChange(android.location.Location)' on a null object reference
                                                                                  at com.mapbox.mapboxsdk.maps.MapView$5.onLocationChanged(MapView.java:2352)
                                                                                  at com.mapbox.mapboxsdk.location.LocationServices.onLocationChanged(LocationServices.java:128)
                                                                                  at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.reportLocation(FusedLocationProviderApiImpl.java:96)
                                                                                  at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:132)
                                                                                  at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:281)
                                                                                  at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:210)
                                                                                  at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:226)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:145)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by tobrun** [comment]
@bleege before looking into that crash, could you rebase with changes I'm about to merge?

**Comment by bleege** [comment]
Looking through the refactored UserLocationView code it looks like `MapboxMap.setOnMyLocationChangeListener()` hasn't changed and that it's continuing to make use of a `null` parameter for `MapboxMap.OnMyLocationChangeListener` to unset the listener but that `MapView.setOnMyLocationChangeListener()` doesn't have a `null` check in it which would remove the listener from LocationServices like it needs to as well as prevent the `onLocationChange()` anonymous method from executing.  I'll look to solve this issue as part of this ticket next.

![20160426-mapboxmap](https://cloud.githubusercontent.com/assets/989928/14827490/435b746a-0ba8-11e6-9b84-cef033254243.png)
_MapboxMap.setOnMyLocationChangeListener()_

![20160426-mapview](https://cloud.githubusercontent.com/assets/989928/14827587/b827c208-0ba8-11e6-862e-c3e76a2ee138.png)
_MapView.setOnMyLocationChangeListener()_

**Comment by bleege** [comment]
Oops... looks like the GitHub Web page refreshed too late in my browser and I didn't have @tobrun's comment when I made mine.  I'll wait for #4851 to land and then do the rebase to see if that fixes the crash.

**Comment by tobrun** [comment]
On top of my head. I remember adding an if check to avoid that null pointer ;)

**Comment by bleege** [comment]
@tobrun has just landed #4851 so I'll rebase [`4835-userdot`](https://github.com/mapbox/mapbox-gl-native/compare/4835-userdot) on top of it and see how things work now.

**Comment by bleege** [comment]
Testing with the new code works!

Before finishing up however, I'd still like to add functionality to remove the MapboxMap.OnMyLocationChangeListener from the LocationServices listeners and reclaim the memory as well as prevent any hidden NullPointerExceptions from cropping up.

**Comment by bleege** [comment]
Rebased and Merged!
