### ISSUE TITLE
App crashes due to strict mode configuration and a resource leak

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5221]
I have noticed this a couple of times already, 
the activity showing the map kills itself due to a Strict mode configuration. 

> 06-03 10:23:00.676 25096-25105/com.mapbox.mapboxsdk.testapp E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                          java.lang.Throwable: Explicit termination method 'end' not called
                                                                              at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                              at java.util.zip.Inflater.<init>(Inflater.java:104)
                                                                              at okio.GzipSource.<init>(GzipSource.java:62)
                                                                              at okhttp3.internal.http.HttpEngine.unzip(HttpEngine.java:506)
                                                                              at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
                                                                              at okhttp3.RealCall.getResponse(RealCall.java:244)
                                                                              at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                                                                              at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                              at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                              at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                              at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)

**Comment by tobrun** [comment]
This option was disabled for CI integration #6277
