### ISSUE TITLE
Telemetry error on older device

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5377]
When trying to use the Mapbox Android SDK on a Samsung Galaxy S2 device, the map view is just a black screen and the following is printed in the logcat:

```
06-16 10:09:00.580 27439-27439/com.baseride.CloudFleet I/com.mapbox.mapboxsdk.maps.MapView: MapView start Telemetry...
06-16 10:09:00.585 27439-27439/com.baseride.CloudFleet I/MapboxEventManager: Telemetry initialize() called...
06-16 10:09:00.585 27439-27439/com.baseride.CloudFleet I/MapboxEventManager: Right before Telemetry set enabled in initialized()
06-16 10:09:00.590 27439-27439/com.baseride.CloudFleet I/MapboxEventManager: setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
06-16 10:09:00.590 27439-27439/com.baseride.CloudFleet D/MapboxEventManager: Starting Telemetry Up!
06-16 10:09:00.590 27439-27439/com.baseride.CloudFleet I/MapboxEventManager: Permissions are good, see if GPS is enabled and if not then setup Ambient.
06-16 10:09:00.595 27439-27439/com.baseride.CloudFleet E/MapboxEventManager: Error Trying to load Staging Credentials: java.lang.NullPointerException
06-16 10:09:00.620 27439-27439/com.baseride.CloudFleet D/libEGL: loaded /system/lib/egl/libEGL_mali.so
06-16 10:09:00.640 27439-27439/com.baseride.CloudFleet D/libEGL: loaded /system/lib/egl/libGLESv1_CM_mali.so
06-16 10:09:00.640 27439-27439/com.baseride.CloudFleet D/libEGL: loaded /system/lib/egl/libGLESv2_mali.so

[ 06-16 10:09:00.645 27439:0x6b2f D/ ]
Device driver API match
Device driver API version: 10
User space API version: 10


[ 06-16 10:09:00.645 27439:0x6b2f D/ ]
mali: REVISION=Linux-r2p4-02rel0 BUILD_DATE=Mon Mar 5 09:47:55 KST 2012
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: EGL Vendor: Android
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: EGL Version: 1.4 Android META-EGL
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: EGL Client APIs: OpenGL ES
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: EGL Client Extensions: EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Found 5 configs
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Config 0:
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Caveat: 12344
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Conformant: 5
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Color: 32
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Red: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Green: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Blue: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha mask: 0
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Depth: 24
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Stencil: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Sample buffers: 0
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Samples: 0
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Config 1:
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Caveat: 12344
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Conformant: 5
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Color: 32
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Red: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Green: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Blue: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha mask: 0
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Depth: 24
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Stencil: 8
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Sample buffers: 0
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Samples: 0
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Config 2:
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Caveat: 12344
06-16 10:09:00.650 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Conformant: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Color: 32
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Red: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Green: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Blue: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha mask: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Depth: 24
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Stencil: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Sample buffers: 1
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Samples: 4
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Config 3:
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Caveat: 12344
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Conformant: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Color: 16
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Red: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Green: 6
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Blue: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha mask: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Depth: 24
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Stencil: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Sample buffers: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Samples: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Config 4:
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Caveat: 12344
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Conformant: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Color: 16
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Red: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Green: 6
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Blue: 5
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Alpha mask: 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Depth: 24
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Stencil: 8
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Sample buffers: 1
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: ...Samples: 4
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Chosen config is 0
06-16 10:09:00.655 27439-27439/com.baseride.CloudFleet I/mbgl: [OpenGL]: Chosen window format is 1
06-16 10:09:00.670 27439-27439/com.baseride.CloudFleet I/MapboxEventManager: flushEventsQueueImmediately() called...
06-16 10:09:00.670 27439-27439/com.baseride.CloudFleet D/MapboxEventManager: turnstile event pushed.
06-16 10:09:00.725 27439-27439/com.baseride.CloudFleet I/TelemetryService: onCreate() called
06-16 10:09:00.725 27439-27439/com.baseride.CloudFleet I/TelemetryService: onStartCommand() called
06-16 10:09:00.730 27439-27439/com.baseride.CloudFleet W/TextureView: A TextureView or a subclass can only be used with hardware acceleration enabled.
06-16 10:09:00.830 27439-27439/com.baseride.CloudFleet D/dalvikvm: GC_FOR_ALLOC freed 628K, 12% free 17749K/19975K, paused 30ms
06-16 10:09:00.835 27439-27439/com.baseride.CloudFleet I/dalvikvm-heap: Grow heap (frag case) to 18.825MB for 1463056-byte allocation
06-16 10:09:00.870 27439-27439/com.baseride.CloudFleet D/dalvikvm: GC_FOR_ALLOC freed 3K, 11% free 19175K/21447K, paused 37ms
06-16 10:09:01.840 27439-27762/com.baseride.CloudFleet D/MapboxEventManager: response code = 204 for events 2
06-16 10:09:02.290 27439-27441/com.baseride.CloudFleet D/dalvikvm: GC_CONCURRENT freed 1930K, 11% free 19261K/21447K, paused 2ms+3ms
06-16 10:09:03.575 27439-27441/com.baseride.CloudFleet D/dalvikvm: GC_CONCURRENT freed 2076K, 11% free 19233K/21447K, paused 7ms+10ms
06-16 10:09:10.595 27439-27931/com.baseride.CloudFleet D/MapboxEventManager: No events in the queue to send so returning.
06-16 10:09:19.690 27439-27522/com.baseride.CloudFleet D/Vehicle: getStatus(): Vehicle - Tablet 4.4.2 ECh test-ech-44_30684, Seconds - 9121790
06-16 10:09:19.690 27439-27522/com.baseride.CloudFleet D/Vehicle: getStatus(): Vehicle - ECh Test test-ech_30622, Seconds - 1175501
06-16 10:09:19.690 27439-27522/com.baseride.CloudFleet D/Vehicle: getStatus(): Vehicle - ECh Test test-ech_30622, Seconds - 1175529
06-16 10:09:19.690 27439-27522/com.baseride.CloudFleet D/Vehicle: getStatus(): Vehicle - Tablet 4.4.2 ECh test-ech-44_30684, Seconds - 9121818
06-16 10:09:32.315 27439-28282/com.baseride.CloudFleet D/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 304: Not Modified
```

Trying with Mapbox SDK `4.0.0-beta.2` resulted in this error:

```
06-15 14:27:31.710 23382-26150/com.baseride.CloudFleet E/MapboxEventManager: FlushTheEventsTask borked: org.json.JSONException: Forbidden numeric value: NaN
06-15 14:27:31.710 23382-26150/com.baseride.CloudFleet W/System.err: org.json.JSONException: Forbidden numeric value: NaN
06-15 14:27:31.720 23382-26150/com.baseride.CloudFleet W/System.err: at org.json.JSON.checkDouble(JSON.java:25)
06-15 14:27:31.725 23382-26150/com.baseride.CloudFleet W/System.err: at org.json.JSONObject.put(JSONObject.java:260)
06-15 14:27:31.730 23382-26150/com.baseride.CloudFleet W/System.err: at org.json.JSONObject.putOpt(JSONObject.java:274)
06-15 14:27:31.735 23382-26150/com.baseride.CloudFleet W/System.err: at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:553)
06-15 14:27:31.740 23382-26150/com.baseride.CloudFleet W/System.err: at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:520)
06-15 14:27:31.745 23382-26150/com.baseride.CloudFleet W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:264)
06-15 14:27:31.750 23382-26150/com.baseride.CloudFleet W/System.err: at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
06-15 14:27:31.760 23382-26150/com.baseride.CloudFleet W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:137)
06-15 14:27:31.765 23382-26150/com.baseride.CloudFleet W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
06-15 14:27:31.775 23382-26150/com.baseride.CloudFleet W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-15 14:27:31.780 23382-26150/com.baseride.CloudFleet W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-15 14:27:31.790 23382-26150/com.baseride.CloudFleet W/System.err: at java.lang.Thread.run(Thread.java:856)
```

On a more recent device, error doesn't occur, the [example code](https://www.mapbox.com/android-sdk/examples/) is being used.

Device: Samsung Galaxy S2 (GT-I9100)
OS: Android 4.0.3 (API 15)
Mapbox SDK: `4.0.1`/ `4.1.0-beta.2`/`4.0.0-beta.2`

cc: @tobrun

**Comment by tobrun** [comment]
I verified and this shouldn't occur anymore due to the following construction in `FlushTheEventsTask ` :

```java
} catch (Exception e) {
       Log.e(TAG, "FlushTheEventsTask borked: " + e);
       e.printStackTrace();
}
```

Closing for now, reopen if still an issue after retesting with `4.1.0-beta3`.

**Comment by ech89899** [comment]
I still have the issue after updating Mapbox to 4.1.0-beta.3.
My activity with Mapbox MapView looks like this on Android 4.0.3 device:
![screenshot_2016-06-25-16-33-19](https://cloud.githubusercontent.com/assets/11990453/16357028/000eb32e-3afc-11e6-8121-77dc641384e8.png)
