### ISSUE TITLE
Android Mapbox crash after set 'minifyEnabled' to true

### ISSUE THREAD

**Issue by cbiao** [mapbox/mapbox-gl-native#5488]
**Platform:**
- Android 6.0.1
- Android Studio 2.1.2
- compileSdkVersion 23
- buildToolsVersion 23.0.3
- ProGuard 4.7

**Mapbox SDK version: 4.1.0-beta.3**
### Steps to trigger behavior

 1. set `minifyEnabled` to true in Android Studio.
 1. even try to add `-keep class *.** { *; }` to proguard-rules.pro, still not working.

or take **MapboxGLAndroidSDKTestApp** for example:

1. build `release-android-v4.1.0` source (build type release, set access tokens and sign).
1. keep `minifyEnabled false` unchanged, map of test app works fine.
1. set `minifyEnabled` to true, rebuild (build type release, set access tokens and sign).
1. click any sample of test app, crash.

### Expected behavior
Everything is ok.

### Actual behavior
Map works fine when minifyEnabled is false, but crash after set to true:

```
06-27 18:34:04.196: E/AndroidRuntime(10347): FATAL EXCEPTION: main
06-27 18:34:04.196: E/AndroidRuntime(10347): Process: com.mapbox.mapboxsdk.testapp, PID: 10347
06-27 18:34:04.196: E/AndroidRuntime(10347): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxsdk.testapp/com.mapbox.mapboxsdk.testapp.activity.maplayout.MapPaddingActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.mapbox.mapboxsdk.maps.MapView
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.os.Looper.loop(Looper.java:148)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at java.lang.reflect.Method.invoke(Native Method)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-27 18:34:04.196: E/AndroidRuntime(10347): Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.mapbox.mapboxsdk.maps.MapView
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.testapp.activity.maplayout.MapPaddingActivity.onCreate(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.Activity.performCreate(Activity.java:6251)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	... 9 more
06-27 18:34:04.196: E/AndroidRuntime(10347): Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.mapbox.mapboxsdk.maps.MapView
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	... 17 more
06-27 18:34:04.196: E/AndroidRuntime(10347): Caused by: java.lang.reflect.InvocationTargetException
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at java.lang.reflect.Constructor.newInstance(Native Method)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	... 22 more
06-27 18:34:04.196: E/AndroidRuntime(10347): Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.maps.MapboxMap$MarkerViewAdapter.<init>(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.annotations.MarkerViewManager$ImageMarkerViewAdapter.<init>(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.annotations.MarkerViewManager.<init>(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.maps.MapboxMap.<init>(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.maps.MapView.initialize(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	at com.mapbox.mapboxsdk.maps.MapView.<init>(Unknown Source)
06-27 18:34:04.196: E/AndroidRuntime(10347): 	... 24 more
```

**Comment by chanbiao** [comment]
Finally, I found the lost ProGuard rule:

> `-keepattributes Signature`

I suggest Mapbox Android SDK should add this rule to [**proguard-rules.pro**](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/proguard-rules.pro).

**Comment by cbiao** [comment]
Finally, I found the lost ProGuard rule:

> `-keepattributes Signature`

I suggest Mapbox Android SDK should add this rule to [**proguard-rules.pro**](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/proguard-rules.pro).

**Comment by tobrun** [comment]
Recently looked into optimising proguard for 4.2.0 in #6718. Closing
