### ISSUE TITLE
Crashes at map init with empty CameraPosition option.

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#5607]
I am building a Cordova plugin for Mapbox in https://github.com/Telerik-Verified-Plugins/Mapbox/pull/29

**Platform:** Android
**Mapbox SDK version:** 4.1.0-beta.3

### Steps to trigger behavior

 1. Create a `MapboxMapOptions` object with an empty camera position.
```
  public MapboxMapOptions options = new MapboxMapOptions();
  options.camera(new CameraPosition.Builder().build());
```
 2. Init the map with this option object.

  `_mapView = new MapView(_activity, options);`

### Actual behavior
Crash when attempting to access last camera position which obviously does not exist:

* here (both on Nexus emulator and USB Galaxy S3 mini device):
```
--------- beginning of /dev/log/system
    07-07 05:59:58.006 3255-3255/io.cordova.hellocordova E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.cordova.hellocordova, PID: 3255
    java.lang.NullPointerException
    at com.mapbox.mapboxsdk.camera.CameraUpdateFactory$CameraPositionUpdate.getCameraPosition(CameraUpdateFactory.java:190)
    at com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:278)
    at com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:266)
    at com.mapbox.mapboxsdk.maps.MapView.setInitialState(MapView.java:260)
    at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:247)
    at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:182)
    at com.telerik.plugins.mapbox.MapController.<init>(MapController.java:65)
    at com.telerik.plugins.mapbox.Map.<init>(Map.java:80)
    at com.telerik.plugins.mapbox.MapsManager.createMap(MapsManager.java:36)
    at com.telerik.plugins.mapbox.CDVMapbox$1.run(CDVMapbox.java:163)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5017)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    at dalvik.system.NativeStart.main(Native Method)
    07-07 05:59:58.016 1620-1895/system_process W/ActivityManager:   Force finishing activity io.cordova.hellocordova/.MainActivity
```

* and also here (just on a the USB Galaxy S3 mini device) when I add the locationEnabled option.
```
07-07 12:12:24.122 3211-3211/io.cordova.hellocordova W/System.err: java.lang.NullPointerException
07-07 12:12:24.132 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$MyLocationShowBehavior.updateLatLng(MyLocationView.java:713)
07-07 12:12:24.132 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setLocation(MyLocationView.java:402)
07-07 12:12:24.132 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:374)
07-07 12:12:24.132 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(MyLocationView.java:341)
07-07 12:12:24.132 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.MapView.setMyLocationEnabled(MapView.java:2415)
07-07 12:12:24.132 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(MapboxMap.java:1526)
07-07 12:12:24.212 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.MapView.setInitialState(MapView.java:289)
07-07 12:12:24.212 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:247)
07-07 12:12:24.212 3211-3211/io.cordova.hellocordova W/System.err:     at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:182)
07-07 12:12:24.212 3211-3211/io.cordova.hellocordova W/System.err:     at com.telerik.plugins.mapbox.MapController.<init>(MapController.java:65)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at com.telerik.plugins.mapbox.Map.<init>(Map.java:80)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at com.telerik.plugins.mapbox.MapsManager.createMap(MapsManager.java:36)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at com.telerik.plugins.mapbox.CDVMapbox$1.run(CDVMapbox.java:163)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at android.app.Activity.runOnUiThread(Activity.java:4630)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at com.telerik.plugins.mapbox.CDVMapbox.execute(CDVMapbox.java:160)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:135)
07-07 12:12:24.232 3211-3211/io.cordova.hellocordova W/System.err:     at org.apache.cordova.engine.SystemWebChromeClient.onJsPrompt(SystemWebChromeClient.java:124)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:886)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at android.os.Looper.loop(Looper.java:137)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4867)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
07-07 12:12:24.262 3211-3211/io.cordova.hellocordova W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by tobrun** [comment]
It's expected for a null pointer to be thrown in that case, this is on par what Google Maps SDK would produce [here](https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition.html#CameraPosition(com.google.android.gms.maps.model.LatLng, float, float, float)).
