### ISSUE TITLE
MyLocationView Drawables not parceling with MapboxMapOptions

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5875]
When the map is contained inside a fragment and the user location is enabled, the view isn't showing up on the map. You are still able to get the user location position though.

cc: @tobrun

**Comment by tobrun** [comment]
Looked into this and noticed that no views are shown on top of the map (eg. MyLocationView, logo, compass,..).

**Comment by tobrun** [comment]
Just did another test with a ViewMarker and it's showing up, that only leaves the issue for MyLocationView

**Comment by tobrun** [comment]
Figured it out, the issue occurs with MapboxMapOptions and drawable integration. We are currently not serialising the drawables. A workaround for now is to execute the following code in the `OnMapReadyCallback`:

```
foregroundDrawable = ContextCompat.getDrawable(context, R.drawable.ic_mylocationview_normal);
foregroundBearingDrawable = ContextCompat.getDrawable(context, R.drawable.ic_mylocationview_bearing);
backgroundDrawable = ContextCompat.getDrawable(context, R.drawable.ic_mylocationview_background);

-> insert these into: mMapboxMap.getMyLocationViewSettings().set...Drawable()
```

cc @cammace

**Comment by zugaldia** [comment]
@cammace Could you check if https://github.com/mapbox/mapbox-gl-native/pull/5984 fixes the original issue?

**Comment by cammace** [comment]
Tested if the user location view shows in the fragment:

<img src="https://cloud.githubusercontent.com/assets/5652865/17740146/91bc19f0-6465-11e6-8f7b-a331fa3661c4.png" width=360/>


it worked until you pause the activity, the app will crash giving this error: 
```
08-17 10:14:53.065 13274-13274/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 13274
                                                                              java.lang.IllegalArgumentException: unsupported drawable type
                                                                                  at com.mapbox.mapboxsdk.maps.MapboxMapOptions.getBitmapFromDrawable(MapboxMapOptions.java:154)
                                                                                  at com.mapbox.mapboxsdk.maps.MapboxMapOptions.writeToParcel(MapboxMapOptions.java:909)
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1495)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1401)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:723)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:763)
                                                                                  at android.app.FragmentState.writeToParcel(Fragment.java:147)
                                                                                  at android.os.Parcel.writeTypedArray(Parcel.java:1306)
                                                                                  at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:381)
                                                                                  at android.os.Parcel.writeParcelable(Parcel.java:1495)
                                                                                  at android.os.Parcel.writeValue(Parcel.java:1401)
                                                                                  at android.os.Parcel.writeArrayMapInternal(Parcel.java:723)
                                                                                  at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
                                                                                  at android.os.Bundle.writeToParcel(Bundle.java:1133)
                                                                                  at android.os.Parcel.writeBundle(Parcel.java:763)
                                                                                  at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3603)
                                                                                  at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3744)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by tobrun** [comment]
Thanks for thoroughly testing this. It seemed we had to add support gradientdrawable. 
This is currently not crashing anymore but is resulting in:

![device-2016-08-19-104529](https://cloud.githubusercontent.com/assets/2151639/17804045/1c4401d8-65fa-11e6-9f4f-cc72217a353d.png)
