### ISSUE TITLE
[Android] Fatal Exception: java.lang.IllegalArgumentException: height cannot be greater than 65535.

### ISSUE THREAD

**Issue by DmitryTankovich** [mapbox/mapbox-gl-native#6111]
Fatal Exception: java.lang.IllegalArgumentException: height cannot be greater than 65535.
       at com.mapbox.mapboxsdk.maps.NativeMapView.resizeView(SourceFile:146)
       at com.mapbox.mapboxsdk.maps.MapView.onSizeChanged(SourceFile:1337)
       at android.view.View.sizeChange(View.java:16019)
       at android.view.View.setFrame(View.java:15992)
       at android.view.View.layout(View.java:15899)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.support.v4.widget.DrawerLayout.onLayout(SourceFile:1187)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1692)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1534)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1443)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
       at android.view.View.layout(View.java:15903)
       at android.view.ViewGroup.layout(ViewGroup.java:4932)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2425)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2140)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1316)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6804)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
       at android.view.Choreographer.doCallbacks(Choreographer.java:613)
       at android.view.Choreographer.doFrame(Choreographer.java:583)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5752)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jfirebaugh** [comment]
@DmitryTankovich This issue and your two subsequent issues are missing key information that we need to diagnose what's happening. Can you please use the template that is provided when submitting an issue? 

```
<!--
Hello and thanks for contributing! To help us diagnose your problem quickly, please:

 - Include a minimal demonstration of the bug, including code, logs, and screenshots.
 - Ensure you can reproduce the bug using the latest release.
 - Only post to report a bug or request a feature; direct all other questions to: https://stackoverflow.com/questions/tagged/mapbox
-->

**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

### Expected behavior

### Actual behavior
```

**Comment by tobrun** [comment]
I have heard about this exception once before. The user wasn't able to give me reproducible scenario since he was collecting these stack traces from a crash reporting tool. 

It's related to the following code:

`NativeMapView.java`
```
public void resizeView(int width, int height) {
        if (width < 0) {
            throw new IllegalArgumentException("width cannot be negative.");
        }

        if (height < 0) {
            throw new IllegalArgumentException("height cannot be negative.");
        }

        if (width > 65535) {
            throw new IllegalArgumentException(
                    "width cannot be greater than 65535.");
        }

        if (height > 65535) {
            throw new IllegalArgumentException(
                    "height cannot be greater than 65535.");
        }
        nativeViewResize(mNativeMapViewPtr, width, height);
    }
```

The stack traces I looked at indicated a clean startup and only occurred after a orientation change. I also take a look at the impacted devices and couldn't find any device that should return these kind of high values (ranges from top tier device to low end). I think at this point it's a bug in the android system that sporadically returns incorrect size values but haven't been able to reproduce myself. 

@DmitryTankovich 
Are you able to give us a bit more information on this issue? use-case? steps to reproduce?

@jfirebaugh 
Do you know where the magic number 65535 is coming from?

Next steps is to reproducing this and look into not throwing a runtime exception.

**Comment by DmitryTankovich** [comment]
@tobrun 
94% samsung devices:
GT-I9301I, GT-I9190, GT-I9192
OS Versios:
 4.4.2, 4.4.4, 5.0.2, 5.1.1

mapbox-android-sdk:4.1.0-beta.3

I don't have more information

**Comment by DmitryTankovich** [comment]
same error
com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar

**Comment by DmitryTankovich** [comment]
"if (height > 65535)"
Maybe it would be better to remove this check?

**Comment by sictiru** [comment]
I'm having the same issued but in resizeFramebuffer

Fatal Exception: java.lang.IllegalArgumentException: fbHeight cannot be greater than 65535.
       at com.mapbox.mapboxsdk.maps.NativeMapView.resizeFramebuffer(NativeMapView.java:231)
       at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceChanged(MapView.java:436)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:698)
       at android.view.SurfaceView.setFrame(SurfaceView.java:364)

Samsung Note4 and S7 Edge with 5.1.1 and 7.0
Mapbox version 5.1.5
