### ISSUE TITLE
BulkMarkerActivity In Android TestApp Leaks

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#6239]
When running the TestApp's `BulkMarkerActivity` and then pressing the back button a memory leak occurs which inevitably leads issues running the TestApp.

``` java
09-01 17:38:15.800 30957-30957/com.mapbox.mapboxsdk.testapp E/WindowManager: android.view.WindowLeaked: Activity com.mapbox.mapboxsdk.testapp.activity.annotation.BulkMarkerActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{215450ff G.E..... R.....ID 0,0-1002,483} that was originally added here
                                                                                 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:457)
                                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
                                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                                 at android.app.Dialog.show(Dialog.java:312)
                                                                                 at android.app.ProgressDialog.show(ProgressDialog.java:116)
                                                                                 at android.app.ProgressDialog.show(ProgressDialog.java:99)
                                                                                 at com.mapbox.mapboxsdk.testapp.activity.annotation.BulkMarkerActivity$LoadLocationTask.<init>(BulkMarkerActivity.java:268)
                                                                                 at com.mapbox.mapboxsdk.testapp.activity.annotation.BulkMarkerActivity.onItemSelected(BulkMarkerActivity.java:94)
                                                                                 at android.widget.AdapterView.fireOnSelected(AdapterView.java:1093)
                                                                                 at android.widget.AdapterView.access$200(AdapterView.java:54)
                                                                                 at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1058)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5835)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

/cc @jfirebaugh

**Comment by tobrun** [comment]
Haven't seen any reports anymore after doing multiple leak fixes in the last month.
Closing.
