### ISSUE TITLE
Crash when the visibility of MapView is set to GONE 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6287]
User reported crash, occurs when you set the visibility to GONE in xml.

**Comment by tobrun** [comment]
I did a test with our `Press for Marker Activity` where I set the visibility to View.GONE in xml and hooked into the `reset` button click event to set visibility to View.VISIBLE.

Following gif shows no crash and everything is working as expected:

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/2151639/18331343/02ee66a6-7513-11e6-8fa2-7167ff7dc6d3.gif)

Closing as not reproducible..

**Comment by zhangkaiyue0701** [comment]
build.gradle
`compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.1@aar'){
        transitive=true
    }`

xml
```
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone"
        mapbox:style_url="@string/style_mapbox_streets" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/location_toggle_fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|bottom"
        android:layout_margin="16dp"
        tools:backgroundTint="#E55E5E" />

    <Button
        android:id="@+id/button_huan"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="change"/>

</android.support.design.widget.CoordinatorLayout>
```


MainActivity
```
public class MainActivity extends AppCompatActivity {

    @Bind(R.id.button_huan) Button button;
    private MapView mapView;
    private MapboxMap map;
    FloatingActionButton floatingActionButton;
    LocationServices locationServices;

    private static final int PERMISSIONS_LOCATION = 0;
    public boolean huan = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MapboxAccountManager.start(this,
            "pk.eyJ1IjoieXVleWluZ2t5IiwiYSI6ImI5OThkNTM0ZmE2YzZjMWZlMjYwMzU0MDIxMjgzZjVmIn0.bS1e1nHEhhgi5bc2d1pvyg");
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        locationServices = LocationServices.getLocationServices(MainActivity.this);

        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                map = mapboxMap;
            }
        });

        floatingActionButton = (FloatingActionButton) findViewById(R.id.location_toggle_fab);
        floatingActionButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (map != null) {
                    toggleGps(!map.isMyLocationEnabled());
                }
            }
        });

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (huan) {
                    map.setStyleUrl("mapbox://styles/yueyingky/cirx0wx4c002kgum64as7gc67");
                } else {
                    map.setStyleUrl("mapbox://styles/yueyingky/cirx94p230003g3ncicn3vijl");
                }
                huan = !huan;
            }
        });
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @UiThread
    public void toggleGps(boolean enableGps) {
        if (enableGps) {
            // Check if user has granted location permission
            if (!locationServices.areLocationPermissionsGranted()) {
                ActivityCompat.requestPermissions(this, new String[] {
                    Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION
                }, PERMISSIONS_LOCATION);
            } else {
                enableLocation(true);
            }
        } else {
            enableLocation(false);
        }
    }

    private void enableLocation(boolean enabled) {
        if (enabled) {
            locationServices.addLocationListener(new LocationListener() {
                @Override
                public void onLocationChanged(Location location) {
                    if (location != null) {
                        // Move the map camera to where the user location is
                        map.setCameraPosition(
                            new CameraPosition.Builder().target(new LatLng(location)).zoom(16).build());
                    }
                }
            });
            floatingActionButton.setAlpha(0.5f);
        } else {
            floatingActionButton.setAlpha(0.8f);
        }
        // Enable or disable the location layer on the map
        map.setMyLocationEnabled(enabled);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String permissions[],
                                           @NonNull int[] grantResults) {
        switch (requestCode) {
            case PERMISSIONS_LOCATION: {
                if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    enableLocation(true);
                }
            }
        }
    }
}
```


log
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.zhangkaiyue.mapboxdemo/com.example.zhangkaiyue.mapboxdemo.MainActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
at android.app.ActivityThread.access$700(ActivityThread.java:168)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:177)
at android.app.ActivityThread.main(ActivityThread.java:5493)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
at android.view.LayoutInflater.createView(LayoutInflater.java:669)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:804)
at android.view.LayoutInflater.inflate(LayoutInflater.java:526)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
at android.view.LayoutInflater.inflate(Native Method)
at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
at android.view.LayoutInflater.inflate(LayoutInflater.java:382)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
at com.example.zhangkaiyue.mapboxdemo.MainActivity.onCreate(MainActivity.java:43)
at android.app.Activity.performCreate(Activity.java:5372)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
at android.app.ActivityThread.access$700(ActivityThread.java:168) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:177) 
at android.app.ActivityThread.main(ActivityThread.java:5493) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at android.view.LayoutInflater.createView(LayoutInflater.java:643)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:804) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:526) 
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
at android.view.LayoutInflater.inflate(Native Method) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:382) 
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
at com.example.zhangkaiyue.mapboxdemo.MainActivity.onCreate(MainActivity.java:43) 
at android.app.Activity.performCreate(Activity.java:5372) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
at android.app.ActivityThread.access$700(ActivityThread.java:168) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:177) 
at android.app.ActivityThread.main(ActivityThread.java:5493) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.NullPointerException
at com.mapbox.mapboxsdk.maps.MapView.onVisibilityChanged(MapView.java:1502)
at android.view.View.dispatchVisibilityChanged(View.java:8115)
at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1096)
at android.view.View.setFlags(View.java:9488)
at android.view.View.<init>(View.java:3943)
at android.view.ViewGroup.<init>(ViewGroup.java:475)
at android.widget.FrameLayout.<init>(FrameLayout.java:101)
at android.widget.FrameLayout.<init>(FrameLayout.java:97)
at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:171)
at java.lang.reflect.Constructor.constructNative(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
at android.view.LayoutInflater.createView(LayoutInflater.java:643) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java:804) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:526) 
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
at android.view.LayoutInflater.inflate(Native Method) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:382) 
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
at com.example.zhangkaiyue.mapboxdemo.MainActivity.onCreate(MainActivity.java:43) 
at android.app.Activity.performCreate(Activity.java:5372) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
at android.app.ActivityThread.access$700(ActivityThread.java:168) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:177) 
at android.app.ActivityThread.main(ActivityThread.java:5493) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by KarenZZhang** [comment]
@tobrun

**Comment by KarenZZhang** [comment]
@zugaldia thank you!!!

**Comment by zhangkaiyue0701** [comment]
Now I write the MainActivity like this, but it still crashes.   Phone: Samsung Galaxy s3 GT-I93001, Android: 4.3. 

MainActivity
```
public class MainActivity extends AppCompatActivity {

    @Bind(R.id.button_huan) Button button;
    private MapView mapView;
    private MapboxMap map;

    public boolean change = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MapboxAccountManager.start(this,
            "pk.eyJ1IjoieXVleWluZ2t5IiwiYSI6ImI5OThkNTM0ZmE2YzZjMWZlMjYwMzU0MDIxMjgzZjVmIn0.bS1e1nHEhhgi5bc2d1pvyg");
        setContentView(R.layout.activity_main);
        ButterKnife.bind(this);

        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mapView.getVisibility() == View.GONE) {
                    mapView.setVisibility(View.VISIBLE);
                    mapView.getMapAsync(new OnMapReadyCallback() {
                        @Override
                        public void onMapReady(MapboxMap mapboxMap) {
                            map = mapboxMap;
                            changeStyle();
                        }
                    });
                } else {
                    changeStyle();
                }
            }
        });
    }

    private void changeStyle() {
        if (change) {
            map.setStyleUrl("mapbox://styles/yueyingky/cirx0wx4c002kgum64as7gc67");
        } else {
            map.setStyleUrl("mapbox://styles/yueyingky/cirx94p230003g3ncicn3vijl");
        }
        change = !change;
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }
}
```

**Comment by KarenZZhang** [comment]
@zugaldia

**Comment by zugaldia** [comment]
@zhangkaiyue0701 could you send the updated logcat for this crash?

**Comment by zhangkaiyue0701** [comment]
```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.zhangkaiyue.mapboxdemo/com.example.zhangkaiyue.mapboxdemo.MainActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
  at android.app.ActivityThread.access$700(ActivityThread.java:168)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:177)
  at android.app.ActivityThread.main(ActivityThread.java:5493)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:525)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
  at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
  at android.view.LayoutInflater.createView(LayoutInflater.java:669)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:804)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:526)
  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
  at android.view.LayoutInflater.inflate(Native Method)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:382)
  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
  at com.example.zhangkaiyue.mapboxdemo.MainActivity.onCreate(MainActivity.java:40)
  at android.app.Activity.performCreate(Activity.java:5372)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
  at android.app.ActivityThread.access$700(ActivityThread.java:168) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:177) 
  at android.app.ActivityThread.main(ActivityThread.java:5493) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:525) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
  at dalvik.system.NativeStart.main(Native Method) 
 Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Constructor.constructNative(Native Method)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
  at android.view.LayoutInflater.createView(LayoutInflater.java:643)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745) 
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:804) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:526) 
  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
  at android.view.LayoutInflater.inflate(Native Method) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:382) 
  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
  at com.example.zhangkaiyue.mapboxdemo.MainActivity.onCreate(MainActivity.java:40) 
  at android.app.Activity.performCreate(Activity.java:5372) 
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
  at android.app.ActivityThread.access$700(ActivityThread.java:168) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:177) 
  at android.app.ActivityThread.main(ActivityThread.java:5493) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:525) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
  at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.NullPointerException
  at com.mapbox.mapboxsdk.maps.MapView.onVisibilityChanged(MapView.java:1502)
  at android.view.View.dispatchVisibilityChanged(View.java:8115)
  at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1096)
  at android.view.View.setFlags(View.java:9488)
  at android.view.View.<init>(View.java:3943)
  at android.view.ViewGroup.<init>(ViewGroup.java:475)
  at android.widget.FrameLayout.<init>(FrameLayout.java:101)
  at android.widget.FrameLayout.<init>(FrameLayout.java:97)
  at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:171)
  at java.lang.reflect.Constructor.constructNative(Native Method) 
  at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
  at android.view.LayoutInflater.createView(LayoutInflater.java:643) 
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745) 
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:804) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:526) 
  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
  at android.view.LayoutInflater.inflate(Native Method) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:382) 
  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
  at com.example.zhangkaiyue.mapboxdemo.MainActivity.onCreate(MainActivity.java:40) 
  at android.app.Activity.performCreate(Activity.java:5372) 
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270) 
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362) 
  at android.app.ActivityThread.access$700(ActivityThread.java:168) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:177) 
  at android.app.ActivityThread.main(ActivityThread.java:5493) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:525) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041) 
  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
  at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by zugaldia** [comment]
@zhangkaiyue0701 Thanks for the info, unfortunately I'm unable to reproduce this one. Could you try:

1. With the latest `beta2` (I see in https://github.com/mapbox/mapbox-gl-native/issues/6287#issuecomment-245570869 that you were using `beta1`).
2. In a different device or emulator?
3. Moving the `MapView` from being a direct child of `CoordinatorLayout`? For example, to use a `RelativeLayout` you could change `activity_main.xml` to be like:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    ...
    
    <include layout="@layout/content_main" />

    <android.support.design.widget.FloatingActionButton
        ...
    />

</android.support.design.widget.CoordinatorLayout>
```

And then `content_main.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:showIn="@layout/activity_main">

    (Map and button go here)

</RelativeLayout>

```

Thanks, let me know if this helps.

**Comment by zugaldia** [comment]
Tracking this one here now: https://github.com/mapbox/mapbox-gl-native/issues/6317.
