### ISSUE TITLE
Error: " libGL.so.1: cannot open shared object file" in Ubuntu server without GUI

### ISSUE THREAD

**Issue by kjdongzh** [mapbox/mapbox-gl-native#6439]
I installed "mapbox-gl-native" for node in my Ubuntu server without GUI like this:
`
npm install mapbox-gl-native --save
`
when require the "mapbox-gl-native" module in a js file,it prompt errors
```bash
Error: libGL.so.1: cannot open shared object file: No such file or directory
at Error (native)
at Object.Module._extensions..node (module.js:434:18)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function._load (/home/bygis/n/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/bygis/judy/controllers/style.js:8:12)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function._load (/home/bygis/n/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/bygis/judy/router.js:5:14)
```
And this is my ENV:
```bash
Ubuntu 14.04 Server
node 4.4.4
npm 2.15.1
```

But it work fine when i use  mapbox-gl-native in Ubuntu 14.04 Server VM with GUI. How I can use node-mapbox-gl-native on a Ubuntu 14.04 Server without GUI? Whether to need to install any other module?

**Comment by jingsam** [comment]
Relate to #4922

**Comment by kkaefer** [comment]
You'll need to install the GL subsystem. Have a look at https://github.com/mapbox/mapbox-gl-native/blob/master/platform/linux/README.md

**Comment by lf1991** [comment]
I meet same isuse,the error is:  Error: libEGL.so.1: cannot open shared object file: No such file or directory.


CENTOS 7.6 node10.x how can I do ,this issue is Ubantu,no centos.thanks
