### ISSUE TITLE
Crash GeoJSON Clustering Activity

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6679]
The test activity crashes on start on a Alcatel Idol 4, Android 6.0.1 with logcat output:

```java
10-12 17:50:59.369 2041-2041/com.mapbox.mapboxsdk.testapp E/art: JNI ERROR (app bug): accessed stale local reference 0x29 (index 10 in a table of size 10)
10-12 17:50:59.405 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x29
10-12 17:50:59.405 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]     from void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.initialize(java.lang.String, java.lang.Object)
10-12 17:50:59.405 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
10-12 17:50:59.405 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x73ab1360 self=0xab100990
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=2041 nice=-3 cgrp=default sched=0/0 handle=0xf7592b38
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 2599689429 620254239 4298 ) utm=206 stm=53 core=5 HZ=100
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xff6f1000-0xff6f3000 stackSize=8MB
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 0035c8ad  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+116)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 0033d383  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+138)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0024f539  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+760)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0024fc41  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+68)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 0033e0df  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+686)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 000ffeb5  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+900)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 00107ad7  /system/lib/libart.so (_ZN3art8CheckJNI12IsInstanceOfEP7_JNIEnvP8_jobjectP7_jclass+374)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 00048c44  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 000a63c4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 000a2948  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 000a76f0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 000a6b4c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 000a6ac8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 000a6c1c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #14 pc 00781501  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.initialize(java.lang.String, java.lang.Object)+116)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #15 pc 007812e7  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.<init>(java.lang.String, java.net.URL, com.mapbox.mapboxsdk.style.sources.GeoJsonOptions)+90)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #16 pc 00a447dd  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity.addClusteredGeoJsonSource()+560)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #17 pc 00a44543  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity.access$100(com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity)+86)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #18 pc 007a0f4f  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity$1.onMapReady(com.mapbox.mapboxsdk.maps.MapboxMap)+586)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #19 pc 0076f8c9  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.MapView$1.onMapChanged(int)+844)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #20 pc 003791d9  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.MapView.onMapChanged(int)+236)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #21 pc 00392f13  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (void com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(int)+62)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #22 pc 000e61b1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #23 pc 003eb50b  /system/lib/libart.so (art_quick_invoke_stub+170)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   native: #24 pc 007fd674  [stack] (???)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.initialize(Native method)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.<init>(GeoJsonSource.java:95)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity.addClusteredGeoJsonSource(GeoJsonClusteringActivity.java:119)
10-12 17:50:59.406 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity.access$100(GeoJsonClusteringActivity.java:39)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity$1.onMapReady(GeoJsonClusteringActivity.java:64)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.MapView$1.onMapChanged(MapView.java:480)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.MapView.onMapChanged(MapView.java:2586)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:570)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.MessageQueue.nativePollOnce(Native method)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.MessageQueue.next(MessageQueue.java:323)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Looper.loop(Looper.java:135)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.main(ActivityThread.java:5515)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.reflect.Method.invoke!(Native method)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:654)
10-12 17:50:59.407 2041-2041/com.mapbox.mapboxsdk.testapp A/art: art/runtime/java_vm_ext.cc:410] 
```

NDK stack output:

```JAVA
********** Crash dump: **********
Build fingerprint: 'TCL/6055K/idol4:6.0.1/MMB29M/v1AHE-0:user/release-keys'
pid: 2041, tid: 2041, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Stack frame #00 pc 00044330  /system/lib/libc.so (tgkill+12)
Stack frame #01 pc 00041f31  /system/lib/libc.so (pthread_kill+32)
Stack frame #02 pc 0001ba5f  /system/lib/libc.so (raise+10)
Stack frame #03 pc 00018c01  /system/lib/libc.so (__libc_android_abort+34)
Stack frame #04 pc 000167c0  /system/lib/libc.so (abort+4)
Stack frame #05 pc 003216f1  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+212)
Stack frame #06 pc 000f3c6d  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2212)
Stack frame #07 pc 0024f835  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1524)
Stack frame #08 pc 0024fc41  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+68)
Stack frame #09 pc 0033e0df  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+686)
Stack frame #10 pc 000ffeb5  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+900)
Stack frame #11 pc 00107ad7  /system/lib/libart.so (_ZN3art8CheckJNI12IsInstanceOfEP7_JNIEnvP8_jobjectP7_jclass+374)
Stack frame #12 pc 00048c44  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine _JNIEnv::IsInstanceOf(_jobject*, _jclass*) at /Users/Nurbot/mapbox-gl-native/mason_packages/osx-x86_64/android-ndk/arm-9-r12b/sysroot/usr/include/jni.h:603
Stack frame #13 pc 000a63c4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::style::conversion::toBool(mbgl::android::Value const&) at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../platform/android/src/style/sources/../android_conversion.hpp:54
Stack frame #14 pc 000a2948  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::style::conversion::Result<mbgl::style::GeoJSONOptions> mbgl::style::conversion::convert<mbgl::style::GeoJSONOptions, mbgl::android::Value>(mbgl::android::Value const&) at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../include/mbgl/style/conversion.hpp:90
Stack frame #15 pc 000a76f0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__unique_if<mbgl::android::GeoJSONSource>::__unique_single std::__ndk1::make_unique<mbgl::android::GeoJSONSource, _JNIEnv&, jni::Object<jni::StringTag>, jni::Object<jni::ObjectTag> >(_JNIEnv&, jni::Object<jni::StringTag>&&, jni::Object<jni::ObjectTag>&&) at /Users/Nurbot/mapbox-gl-native/mason_packages/osx-x86_64/android-ndk/arm-9-r12b/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/memory:3047
Stack frame #16 pc 000a6b4c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../mason_packages/headers/jni.hpp/2.0.0/include/jni/native_method.hpp:302
Stack frame #17 pc 000a6ac8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../mason_packages/headers/jni.hpp/2.0.0/include/jni/native_method.hpp:112 (discriminator 3)
Stack frame #18 pc 000a6c1c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *, jni::jstring *, jni::jobject *> at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../mason_packages/headers/jni.hpp/2.0.0/include/jni/native_method.hpp:59
Stack frame #19 pc 00f87501  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.initialize(java.lang.String, java.lang.Object)+116)
Stack frame #20 pc 00f872e7  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.style.sources.GeoJsonSource.<init>(java.lang.String, java.net.URL, com.mapbox.mapboxsdk.style.sources.GeoJsonOptions)+90)
Stack frame #21 pc 0124a7dd  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity.addClusteredGeoJsonSource()+560)
Stack frame #22 pc 0124a543  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity.access$100(com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity)+86)
Stack frame #23 pc 00fa6f4f  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.testapp.activity.style.GeoJsonClusteringActivity$1.onMapReady(com.mapbox.mapboxsdk.maps.MapboxMap)+586)
Stack frame #24 pc 00f758c9  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.maps.MapView$1.onMapChanged(int)+844)
Stack frame #25 pc 00b7f1d9  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.maps.MapView.onMapChanged(int)+236)
Stack frame #26 pc 00b98f13  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x806000) (void com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(int)+62)
Stack frame #27 pc 000e61b1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
Stack frame #28 pc 003eb50b  /system/lib/libart.so (art_quick_invoke_stub+170)
Stack frame #29 pc 007fd674  [stack]
```

Afterwards it also dumps out a whole [runtime aborting](https://gist.github.com/tobrun/a5353457dcfd35a5f343bf27c33cd978) message.

cc @ivovandongen

**Comment by ivovandongen** [comment]
@tobrun I was able to reproduce this on a Nexus 5. Will investigate now.
