### ISSUE TITLE
Caused by java.lang.RuntimeException: The dimensions from location and bearing drawables should be match

### ISSUE THREAD

**Issue by DmitryTankovich** [mapbox/mapbox-gl-native#6839]
Devices Samsung SM-G925F, SM-G920F
OS 6.0.1
com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar

Caused by java.lang.RuntimeException: The dimensions from location and bearing drawables should be match
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setForegroundDrawables(SourceFile:156)
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationViewSettings.setForegroundDrawable(SourceFile:101)
       at com.mapbox.mapboxsdk.maps.MapView.setInitialState(SourceFile:283)
       at com.mapbox.mapboxsdk.maps.MapView.initialize(SourceFile:247)
       at com.mapbox.mapboxsdk.maps.MapView.(SourceFile)
       at mapbox.BaseMapView.(SourceFile)
       at mapbox.MMapView.(SourceFile)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:631)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:966)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:843)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:284)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:140)
       at ui_activities.MainActivity.onCreate(SourceFile:153)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by tobrun** [comment]
@DmitryTankovich any more information on this issue? 
The exception thrown shows that the sizes from those 2 drawables do not match:

`MyLocationViewSettings`:

```java
  /**
     * Set the foreground drawable of the MyLocationView
     * <p>
     * The foreground drawable is the image visible on screen
     * </p>
     *
     * @param foregroundDrawable        the drawable to show as foreground without bearing
     * @param foregroundBearingDrawable the drawable to show as foreground when bearing is enabled
     */
    public void setForegroundDrawable(Drawable foregroundDrawable, Drawable foregroundBearingDrawable) {
        this.foregroundDrawable = foregroundDrawable;
        this.foregroundBearingDrawable = foregroundBearingDrawable;
        myLocationView.setForegroundDrawables(foregroundDrawable, foregroundBearingDrawable);
    }
```

To have a correctly working transformation the 2 state images should match.

**Comment by tobrun** [comment]
This is an expected exception, without additional information not actionable, closing.
