### ISSUE TITLE
bad alloc in native render

### ISSUE THREAD

**Issue by zimbricchio** [mapbox/mapbox-gl-native#6881]
**Platform:** 
Android 6

**Mapbox SDK version:**
4.2.0-beta.4
4.1.1

**Device:** 
Samsung Galaxy Note 4 
Samsung Galaxy S5

I have an activity that contains a map using a MapView.

```
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:style_url="@string/style_mapbox_streets"
        android:layout_below="@+id/pnlAddress"
    />
```

The MapView fills the content view and has a couple of simple controls drawn on top of it.
A marker is added to the MapView in the activity's onCreate.

When the app starts, it **downloads an offline area**.
The map is inside that offline area.

My app goes thru a series of activities in a cycle.
Hence the map activity gets created and destroyed repeatedly.
Methods onCreate, onPause, and so on, are properly overridden.

**After less than 10 times that the activity gets created**, the app will crash because of **std::bad_alloc error** coming from **NativeMapView.nativeRender**.

**Edit:**
just got an **java.lang.Error: eglSwapBuffers() failed** error again from **NativeMapView.nativeRender**.

Any clues?
I will try to test on more devices and remove some parts of my code to see if I can get rid of the problem.

Thx for any suggestions.

LogCat:

```
java.lang.Error: std::bad_alloc
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:143)
at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:1460)
at android.view.View.draw(View.java:17469)
at android.view.View.updateDisplayListIfDirty(View.java:16464)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
at android.view.View.updateDisplayListIfDirty(View.java:16424)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
at android.view.View.updateDisplayListIfDirty(View.java:16424)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
at android.view.View.updateDisplayListIfDirty(View.java:16424)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
at android.view.View.updateDisplayListIfDirty(View.java:16424)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
at android.view.View.updateDisplayListIfDirty(View.java:16424)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
at android.view.View.updateDisplayListIfDirty(View.java:16424)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:695)
at android.view.Choreographer.doFrame(Choreographer.java:631)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7225)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by vanshg** [comment]
I'm having a similar issue. I've been getting constant crash reports in NativeMapView#nativeRender. I haven't been able to reproduce on my end, so I'm not really sure what the issue is. Here is the stack trace I get

```
Exception java.lang.Error: std::bad_alloc
com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender (NativeMapView.java)
com.mapbox.mapboxsdk.maps.NativeMapView.render (NativeMapView.java:143)
com.mapbox.mapboxsdk.maps.MapView.onDraw (MapView.java:1491)
android.view.View.draw (View.java:17476)
android.view.View.updateDisplayListIfDirty (View.java:16469)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
android.view.View.updateDisplayListIfDirty (View.java:16429)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3885)
android.view.View.updateDisplayListIfDirty (View.java:16429)
android.view.ViewGroup.recreateChildDisplayList (ViewGroup.java:3905)
```

I also get a couple differnt Exceptions:
Exception java.lang.Error: std::bad_alloc
Exception java.lang.Error: eglMakeCurrent() failed
Exception java.lang.Error: eglSwapBuffers() failed

Any way I can narrow down what's causing the errors?

**Comment by zimbricchio** [comment]
Did you take a look at this #6921?

Basically I was creating an activity with a map inside multiple times and so would run out of memory.

The solution for me was to "go back" to the activity restarting the task:

```     
        final Intent intent = new Intent(this, aClass);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
        goToActivity(intent);
```

Or you can just call Activity#Finish to get rid of it.

**Comment by vanshg** [comment]
@zimbricchio Hm I don't think that's the case. The map is in my MainActivity, and I only ever have 1 instance of my MainActivity
