### ISSUE TITLE
Error receiving broadcast Intent: com.mapbox.mapboxsdk.telemetry.TelemetryLocationReceiver

### ISSUE THREAD

**Issue by mrfaa** [mapbox/mapbox-gl-native#6934]
**Platform: Android 6.0.1 , Nexus 4**
**Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar**

### Steps to trigger behavior
Random Bug.

### Crash report

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.mapbox.mapboxsdk.telemetry.TelemetryLocationReceiver flg=0x10 pkg=XXX } in com.mapbox.mapboxsdk.telemetry.TelemetryLocationReceiver@6fe5dee
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
       at com.mapbox.mapboxsdk.telemetry.TelemetryLocationReceiver.onReceive(TelemetryLocationReceiver.java:64)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by tobrun** [comment]
Seems that we are not null checking the incoming intent or the related bundle, 
thank you for reporting @mrfaa!
