### ISSUE TITLE
Freeze on instance state recreation

### ISSUE THREAD

**Issue by JustSayBien** [mapbox/mapbox-gl-native#7144]
**Platform:** Android 7.0
**Mapbox SDK version:** 4.2.0 Beta 5

### Steps to trigger behavior

 1. Create MapView with myLocation enabled
 2. Turn your device (portrait to landscape) to trigger an orientation change respectively instance recreation

### Expected behavior
App should not freeze.

### Actual behavior
App freezes. After some time following exception is logged:
```
Key tilt expected Float but value was a java.lang.Double.  The default value 0.0 was returned
Attempt to cast generated internal exception:
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
    at android.os.BaseBundle.getFloat(BaseBundle.java:941)
    at android.os.Bundle.getFloat(Bundle.java:734)
    at android.os.BaseBundle.getFloat(BaseBundle.java:923)
    at android.os.Bundle.getFloat(Bundle.java:721)
    at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.onRestoreInstanceState(MyLocationView.java:404)
    at android.view.View.dispatchRestoreInstanceState(View.java:15633)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3274)
    at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3274)
    at android.view.View.restoreHierarchyState(View.java:15611)
    at android.support.v4.app.Fragment.restoreViewState(Fragment.java:480)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1140)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1277)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2154)
    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
    at android.app.Activity.performStart(Activity.java:6681)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4483)
    at android.app.ActivityThread.-wrap19(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Not sure if this happens in every scenario ("show user location" of the mapbox demo app seems to work fine). I am using a custom style. No problems with previous version 4.2.0 Beta 4.

**Comment by tobrun** [comment]
Thank you for flagging, we recently tried streamlining the usage of double/float. This occurence slipped was handled correctly. Pachting up now.
