### ISSUE TITLE
Unregister the ConnectivityReceiver

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#7176]
Currently, we're registering a `ConnectivityReceiver` in `MapboxAccountManager`, but we are not unregistering it. For users with Leak Canary installed, you can observe an error like the following:

```
MainActivity has leaked IntentReceiver com.mapbox.mapboxsdk.net.ConnectivityReceiver@9d069e70 that was originally registered here. Are you missing a call to unregisterReceiver()? android.app.IntentReceiverLeaked: Activity .MainActivity has leaked IntentReceiver com.mapbox.mapboxsdk.net.ConnectivityReceiver@9d069e70 that was originally registered here. Are you missing a call to unregisterReceiver()?
 at android.app.LoadedApk$ReceiverDispatcher.(LoadedApk.java:805)
 at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:606)
 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1430)
 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1410)
 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1404)
 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:467)
 at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:35)
 at com.mapbox.mapboxsdk.MapboxAccountManager.start(MapboxAccountManager.java:53)
 at info.masterskaya.om.rxjavanetexample.MainActivity.onCreate(MainActivity.java:39)
 at android.app.Activity.performCreate(Activity.java:5231)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
 at android.app.ActivityThread.access$800(ActivityThread.java:135)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:136)
 at android.app.ActivityThread.main(ActivityThread.java:5017)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
 at dalvik.system.NativeStart.main(Native Method)
```

(Ref: http://stackoverflow.com/questions/40701400/android-mapbox-how-to-unregister-intentreceiver)

/cc: @mapbox/android @Guardiola31337

**Comment by sddamico** [comment]
The easier workaround would be to use the application context when registering the receiver `context.getApplicationContext()`, especially since it is meant to be an application signleton
