### ISSUE TITLE
MapView rendering problem in android studio 2.2.3

### ISSUE THREAD

**Issue by arpit999bicubic** [mapbox/mapbox-gl-native#7320]
**Platform: Android**
**Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar'**

**Here is error 

`ava.lang.UnsupportedOperationException: Unsupported Service: location
	at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:602)
	at com.mapzen.android.lost.internal.FusionEngine.<init>(FusionEngine.java:38)
	at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.<init>(FusedLocationProviderApiImpl.java:27)
	at com.mapzen.android.lost.internal.LostApiClientImpl.connect(LostApiClientImpl.java:21)
	at com.mapbox.mapboxsdk.location.LocationServices.toggleGPS(LocationServices.java:88)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:382)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(MyLocationView.java:335)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.init(MyLocationView.java:121)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.<init>(MyLocationView.java:112)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.BridgeInflater.inflate(BridgeInflater.java:299)
	at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:192)
	at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:170)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$70(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by tobrun** [comment]
Thank you for reaching out and reporting your problem.
Would you able to validate with one of our newer versions of the library? 

```gradle
   compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.5@aar') {
        transitive=true
    }
```

Could you add some information how to trigger this exception?

**Comment by arpit999bicubic** [comment]
i am using CoordinatorLayout. with overlap other layout above mapbox. sorry for my bad english.

**Here is my code 

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/coordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#a3b1ef"
    android:fitsSystemWindows="true"
    tools:context=".activity.SelectTourActivity">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView_tour_select"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:style_url="mapbox://styles/bicubicstudios/citpl5t1c00102iqcxb2jlkhi"
        mapbox:zoom="10" />

    <LinearLayout
        android:id="@+id/bottom_sheet"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#fff"
        android:gravity="center"
        android:orientation="vertical"
        app:layout_behavior="@string/bottom_sheet_behavior">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="16dp"
            android:layout_marginTop="16dp"
            android:background="#fff" />

    </LinearLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <RelativeLayout
                android:id="@+id/rel_tour_first"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="13dp"
                android:background="@color/white_one"
                android:padding="8dp">

                
                <ImageView
                    android:id="@+id/img_tour"
                    android:layout_width="80dp"
                    android:layout_height="80dp"
                    android:layout_alignParentLeft="true"
                    android:layout_alignParentStart="true"
                    android:layout_marginEnd="8dp"
                    android:layout_marginRight="8dp"
                    android:background="@drawable/profile" />


                <RelativeLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerVertical="true"
                    android:layout_toEndOf="@+id/img_tour"
                    android:layout_toLeftOf="@+id/lin_end"
                    android:layout_toRightOf="@+id/img_tour"
                    android:layout_toStartOf="@+id/lin_end"
                    android:gravity="center_vertical">

                    
                    <TextView
                        android:id="@+id/title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="8dp"
                        android:layout_marginStart="8dp"
                        android:text="Title"
                        android:textSize="20sp"
                        android:textStyle="bold" />

                    <TextView
                        android:id="@+id/tv_desc"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_below="@+id/title"
                        android:layout_marginLeft="8dp"
                        android:layout_marginStart="8dp"
                        android:text="Description kjkljkl kljnlk"
                        android:textSize="16sp" />

                </RelativeLayout>

                <LinearLayout
                    android:id="@+id/lin_end"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentEnd="true"
                    android:layout_alignParentRight="true"
                    android:layout_centerVertical="true"
                    android:gravity="center_vertical"
                    android:orientation="vertical"
                    android:paddingRight="8dp">

                    <ImageView
                        android:layout_width="40dp"
                        android:layout_height="40dp"
                        android:layout_gravity="center_horizontal"
                        android:background="@mipmap/tour_delete_button"
                        android:gravity="center_horizontal" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        android:layout_marginTop="5dp"
                        android:gravity="center_horizontal"
                        android:text="20 MB" />

                </LinearLayout>


            </RelativeLayout>

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="top">

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1dp"
                    android:layout_centerVertical="true"
                    android:layout_toEndOf="@+id/complete_tours"
                    android:layout_toLeftOf="@+id/complete_tours"
                    android:layout_toRightOf="@+id/complete_tours"
                    android:background="@color/black" />

                <com.bicubic.gincana.widget.CustomTextView
                    android:id="@+id/complete_tours"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:background="@drawable/round_corner_black"
                    android:gravity="center_horizontal"
                    android:paddingBottom="4dp"
                    android:paddingLeft="8dp"
                    android:paddingRight="8dp"
                    android:paddingTop="4dp"
                    android:text="Completed tours"
                    android:textColor="@color/yellow"
                    android:textSize="16sp"
                    app:font="varelaround_regular.ttf" />

                <View
                    android:layout_width="match_parent"
                    android:layout_height="1dp"
                    android:layout_alignParentLeft="true"
                    android:layout_alignParentStart="true"
                    android:layout_centerVertical="true"
                    android:layout_toLeftOf="@+id/complete_tours"
                    android:layout_toRightOf="@+id/complete_tours"
                    android:layout_toStartOf="@+id/complete_tours"
                    android:background="@color/black" />

            </RelativeLayout>

        </RelativeLayout>


    </FrameLayout>

</android.support.design.widget.CoordinatorLayout>`


Do you need any other information please ask ?? 
Because this is very annoying. Every time i changed in layout this error come up.

**Comment by tobrun** [comment]
Could you show me a screenshot where you are seeing this exception occurring?
We have similar layout in our test app and not seeing any issues with AS 2.2.3:

<img width="1082" alt="screen shot 2016-12-07 at 18 10 36" src="https://cloud.githubusercontent.com/assets/2151639/20978316/b76f3ef2-bca8-11e6-8a5a-b8f61a551b54.png">

**Comment by arpit999bicubic** [comment]
Today when I open my project  the issue are surprisingly gone. May be its an issue of AndroidStudio. Anyways.! Thanks for prompt response.
