### ISSUE TITLE
Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by DmitryTankovich** [mapbox/mapbox-gl-native#7452]
```
com.mapbox.mapboxsdk.net.ConnectivityReceiver@2e41666 that was originally registered here. Are you missing a call to unregisterReceiver()?
    at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
    at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
    at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:35)
    at com.mapbox.mapboxsdk.MapboxAccountManager.start(MapboxAccountManager.java:53)
```

Nexus 5
Android 6.0.1
com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.5@aar'

Press home -> open from recent

**Comment by cammace** [comment]
Place the accountManager inside your application object similar to what we are doing inside our [testapp](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapboxApplication.java#L39). Once this is done, remove any account manager calls you might have inside activities. Let me know if this resolves the issue.

**Comment by tobrun** [comment]
the underlying issue seem to starting up MapboxAccountManager with an non application context, this is something that should be enforced by the ConnectivityChangeListener, picking this up as part of a refactor.
