### ISSUE TITLE
NullPointerException if TrackingSettings.setMyBearingTrackingMode(MyBearingTracking.GPS)

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#7502]
**Platform:** Android
**Mapbox SDK version:** 4.2.0

### Steps to trigger behavior

 1. switch off geolocation on device
 2. `TrackingSettings trackingSettings = mapboxMap.getTrackingSettings();
      trackingSettings.setMyBearingTrackingMode(MyBearingTracking.GPS);`
 3. crash log:
`java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.getBearing()' on a null object reference
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setBearing(Unknown Source)
	at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setCameraPosition(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapView.invalidateCameraPosition(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapboxMap.invalidateCameraPosition(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapboxMap.access$500(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapboxMap$MapChangeCameraPositionListener.onMapChanged(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapView.onMapChanged(Unknown Source)
	at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(Unknown Source)
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeJumpTo(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.jumpTo(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapView.jumpTo(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapboxMap$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
	at dalvik.system.NativeStart.main(Native Method)`

not reproduced on 4.2.0-beta4

**Comment by tobrun** [comment]
@klblk thank you for the report, I patched this up in https://github.com/mapbox/mapbox-gl-native/pull/7505 for master and also ported this to `release-android-v4.2.1`in https://github.com/mapbox/mapbox-gl-native/commit/1730f0ddc3d2dba2a6e09520869383d35c85a509 for a possible bugfix release.
