### ISSUE TITLE
java.lang.Error: eglCreateWindowSurface() failed

### ISSUE THREAD

**Issue by AlexMoore81** [mapbox/mapbox-gl-native#7518]
```
java.lang.Error: eglCreateWindowSurface() failed
                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
                      at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:126)
                      at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:1432)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Android 6.0.1 (Motorola G4), Android 7.1.1 (Google emulator)
Mapbox SDK version: 4.2.0-beta.3

tried to reproduce sample activity https://www.mapbox.com/android-sdk/examples/
(A simple map view)
Application crashed.

also tried to add (android:layerType="software" to root layout, didn't help)

**Comment by tobrun** [comment]
The fix for this landed in 4.2.0-beta.4 and is available in the latest 4.2.1 release. Closing.

**Comment by AlexMoore81** [comment]
Confirm, fixed

**Comment by whitecloud-sas** [comment]
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.2@aar') {
        transitive = true
    }

E/UncaughtException: java.lang.Error: eglCreateWindowSurface() failed
                                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
                                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:131)
                                                                                         at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:1521)
                                                                                         at android.view.SurfaceView.updateWindow(SurfaceView.java:676)
                                                                                         at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:203)
                                                                                         at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
                                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
                                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
                                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                                         at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                                                         at android.os.Handler.handleCallback(Handler.java:815)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                         at android.os.Looper.loop(Looper.java:207)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5774)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by nscherer** [comment]
I'm still getting this with 5.1.0 when trying to use a MapView.  A MapFragment works.  I am making all the required lifecycle calls.  This is using a Fragment, not an Activity; I think it works from an Activity.

**Comment by JackenLiu** [comment]
@AlexMoore81 Hey have you fixed this problem yet? I get the same problem , that's kill me
