### ISSUE TITLE
Randomly occurs : FATAL EXCEPTION: main Process: java.lang.Error: eglSwapBuffers() failed

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#7590]
**Platform: Android **
**Mapbox SDK version: 4.2.1**

### Steps to trigger behavior

 1. Random (Mostly on Resume)
Map crashes with following error and it's random no specific steps found to reproduce it yet 

I am trying to find reproducible steps if found I will get back here again 

### Actual behavior

```
com.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.app, PID: 30125
                                                          java.lang.Error: eglSwapBuffers() failed
                                                              at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                              at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:143)
                                                              at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:1491)
                                                              at android.view.View.draw(View.java:17476)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.draw(View.java:17479)
                                                              at android.support.v4.view.ViewPager.draw(ViewPager.java:2341)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                              at android.view.View.draw(View.java:17245)
                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                              at android.view.View.draw(View.java:17479)
                                                              at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3190)
                                                              at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                              at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                              at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                              at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                              at android.view.ViewRootImpl.draw(ViewRootImpl.java:3184)
                                                              at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2983)
                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2572)
                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                              at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at android.os.Looper.loop(Looper.java:158)
                                                              at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                          	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1

```

**Comment by tobrun** [comment]
Thank you for reporting, we have seen this issue on our CI tests and are tracking it in #6647. 
We are looking into resolving this with migrating to GlSurfaceView in #5766. Closing as a duplicate.

**Comment by sidd5sci** [comment]
00:57:14.566 4769-4769/comtempsmashpro.httptakenkart.smashpro E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: comtempsmashpro.httptakenkart.smashpro, PID: 4769
                                                                                      java.lang.OutOfMemoryError
                                                                                          at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                                          at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:587)
                                                                                          at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:422)
                                                                                          at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:445)
                                                                                          at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:475)
                                                                                          at comtempsmashpro.httptakenkart.smashpro.GameSurface.surfaceCreated(GameSurface.java:152)
                                                                                          at android.view.SurfaceView.updateWindow(SurfaceView.java:572)
                                                                                          at android.view.SurfaceView.access$000(SurfaceView.java:86)
                                                                                          at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:175)
                                                                                          at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1871)
                                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
                                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                          at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                          at dalvik.system.NativeStart.main(Native Method)
03-18 00:57:21.206 4769-4769/? I/Process: Sending signal. PID: 4769 SIG: 9


please help me in this ,i am making a game as i load more bitmaps this error comes
