### ISSUE TITLE
StrictModeDiskReadViolation: blocking UiThread several seconds

### ISSUE THREAD

**Issue by grote** [mapbox/mapbox-gl-native#7896]
**Platform:** Android 5
**Mapbox SDK version:** 4.2.1

I noticed that my Android activity needs a long time to load the view that contains a `com.mapbox.mapboxsdk.maps.MapView` which is inflated from a layout XML resource , so I enabled strict mode like this:
```java
StrictMode.ThreadPolicy.Builder threadPolicy = new StrictMode.ThreadPolicy.Builder();
threadPolicy.detectAll();
threadPolicy.penaltyLog();
StrictMode.setThreadPolicy(threadPolicy.build());
StrictMode.VmPolicy.Builder vmPolicy = new StrictMode.VmPolicy.Builder();
vmPolicy.detectAll();
vmPolicy.penaltyLog();
StrictMode.setVmPolicy(vmPolicy.build());
```
This sheds light on the situation. It seems like you are doing lots of work on Android's `UiThread` and effectively blocking it for a couple of seconds as these excerpts from logcat show:
```
D/StrictMode: StrictMode policy violation; ~duration=1721 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1152)
                  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
                  at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:165)
                  at dalvik.system.DexPathList.findLibrary(DexPathList.java:383)
                  at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
                  at java.lang.Runtime.loadLibrary(Runtime.java:360)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.maps.NativeMapView.<clinit>(NativeMapView.java:60)
                  at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:217)
                  at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:175)
                  at java.lang.reflect.Constructor.newInstance(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)

D/StrictMode: StrictMode policy violation; ~duration=1581 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1152)
                  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
                  at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:165)
                  at dalvik.system.DexPathList.findLibrary(DexPathList.java:383)
                  at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
                  at java.lang.Runtime.loadLibrary(Runtime.java:360)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:9)
                  at java.lang.Runtime.nativeLoad(Native Method)
                  at java.lang.Runtime.doLoad(Runtime.java:428)
                  at java.lang.Runtime.loadLibrary(Runtime.java:369)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.maps.NativeMapView.<clinit>(NativeMapView.java:60)
                  at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:217)
                  at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:175)
                  at java.lang.reflect.Constructor.newInstance(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)

D/StrictMode: StrictMode policy violation; ~duration=1571 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1152)
                  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
                  at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:165)
                  at dalvik.system.DexPathList.findLibrary(DexPathList.java:383)
                  at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
                  at java.lang.Runtime.loadLibrary(Runtime.java:360)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.offline.OfflineManager.<clinit>(OfflineManager.java:30)
                  at java.lang.Runtime.nativeLoad(Native Method)
                  at java.lang.Runtime.doLoad(Runtime.java:428)
                  at java.lang.Runtime.loadLibrary(Runtime.java:369)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.maps.NativeMapView.<clinit>(NativeMapView.java:60)
                  at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:217)
                  at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:175)
                  at java.lang.reflect.Constructor.newInstance(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)

D/StrictMode: StrictMode policy violation; ~duration=1566 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1152)
                  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
                  at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:165)
                  at dalvik.system.DexPathList.findLibrary(DexPathList.java:383)
                  at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
                  at java.lang.Runtime.loadLibrary(Runtime.java:360)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.offline.OfflineRegion.<clinit>(OfflineRegion.java:26)
                  at java.lang.Runtime.nativeLoad(Native Method)
                  at java.lang.Runtime.doLoad(Runtime.java:428)
                  at java.lang.Runtime.loadLibrary(Runtime.java:369)
                  at java.lang.System.loadLibrary(System.java:988)
                  at com.mapbox.mapboxsdk.maps.NativeMapView.<clinit>(NativeMapView.java:60)
                  at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:217)
                  at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:175)
                  at java.lang.reflect.Constructor.newInstance(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
```
All the above are caused by simply setting a content view in the `Activity#onCreate()` like so:
```java
setContentView(R.layout.activity_map);
```
This layout file includes this:
```xml
<com.mapbox.mapboxsdk.maps.MapView
	android:id="@+id/map"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	app:access_token="[my access token]"
	app:compass_enabled="true"
	app:compass_margin_top="72dp"
	app:debug_active="false"
	app:logo_enabled="false"
	app:my_location_enabled="false"
	app:rotate_enabled="true"
	app:style_url="@string/style_mapbox_streets"
	app:tilt_enabled="false"
	app:zoom_controls_enabled="false"
	app:zoom_enabled="true"/>
```
Is maybe setting the style and the token here that causes the library to load things on the UIThread it shouldn't load during view inflation?

Anyway, there are two more StrictModeDiskReadViolations:
```
D/StrictMode: StrictMode policy violation; ~duration=1554 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1152)
                  at libcore.io.BlockGuardOs.access(BlockGuardOs.java:67)
                  at java.io.File.doAccess(File.java:283)
                  at java.io.File.exists(File.java:363)
                  at android.app.ContextImpl.createFilesDirLocked(ContextImpl.java:1108)
                  at android.app.ContextImpl.getFilesDir(ContextImpl.java:1131)
                  at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:202)
                  at com.mapbox.mapboxsdk.offline.OfflineManager.getDatabasePath(OfflineManager.java:139)
                  at com.mapbox.mapboxsdk.maps.NativeMapView.<init>(NativeMapView.java:69)
                  at com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:217)
                  at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:175)
                  at java.lang.reflect.Constructor.newInstance(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                  at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)

D/StrictMode: StrictMode policy violation; ~duration=297 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1152)
                  at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:202)
                  at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:259)
                  at com.mapbox.mapboxsdk.telemetry.MapboxEventManager.initialize(MapboxEventManager.java:146)
                  at com.mapbox.mapboxsdk.MapboxAccountManager.start(MapboxAccountManager.java:50)
                  at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:389)
```
I am not even using the OfflineManager, yet. 

### Steps to trigger behavior

 1. enable strict mode
 2. start activity that inflates a MapView as shown above
 3. observe strictmode violations in logcat

### Expected behavior

No strict mode violations occur. Disk reads are offloaded to other threads and do not block the UiThread. Maybe show a progress bar or something until the map is loaded.

There's a `MapView#getMapAsync()` method that I am using and that I would expect to do this work.

### Actual behavior

Several strict mode violations occur blocking the UiThread for several seconds.

**Comment by tobrun** [comment]
The first code block is something we can't handle differently at this time. Those lines are pointing to loading native libraries. See this similar issue on [Realm](https://github.com/realm/realm-java/issues/3976). The other entries found on current master are related to starting up telemetry, this is now ticketed upstream in https://github.com/mapbox/mapbox-java/issues/298.

The best way to quickly show a MapView without additional lag is by starting up MapboxAccountManager.java (v4.2.x) or Mapbox.java (v5.x) from the application object. This will initialize those components once and not during layout inflation.

Closing as follow up tickets have been created and other logs are non actionable.

**Comment by grote** [comment]
Thanks for the response and for creating a follow up ticket @tobrun!

> The best way to quickly show a MapView without additional lag is by starting up MapboxAccountManager.java (v4.2.x) or Mapbox.java (v5.x) from the application object. This will initialize those components once and not during layout inflation.

Can I do this on a non-UI thread as well? My map was meant to be shown in the first activity launched after starting the app. Is the initialization of the `MapboxAccountManager` thread-safe? Any side-effects to be expected when it is initialized on one thread and then soon initialized again from another?

**Comment by grote** [comment]
I've had a look at the Realm ticket you linked and I don't see a reason why you couldn't load the library on another thread (maybe from `NativeMapView` or earlier) and notify the `MapView` when that is ready and draw it only at that time (before showing a progress bar), liberating the UI Thread, so it can already showing other UI elements and providing a smoother user experience.

**Comment by tobrun** [comment]
> Can I do this on a non-UI thread as well? My map was meant to be shown in the first activity launched after starting the app. Is the initialization of the MapboxAccountManager thread-safe? Any side-effects to be expected when it is initialized on one thread and then soon initialized again from another?

A user reached out about this in #7660 and indicated this isn't possible atm, we are taking this in consideration with the move from `MapboxAccountManager.java` to `Mapbox.java` for 5.0.0. 

> I've had a look at the Realm ticket you linked and I don't see a reason why you couldn't load the library on another thread (maybe from NativeMapView or earlier) and notify the MapView when that is ready and draw it only at that time (and before just show a progress bar), liberating the UI Thread, so it can already show other UI elements and providing a smoother user experience.

As mentioned in that ticket: this is technically possible but this would result in the NativeMapView living on that thread thus would require additional synchronization for communication to that object. We are looking at doing something like this in #5766.
