### ISSUE TITLE
Crash when disabling telemetry - Android 5.0.0-beta.1

### ISSUE THREAD

**Issue by dbrant** [mapbox/mapbox-gl-native#8101]
I'm initializing Mapbox like so:

```
Mapbox.getInstance(getApplicationContext(), getString(R.string.mapbox_public_token));
MapboxTelemetry.getInstance().setTelemetryEnabled(false);
```
...and almost immediately after the above call (before I initialize my MapView), it crashes with the following exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapzen.android.lost.api.PendingResult com.mapzen.android.lost.internal.FusedLocationProviderService.removeLocationUpdates(com.mapzen.android.lost.api.LostApiClient, com.mapzen.android.lost.api.LocationListener)' on a null object reference
                                                                       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.removeLocationUpdates(FusedLocationProviderApiImpl.java:145)
                                                                       at com.mapbox.mapboxsdk.location.LocationSource.removeLocationUpdates(LocationSource.java:127)
                                                                       at com.mapbox.services.android.telemetry.MapboxTelemetry.shutdownTelemetry(MapboxTelemetry.java:568)
                                                                       at com.mapbox.services.android.telemetry.MapboxTelemetry.onResponse(MapboxTelemetry.java:558)
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)
```

If I don't disable telemetry, it works correctly.

**Platform:** Android API 25
**Mapbox SDK version:** 5.0.0-beta.1

**Comment by Emeritus-DarranKelinske** [comment]
Are you able to get the app to load when telemetry is working?

**Comment by dbrant** [comment]
Yep, when telemetry is enabled, the MapView works correctly.
