### ISSUE TITLE
Android Wear support 5.0.0

### ISSUE THREAD

**Issue by cjkiller** [mapbox/mapbox-gl-native#8150]
Hi, I'm trying to create an Android Wear map app. Using mapbox 5.0.0 All working fine on Nixon Mission, Moto 360 but is crashing out on the Sony smartwatch 3. Renders fine with 4.2.2. I've noticed the Sony smartwatch 3 has a lot less opengl es extensions than the others, maybe thats important.

**Platform:** Android (wear)
**Mapbox SDK version:** 5.0.0 beta and snapshot

### Steps to trigger behavior

 1. Show a map

### Expected behavior
Map renders
### Actual behavior
Crashes out with 
E/mbgl: {.trackwear.maps}[Shader]: Program failed to link: ERROR:LINK-4 (line -1) Too many attribute values
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: io.trackwear.maps, PID: 3416
                                                 java.lang.Error: program failed to link
                                                     at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                     at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:175)
                                                     at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:444)
                                                     at android.view.View.draw(View.java:16184)

**Comment by marksev1** [comment]
+1, please fix this, there are a lot of SW3 users that would like to use your mapping solution in the Wear apps.

**Comment by marksev1** [comment]
Should this issue be fixed in the beta2 already?

**Comment by niedzielski** [comment]
One of our users is reporting a similar issue on his phone, a Samsung GT-S7582 with CyanogenMod 4.4.4 (API 19). This is on Mapbox v5.0.0-beta.2:

```
03-07 22:33:06.582 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglCreateContext() config: 13 context: 0x52a21c98, VC context 3, Thread 11630
03-07 22:33:06.642 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(NULL) Thread: 11630
03-07 22:33:06.642 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglDestroySurface() surface: 0x40063f00, android window 0x506a22a0, Thread: 11630
03-07 22:33:06.652 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: Set SWAP INTERVAL 0
03-07 22:33:06.652 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglCreateWindowSurface() surface: 0x506faf10, VC surface: 3, Thread: 11630
03-07 22:33:06.652 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(0x40063e68, 0x506faf10, 0x506faf10) Thread: 11630
03-07 22:33:06.672 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: Set SWAP INTERVAL 0
03-07 22:33:06.682 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglCreateWindowSurface() surface: 0x541c2f88, VC surface: 4, Thread: 11630
03-07 22:33:06.682 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(0x52a21c98, 0x541c2f88, 0x541c2f88) Thread: 11630
03-07 22:33:06.682 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(0x52a21c98, 0x541c2f88, 0x541c2f88) Thread: 11630
03-07 22:33:06.682 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(0x40063e68, 0x506faf10, 0x506faf10) Thread: 11630
03-07 22:33:07.012 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(0x52a21c98, 0x541c2f88, 0x541c2f88) Thread: 11630
03-07 22:33:07.032 11630-11630/org.wikipedia.alpha E/mbgl: {wikipedia.alpha}[Shader]: Program failed to link: ERROR:LINK-4 (line -1) Too many attribute values
03-07 22:33:07.032 11630-11630/org.wikipedia.alpha D/HAWAII_EGL: eglMakeCurrent(0x40063e68, 0x506faf10, 0x506faf10) Thread: 11630
03-07 22:33:07.032 11630-11630/org.wikipedia.alpha D/AndroidRuntime: Shutting down VM
03-07 22:33:07.032 11630-11630/org.wikipedia.alpha W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41c89ce0)
03-07 22:33:07.042 11630-11630/org.wikipedia.alpha E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.wikipedia.alpha, PID: 11630
                                                                     java.lang.Error: program failed to link
                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:174)
                                                                         at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:420)
                                                                         at android.view.View.draw(View.java:14489)
                                                                         at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                                         at android.view.View.getDisplayList(View.java:13386)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.View.draw(View.java:14206)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                         at android.view.View.getDisplayList(View.java:13381)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                         at android.view.View.getDisplayList(View.java:13324)
                                                                         at android.view.View.getDisplayList(View.java:13428)
                                                                         at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1577)
                                                                         at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1451)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2380)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2252)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

**Comment by cjkiller** [comment]
Fixed in a native update. https://github.com/mapbox/mapbox-gl-native/pull/8267/commits/03f770c2381c9b619987f7f8231631b1339da43b  All working now on sw3.

**Comment by marksev1** [comment]
wooohoooo!!!!
