### ISSUE TITLE
Crash "java.lang.Error: vector" on map scroll

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8202]
**Platform:** Android
**Mapbox SDK version:** 5.0.0-SNAPSHOT (and beta.1)

### Crash log

>java.lang.Error: vector
                                                                        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(Native Method)
                                                                        at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:639)
                                                                        at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(AnnotationManager.java:398)
                                                                        at com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(MapboxMap.java:978)
                                                                        at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:463)
                                                                        at com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(MarkerViewManager.java:449)
                                                                        at com.mapbox.mapboxsdk.maps.AnnotationManager.update(AnnotationManager.java:69)
                                                                        at com.mapbox.mapboxsdk.maps.MapboxMap.onUpdate(MapboxMap.java:162)
                                                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1019)
                                                                        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:936)
                                                                        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeMoveBy(Native Method)
                                                                        at com.mapbox.mapboxsdk.maps.NativeMapView.moveBy(NativeMapView.java:333)
                                                                        at com.mapbox.mapboxsdk.maps.Transform.moveBy(Transform.java:279)
                                                                        at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onScroll(MapGestureDetector.java:384)
                                                                        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:579)
                                                                        at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:479)
                                                                        at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:542)
                                                                        at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:188)
                                                                        at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:310)
                                                                        at android.view.View.dispatchTouchEvent(View.java:8471)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                        at android.view.View.dispatchPointerEvent(View.java:8666)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                    	at android.view.

>E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: my.app, PID: 31272
                                                                  java.lang.Error: vector
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(Native Method)
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:639)
                                                                      at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(AnnotationManager.java:398)
                                                                      at com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(MapboxMap.java:978)
                                                                      at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:463)
                                                                      at com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(MarkerViewManager.java:449)
                                                                      at com.mapbox.mapboxsdk.maps.AnnotationManager.update(AnnotationManager.java:69)
                                                                      at com.mapbox.mapboxsdk.maps.MapboxMap.onUpdate(MapboxMap.java:162)
                                                                      at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1019)
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:936)
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeMoveBy(Native Method)
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.moveBy(NativeMapView.java:333)
                                                                      at com.mapbox.mapboxsdk.maps.Transform.moveBy(Transform.java:279)
                                                                      at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onScroll(MapGestureDetector.java:384)
                                                                      at android.view.GestureDetector.onTouchEvent(GestureDetector.java:579)
                                                                      at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:479)
                                                                      at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:542)
                                                                      at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:188)
                                                                      at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:310)
                                                                      at android.view.View.dispatchTouchEvent(View.java:8471)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                      at android.view.View.dispatchPointerEvent(View.java:8666)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                  	at android.view.ViewRootImpl$ViewPostImeInpu

**Comment by tobrun** [comment]
@klblk do you have a use-case to reproduce this issue? 
not able to reproduce this with the testapp atm.

**Comment by klblk** [comment]
I use a lot of animated custom MarkerViews (with custom MarkerViewAdapter). 
Reproduced randomly when scrolls.
Not reproduced with mapbox sdk 4.2.2. 
Device - Nexus 4 (Android 5.1.1 - native)
Video: https://drive.google.com/open?id=0B1bUt15ODm_haGtwSHA2eFRPQlk

More log:
`Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.Error: allocator<T>::allocate(size_t n) 'n' exceeds maximum supported size
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeQueryPointAnnotations(Native Method)
                                                                      at com.mapbox.mapboxsdk.maps.NativeMapView.queryPointAnnotations(NativeMapView.java:641)
                                                                      at com.mapbox.mapboxsdk.maps.AnnotationManager.getMarkerViewsInRect(AnnotationManager.java:398)
                                                                      at com.mapbox.mapboxsdk.maps.MapboxMap.getMarkerViewsInRect(MapboxMap.java:984)
                                                                      at com.mapbox.mapboxsdk.annotations.MarkerViewManager.invalidateViewMarkersInVisibleRegion(MarkerViewManager.java:463)
                                                                      at com.mapbox.mapboxsdk.annotations.MarkerViewManager.update(MarkerViewManager.java:449)
                                                                      at com.mapbox.mapboxsdk.maps.AnnotationManager.update(AnnotationManager.java:69)`

**Comment by tobrun** [comment]
@klblk thank you for adding that information, will try reproducing this. FWIW I would highly advice you to into using a SymbolLayer instead of MarkerViews for this scenario. This will not only increase stability but will also improve the UX as a SymbolLayer doesn't have the MarkerView jiggling issue.

**Comment by tobrun** [comment]
`allocator<T>::allocate(size_t n) 'n' exceeds maximum supported` indicates that there are too many ViewMarkers on the map, though I'm not seeing that many in the video. On top of that I'm able to show up to 10000 ViewMarkers without running into this error.

Do you have more information on the device used for testing?

**Comment by klblk** [comment]
Reproduced on test app: 
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedMarkerActivity.java

Change "i < 10" to "i < 55" (or more). Not 100%  reproduced, but crash log one. 

```
Device Nexus 4: 
BOARD: MAKO
BRAND: google
CODENAME: REL
CPU_ABI: armeabi-v7a
CPU_ABI2: armeabi
DEVICE: mako
DISPLAY: LMY48T
HARDWARE: mako
MANUFACTURER: LGE
MODEL: Nexus 4
PRODUCT: occam
RELEASE: 5.1.1
SDK_INT: 22  
OpenGL renderer: Adreno (TM) 320
OpenGL version: OpenGL ES 3.0 V@104.0 AU@  (GIT@Id3510ff6dc)
```

**Comment by klblk** [comment]
Yes, I rebuild app for SymbolLayer (but there are other problems). This old logic for mapbox sdk 4.

**Comment by tobrun** [comment]
I was able to reproduce this crash by calling queryPointAnnotations constantly. After a ~1000 executions I'm seeing the same crash. I'm not always seeing this crash sometimes I'm also hitting #8275 or seeing the following symbolicated stacktrace:

```
********** Crash dump: **********
Build fingerprint: 'google/angler/angler:7.1.2/NPG05F/3729850:user/release-keys'
pid: 25377, tid: 25377, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x1000d
Stack frame #00 pc 0015d0bc  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::__get_long_size() const at /Users/Nurbot/mapbox-gl-native/mason_packages/osx-x86_64/android-ndk/arm-v7-9-r13b/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/string:1797
Stack frame #01 pc 0015d015  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine AnnotationTileFeature at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../src/mbgl/annotation/annotation_tile.hpp:27
Stack frame #02 pc 0016a461  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::FeatureIndex::addFeature(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > > > > >&, mbgl::IndexedSubfeature const&, mbgl::GeometryCoordinates const&, std::experimental::fundamentals_v1::optional<std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > > const&, mbgl::GeometryTileData const&, mbgl::CanonicalTileID const&, mbgl::style::Style const&, float, float) const at /Users/Nurbot/mapbox-gl-native/src/mbgl/geometry/feature_index.cpp:113 (discriminator 1)
Stack frame #03 pc 0016a363  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::FeatureIndex::query(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > > > > >&, mbgl::GeometryCoordinates const&, float, double, double, std::experimental::fundamentals_v1::optional<std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > > const&, mbgl::GeometryTileData const&, mbgl::CanonicalTileID const&, mbgl::style::Style const&, mbgl::CollisionTile const*) const at /Users/Nurbot/mapbox-gl-native/src/mbgl/geometry/feature_index.cpp:90
Stack frame #04 pc 001d2075  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTile::queryRenderedFeatures(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > > > > >&, mbgl::GeometryCoordinates const&, mbgl::TransformState const&, std::experimental::fundamentals_v1::optional<std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > > const&) at /Users/Nurbot/mapbox-gl-native/src/mbgl/tile/geometry_tile.cpp:148
Stack frame #05 pc 000b8e73  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::style::Source::Impl::queryRenderedFeatures(mbgl::style::QueryParameters const&) const at /Users/Nurbot/mapbox-gl-native/src/mbgl/style/source_impl.cpp:246
Stack frame #06 pc 000bd071  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::style::Style::queryRenderedFeatures(mbgl::style::QueryParameters const&) const at /Users/Nurbot/mapbox-gl-native/src/mbgl/style/style.cpp:523
Stack frame #07 pc 0009d5a9  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::Map::queryRenderedFeatures(mapbox::geometry::box<double> const&, std::experimental::fundamentals_v1::optional<std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > > const&) at /Users/Nurbot/mapbox-gl-native/src/mbgl/map/map.cpp:826 (discriminator 1)
Stack frame #08 pc 0009d6d3  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::Map::queryPointAnnotations(mapbox::geometry::box<double> const&) at /Users/Nurbot/mapbox-gl-native/src/mbgl/map/map.cpp:840 (discriminator 3)
Stack frame #09 pc 00073283  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::android::NativeMapView::queryPointAnnotations(_JNIEnv&, jni::Object<mbgl::android::RectF>) at /Users/Nurbot/mapbox-gl-native/platform/android/src/native_map_view.cpp:704 (discriminator 2)
Stack frame #10 pc 00088193  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *, jni::jobject *> at /Users/Nurbot/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #11 pc 00525705  /data/app/com.mapbox.mapboxsdk.testapp-2/oat/arm/base.odex (offset 0x4fc000)
```

**Comment by Guardiola31337** [comment]
I was able to reproduce the crash, just increasing marker views up to 100, like mentioned [here](https://github.com/mapbox/mapbox-gl-native/issues/8202#issuecomment-283853114).

Crash dump.

```
********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 24651, tid: 24651, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Stack frame #00 pc 00312dd8  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine AnnotationTileFeature at /Users/pguardiola/mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../src/mbgl/annotation/annotation_tile.hpp:27 (discriminator 7)
Stack frame #01 pc 00312bbf  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__unique_if<mbgl::AnnotationTileFeature>::__unique_single std::__ndk1::make_unique<mbgl::AnnotationTileFeature, mbgl::AnnotationTileFeature const&>(mbgl::AnnotationTileFeature const&) at /Users/pguardiola/mapbox/mapbox-gl-native/mason_packages/osx-x86_64/android-ndk/arm-v7-9-r13b/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/memory:3149
Stack frame #02 pc 00335195  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::FeatureIndex::addFeature(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > > > > >&, mbgl::IndexedSubfeature const&, mbgl::GeometryCoordinates const&, mbgl::QueryOptions const&, mbgl::GeometryTileData const&, mbgl::CanonicalTileID const&, mbgl::style::Style const&, float, float) const at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/geometry/feature_index.cpp:116
Stack frame #03 pc 00334eef  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::FeatureIndex::query(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > > > > >&, mbgl::GeometryCoordinates const&, float, double, double, mbgl::QueryOptions const&, mbgl::GeometryTileData const&, mbgl::CanonicalTileID const&, mbgl::style::Style const&, mbgl::CollisionTile const*) const at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/geometry/feature_index.cpp:93
Stack frame #04 pc 00439e47  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTile::queryRenderedFeatures(std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::vector<mapbox::geometry::feature<double>, std::__ndk1::allocator<mapbox::geometry::feature<double> > > > > >&, mbgl::GeometryCoordinates const&, mbgl::TransformState const&, mbgl::QueryOptions const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile.cpp:149
Stack frame #05 pc 001735dd  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::style::Source::Impl::queryRenderedFeatures(mapbox::geometry::line_string<double, std::__ndk1::vector> const&, mbgl::TransformState const&, mbgl::QueryOptions const&) const at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/style/source_impl.cpp:248
Stack frame #06 pc 00181299  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::style::Style::queryRenderedFeatures(mapbox::geometry::line_string<double, std::__ndk1::vector> const&, mbgl::TransformState const&, mbgl::QueryOptions const&) const at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/style/style.cpp:525
Stack frame #07 pc 0012e6fb  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::Map::queryRenderedFeatures(mapbox::geometry::box<double> const&, mbgl::QueryOptions const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/map/map.cpp:825 (discriminator 1)
Stack frame #08 pc 0012ea85  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::Map::queryPointAnnotations(mapbox::geometry::box<double> const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/map/map.cpp:841
Stack frame #09 pc 000bd2cb  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine mbgl::android::NativeMapView::queryPointAnnotations(_JNIEnv&, jni::Object<mbgl::android::RectF>) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/native_map_view.cpp:714 (discriminator 1)
Stack frame #10 pc 000f8ffd  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245 (discriminator 325)
Stack frame #11 pc 000f8f63  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112 (discriminator 187)
Stack frame #12 pc 000f8f03  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #13 pc 000f90a5  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *, jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #14 pc 000f905b  /data/app/com.mapbox.mapboxsdk.testapp-2/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *, jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #15 pc 00171e2f  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-2@base.apk@classes.dex
```

cc/ @ivovandongen

**Comment by jfirebaugh** [comment]
Same as #8289, let's track there.
