### ISSUE TITLE
Error GL_INVALID_VALUE at attribute.cpp:12

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8241]
When running tests on Firebase test lab, I'm hitting a crash on a Galaxy Tab 3, API Level 19.

```
 FATAL EXCEPTION: main
 Process: com.mapbox.mapboxsdk.testapp, PID: 15361
 java.lang.Error: glBindAttribLocation(id, location, name): Error GL_INVALID_VALUE at /Users/Nurbot/mapbox-gl-native/src/mbgl/gl/attribute.cpp:12
 	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
 	at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:174)
 	at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:420)
 	at android.view.View.draw(View.java:15400)
 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
 	at android.view.View.getDisplayList(View.java:14294)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.View.draw(View.java:15114)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
 	at android.view.View.getDisplayList(View.java:14289)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.View.draw(View.java:15114)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
 	at android.view.View.draw(View.java:15403)
 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
 	at android.view.View.getDisplayList(View.java:14294)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.View.draw(View.java:15114)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
 	at android.view.View.draw(View.java:15403)
 	at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:444)
 	at android.view.View.getDisplayList(View.java:14294)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.View.draw(View.java:15114)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
 	at android.view.View.getDisplayList(View.java:14289)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.View.draw(View.java:15114)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
 	at android.view.View.getDisplayList(View.java:14289)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.View.draw(View.java:15114)
 	at android.view.ViewGroup.drawChild(ViewGroup.java:3319)
 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
 	at android.view.View.draw(View.java:15403)
 	at android.widget.FrameLayout.draw(FrameLayout.java:472)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2583)
 	at android.view.View.getDisplayList(View.java:14294)
 	at android.view.View.getDisplayList(View.java:14336)
 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1585)
 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1457)
 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2779)
 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2645)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2213)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
 	at android.view.Choreographer.doFrame(Choreographer.java:583)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
 	at android.os.Handler.handleCallback(Handler.java:733)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:146)
 	at android.app.ActivityThread.main(ActivityThread.java:5598)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
 	at dalvik.system.NativeStart.main(Native Method)
            
```

**Comment by jfirebaugh** [comment]
This is #8183.
