### ISSUE TITLE
Error glClear(mask): Error GL_OUT_OF_MEMORY 

### ISSUE THREAD

**Issue by ragaisis** [mapbox/mapbox-gl-native#8329]
**Platform:** Android
**Mapbox SDK version:** current mapbox master branch SHA: c880560f80d863189dd9e169392119e8ac04bc13 

Saw crash error in Fabric, while gave application to test users:

```
Fatal Exception: java.lang.Error
glClear(mask): Error GL_OUT_OF_MEMORY at /Users/jonas/Projects/mapbox-gl-native/src/mbgl/gl/context.cpp:420
com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender
```

It's related to mapbox core, so I'm registering issue and attaching the logs:

[issue_57_crash_58C15C8D03D900015D383FB6D8C5153D_91d73fea788a480489de74f35e2720f3_0_v1.txt](https://github.com/mapbox/mapbox-gl-native/files/831330/issue_57_crash_58C15C8D03D900015D383FB6D8C5153D_91d73fea788a480489de74f35e2720f3_0_v1.txt)

**Comment by zugaldia** [comment]
@ragais Thanks for the report. Could you share some more information about how this issue is happening for your users? Are you seeing this on specific devices or all? Is this a custom style?

**Comment by ragaisis** [comment]
@zugaldia 
We're using our own map server, so yes it's custom style. Basically, I can't figure it out the reason why it's crashing. The only device that crashed is Galaxy A5(2016), but we don't have public app yet, so there is small test user group. And this crash report is from Fabric and was caused by our test user. He doesn't know why it's crashing too, so no pattern to reproduce 😞 

One more thing that could be related to this issue is that maps are not rendering correctly to that specific user. On our test devices maps are looking good (tested on Galaxy S5, Lenovo Lenovo Tab3 A7-10 (budget tablet)), but on some devices (including Galaxy A5(2016)) colors are totally different (like inverted). Previously everything worked fine, map rendered correctly and we didn't received that crash, so I don't know which mapbox changes could affect that. Maybe color inversion is not related issue and I should create another one, but I'm trying to give all info I know.

There are 2 cropped screenshots with inverted colors:
![screenshot_20170309-154317 copy](https://cloud.githubusercontent.com/assets/2177892/23886684/7c35a7d0-0885-11e7-9d3a-69484f4244a4.png)
![screenshot_20170309-155421 copy](https://cloud.githubusercontent.com/assets/2177892/23886685/7c3c5530-0885-11e7-82fe-218472a8a3f2.png)

**Comment by ragaisis** [comment]
@zugaldia  looks like I was able to reproduce this crash after switching from landscape to portrait and vice versa for a several times. Adding logs from logcat:

```
03-22 08:08:50.454 1454-3016/? E/LocSvc_ApiV02: I/<--- void globalEventCb(locClientHandleType, uint32_t, locClientEventIndUnionType, void*) line 105 QMI_LOC_EVENT_GNSS_SV_INFO_IND_V02
03-22 08:08:50.534 1454-3016/? E/LocSvc_ApiV02: I/<--- void globalEventCb(locClientHandleType, uint32_t, locClientEventIndUnionType, void*) line 105 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
03-22 08:08:50.544 1454-3016/? E/LocSvc_ApiV02: I/<--- void globalEventCb(locClientHandleType, uint32_t, locClientEventIndUnionType, void*) line 105 QMI_LOC_EVENT_POSITION_REPORT_IND_V02
03-22 08:08:50.724 404-404/? E/lowmemorykiller: Error writing /proc/21405/oom_score_adj; errno=22
03-22 08:08:50.764 19665-19665/? E/Adreno-GSL: <gsl_memory_alloc_pure:1971>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
03-22 08:08:50.784 404-404/? E/lowmemorykiller: Error writing /proc/21405/oom_score_adj; errno=22
03-22 08:08:50.784 19665-19665/? E/Adreno-GSL: <gsl_memory_alloc_pure:1971>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
03-22 08:08:50.794 19665-19665/? E/Adreno-GSL: <gsl_memory_alloc_pure:1971>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
03-22 08:08:51.184 19665-19954/? E/File: fail readDirectory() errno=2
03-22 08:08:51.184 19665-19954/? E/File: fail readDirectory() errno=2
03-22 08:08:51.194 19665-19665/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mydomain.myapp.dev, PID: 19665
                                                   java.lang.Error: glTexImage2D(GL_TEXTURE_2D, 0, static_cast<GLenum>(format), size.width, size.height, 0, static_cast<GLenum>(format), GL_UNSIGNED_BYTE, data): Error GL_OUT_OF_MEMORY at /Users/jonas/Projects/mapbox-gl-native/src/mbgl/gl/context.cpp:306
                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                       at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:175)
                                                       at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:423)
                                                       at android.view.View.draw(View.java:17476)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3907)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3887)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3185)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2984)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2573)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1488)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7451)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by zugaldia** [comment]
Thanks @ragaisis , I'm seeing an `GL_OUT_OF_MEMORY` exception in the log. Are you implementing the [`onLowMemory()` callback](https://www.mapbox.com/android-sdk/#lifecycle_methods) for the map? If so, could you verify that's being invoked?

**Comment by ragaisis** [comment]
@zugaldia yes, I'm using onLowMemory callback in my parent map fragment

```
 @Override
    public void onLowMemory() {
        if (mapView != null) {
            mapView.onLowMemory();
        }
        super.onLowMemory();
    }
```

Strange, today after trying to log onLowMemory to see if it's called I couldn't catch exact error as I wrote above. App is still crashing, but failure (error message) is different. FYI, onLowMemory was not called

```
03-23 07:22:16.922 11075-11075/com.mydomain.myapp.dev E/mbgl: {skus.myapp.dev}[Style]: Failed to load tile 5/17/9=>5 for source com.mapbox.annotations: std::bad_alloc
03-23 07:22:16.962 11075-11214/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:16.962 11075-11214/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0x9ae3cee0, fd=89 (Out of memory)
03-23 07:22:16.962 11075-11214/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:16.962 11075-11214/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:16.962 11075-11214/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0x9a636ef0, fd=101 (Out of memory)
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0x9ae3d0c0, fd=103 (Out of memory)
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0x9ae3d250, fd=108 (Out of memory)
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:16.972 11075-11214/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:17.102 11075-11075/com.mydomain.myapp.dev E/ViewSystem: ViewRootImpl #2 Surface is not valid.
03-23 07:22:17.212 11075-11075/com.mydomain.myapp.dev E/mbgl: {skus.myapp.dev}[Style]: Failed to load tile 5/18/9=>5 for source general: unknown pbf field type exception
03-23 07:22:17.282 11075-11075/com.mydomain.myapp.dev E/mbgl: {skus.myapp.dev}[Style]: Failed to load tile 5/17/9=>5 for source general: unknown pbf field type exception
03-23 07:22:18.032 11075-11075/com.mydomain.myapp.dev E/MotionRecognitionManager: mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@a605ce3
03-23 07:22:18.032 11075-11075/com.mydomain.myapp.dev E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@57e9a55
03-23 07:22:18.032 11075-11075/com.mydomain.myapp.dev E/MotionRecognitionManager: motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@57e9a55
03-23 07:22:18.252 11075-11075/com.mydomain.myapp.dev E/ViewRootImpl: sendUserActionEvent() mView == null
03-23 07:22:18.252 11075-11075/com.mydomain.myapp.dev E/ViewRootImpl: sendUserActionEvent() mView == null
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0xac2b7f70, fd=74 (Out of memory)
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0xac2b7fc0, fd=80 (Out of memory)
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdmemalloc: ion: Failed to map memory in the client: Out of memory
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdgralloc: Could not mmap handle 0xac2b8010, fd=86 (Out of memory)
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/qdgralloc: gralloc_register_buffer: gralloc_map failed
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/GraphicBuffer: unflatten: registerBuffer failed: Out of memory (-12)
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -12
03-23 07:22:18.372 11075-11075/com.mydomain.myapp.dev E/mbgl: {skus.myapp.dev}[OpenGL]: eglSwapBuffers() returned error 12301
03-23 07:22:18.392 11075-11075/com.mydomain.myapp.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.mydomain.myapp.dev, PID: 11075
                                                                             java.lang.Error: eglSwapBuffers() failed
                                                                                 at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                                 at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:175)
                                                                                 at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:423)
                                                                                 at android.view.View.draw(View.java:17476)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16464)
                                                                                 at android.view.View.draw(View.java:17245)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3923)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3713)
                                                                                 at android.view.View.draw(View.java:17479)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                                                 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                                 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                                 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:3185)
                                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2984)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2573)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1488)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7451)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by zugaldia** [comment]
> but on some devices (including Galaxy A5(2016)) colors are totally different (like inverted).

@ragaisis Yesterday we released 5.0.1 https://github.com/mapbox/mapbox-gl-native/issues/8501 that fixed a shader precision issue that created a rendering problem on some devices, and it might help your case. Could you check again with this version when you have a chance and see if a) the rendering problems persist or b) the error you get is now different?

**Comment by ragaisis** [comment]
Currently I'm having problems building mapbox android SDK, but I will let you know.

**Comment by jfirebaugh** [comment]
At the risk of stating the obvious: it appears the application is running out of memory. Have you investigated why this might be?

**Comment by jfirebaugh** [comment]
Absent evidence that this is not merely a general application low memory situation, I don't think we're going to be able to invest resources in investigating this further.

**Comment by ragaisis** [comment]
FYI, this crash was easy reproduced when user was rotating application between landscape and portrait several times (at least in my application)

Solved by adding  **configChanges="orientation|screenSize"** Then map is not recreated and it save memory and will not throw outOfMemory so often.

```
 <activity
            android:name=".ui.MainActivity"
            android:configChanges="orientation|screenSize">
```
