### ISSUE TITLE
NPE when unregistering location

### ISSUE THREAD

**Issue by peterneubauer** [mapbox/mapbox-gl-native#8375]
Hi there,
users get crashed because of this. Seems this is not our code doing but Telemetry not handling things gracefully.

```03-13 19:58:12.424 E/AndroidRuntime(14476): FATAL EXCEPTION: OkHttp Dispatcher
03-13 19:58:12.424 E/AndroidRuntime(14476): Process: app.mapillary, PID: 14476
03-13 19:58:12.424 E/AndroidRuntime(14476): java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapzen.android.lost.api.PendingResult com.mapzen.android.lost.internal.FusedLocationProviderService.removeLocationUpdates(com.mapzen.android.lost.api.LostApiClient, com.mapzen.android.lost.api.LocationListener)' on a null object reference
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.removeLocationUpdates(FusedLocationProviderApiImpl.java:130)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at com.mapbox.mapboxsdk.location.LocationSource.removeLocationUpdates(LocationSource.java:127)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at com.mapbox.services.android.telemetry.MapboxTelemetry.shutdownTelemetry(MapboxTelemetry.java:568)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at com.mapbox.services.android.telemetry.MapboxTelemetry.onResponse(MapboxTelemetry.java:558)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-13 19:58:12.424 E/AndroidRuntime(14476): 	at java.lang.Thread.run(Thread.java:818)
03-13 19:58:12.514 D/SensorManager(14476): unregisterListener ::   
03-13 19:58:12.514 I/FA      (14476): Tag Manager is not found and thus will not be used
03-13 19:58:13.124 D/app.mapillary.android.activity.TabbedMainActivity(14476): onDestroy()
```

**Comment by tobrun** [comment]
@peterneubauer thank you for the report, which version of the SDK are you using?
This seems a lot like the crash that was solved with https://github.com/mapbox/mapbox-gl-native/pull/8255.

**Comment by peterneubauer** [comment]
Yeah might be, my SDK version is older than that, `5.0.0-beta.1`. When is the next beta coming out?

**Comment by tobrun** [comment]
Beta.3, that contains this fix for this has landed with #8350 last week. Would be awesome if you could retest. There shouldn't be too many differences to the API between beta.1 and beta.3.

**Comment by peterneubauer** [comment]
Have changed to it, let's see if the mapillary testers  report back!

**Comment by tobrun** [comment]
Cool, closing this issue in meantime, feel free to comment if it would still occur! Thanks again for reaching out and reporting your issue.
