### ISSUE TITLE
[android-wear] App doesn't show MyLocationView in the map

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#8506]
**Platform:** Android Wear
**Mapbox SDK version:** `5.0.0`

### Steps to trigger behavior

I run into this one [adding user location tracking in the demo wear app](https://github.com/mapbox/mapbox-android-demo/pull/255).

 1. Open `LocationTrackingActivity`
 2. Call `map.setMyLocationEnabled(true);`
 3. App doesn't show `MyLocationView` in the map because of GPS and WiFi permissions

### Expected behavior

App shows `MyLocationView` in the map

### Actual behavior

App doesn't show `MyLocationView` in the map

### Logcat

```
03-23 10:56:23.620 6869-6869/? E/g: Unable to register for GPS updates.
                                    java.lang.IllegalArgumentException: provider doesn't exist: gps
                                        at android.os.Parcel.readException(Parcel.java:1624)
                                        at android.os.Parcel.readException(Parcel.java:1573)
                                        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
                                        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
                                        at com.mapzen.android.lost.internal.g.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.g.b(Unknown Source)
                                        at com.mapzen.android.lost.internal.n.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.e.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.FusedLocationProviderService.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.d.a(Unknown Source)
                                        at com.mapbox.mapboxsdk.c.a.d(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$GpsLocationListener.onConnected(Unknown Source)
                                        at com.mapbox.mapboxsdk.c.a.f(Unknown Source)
                                        at com.mapzen.android.lost.internal.p.a(Unknown Source)
                                        at com.mapbox.mapboxsdk.c.a.a(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.TrackingSettings.setMyLocationEnabled(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(Unknown Source)
                                        at com.mapbox.mapboxandroiddemo.examples.LocationTrackingActivity$2.onMapReady(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run(Unknown Source)
                                        at android.os.Handler.handleCallback(Handler.java:739)
                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                        at android.os.Looper.loop(Looper.java:148)
                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
                                        at java.lang.reflect.Method.invoke(Native Method)
                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-23 10:56:23.623 6869-6869/? E/g: Unable to register for network updates.
                                    java.lang.IllegalArgumentException: provider doesn't exist: network
                                        at android.os.Parcel.readException(Parcel.java:1624)
                                        at android.os.Parcel.readException(Parcel.java:1573)
                                        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
                                        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:880)
                                        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:464)
                                        at com.mapzen.android.lost.internal.g.b(Unknown Source)
                                        at com.mapzen.android.lost.internal.g.b(Unknown Source)
                                        at com.mapzen.android.lost.internal.n.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.e.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.FusedLocationProviderService.a(Unknown Source)
                                        at com.mapzen.android.lost.internal.d.a(Unknown Source)
                                        at com.mapbox.mapboxsdk.c.a.d(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$GpsLocationListener.onConnected(Unknown Source)
                                        at com.mapbox.mapboxsdk.c.a.f(Unknown Source)
                                        at com.mapzen.android.lost.internal.p.a(Unknown Source)
                                        at com.mapbox.mapboxsdk.c.a.a(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.TrackingSettings.setMyLocationEnabled(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapboxMap.setMyLocationEnabled(Unknown Source)
                                        at com.mapbox.mapboxandroiddemo.examples.LocationTrackingActivity$2.onMapReady(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000(Unknown Source)
                                        at com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run(Unknown Source)
                                        at android.os.Handler.handleCallback(Handler.java:739)
                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                        at android.os.Looper.loop(Looper.java:148)
                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
                                        at java.lang.reflect.Method.invoke(Native Method)
                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

It's related with the way permissions are requested in [Lost](https://github.com/mapzen/lost). They aren't supporting wear (there are watches without GPS/WFi) and they are requiring those [`uses-feature`](https://github.com/mapzen/lost/blob/master/lost/src/main/AndroidManifest.xml#L9)s.

cc/ @zugaldia @tobrun

**Comment by zugaldia** [comment]
@Guardiola31337 If this is a limitation of LOST's API, could you open a ticket with https://github.com/mapzen/lost ? We can then close this ticket once we've confirmed the behavior has been fixed.

**Comment by Guardiola31337** [comment]
@zugaldia [follow up question](https://github.com/mapzen/lost/issues/169#issuecomment-288971298).

**Comment by tobrun** [comment]
wear module has been removed, follow up work should happen in the plugins repo.

**Comment by Guardiola31337** [comment]
Follow up ticket in `android-demo` https://github.com/mapbox/mapbox-android-demo/issues/449
