### ISSUE TITLE
UnsatisfiedLinkError: Bad file descriptor

### ISSUE THREAD

**Issue by MariusBoepple** [mapbox/mapbox-gl-native#8507]
**Platform:** Android
**Mapbox SDK version:** `4.2.2`, Mapbox Android services `1.3.1`

Thrown in `MapboxAccountManager.start(this, accessToken)`:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: unable to stat file for the library "/data/app/com.example.app-2/lib/arm64/libmapbox-gl.so": Bad file descriptor
       at java.lang.Runtime.loadLibrary0(Runtime.java:994)
       at java.lang.System.loadLibrary(System.java:1533)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:9)
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:38)
       at com.mapbox.mapboxsdk.MapboxAccountManager.start(MapboxAccountManager.java:53)
       at com.example.app.MyApplication.onCreate(MyApplication.java:170)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by jfirebaugh** [comment]
We're unable to replicate this issue. Does it still occur in v5.0.1? Can you provide any additional details that would allow us to replicate it?

**Comment by MariusBoepple** [comment]
We still have crashes with `5.0.1`.

Here's the full stacktrace of the last one: [full_stacktrace.txt](https://github.com/mapbox/mapbox-gl-native/files/904879/stacktrace.txt)

**Comment by jfirebaugh** [comment]
This is likely to be some sort of configuration or installation issue. Unfortunately, without details that would allow us to reproduce the error, it's very unlikely that we can help.

**Comment by MariusBoepple** [comment]
It's gone with `5.0.2`

**Comment by tobrun** [comment]
@MariusBoepple thank you for reporting that back to us!
