### ISSUE TITLE
Vertex shader fill failed to compile on Android KitKat

### ISSUE THREAD

**Issue by azharj-eman** [mapbox/mapbox-gl-native#8508]
**Platform: Android**
**Mapbox SDK version: 4.1.1**
Note: Have not upgraded to v5.0.0 due to marker click listener issues.

In the past 30 days, 97% of affected users have been running Android KitKat. The devices with the crash seem to be low end ones, there is an example of a few samsung devices below.

Can you help me understand what is going on here? Apologies for the lack of extra information - I cannot reproduce this myself.  

**Crashlytics gives me the following error log:**
```
Fatal Exception: java.lang.Error: Vertex shader fill failed to compile
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:128)
       at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:1327)
       at android.view.View.draw(View.java:15246)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:14140)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.getDisplayList(View.java:14135)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.View.draw(View.java:14960)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3318)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3155)
       at android.view.View.draw(View.java:15249)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2583)
       at android.view.View.getDisplayList(View.java:14140)
       at android.view.View.getDisplayList(View.java:14182)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1585)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1457)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2768)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2634)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6540)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
       at android.view.Choreographer.doCallbacks(Choreographer.java:613)
       at android.view.Choreographer.doFrame(Choreographer.java:583)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Brief explanation of how I am using Mapbox:**
When the map is created, I call 2 endpoints that return 2 arrays of objects of which then get represented by Markers on the map. A marker is created like so:

            IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
            Drawable iconDrawable = ContextCompat.getDrawable(MainActivity.this, drawableId);
            Icon icon = iconFactory.fromDrawable(iconDrawable, width, height);
            MarkerViewOptions markerViewOptions = new MarkerViewOptions()
                    .position(position)
                    .anchor(0.5f, 0.5f)
                    .icon(icon);
            mMapboxMap.addMarker(markerViewOptions);

In previous builds there was an issue with marker removal and I thought may be linked somehow. I fixed the marker removal in a recent build but this issue still remains.

Grateful for any help.

### Breakdown of Samsung devices:
![image](https://cloud.githubusercontent.com/assets/20399540/24247090/25ece12e-0fc2-11e7-8152-6892797d7766.png)

**Comment by jfirebaugh** [comment]
Even if you aren't able to update to v5.0.1 currently, can you verify whether this issue occurs in that version or not? Can you provide a device log from an affected device?
