### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#8529]
**Platform: Android**
**Mapbox SDK version: 5.0.1**

Hi MapBox Team. I'm Found A problem crash when i'm updated from 4.2.1 to 5.0.1.

Full of error tracer!

```
java.lang.IllegalArgumentException: pointerIndex out of range
                                                                      at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                      at android.view.MotionEvent.getX(MotionEvent.java:2293)
                                                                      at com.almeros.android.multitouch.gesturedetectors.TwoFingerGestureDetector.updateStateByEvent(TwoFingerGestureDetector.java:90)
                                                                      at com.almeros.android.multitouch.gesturedetectors.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:147)
                                                                      at com.almeros.android.multitouch.gesturedetectors.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:73)
                                                                      at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:138)
                                                                      at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:296)
                                                                      at com.mapbox.mapboxsdk.annotations.MarkerViewContainer.dispatchTouchEvent(MarkerViewContainer.java:28)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SlidingUpPanelLayout.java:943)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2844)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2519)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2866)
                                                                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1861)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                      at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2827)
                                                                      at android.view.View.dispatchPointerEvent(View.java:10246)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5456)
                                                                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5292)
                                                                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4731)
                                                                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4784)
                                                                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4750)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4891)
                                                                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4758)
                                                                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4948)
                                                                  	at android.view.ViewRootImpl$InputStage.delive
```

**Comment by tobrun** [comment]
@Buminta are you using an own `View.OnTouchListener` with `MapView`?

**Comment by Buminta** [comment]
@tobrun
Yep!
I using it! But it's not working With new version 5.x.x

**Comment by tobrun** [comment]
We don't consider this a part of our public supported API
though we are looking into this issue in https://github.com/mapbox/mapbox-gl-native/issues/8515.
Closing as a duplicate, thank you for reaching out!

**Comment by Larnoo** [comment]
I don't use a `View.OnTouchListener` with `MapView`.  But have the same problem.

- Android 6.0.1 
- Nexus 5
- Mapbox SDK Android 5.0.0 Beta 3

When I was zooming mapView by Gesture, The Exception happened.

```
java.lang.IllegalArgumentException: pointerIndex out of range
                                                                    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                    at android.view.MotionEvent.getX(MotionEvent.java:2072)
                                                                    at com.almeros.android.multitouch.gesturedetectors.TwoFingerGestureDetector.updateStateByEvent(TwoFingerGestureDetector.java:90)
                                                                    at com.almeros.android.multitouch.gesturedetectors.RotateGestureDetector.handleInProgressEvent(RotateGestureDetector.java:147)
                                                                    at com.almeros.android.multitouch.gesturedetectors.BaseGestureDetector.onTouchEvent(BaseGestureDetector.java:73)
                                                                    at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:138)
                                                                    at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:291)
                                                                    at com.mapbox.mapboxsdk.annotations.MarkerViewContainer.dispatchTouchEvent(MarkerViewContainer.java:28)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                    at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                    at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                    at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.ja
```

**Comment by tobrun** [comment]
We are reverting changes to onTouch introduced in 5.x version to 4.x, a patch release is upcoming for v5.0.2
