### ISSUE TITLE
[android] Circle Layer example crashes

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#8546]
**Platform:** Android
**Mapbox SDK version:** `master` branch

### Steps to trigger behavior

 1. Open test app
 2. Navigate to Circle layer example
 3. Click on FAB
 4. Click on FAB again
 5. App crashes

### Expected behavior
App doesn't crash

### Actual behavior
App crashes

![circlelayercrash](https://cloud.githubusercontent.com/assets/1668582/24391913/de551970-1391-11e7-8743-ac5bb210816a.gif)

### Logcat

```
03-28 08:29:21.155 4084-4084/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.mapbox.mapboxsdk.testapp, PID: 4084
                                                                            com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source bus_route already exists
                                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
                                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:830)
                                                                                at com.mapbox.mapboxsdk.maps.MapboxMap.addSource(MapboxMap.java:406)
                                                                                at com.mapbox.mapboxsdk.testapp.activity.style.CircleLayerActivity$1$1.onClick(CircleLayerActivity.java:87)
                                                                                at android.view.View.performClick(View.java:5198)
                                                                                at android.view.View$PerformClick.run(View.java:21147)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by tobrun** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/pull/8274
