### ISSUE TITLE
DeadObjectException after close a second activity with MapBox

### ISSUE THREAD

**Issue by cavarzan** [mapbox/mapbox-gl-native#8697]
**Platform:** Android
**Mapbox SDK version:** 5.0.0

### Steps to trigger behavior

 1. Create a MapBox fragment in some activity.
 2. Start another activity that also contains a MapBox object
 3. Close the activity to go back to previous screen.
 4. Repeat this process 3 - 4 times

### Expected behavior
The map still loaded without any crash

### Actual behavior
After closing the second activity and going back to first activity, the app crashes due to the exception:

 ```
        ActivityManager  I  Process my.app.package (pid 6799) has died
                         W  Scheduling restart of crashed service my.app.package/com.mapbox.services.android.telemetry.service.TelemetryService in 1000ms
                         W  Scheduling restart of crashed service  my.app.package/com.mapzen.android.lost.internal.FusedLocationProviderService in 1000ms
         WindowAnimator  W  Failed to dispatch window animation state change.
                         W  android.os.DeadObjectException
                         W      at android.os.BinderProxy.transactNative(Native Method)
                         W      at android.os.BinderProxy.transact(Binder.java:503)
                         W      at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                         W      at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                         W      at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                         W      at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                         W      at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                         W      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                         W      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                         W      at android.view.Choreographer.doFrame(Choreographer.java:603)
                         W      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                         W      at android.os.Handler.handleCallback(Handler.java:739)
                         W      at android.os.Handler.dispatchMessage(Handler.java:95)
                         W      at android.os.Looper.loop(Looper.java:148)
                         W      at android.os.HandlerThread.run(HandlerThread.java:61)
                         W      at com.android.server.ServiceThread.run(ServiceThread.java:46)
                         W  Failed to dispatch window animation state change.
                         W  android.os.DeadObjectException
                         W      at android.os.BinderProxy.transactNative(Native Method)
                         W      at android.os.BinderProxy.transact(Binder.java:503)
                         W      at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                         W      at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                         W      at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                         W      at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                         W      at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                         W      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                         W      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                         W      at android.view.Choreographer.doFrame(Choreographer.java:603)
                         W      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                         W      at android.os.Handler.handleCallback(Handler.java:739)
                         W      at android.os.Handler.dispatchMessage(Handler.java:95)
                         W      at android.os.Looper.loop(Looper.java:148)
                         W      at android.os.HandlerThread.run(HandlerThread.java:61)
                         W      at com.android.server.ServiceThread.run(ServiceThread.java:46)
         SurfaceFlinger  W  couldn't log to binary event log: overflow.
```

**Comment by tobrun** [comment]
@cavarzan thank you for reaching out.  Do you have more information on the device you were using to test this? Do you some code to reproduce? I'm not able to reproduce this on a low end device which the steps mentioned in OP:

![ezgif com-video-to-gif 33](https://cloud.githubusercontent.com/assets/2151639/24998128/5e0785c8-2039-11e7-88a3-6cd3d4865556.gif)

**Comment by cavarzan** [comment]
@tobrun I think that was a lot of polygons and markers in the map.
We made some tests and remove all polygons and markers layers from `MapboxMap` in `onStop` method, recreating again when needed. Seems to fix it now.

**Comment by sfariv** [comment]
I still see this with the latest sdk version `android-v6.7.1`. 

Create an activity with a fragment that has mapbox in it, sending the activity to the background causes the exception...

**Comment by tobrun** [comment]
@sfavariv please open a new issue and provide an minimal reproducible test-case, thank you
