### ISSUE TITLE
Crash on Galaxy A3(2016) (a3xelte)

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8719]
**Platform:** Android - Galaxy A3(2016) (a3xelte)
**Mapbox SDK version:** 5.0.2

Google play console crash: 
![0df2028688c20b9c93a2e2c3ab691896](https://cloud.githubusercontent.com/assets/6357562/24939028/da84d842-1f64-11e7-8f56-139b52d295bb.png)

Log: 
```
java.lang.Error: eglSwapBuffers() failed
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.render(Unknown Source)
	at com.mapbox.mapboxsdk.maps.MapView.onDraw(Unknown Source)
	at android.view.View.draw(View.java:17524)
	at android.view.View.updateDisplayListIfDirty(View.java:16517)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
	at android.view.View.updateDisplayListIfDirty(View.java:16477)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3230)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3029)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2611)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7520)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:622)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by jfirebaugh** [comment]
Thanks for the report; we're tracking this issue in #6647.
