### ISSUE TITLE
Renderer Bug

### ISSUE THREAD

**Issue by Larnoo** [mapbox/mapbox-gl-native#8740]
**Platform:** Android6.0  HUAWEI MT7-TL00   openGL 3.0
**Mapbox SDK version:**  5.0.0

### Steps to trigger behavior

 1. map style is from asset; native lib contains arm-v7, arm-v8
 2. The normal appearance  are as follows

![sdfsdfsdfsdf](https://cloud.githubusercontent.com/assets/15139682/25003206/da49424c-2080-11e7-9473-7faf5cb4f75d.jpg)

 3. Abnormal appearance are as follows

![device-2017-04-13-192008](https://cloud.githubusercontent.com/assets/15139682/25003214/e6155336-2080-11e7-8cf8-22a6cbcf8c64.png)

```
04-13 18:56:18.971 28363-28363/com.ckditu.map I/art: Thread[1,tid=28363,Native,Thread*=0xb8929f20,peer=0x7482adf0,"main"] recursive attempt to load library "/data/app/com.ckditu.map-2/lib/arm/libmapbox-gl.so"
04-13 18:56:18.984 28363-28363/com.ckditu.map I/art: Thread[1,tid=28363,Native,Thread*=0xb8929f20,peer=0x7482adf0,"main"] recursive attempt to load library "/data/app/com.ckditu.map-2/lib/arm/libmapbox-gl.so"
04-13 18:56:18.985 28363-28363/com.ckditu.map I/art: Thread[1,tid=28363,Native,Thread*=0xb8929f20,peer=0x7482adf0,"main"] recursive attempt to load library "/data/app/com.ckditu.map-2/lib/arm/libmapbox-gl.so"

....

04-13 18:56:20.017 28363-28376/com.ckditu.map W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                        java.lang.NullPointerException: Attempt to read from field 'android.view.HardwareRenderer android.view.View$AttachInfo.mHardwareRenderer' on a null object reference
                                                            at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:542)
                                                            at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1128)
                                                            at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:560)
                                                            at android.os.Binder.execTransact(Binder.java:453)
04-13 18:56:20.334 28363-28376 W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                        java.lang.NullPointerException: Attempt to read from field 'android.view.HardwareRenderer android.view.View$AttachInfo.mHardwareRenderer' on a null object reference
                                                            at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:542)
                                                            at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1128)
                                                            at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:560)
                                                            at android.os.Binder.execTransact(Binder.java:453)
04-13 18:56:20.452 28363-28363/com.ckditu.map I/RongLog-Push[RongPushClient]: clearAllNotifications
04-13 18:56:20.455 28363-28363/com.ckditu.map I/RongLog-Push[RongPushClient]: clearAllPushNotifications
04-13 18:56:20.677 28363-28375/com.ckditu.map W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                        java.lang.NullPointerException: Attempt to read from field 'android.view.HardwareRenderer android.view.View$AttachInfo.mHardwareRenderer' on a null object reference
                                                            at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:542)
                                                            at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1128)
                                                            at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:560)
                                                            at android.os.Binder.execTransact(Binder.java:453)
04-13 18:56:20.967 28363-28575 I/OpenGLRenderer: Initialized EGL, version 1.4
04-13 18:56:25.338 28363-28375 W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                        java.lang.NullPointerException: Attempt to read from field 'android.view.HardwareRenderer android.view.View$AttachInfo.mHardwareRenderer' on a null object reference
                                                            at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:542)
                                                            at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1128)
                                                            at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:560)
                                                            at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by jfirebaugh** [comment]
This was fixed in 5.0.1, and the latest version is 5.0.2. If you upgrade, it should be fixed.
