### ISSUE TITLE
Cant' install mapbox-gl-native on FreeBSD

### ISSUE THREAD

**Issue by Munrok** [mapbox/mapbox-gl-native#8777]
I can't install mapbox/mapbox-gl-native on FreeBSD (tested on gcc and clang), logs:

```
[user@moon]:<~>$ npm install @mapbox/mapbox-gl-native

> @mapbox/mapbox-gl-native@3.4.7 preinstall /usr/home/user/node_modules/.staging/@mapbox/mapbox-gl-native-ae74db72
> npm install node-pre-gyp

@mapbox/mapbox-gl-native@3.4.7 /usr/home/user/domains/mydomain.com/public_nodejs/node_modules/.staging/@mapbox/mapbox-gl-native-ae74db72
├─┬ node-pre-gyp@0.6.34 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ nopt@4.0.1 
│ │ ├── abbrev@1.1.0 
│ │ └─┬ osenv@0.1.4 
│ │   ├── os-homedir@1.0.2 
│ │   └── os-tmpdir@1.0.2 
│ ├─┬ npmlog@4.0.2 
│ │ ├─┬ are-we-there-yet@1.1.2 
│ │ │ └── delegates@1.0.0 
│ │ ├── console-control-strings@1.1.0 
│ │ ├─┬ gauge@2.7.3 
│ │ │ ├── aproba@1.1.1 
│ │ │ ├── has-unicode@2.0.1 
│ │ │ ├── object-assign@4.1.1 
│ │ │ ├── signal-exit@3.0.2 
│ │ │ ├─┬ string-width@1.0.2 
│ │ │ │ ├── code-point-at@1.1.0 
│ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
│ │ │ │   └── number-is-nan@1.0.1 
│ │ │ ├─┬ strip-ansi@3.0.1 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ └── wide-align@1.1.0 
│ │ └── set-blocking@2.0.0 
│ ├─┬ rc@1.2.1 
│ │ ├── deep-extend@0.4.1 
│ │ ├── ini@1.3.4 
│ │ ├── minimist@1.2.0 
│ │ └── strip-json-comments@2.0.1 
│ ├─┬ rimraf@2.6.1 
│ │ └─┬ glob@7.1.1 
│ │   ├── fs.realpath@1.0.0 
│ │   ├── inflight@1.0.6 
│ │   ├─┬ minimatch@3.0.3 
│ │   │ └─┬ brace-expansion@1.1.7 
│ │   │   ├── balanced-match@0.4.2 
│ │   │   └── concat-map@0.0.1 
│ │   └── path-is-absolute@1.0.1 
│ ├── semver@5.3.0 
│ ├─┬ tar@2.2.1 
│ │ ├── block-stream@0.0.9 
│ │ ├─┬ fstream@1.0.11 
│ │ │ └── graceful-fs@4.1.11 
│ │ └── inherits@2.0.3 
│ └─┬ tar-pack@3.4.0 
│   ├─┬ debug@2.6.3 
│   │ └── ms@0.7.2 
│   ├── fstream-ignore@1.0.5 
│   ├─┬ once@1.4.0 
│   │ └── wrappy@1.0.2 
│   ├─┬ readable-stream@2.2.9 
│   │ ├── buffer-shims@1.0.0 
│   │ ├── core-util-is@1.0.2 
│   │ ├── isarray@1.0.0 
│   │ ├── process-nextick-args@1.0.7 
│   │ ├── string_decoder@1.0.0 
│   │ └── util-deprecate@1.0.2 
│   └── uid-number@0.0.6 
└─┬ request@2.81.0 
  ├── aws-sign2@0.6.0 
  ├── aws4@1.6.0 
  ├── caseless@0.12.0 
  ├─┬ combined-stream@1.0.5 
  │ └── delayed-stream@1.0.0 
  ├── extend@3.0.0 
  ├── forever-agent@0.6.1 
  ├─┬ form-data@2.1.4 
  │ └── asynckit@0.4.0 
  ├─┬ har-validator@4.2.1 
  │ ├─┬ ajv@4.11.7 
  │ │ ├── co@4.6.0 
  │ │ └─┬ json-stable-stringify@1.0.1 
  │ │   └── jsonify@0.0.0 
  │ └── har-schema@1.0.5 
  ├─┬ hawk@3.1.3 
  │ ├── boom@2.10.1 
  │ ├── cryptiles@2.0.5 
  │ ├── hoek@2.16.3 
  │ └── sntp@1.0.9 
  ├─┬ http-signature@1.1.1 
  │ ├── assert-plus@0.2.0 
  │ ├─┬ jsprim@1.4.0 
  │ │ ├── assert-plus@1.0.0 
  │ │ ├── extsprintf@1.0.2 
  │ │ ├── json-schema@0.2.3 
  │ │ └── verror@1.3.6 
  │ └─┬ sshpk@1.13.0 
  │   ├── asn1@0.2.3 
  │   ├── assert-plus@1.0.0 
  │   ├── bcrypt-pbkdf@1.0.1 
  │   ├─┬ dashdash@1.14.1 
  │   │ └── assert-plus@1.0.0 
  │   ├── ecc-jsbn@0.1.1 
  │   ├─┬ getpass@0.1.6 
  │   │ └── assert-plus@1.0.0 
  │   ├── jodid25519@1.0.2 
  │   ├── jsbn@0.1.1 
  │   └── tweetnacl@0.14.5 
  ├── is-typedarray@1.0.0 
  ├── isstream@0.1.2 
  ├── json-stringify-safe@5.0.1 
  ├─┬ mime-types@2.1.15 
  │ └── mime-db@1.27.0 
  ├── oauth-sign@0.8.2 
  ├── performance-now@0.2.0 
  ├── qs@6.4.0 
  ├── safe-buffer@5.0.1 
  ├── stringstream@0.0.5 
  ├─┬ tough-cookie@2.3.2 
  │ └── punycode@1.4.1 
  ├── tunnel-agent@0.6.0 
  └── uuid@3.0.1 


> @mapbox/mapbox-gl-native@3.4.7 install /usr/home/user/node_modules/@mapbox/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.7/node-v46-freebsd-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/node_modules/node-pre-gyp/lib/install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:82:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:97:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:322:20)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! System FreeBSD 10.3-STABLE
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/home/user/node_modules/@mapbox/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native
node-pre-gyp ERR! node -v v4.7.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.7/node-v46-freebsd-x64.tar.gz
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 3: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 4: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 5: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 6: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 7: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 9: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 12: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 13: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 14: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 17: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 18: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 19: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 20: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 21: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 23: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 25: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 27: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 29: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 31: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 33: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 35: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 37: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 39: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 40: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 42: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 43: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 45: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 55: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 192: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 196: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 280: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 284: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 305: warning: duplicate script for target "test" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 109: warning: using previous script for "test" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 309: warning: duplicate script for target "benchmark" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 113: warning: using previous script for "benchmark" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 311: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 313: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 319: warning: duplicate script for target "run-test-%" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 121: warning: using previous script for "run-test-%" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 325: warning: duplicate script for target "run-benchmark-%" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 127: warning: using previous script for "run-benchmark-%" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 329: warning: duplicate script for target "render" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 139: warning: using previous script for "render" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 333: warning: duplicate script for target "offline" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 143: warning: using previous script for "offline" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 337: warning: duplicate script for target "glfw-app" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 131: warning: using previous script for "glfw-app" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 341: warning: duplicate script for target "run-glfw-app" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 135: warning: using previous script for "run-glfw-app" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 345: warning: duplicate script for target "node" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 147: warning: using previous script for "node" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 353: warning: duplicate script for target "tidy" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 186: warning: using previous script for "tidy" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 357: warning: duplicate script for target "check" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 190: warning: using previous script for "check" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 359: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 363: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 365: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 367: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 369: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 371: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 377: warning: duplicate script for target "/build.ninja" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 298: warning: using previous script for "/build.ninja" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 388: warning: duplicate script for target "/build.ninja" ignored
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 298: warning: using previous script for "/build.ninja" defined here
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 390: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 417: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 495: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 581: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 584: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 585: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 586: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 588: Need an operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 648: Missing dependency operator
make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 652: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native
npm WARN user@1.0.0 No description
npm WARN user@1.0.0 No repository field.
npm ERR! FreeBSD 10.3-STABLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@mapbox/mapbox-gl-native"
npm ERR! node v4.7.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! @mapbox/mapbox-gl-native@3.4.7 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mapbox/mapbox-gl-native@3.4.7 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @mapbox/mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @mapbox/mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @mapbox/mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/user/npm-debug.log

```

**Comment by jfirebaugh** [comment]
> make: "/usr/home/user/domains/mydomain.com/public_nodejs/node_modules/@mapbox/mapbox-gl-native/Makefile" line 3: Missing dependency operator

On FreeBSD you'll need to arrange for `make` to invoke GNU make, not BSD make.

**Comment by dBitech** [comment]
Even using gmake in place of make I get the following:

Makefile:25: *** Cannot determine host platform.
