### ISSUE TITLE
[android] Freeze when using MapBox map with BottomNavigationView

### ISSUE THREAD

**Issue by nikolleto** [mapbox/mapbox-gl-native#8796]
I've uploaded the video with that issue: https://www.youtube.com/watch?v=icDzlOIjH90

Freeze occurs when I'm switching to section that contains MapBox's map. Content freezes and no longer changes.

dependency in my `build.gradle` file:

```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar') {
        transitive = true
    }
```

fragment_map.xml:

```
<com.mapbox.mapboxsdk.maps.MapView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/map_view"/>
```

I'm also using Jake Wharton's Butterknife library to bind views, so this is how I'm binding MapView:

`@BindView(R.id.map_view) MapView mapView;`

I'm using `BottomNavigationView` from `android.support.design` library. This is how I switch between sections:

```
private void replaceFragment(Fragment fragment) {
        FragmentManager fragmentManager = getSupportFragmentManager();
        fragmentManager.beginTransaction()
                .replace(R.id.content_holder, fragment)
                .commit();
        fragmentManager.executePendingTransactions();
}
```

**Platform:Nexus 5X (Android 7.1.2)
**Mapbox SDK version:5.0.2

**Comment by tobrun** [comment]
Could you provide us with a minimal example to reproduce?

I tried out adding a bottom bar to reproduce but wasn't able to reproduce:
![ezgif com-video-to-gif 40](https://cloud.githubusercontent.com/assets/2151639/25325341/63d25f56-28cb-11e7-9142-f1b632a0b2c8.gif)

**Comment by nikolleto** [comment]
@tobrun Thank you for the answer. It seems that I have completely different issue. I've made a sample project to test MapBox. Now I'm getting crash with stacktrace:

```
E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
E/mbgl: {s.myapplication}[OpenGL]: eglCreateWindowSurface() returned error 12296
```

```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: nicks.myapplication, PID: 17035
                  java.lang.Error: eglCreateWindowSurface() failed
                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
                      at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:155)
                      at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:446)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
As I previously mentioned, I'm trying to run the app on LG Nexus 5X.

**Platform:Nexus 5X (Android 7.1.2)
**Mapbox SDK version:5.0.2

I've uploaded the project to github: https://github.com/nikolleto/MyProject
You may clone it and reproduce the error.

**Comment by nikolleto** [comment]
I'm closing this thread because the issue isn't related to the BottomNavigationView.
