### ISSUE TITLE
Android Error init map eglChooseConfig() failed

### ISSUE THREAD

**Issue by javi2491** [mapbox/mapbox-gl-native#8810]
Hi, App crash when init map.Please help me.

Platform:Android 4.1.1
Mapbox SDK version:5.0.1@aar

` STACK_TRACE:java.lang.Error: eglChooseConfig() failed
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:126)
	at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:213)
	at com.yovoytaxi.passengerapp.PlaceActivity.onCreate(PlaceActivity.java:126)
	at android.app.Activity.performCreate(Activity.java:5187)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
	at android.app.ActivityThread.access$600(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4847)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:535)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by ivovandongen** [comment]
Hi @javi2491 what device are you running on?

**Comment by javi2491** [comment]
Sorry, I do not have that information, but I do need help.

**Comment by vanshg** [comment]
Hi, I seem to be getting this crash in my users' crash logs too. 

The device in question seems to be an Oppo R830, running Android 4.4.2. Upon crash, user seemed to have 56.87KB VM free and 828.09KB VM free another time. So maybe this might be a crash related to low memory.


```
com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay (NativeMapView.java)
com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay (NativeMapView.java:115)
com.mapbox.mapboxsdk.maps.MapView.onCreate (MapView.java:468)
com.airmap.airmap.Activities.MainActivity.setupMap (MainActivity.java:249)
com.airmap.airmap.Activities.MainActivity.onCreate (MainActivity.java:160)
android.app.Activity.performCreate (Activity.java:5231)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1104)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2157)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2243)
android.app.ActivityThread.access$800 (ActivityThread.java:135)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1196)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5019)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:779)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:595)
dalvik.system.NativeStart.main (NativeStart.java)
```

**Comment by paulVulog** [comment]
What is the status of this issue ? 
I have the same issue. 
Fatal Exception: java.lang.Error: eglChooseConfig() failed
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:126)
       at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:213)
...

My Crash report give me the following devices : 

- QEMU - Standard PC (i440FX + PIIX, 1996)
- xiaomi-1s
- Samsung - Galaxy S5
- Trendmicro - GI-I9500_TMMARS
- other

Mainly Android 4.x

Mapbox version "5.0.1@aar"

Looks like an unsupported device issue. Is there a way to test if the device support Mapbox ?

**Comment by algoroq** [comment]
Hello from my crash logs.

For Sony Tablet S (Android 4.0.3):
Fatal Exception: java.lang.Error: No config chosen
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
       at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:205)
       at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:200)

For - GI-I9500_TMMARS (Android 5.1):
Fatal Exception: java.lang.Error: eglChooseConfig() failed
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
       at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:205)
       at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:200)

Mapbox version: "**v5.1.0-beta.1**"

**Comment by MozThinker** [comment]
Hi, I'm having same issue for all devices running Android Jelly Bean. Any solution?
Thanks in advance.

**Comment by NancyAndroid** [comment]
I have same issue please let me know how to resolve. I am using 
com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3@aar

**Comment by mdakram** [comment]
any update on this?

**Comment by P-Zenker** [comment]
Hey,

I only received this issue once on a customer device. 

```
java.lang.Error: eglChooseConfig() failed
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
	at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
	at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:199)
	at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:194)
```

Android-Version: 4.3.1 (18)
Smartphone-Model: GT-I8190
Smartphone-Device: golden
Smartphone-Brand: samsung
Smartphone-Produkt: goldenxx

- com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar

On my own Samsung S3 mini I couldn't reproduce this issue. I don't know how I even get Android 4.3.1 on my S3 mini - it currently runs with Android 4.2.2.

**Comment by DaveNOTDavid** [comment]
Any updates?

**Comment by Ami-Patel** [comment]
Hello I am facing same issue in genymotion
Genymotion : 2.11.0 and Custom Android Phone version 5.0.0 
Mapbox version : 5.4.1.
