### ISSUE TITLE
Crash in Android 4.1.1 I' am using MapboxSdk version 5.0.1

### ISSUE THREAD

**Issue by javi2491** [mapbox/mapbox-gl-native#8811]
Hi, I have a problem I am getting this crash of my application, I need help.
I still do not know how it goes.
I need help.

Platform: ANDROID 4.1.1
Mapbox SDK version: 5.0.1@aar

```
STACK_TRACE:java.lang.NullPointerException
	at com.mapzen.android.lost.internal.GeofenceIntentHelper.transitionForIntent(GeofenceIntentHelper.java:20)
	at com.mapzen.android.lost.api.GeofencingIntentSender.shouldSendIntent(GeofencingIntentSender.java:51)
	at com.mapzen.android.lost.api.GeofencingIntentSender.sendIntent(GeofencingIntentSender.java:35)
	at com.mapzen.android.lost.internal.GeofencingIntentService.onHandleIntent(GeofencingIntentService.java:25)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by tobrun** [comment]
The underlying issue will be related to the used LOST dependency v2.2.0, PR updating this in #8872
