### ISSUE TITLE
[Android] Mapbox not starting in a Fragment

### ISSUE THREAD

**Issue by nikolleto** [mapbox/mapbox-gl-native#8860]
Hello again. I still can't run the library on Android. Now I've made a sample project, so you can get it on github and check what's wrong: https://github.com/nikolleto/MyProject

When I run the app it crashes:

> E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
E/mbgl: {s.myapplication}[OpenGL]: eglCreateWindowSurface() returned error 12296

> D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: nicks.myapplication, PID: 17035
                  java.lang.Error: eglCreateWindowSurface() failed
                      at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCreateSurface(Native Method)
                      at com.mapbox.mapboxsdk.maps.NativeMapView.createSurface(NativeMapView.java:155)
                      at com.mapbox.mapboxsdk.maps.MapView$SurfaceCallback.surfaceCreated(MapView.java:446)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Platform:Nexus 5X (Android 7.1.2)
**Mapbox SDK version:5.0.2

It also reproduces on Nexus 5X (Android 7.1.0) which's available via Genymotion.

**Comment by tobrun** [comment]
@nikolleto thank you for reaching out and reporting your issue, it seems that you have forgotten to include the [required lifecycle methods](https://www.mapbox.com/android-sdk/#lifecycle_methods) in your code [here](https://github.com/nikolleto/MyProject/blob/master/app/src/main/java/nicks/myapplication/MapFragment.java#L25). 

With upcoming 5.1.0 release, we have tried to make this use-case a bit more robust, it shouldn't crash anymore though it will also not show you an map as it wasn't correctly initialized.
