### ISSUE TITLE
Mapbox Android crashes in Android O

### ISSUE THREAD

**Issue by sidky** [mapbox/mapbox-gl-native#8881]
**Platform:**
Android O (ran in the emulator)

**Mapbox SDK version:**
5.0.2

### Steps to trigger behavior

Mapbox crashes on start. Added `MapBox` in the activity layout, and opened the activity. It crashed while inflating the view.
https://gist.github.com/sidky/df6c0d11f30271920c4f7c95901c87b0

### Stacktrace ###
```
                        E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.sidky.mapbox.mapboxtest/com.github.sidky.mapbox.mapboxtest.MainActivity}: android.view.InflateException: Binary XML file line #6: Binary
                             XML file line #6: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
                         E      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:156)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6440)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746)
                         E  Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                         E  Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                         E  Caused by: java.lang.reflect.InvocationTargetException
                         E      at java.lang.reflect.Constructor.newInstance0(Native Method)
                         E      at java.lang.reflect.Constructor.newInstance(Constructor.java:333)
                         E      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                         E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                         E      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                         E      at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
                         E      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                         E      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                         E      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
                         E      at android.app.Activity.setContentView(Activity.java:2492)
                         E      at com.github.sidky.mapbox.mapboxtest.MainActivity.onCreate(MainActivity.java:61)
                         E      at android.app.Activity.performCreate(Activity.java:6773)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1195)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
                         E      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:156)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6440)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746)
                         E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getRowBytes()' on a null object reference
                         E      at com.mapbox.mapboxsdk.maps.IconManager.loadIcon(IconManager.java:105)
                         E      at com.mapbox.mapboxsdk.maps.IconManager.<init>(IconManager.java:39)
                         E      at com.mapbox.mapboxsdk.maps.AnnotationManager.<init>(AnnotationManager.java:52)
                         E      at com.mapbox.mapboxsdk.maps.MapView.initialise(MapView.java:143)
                         E      at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:93)
                         E      ... 25 more

```

**Comment by sidky** [comment]
Duplicate of https://github.com/mapbox/mapbox-gl-native/issues/8766
