### ISSUE TITLE
[node] Crash in node_mbgl::NodeMap::renderFinished()

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#8892]
```
	
[Current thread is 1 (Thread 0x7f4371366780 (LWP 6776))]
Thread 30 (Thread 0x7f43536cc700 (LWP 6805)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 29 (Thread 0x7f43566d2700 (LWP 6799)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 28 (Thread 0x7f43576d4700 (LWP 6797)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 27 (Thread 0x7f4358ed7700 (LWP 6794)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 26 (Thread 0x7f435b6dc700 (LWP 6789)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 25 (Thread 0x7f435e6e2700 (LWP 6783)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 24 (Thread 0x7f435dee1700 (LWP 6784)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 23 (Thread 0x7f4355ed1700 (LWP 6800)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 22 (Thread 0x7f43596d8700 (LWP 6793)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 21 (Thread 0x7f435cedf700 (LWP 6786)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 20 (Thread 0x7f4354ecf700 (LWP 6802)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 19 (Thread 0x7f43586d6700 (LWP 6795)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 18 (Thread 0x7f435a6da700 (LWP 6791)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 17 (Thread 0x7f4357ed5700 (LWP 6796)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 16 (Thread 0x7f43546ce700 (LWP 6803)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 15 (Thread 0x7f43556d0700 (LWP 6801)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 14 (Thread 0x7f4359ed9700 (LWP 6792)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 13 (Thread 0x7f435aedb700 (LWP 6790)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 12 (Thread 0x7f435c6de700 (LWP 6787)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 11 (Thread 0x7f4356ed3700 (LWP 6798)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 10 (Thread 0x7f4353ecd700 (LWP 6804)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 9 (Thread 0x7f435bedd700 (LWP 6788)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 8 (Thread 0x7f435eee3700 (LWP 6782)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 7 (Thread 0x7f436e3fd700 (LWP 6780)):
#0  0x00007f4370061867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f4370061914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f43700619ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 6 (Thread 0x7f436dbfc700 (LWP 6781)):
#0  0x00007f4370061867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f4370061914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f43700619ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 5 (Thread 0x7f435d6e0700 (LWP 6785)):
#0  0x00007f437005f3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 4 (Thread 0x7f436f3ff700 (LWP 6778)):
#0  0x00007f4370061867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f4370061914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f43700619ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 3 (Thread 0x7f436ebfe700 (LWP 6779)):
#0  0x00007f4370061867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f4370061914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f43700619ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 2 (Thread 0x7f4371375700 (LWP 6777)):
#0  0x00007f4370061867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f4370061914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f43700619ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fb52f2 in uv_sem_wait (sem=0x1997220 <node::debug_semaphore>) at ../deps/uv/src/unix/thread.c:330
#4  0x0000000000de5b82 in node::DebugSignalThreadMain(void*) ()
#5  0x00007f43700596fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f436fd8fb5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 1 (Thread 0x7f4371366780 (LWP 6776)):
#0  0x00007f436ba9ef97 in Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#1  0x00007f436ba9d3ac in node_mbgl::NodeMap::renderFinished() () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#2  0x0000000000fa822b in uv__async_event (loop=0x1998e00 <default_loop_struct>, w=<optimized out>, nevents=<optimized out>) at ../deps/uv/src/unix/async.c:98
#3  0x0000000000fa8303 in uv__async_io (loop=0x1998e00 <default_loop_struct>, w=0x1998fc8 <default_loop_struct+456>, events=<optimized out>) at ../deps/uv/src/unix/async.c:138
#4  0x0000000000fb88d0 in uv__io_poll (loop=0x1998e00 <default_loop_struct>, timeout=0) at ../deps/uv/src/unix/linux-core.c:380
#5  0x0000000000fa8de6 in uv_run (loop=0x1998e00 <default_loop_struct>, mode=UV_RUN_ONCE) at ../deps/uv/src/unix/core.c:354
#6  0x0000000000df3550 in node::Start(int, char**) ()
#7  0x00007f436fca9830 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00000000007234ad in _start ()
```

/cc @tmpsantos @kkaefer @jfirebaugh @springmeyer

**Comment by mcwhittemore** [comment]
This ticket has been replaced by #8966.
