### ISSUE TITLE
[node] LineBucket crash

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#8965]
```
[Current thread is 1 (Thread 0x7f7302c34780 (LWP 3869))]
Thread 30 (Thread 0x7f72e92d0700 (LWP 3938)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 29 (Thread 0x7f72ea2d2700 (LWP 3936)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 28 (Thread 0x7f72ebad5700 (LWP 3933)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 27 (Thread 0x7f72e4ac7700 (LWP 3947)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 26 (Thread 0x7f72e5ac9700 (LWP 3945)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 25 (Thread 0x7f72ecad7700 (LWP 3931)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 24 (Thread 0x7f72e72cc700 (LWP 3942)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 23 (Thread 0x7f72edad9700 (LWP 3929)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 22 (Thread 0x7f72e7acd700 (LWP 3941)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 21 (Thread 0x7f72ec2d6700 (LWP 3932)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 20 (Thread 0x7f72eeadb700 (LWP 3927)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 19 (Thread 0x7f72eb2d4700 (LWP 3934)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 18 (Thread 0x7f72e82ce700 (LWP 3940)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 17 (Thread 0x7f72efadd700 (LWP 3925)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 16 (Thread 0x7f72ee2da700 (LWP 3928)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 15 (Thread 0x7f72eaad3700 (LWP 3935)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 14 (Thread 0x7f72e9ad1700 (LWP 3937)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 13 (Thread 0x7f72ff3fc700 (LWP 3874)):
#0  0x00007f730192f867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f730192f914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f730192f9ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 12 (Thread 0x7f72e62ca700 (LWP 3944)):
#0  0x00007f73027f3c92 in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#1  0x00007f73027f5a63 in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#2  0x00007f73027f7eca in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#3  0x00007f7302813243 in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#4  0x00007f73028135e5 in ?? () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#5  0x00007f73027f007c in malloc () from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
#6  0x00007f73020e9e78 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f72fd3de02b in void std::vector<mbgl::LineBucket::TriangleElement, std::allocator<mbgl::LineBucket::TriangleElement> >::_M_emplace_back_aux<long&, long&, long&>(long&, long&, long&) () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#8  0x00007f72fd3dc9fb in mbgl::LineBucket::addCurrentVertex(mapbox::geometry::point<short> const&, double&, mapbox::geometry::point<double> const&, double, double, bool, unsigned long, std::vector<mbgl::LineBucket::TriangleElement, std::allocator<mbgl::LineBucket::TriangleElement> >&) () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#9  0x00007f72fd3db7b3 in mbgl::LineBucket::addGeometry(mbgl::GeometryCoordinates const&, mbgl::FeatureType) () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#10 0x00007f72fd3daf85 in mbgl::LineBucket::addFeature(mbgl::GeometryTileFeature const&, mbgl::GeometryCollection const&) () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#11 0x00007f72fd392788 in mbgl::GeometryTileWorker::redoLayout() () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#12 0x00007f72fd3931b6 in mbgl::GeometryTileWorker::coalesced() () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#13 0x00007f72fd2edea5 in mbgl::Mailbox::receive() () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#14 0x00007f72fd2ee012 in mbgl::Mailbox::maybeReceive(std::weak_ptr<mbgl::Mailbox>) () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#15 0x00007f72fd2ecfbf in node_mbgl::NodeThreadPool::Worker::Execute() () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#16 0x0000000000fa5e91 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:95
#17 0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#18 0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#19 0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 11 (Thread 0x7f72f02de700 (LWP 3924)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 10 (Thread 0x7f72e6acb700 (LWP 3943)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 9 (Thread 0x7f72ed2d8700 (LWP 3930)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 8 (Thread 0x7f72ef2dc700 (LWP 3926)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 7 (Thread 0x7f72e52c8700 (LWP 3946)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 6 (Thread 0x7f73003fe700 (LWP 3872)):
#0  0x00007f730192f867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f730192f914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f730192f9ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 5 (Thread 0x7f72e8acf700 (LWP 3939)):
#0  0x00007f730192d3a0 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000000fb5469 in uv_cond_wait (cond=cond@entry=0x1998da0 <cond>, mutex=mutex@entry=0x1998d60 <mutex>) at ../deps/uv/src/unix/thread.c:443
#2  0x0000000000fa5e38 in worker (arg=arg@entry=0x0) at ../deps/uv/src/threadpool.c:75
#3  0x0000000000fb4fc9 in uv__thread_start (arg=<optimized out>) at ../deps/uv/src/unix/thread.c:52
#4  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 4 (Thread 0x7f7300bff700 (LWP 3871)):
#0  0x00007f730192f867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f730192f914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f730192f9ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 3 (Thread 0x7f72ffbfd700 (LWP 3873)):
#0  0x00007f730192f867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f730192f914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f730192f9ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fbf128 in v8::base::Semaphore::Wait() ()
#4  0x0000000000e5b089 in v8::platform::TaskQueue::GetNext() ()
#5  0x0000000000e5b1dc in v8::platform::WorkerThread::Run() ()
#6  0x0000000000fc00e0 in v8::base::ThreadEntry(void*) ()
#7  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 2 (Thread 0x7f7302c43700 (LWP 3870)):
#0  0x00007f730192f867 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f730192f914 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f730192f9ba in sem_wait@@GLIBC_2.2.5 () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x0000000000fb52f2 in uv_sem_wait (sem=0x1997220 <node::debug_semaphore>) at ../deps/uv/src/unix/thread.c:330
#4  0x0000000000de5b82 in node::DebugSignalThreadMain(void*) ()
#5  0x00007f73019276fa in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f730165db5d in clone () from /lib/x86_64-linux-gnu/libc.so.6
Thread 1 (Thread 0x7f7302c34780 (LWP 3869)):
#0  0x00007f72fd29ef97 in Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#1  0x00007f72fd29d3ac in node_mbgl::NodeMap::renderFinished() () from /usr/local/src/app/node_modules/@mapbox/mapbox-gl-native/lib/mapbox_gl_native.node
#2  0x0000000000fa822b in uv__async_event (loop=0x1998e00 <default_loop_struct>, w=<optimized out>, nevents=<optimized out>) at ../deps/uv/src/unix/async.c:98
#3  0x0000000000fa8303 in uv__async_io (loop=0x1998e00 <default_loop_struct>, w=0x1998fc8 <default_loop_struct+456>, events=<optimized out>) at ../deps/uv/src/unix/async.c:138
#4  0x0000000000fb88d0 in uv__io_poll (loop=0x1998e00 <default_loop_struct>, timeout=0) at ../deps/uv/src/unix/linux-core.c:380
#5  0x0000000000fa8de6 in uv_run (loop=0x1998e00 <default_loop_struct>, mode=UV_RUN_ONCE) at ../deps/uv/src/unix/core.c:354
#6  0x0000000000df3550 in node::Start(int, char**) ()
#7  0x00007f7301577830 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00000000007234ad in _start ()
```

/cc @tmpsantos @mcwhittemore @jfirebaugh @kkaefer

**Comment by bsudekum** [comment]
duped https://github.com/mapbox/mapbox-gl-native/issues/8966
