### ISSUE TITLE
[android] native error when mapview.onCreate

### ISSUE THREAD

**Issue by Larnoo** [mapbox/mapbox-gl-native#9120]
**Device:** GI-i9500-TMMARS
**Platform:** Android 5.1
**Mapbox SDK version:** 5.0.0

```
java.lang.Error: eglChooseConfig() failed
    at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(NativeMapView.java)
    at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:127)
    at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:216)
    at com.demo.mapbox.CKSupportMapFragment.onViewCreated(CKSupportMapFragment.java:155)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1314)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1528)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1595)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2363)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:2149)
    at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManagerImpl.java:2103)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:2013)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
```

**Comment by tobrun** [comment]
@Larnoo thank you for the report, do you have any more information on this issue?

**Comment by MateusCarvalho** [comment]
I have the same Bug
`Fatal Exception: java.lang.Error: eglChooseConfig() failed
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(SourceFile)
       at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(SourceFile:127)
       at com.mapbox.mapboxsdk.maps.MapView.onCreate(SourceFile:213)
       at com.motaxis.MainActivity.onCreate(SourceFile:157)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
       at android.app.ActivityThread.-wrap10(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)`

I saw in the CrashLytcs that this error is exclusive in androids with version 5 and 4.

**Comment by ledlie** [comment]
I have the same bug on the same phone. It also occurred for me in Genymotion running their Samsung S4 phone.

**Comment by pamartineza** [comment]
Hi, same here, using last stable release 5.1.0, you can find realtime crash data in this Fabric link http://crashes.to/s/d459a71fc0a

**Comment by fauger** [comment]
Same here on genymotion : Mototola Droid Razr 4.1.1 - API 16 - 540*960 reproduce on mapbox sdk test app
Mapbox version :   5.0

`com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            java.lang.Error: eglChooseConfig() failed
                                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
                                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:129)
                                                                                at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:215)
                                                                                at com.mapbox.mapboxsdk.testapp.activity.maplayout.SimpleMapActivity.onCreate(SimpleMapActivity.java:22)
                                                                                at android.app.Activity.performCreate(Activity.java:5008)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:137)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                at dalvik.system.NativeStart.main(Native Method)`

**Comment by Larnoo** [comment]
@tobrun

 There's not much more information about the issue 
The crash happens on `GI-i9500-TMMARS` `VPhone` devices. Other device don't found the crash

**Comment by drd** [comment]
FWIW, we're also seeing this in Galaxy Tab 10.1 and Galaxy Tab 3 10.1

**Comment by NancyAndroid** [comment]
Please let me know how to solve Same issue Here is my log 
FATAL EXCEPTION: main  java.lang.Error: eglChooseConfig() failed                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)                                                                  at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:199)                                                                  at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:194)                                                                  at com.orbisalert.Activity.MapBoxActivity.onCreate(MapBoxActivity.java:101)                                                                  at android.app.Activity.performCreate(Activity.java:5104)                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)                                                                  at android.app.ActivityThread.startActivityNow(ActivityThread.java:2023)                                                                  at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135)                                                                  at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347)                                                                  at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:749)                                                                  at android.widget.TabHost.setCurrentTab(TabHost.java:413)                                                                  at com.orbisalert.Activity.TabHostActivity.setTabs(TabHostActivity.java:89)                                                                  at com.orbisalert.Activity.TabHostActivity.onCreate(TabHostActivity.java:66)                                                                  at android.app.Activity.performCreate(Activity.java:5104)                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141)                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)                                                                  at android.os.Looper.loop(Looper.java:137)                                                                  at android.app.ActivityThread.main(ActivityThread.java:5041)                                                                  at java.lang.reflect.Method.invokeNative(Native Method)                                                                  at java.lang.reflect.Method.invoke(Method.java:511)                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by grote** [comment]
This happens also if run on an ARM emulator within travis for example.

**Comment by Necklaces** [comment]
Seems like I also get this on a Samsung Galaxy Note II running Replicant 6.

```
10-23 09:37:17.990 17260 17260 E mbgl    : {wherearetheeyes}[OpenGL]: eglChooseConfig() returned no configs.
10-23 09:37:17.990 17260 17260 D AndroidRuntime: Shutting down VM
10-23 09:37:17.990 17260 17260 E AndroidRuntime: FATAL EXCEPTION: main
10-23 09:37:17.990 17260 17260 E AndroidRuntime: Process: org.daylightingsociety.wherearetheeyes, PID: 17260
10-23 09:37:17.990 17260 17260 E AndroidRuntime: Theme: themes:{}
10-23 09:37:17.990 17260 17260 E AndroidRuntime: java.lang.Error: eglChooseConfig() failed
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:127)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:213)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at org.daylightingsociety.wherearetheeyes.MainActivity.onCreate(MainActivity.java:73)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-23 09:37:17.990 17260 17260 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by tobrun** [comment]
Closing as a duplicate #7273
