### ISSUE TITLE
[android] NullPointerException when rapidly changing screen orientation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#9127]
**Platform:** Android
**Mapbox SDK version:** 5.1.0-beta.3

### Steps to trigger behavior

 Rapidly change screen orientation a couple of times

### Expected behavior

 App restores saved instance

### Actual behavior

App crashes

Here is crash insight:
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.mapbox.mapboxsdk.maps.MapView.getContext()' on a null object reference
                                                                                            at com.mapbox.mapboxsdk.maps.NativeMapView.getContext(NativeMapView.java:901)
                                                                                            at com.mapbox.mapboxsdk.maps.IconManager.loadIconForMarkerView(IconManager.java:78)
                                                                                            at com.mapbox.mapboxsdk.maps.AnnotationManager.prepareViewMarker(AnnotationManager.java:270)
                                                                                            at com.mapbox.mapboxsdk.maps.AnnotationManager.addMarker(AnnotationManager.java:229)
                                                                                            at com.mapbox.mapboxsdk.maps.MapboxMap.addMarker(MapboxMap.java:1123)
                                                                                            at mapboxdependencytest.MainActivity$1.onMapReady(MainActivity.java:35)
                                                                                            at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:964)
                                                                                            at com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000(MapView.java:929)
                                                                                            at com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run(MapView.java:947)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:211)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5321)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)`

and code which creates it:
`public class MainActivity extends AppCompatActivity {

    private MapView mapView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, "...");

        setContentView(R.layout.activity_main);

        mapView = (MapView) findViewById(R.id.map_view);

        mapView.onCreate(savedInstanceState);

        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                mapboxMap.addMarker(new MarkerViewOptions().position(new LatLng(51,16))); //exception is thrown on this line
                mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener(new MapboxMap.OnMarkerViewClickListener() {
                    @Override
                    public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view, @NonNull MapboxMap.MarkerViewAdapter adapter) {
                        Toast.makeText(MainActivity.this, "Marker click", Toast.LENGTH_SHORT).show();
                        return true;
                    }
                });
            }
        });
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    public void onStart() {
        super.onStart();
        mapView.onStart();
    }

    @Override
    public void onStop() {
        super.onStop();

        mapView.onStop();
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();

        mapView.onDestroy();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }
}`

**Comment by tobrun** [comment]
closed with #9128, feel free to retest the SNAPSHOT
