### ISSUE TITLE
Telemetry event out of memory exception

### ISSUE THREAD

**Issue by SimonPSH** [mapbox/mapbox-gl-native#9131]
Android : 5,6,7,O
Mapbox 5.0.2

We upgraded to Mapbox 5.0.2 a few weeks ago and we have been getting a significant of Out of memory exceptions related to Mapbox Telemetry events.  This crash happens on our production app, so we do not have any clear repro steps.  Here are the stack traces of the crash

`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1179656 byte allocation with 1052544 free bytes and 1020KB until OOM
       at java.util.Arrays.copyOf(Arrays.java:3352)
       at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:606)
       at java.lang.StringBuilder.append(StringBuilder.java:215)
       at org.json.JSONStringer.string(JSONStringer.java:344)
       at org.json.JSONStringer.key(JSONStringer.java:375)
       at org.json.JSONObject.writeTo(JSONObject.java:720)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:613)
       at org.json.JSONArray.toString(JSONArray.java:585)
       at com.mapbox.services.android.telemetry.http.TelemetryClient.sendEventsWrapped(TelemetryClient.java:202)
       at com.mapbox.services.android.telemetry.http.TelemetryClient.sendEvents(TelemetryClient.java:117)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.flushEventsQueueImmediately(MapboxTelemetry.java:516)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.putEventOnQueue(MapboxTelemetry.java:402)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.addLocationEvent(MapboxTelemetry.java:444)
       at com.mapbox.services.android.telemetry.TelemetryLocationReceiver.onReceive(TelemetryLocationReceiver.java:27)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)`

This is a very severe issue and might require us to downgrade from Mapbox 5 to 4.

**Comment by tobrun** [comment]
Adding this to the milestone for visibility related to a final 5.1.0 release. 
The actual issue is being handled in https://github.com/mapbox/mapbox-java/issues/467.

**Comment by tobrun** [comment]
Looked into this more and capturing from https://github.com/mapbox/mapbox-java/issues/467 that this is handled and resolved for the upcoming 5.1.0. Feel free to test out the beta or SNAPSHOT build. Feel free to reach out if this is still an issue. Closing as resolved upstream.

**Comment by SimonPSH** [comment]
What's your timeline on releasing 5.1.0?
