### ISSUE TITLE
[Shader]: Program failed to link: Too many varyings

### ISSUE THREAD

**Issue by danieljph** [mapbox/mapbox-gl-native#9209]
Hai guys! Please help me. I got this error message below when open activity contains Mapbox.

**OTHER INFORMATION:**

**Mapbox Version:** 5.0.2
**Build Tools:** build-tools;25.0.3
**Platform Tools:** 25.0.6
**Tools:** 26.0.2
**Emulator:** emulator 26.0.3
**Platforms:** platforms;android-22 v2
**System Image:** system-images;android-22;google_apis;x86 v13

https://www.karyasarma.com

```[Shader]: Program failed to link: Too many varyings
Shutting down VM
FATAL EXCEPTION: main
Process: com.my.app, PID: 4071
java.lang.Error: program failed to link
    at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
    at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:176)
    at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:426)
    at android.view.View.draw(View.java:15231)
    at android.widget.FrameLayout.draw(FrameLayout.java:598)
    at android.view.View.updateDisplayListIfDirty(View.java:14167)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.View.draw(View.java:14959)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
    at android.view.View.updateDisplayListIfDirty(View.java:14162)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.View.draw(View.java:14959)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
    at android.view.View.updateDisplayListIfDirty(View.java:14162)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
    at android.view.View.updateDisplayListIfDirty(View.java:14127)
    at android.view.View.getDisplayList(View.java:14189)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:550)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.disp
Sending signal. PID: 4071 SIG: 9

**Comment by tobrun** [comment]
Thank you for the report, haven't seen this issue before. Are you seeing the same with one of the 5.1.0 or the SNAPSHOT? Installation information can be found [here](https://www.mapbox.com/android-sdk/). Are you using any native code in this application or the dependencies?

**Comment by danieljph** [comment]
Hi @tobrun, unfortunately I only have an APK that using Mapbox 5.0.2 and my APK is using depedencies.
