### ISSUE TITLE
Null pointer exception on LocationRequest in mapbox telemetry service

### ISSUE THREAD

**Issue by SimonPSH** [mapbox/mapbox-gl-native#9259]
**Platform: Android 7.0**
**Mapbox SDK version: 5.1.0-beta.3**
**Mapbox Android Services version: 1.3.1**

We are experiencing a crash on 5.1.0-beta.3 which happens when our Mapbox Map is loaded.  It happened once randomly and again 3 times in a row.

Here is the stack trace

`06-13 15:41:53.042 18182-18182/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapzen.android.lost.api.LocationRequest.getPriority()' on a null object reference
                                                       at android.os.Parcel.readException(Parcel.java:1699)
                                                       at android.os.Parcel.readException(Parcel.java:1646)
                                                       at com.mapzen.android.lost.internal.IFusedLocationProviderService$Stub$Proxy.requestLocationUpdates(IFusedLocationProviderService.java:228)
                                                       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdatesInternal(FusedLocationProviderApiImpl.java:170)
                                                       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:139)
                                                       at com.mapbox.mapboxsdk.location.LocationSource.requestLocationUpdates(LocationSource.java:121)
                                                       at com.mapbox.services.android.telemetry.MapboxTelemetry.onConnected(MapboxTelemetry.java:375)
                                                       at com.mapbox.mapboxsdk.location.LocationSource.onConnected(LocationSource.java:81)
                                                       at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
                                                       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:81)
                                                       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1516)
                                                       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1544)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

We switched from 5.0.1 to 5.1.0-beta.3 to fix another [crash](https://github.com/mapbox/mapbox-gl-native/issues/9131) in the mapbox telemetry service

**Comment by tobrun** [comment]
@SimonPSH could you retest with latest beta.4? That version updates LOST (the location provider dependency) to 3.1.0 (instead of 3.0.0 in beta.3). In the Activity that crashes, are you using any locational components or requesting location updates yourself? Thank you for the report!

**Comment by SimonPSH** [comment]
Yes we are requesting our own location updates.  I'll try with beta.4

**Comment by SimonPSH** [comment]
Beta.4 has a dependency to an unreleased version of mapzen lost, com.mapzen.android:lost:3.0.1-20170607.212149-4.

According to maven central, the latest version is 3.0.0

Any advice on this?

**Comment by tobrun** [comment]
You will have to add `maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }`  to your `repositories` section in your root folder build.gradle.

**Comment by Guardiola31337** [comment]
Hey 👋 @SimonPSH were you able to retest with beta.4?

**Comment by SimonPSH** [comment]
I did not.  We reverted to 4.2.1 and we will wait for a stable release.

**Comment by snkashis** [comment]
@Guardiola31337 I'm still seeing this issue occur in 5.2.1 and 5.3.0.
Strangely it only seems to happen on 7.0 Nougat devices.
We set up LocationEngines like this in onCreate

```
        locationEngine = locationEngineProvider.obtainBestLocationEngineAvailable();
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.activate();
```
Trace below.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapzen.android.lost.api.LocationRequest.getPriority()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1689)
       at android.os.Parcel.readException(Parcel.java:1636)
       at com.mapzen.android.lost.internal.IFusedLocationProviderService$Stub$Proxy.b(IFusedLocationProviderService.java:254)
       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.a(FusedLocationProviderApiImpl.java:195)
       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.a(FusedLocationProviderApiImpl.java:162)
       at com.mapbox.services.android.telemetry.location.LostLocationEngine.requestLocationUpdates(LostLocationEngine.java:135)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.onConnected(MapboxTelemetry.java:492)
       at com.mapbox.services.android.telemetry.location.LostLocationEngine.onConnected(LostLocationEngine.java:78)
       at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.h(FusedLocationServiceConnectionManager.java:86)
       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:94)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by Guardiola31337** [comment]
Hey @snkashis 👋 thanks for reaching out and report your problem.

I've tested using the code you provided on a Samsung Galaxy S7 running Android 7.0 (both `5.2.1` and `5.3.0` versions) and I wasn't able to reproduce any crash.

I'm assuming that you're including Lost in your project. If so, what version of Lost are you using?

Could you add some more information for reproducing the `NullPointerException` (minimal example) or any other specifics around your test setup? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, I'm unable to reproduce.

**Comment by Nexxado** [comment]
We're seeing the same issue on Android with Mapbox `v5.2.1` and Lost `v3.0.2`.
The issue seem to happen on Samsung and Huawei devices running Android 6 and 7.

We're unable to reproduce the issue.

Stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.mapzen.android.lost.api.LocationRequest.getPriority()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1626)
       at android.os.Parcel.readException(Parcel.java:1573)
       at com.mapzen.android.lost.internal.IFusedLocationProviderService$Stub$Proxy.requestLocationUpdates(IFusedLocationProviderService.java:254)
       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdatesInternal(FusedLocationProviderApiImpl.java:195)
       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:162)
       at com.mapbox.services.android.telemetry.location.LostLocationEngine.requestLocationUpdates(LostLocationEngine.java:135)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.onConnected(MapboxTelemetry.java:492)
       at com.mapbox.services.android.telemetry.location.LostLocationEngine.onConnected(LostLocationEngine.java:78)
       at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
       at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:96)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1335)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1352)
```
