### ISSUE TITLE
Calling animateCamera on the map with LatLngBounds causes crash. 

### ISSUE THREAD

**Issue by DejanRistic** [mapbox/mapbox-gl-native#9325]
**Platform: Android Pixel (7.1.2)**
**Mapbox SDK version: 5.1.0-beta.5**

Trying to animate the camera with LatLngBounds causes a crash:

```
map.animateCamera(CameraUpdateFactory.newLatLngBounds(latLngBoundsBuilder.build(), padding);
```

```
java.lang.NoSuchFieldError: no "D" field "mLatSouth" in class "Lcom/mapbox/mapboxsdk/geometry/LatLngBounds;" or its superclasses
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeGetCameraForLatLngBounds(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.getCameraForLatLngBounds(NativeMapView.java:326)
at com.mapbox.mapboxsdk.maps.MapboxMap.getCameraForLatLngBounds(MapboxMap.java:1600)
at com.mapbox.mapboxsdk.camera.CameraUpdateFactory$CameraBoundsUpdate.getCameraPosition(CameraUpdateFactory.java:221)
at com.mapbox.mapboxsdk.maps.Transform.animateCamera(Transform.java:129)
at com.mapbox.mapboxsdk.maps.MapboxMap$3.run(MapboxMap.java:863)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Guardiola31337** [comment]
@DejanRistic thanks for reaching out and report your problem.

Resolved with #9324
