### ISSUE TITLE
[android] glTexImage2D: Error GL_INVALID_VALUE

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9366]
**Platform:** Android 6.0 (Nexus 5)
**Mapbox SDK version:** `master`

### Steps to trigger behavior

 1. 
```java
  private List<MarkerOptions> mMarkerOptions;
  private List<Marker> mMarkers;
  IconFactory mIconFactory;

  // ...

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    mMarkerOptions = new ArrayList<MarkerOptions>();
    mMarkers = new ArrayList<Marker>();
    mIconFactory = IconFactory.getInstance(this);

    // This contains the MapView in XML and needs to be called after the account manager
    setContentView(R.layout.activity_basic_simple_mapview);

    final LatLng start = new LatLng(48.13863, 11.57603);

    // 24 x24 = 576 markers
    final int rows = 24;
    final int cols = 24;
    final int[] additionalCount = {0};
    final List<LatLng> locations = new ArrayList<>();

    mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);
    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(final MapboxMap mapboxMap) {
        mMap = mapboxMap;
        Icon icon = mIconFactory.fromResource(R.drawable.ic_android_2);
        for (int row = 0; row < rows; row++) {
          for (int col = 0; col < cols; col++) {
            LatLng target = new LatLng(start.getLatitude() + col * 0.001, start.getLongitude() + row * 0.001);
            locations.add(target);

            MarkerOptions markerOptions = new MarkerOptions().position(target).icon(mIconFactory.fromResource
              (R.drawable.ic_android_2)).title(String.format(Locale.US, "%dx%d", row, col));

            mMarkerOptions.add(markerOptions);
          }
        }
      }
    });
  }

  public void onAddBtn(View view) {
    for (int i = 0; i < mMarkerOptions.size(); i++) {
      Marker marker = mMap.addMarker(mMarkerOptions.get(i));
      mMarkers.add(marker);
    }
  }
```
 2. Click on `ADD` button
 3. App crashes

### Expected behavior
App doesn't crash

### Actual behavior

```
06-26 12:38:26.189 22593-22593/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.mapbox.mapboxsdk.testapp, PID: 22593
                                                                              java.lang.Error: glTexImage2D(GL_TEXTURE_2D, 0, static_cast<GLenum>(format), size.width, size.height, 0, static_cast<GLenum>(format), GL_UNSIGNED_BYTE, data): Error GL_INVALID_VALUE at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/gl/context.cpp:417
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                                  at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:176)
                                                                                  at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:420)
                                                                                  at android.view.View.draw(View.java:16178)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                                  at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                                  at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                                  at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                                  at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                                  at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                                  at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Note that if you move `Icon` creation out of the `for` loop 
```java
    Icon icon = mIconFactory.fromResource(R.drawable.ic_android_2);
    for (int row = 0; row < rows; row++) {
      for (int col = 0; col < cols; col++) {
          LatLng target = new LatLng(start.getLatitude() + col * 0.001, start.getLongitude() + row * 0.001);
          locations.add(target);

          MarkerOptions markerOptions = new MarkerOptions().position(target).icon(icon).title(String.format(Locale
              .US, "%dx%d", row, col));

          mMarkerOptions.add(markerOptions);
      }
    }
```
or using `MarkerViewOptions` instead of `MarkerOptions`
```java
    for (int row = 0; row < rows; row++) {
          for (int col = 0; col < cols; col++) {
            LatLng target = new LatLng(start.getLatitude() + col * 0.001, start.getLongitude() + row * 0.001);
            locations.add(target);

            MarkerViewOptions markerOptions = new MarkerViewOptions().position(target).icon(mIconFactory.fromResource
              (R.drawable.ic_android_2)).title(String.format(Locale.US, "%dx%d", row, col));

            mMarkerOptions.add(markerOptions);
          }
    }
```
it works fine.

**Comment by Guardiola31337** [comment]
Look #9367 and #9331 

cc/ @ivovandongen @jfirebaugh

**Comment by tobrun** [comment]
Is this crash still reproducible?
