### ISSUE TITLE
CustomLayer crash with GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9380]
On `release-ios-v3.6.0-android-v5.1.0`, our CustomLayer example crashes when adding a CustomLayer to the map. This is only reproducible on a Samsung Galaxy J3 (2016) with Android version 5.1.1. Not showing any issues on Pixel 7.0 / Nexus 5 6.0.

Going to test master and see if I can reproduce the issue there. 
**update**: also on master. 

```
FATAL EXCEPTION: main Process: com.mapbox.mapboxsdk.testapp, 
PID: 7342 java.lang.Error: glGetIntegerv(GL_FRAMEBUFFER_BINDING, & binding): 
Error GL_INVALID_OPERATION at / Users / Nurbot / mapbox - gl - native / src / mbgl / gl / value.cpp: 278
 at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
 at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java: 179)
 at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java: 407)
 at android.view.View.draw(View.java: 16536)
 at android.widget.FrameLayout.draw(FrameLayout.java: 598)
 at android.view.View.updateDisplayListIfDirty(View.java: 15466)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java: 3697)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java: 3676)
 at android.view.View.updateDisplayListIfDirty(View.java: 15426)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java: 3697)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java: 3676)
 at android.view.View.updateDisplayListIfDirty(View.java: 15426)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java: 3697)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java: 3676)
 at android.view.View.updateDisplayListIfDirty(View.java: 15426)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java: 3697)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java: 3676)
 at android.view.View.updateDisplayListIfDirty(View.java: 15426)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java: 3697)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java: 3676)
 at android.view.View.updateDisplayListIfDirty(View.java: 15426)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java: 3697)
 at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java: 3676)
 at android.view.View.updateDisplayListIfDirty(View.java: 15426)
 at android.view.View.getDisplayList(View.java: 15488)
 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java: 309)
 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java: 315)
 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java: 354)
 at android.view.ViewRootImpl.draw(ViewRootImpl.java: 2956)
 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java: 2753)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java: 2339)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java: 1314)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java: 7057)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java: 829)
 at android.view.Choreographer.doCallbacks(Choreographer.java: 606)
 at android.view.Choreographer.doFrame(Choreographer.java: 576)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java: 815)
 at android.os.Handler.handleCallback(Handler.java: 739)
 at android.os.Handler.dispatchMessage(Handler.java: 95)
 at android.os.Looper.loop(Looper.java: 145)
 at android.app.ActivityThread.main(ActivityThread.java: 7007)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java: 372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 1404)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 1199)
```

**Comment by tobrun** [comment]
confirming that this is the same issue as in https://github.com/mapbox/mapbox-gl-native/issues/8448.
