### ISSUE TITLE
out of range destination coordinates for image copy

### ISSUE THREAD

**Issue by chenqingfeid** [mapbox/mapbox-gl-native#9398]
**Platform:Android 
**Mapbox SDK version:5.0.2

### Steps to trigger behavior

 1.Find a place with GPS
 2.Start mapbox 
 3.Crash

**Comment by kkaefer** [comment]
@chenqingfeid can you please describe what you are referring to with "image copy? Do you have backtrace that you could provide us?

**Comment by chenqingfeid** [comment]
com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
2 com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:176)
3 com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:426)
4 android.view.View.draw(View.java:15231)
5 android.widget.FrameLayout.draw(FrameLayout.java:598)
6 android.view.View.updateDisplayListIfDirty(View.java:14167)
7 android.view.View.getDisplayList(View.java:14189)
8 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
9 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
10 android.view.View.updateDisplayListIfDirty(View.java:14127)
11 android.view.View.getDisplayList(View.java:14189)
12 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
13 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
14 android.view.View.updateDisplayListIfDirty(View.java:14127)
15 android.view.View.getDisplayList(View.java:14189)
16 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
17 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
18 android.view.View.updateDisplayListIfDirty(View.java:14127)
19 android.view.View.getDisplayList(View.java:14189)
20 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
21 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
22 android.view.View.updateDisplayListIfDirty(View.java:14127)
23 android.view.View.getDisplayList(View.java:14189)
24 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
25 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
26 android.view.View.updateDisplayListIfDirty(View.java:14127)
27 android.view.View.getDisplayList(View.java:14189)
28 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
29 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
30 android.view.View.updateDisplayListIfDirty(View.java:14127)
31 android.view.View.getDisplayList(View.java:14189)
32 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
33 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
34 android.view.View.updateDisplayListIfDirty(View.java:14127)
35 android.view.View.getDisplayList(View.java:14189)
36 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
37 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
38 android.view.View.updateDisplayListIfDirty(View.java:14127)
39 android.view.View.getDisplayList(View.java:14189)
40 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
41 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
42 android.view.View.updateDisplayListIfDirty(View.java:14127)
43 android.view.View.getDisplayList(View.java:14189)
44 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
45 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
46 android.view.View.updateDisplayListIfDirty(View.java:14127)
47 android.view.View.getDisplayList(View.java:14189)
48 android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
49 android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
50 android.view.View.updateDisplayListIfDirty(View.java:14127)
51 android.view.View.getDisplayList(View.java:14189)
52 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
53 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
54 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
55 android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
56 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
57 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
58 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
59 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
60 android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
61 android.view.Choreographer.doCallbacks(Choreographer.java:580)
62 android.view.Choreographer.doFrame(Choreographer.java:550)
63 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
64 android.os.Handler.handleCallback(Handler.java:739)
65 android.os.Handler.dispatchMessage(Handler.java:95)
66 android.os.Looper.loop(Looper.java:135)
67 android.app.ActivityThread.main(ActivityThread.java:5254)
68 java.lang.reflect.Method.invoke(Native Method)
69 java.lang.reflect.Method.invoke(Method.java:372)
70 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
71 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by chenqingfeid** [comment]
Location Engine onConnected!
06-30 08:02:21.104 5120-5120/com.speedx.s605 E/FusionEngine: Unable to register for network updates.
                                                             java.lang.IllegalArgumentException: provider doesn't exist: network
                                                                 at android.os.Parcel.readException(Parcel.java:1596)
                                                                 at android.os.Parcel.readException(Parcel.java:1545)
                                                                 at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:582)
                                                                 at android.location.LocationManager.requestLocationUpdates(LocationManager.java:867)
                                                                 at android.location.LocationManager.requestLocationUpdates(LocationManager.java:459)
                                                                 at com.mapzen.android.lost.internal.FusionEngine.enableNetwork(FusionEngine.java:154)
                                                                 at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java:112)
                                                                 at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java:45)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.requestLocationUpdates(FusedLocationProviderServiceImpl.java:60)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderService.requestLocationUpdates(FusedLocationProviderService.java:69)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:109)
                                                                 at com.mapbox.mapboxsdk.location.LocationSource.requestLocationUpdates(LocationSource.java:121)
                                                                 at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$GpsLocationListener.onConnected(MyLocationView.java:579)
                                                                 at com.mapbox.mapboxsdk.location.LocationSource.onConnected(LocationSource.java:81)
                                                                 at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:65)
                                                                 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1247)
                                                                 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1264)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
06-30 08:02:21.110 5120-5120/com.speedx.s605 D/Map4MapBox: Location = Location[gps 40.000897,116.483203 acc=7 et=+5m50s809ms alt=88.5 vel=0.0 bear=233.4 {Bundle[mParcelledData.dataSize=40]}]
06-30 08:02:21.125 5120-6382/com.speedx.s605 I/System.out: [socket][/192.168.101.28:36794] connected
06-30 08:02:21.128 5120-5120/com.speedx.s605 E/FusionEngine: Unable to register for network updates.
                                                             java.lang.IllegalArgumentException: provider doesn't exist: network
                                                                 at android.os.Parcel.readException(Parcel.java:1596)
                                                                 at android.os.Parcel.readException(Parcel.java:1545)
                                                                 at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:582)
                                                                 at android.location.LocationManager.requestLocationUpdates(LocationManager.java:867)
                                                                 at android.location.LocationManager.requestLocationUpdates(LocationManager.java:459)
                                                                 at com.mapzen.android.lost.internal.FusionEngine.enableNetwork(FusionEngine.java:154)
                                                                 at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java:112)
                                                                 at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java:45)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.requestLocationUpdates(FusedLocationProviderServiceImpl.java:60)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderService.requestLocationUpdates(FusedLocationProviderService.java:69)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:109)
                                                                 at com.mapbox.mapboxsdk.location.LocationSource.requestLocationUpdates(LocationSource.java:121)
                                                                 at com.mapbox.services.android.telemetry.MapboxTelemetry.onConnected(MapboxTelemetry.java:375)
                                                                 at com.mapbox.mapboxsdk.location.LocationSource.onConnected(LocationSource.java:81)
                                                                 at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
                                                                 at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:65)
                                                                 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1247)
                                                                 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1264)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
06-30 08:02:21.153 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.156 5120-5120/com.speedx.s605 D/GraphicBuffer: register, handle(0xb8237e60) (w:240 h:320 s:256 f:0x1 u:0x000f02)
06-30 08:02:21.170 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.175 5120-6382/com.speedx.s605 D/libc-netbsd: [getaddrinfo]: hostname=api.mapbox.com; servname=(null); cache_mode=(null), netid=0; mark=0
06-30 08:02:21.178 5120-6382/com.speedx.s605 D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
06-30 08:02:21.179 5120-5146/com.speedx.s605 D/GraphicBuffer: register, handle(0xb820e720) (w:240 h:320 s:256 f:0x1 u:0x000f02)
06-30 08:02:21.186 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.221 5120-5133/com.speedx.s605 I/art: Background sticky concurrent mark sweep GC freed 17027(1024KB) AllocSpace objects, 2(32KB) LOS objects, 1% free, 9MB/9MB, paused 15.472ms total 277.100ms
06-30 08:02:21.232 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.240 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.244 5120-5120/com.speedx.s605 D/GraphicBuffer: register, handle(0xb73bcdd8) (w:240 h:320 s:256 f:0x1 u:0x000f02)
06-30 08:02:21.254 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.260 5120-5146/com.speedx.s605 D/GraphicBuffer: register, handle(0xb7261ec0) (w:240 h:320 s:256 f:0x1 u:0x000f02)
06-30 08:02:21.268 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.275 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.277 5120-5120/com.speedx.s605 D/GraphicBuffer: register, handle(0xb830d4e0) (w:240 h:320 s:256 f:0x1 u:0x000f02)
06-30 08:02:21.278 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.285 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.286 5120-5146/com.speedx.s605 D/GraphicBuffer: register, handle(0xb8210740) (w:240 h:320 s:256 f:0x1 u:0x000f02)
06-30 08:02:21.306 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.309 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.315 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.322 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.324 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.331 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.342 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.344 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.352 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.359 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.361 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.376 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.408 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.419 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.424 5120-5128/com.speedx.s605 W/art: Suspending all threads took: 33.296ms
06-30 08:02:21.429 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.435 5120-5133/com.speedx.s605 I/art: Background partial concurrent mark sweep GC freed 2667(123KB) AllocSpace objects, 1(89KB) LOS objects, 17% free, 9MB/11MB, paused 2.059ms total 194.337ms
06-30 08:02:21.455 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.456 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.463 5120-6391/com.speedx.s605 I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
06-30 08:02:21.463 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.466 5120-6391/com.speedx.s605 D/libc-netbsd: [getaddrinfo]: hostname=api.mapbox.com; servname=(null); cache_mode=(null), netid=0; mark=0
06-30 08:02:21.472 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.474 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.482 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.487 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.491 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.498 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.503 5120-6391/com.speedx.s605 D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
06-30 08:02:21.505 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.508 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.513 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.522 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.526 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.533 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.540 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.545 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.555 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.563 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb7cbfd38,w=240,h=320)
06-30 08:02:21.569 5120-6370/com.speedx.s605 I/System.out: [CDS]rx timeout:0
06-30 08:02:21.569 5120-6370/com.speedx.s605 I/System.out: [CDS]rx timeout:0
06-30 08:02:21.572 5120-6391/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:21.576 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.582 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.672 5120-6391/com.speedx.s605 I/System.out: [socket][8] connection api.mapbox.com/13.32.194.37:443;LocalPort=37487(10000)
06-30 08:02:21.674 5120-6391/com.speedx.s605 I/System.out: [CDS]connect[api.mapbox.com/13.32.194.37:443] tm:10
06-30 08:02:21.695 5120-6391/com.speedx.s605 D/Posix: [Posix_connect Debug]Process com.speedx.s605 :443 
06-30 08:02:21.713 5120-6360/com.speedx.s605 I/System.out: [CDS]close[37487]
06-30 08:02:21.716 5120-6391/com.speedx.s605 I/System.out: [socket][9:37487] exception
06-30 08:02:21.718 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.725 5120-5146/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80e6ce0,w=240,h=320)
06-30 08:02:21.817 5120-5120/com.speedx.s605 D/Surface: Surface::setBuffersDimensions(this=0xb80eb560,w=240,h=320)
06-30 08:02:21.835 5120-5120/com.speedx.s605 W/mbgl: {com.speedx.s605}[OpenGL]: Not using Vertex Array Objects
06-30 08:02:21.837 5120-5120/com.speedx.s605 W/mbgl: {com.speedx.s605}[OpenGL]: Not using Vertex Array Objects
06-30 08:02:21.851 5120-5120/com.speedx.s605 D/AndroidRuntime: Shutting down VM
06-30 08:02:21.851 5120-5120/com.speedx.s605 E/CrashReport: Java Crash Happen cause by main(1)
06-30 08:02:21.856 5120-5120/com.speedx.s605 D/Environment: getStorageVolume,  volume:StorageVolume:
                                                                mStorageId=65537 mPath=/storage/sdcard0 mDescriptionId=17040807 
                                                                mPrimary=true mRemovable=false mEmulated=false mMtpReserveSpace=0 
                                                                mAllowMassStorage=true mMaxFileSize=0 mOwner=null mUuid=C00D-07DA 
                                                                mUserLabel=null mState=mounted 
06-30 08:02:21.992 5120-5224/com.speedx.s605 I/SamplingRunner: [Activity AUTO_PAUSED], LastLocation: null
06-30 08:02:22.465 5120-5128/com.speedx.s605 W/art: Suspending all threads took: 63.248ms
06-30 08:02:22.480 5120-6377/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.481 5120-6377/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.608 5120-6382/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.613 5120-6382/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.629 5120-6372/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.630 5120-6372/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.669 5120-6379/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.669 5120-6379/com.speedx.s605 I/System.out: [CDS]rx timeout:10000
06-30 08:02:22.782 5120-5120/com.speedx.s605 I/CrashReport: user log size:0
06-30 08:02:22.783 5120-5120/com.speedx.s605 E/CrashReport: stack frame :71, has cause false
06-30 08:02:22.825 5120-5120/com.speedx.s605 E/CrashReport: #++++++++++Record By Bugly++++++++++#
06-30 08:02:22.825 5120-5120/com.speedx.s605 E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
06-30 08:02:22.825 5120-5120/com.speedx.s605 E/CrashReport: # PKG NAME: com.speedx.s605
06-30 08:02:22.825 5120-5120/com.speedx.s605 E/CrashReport: # APP VER: debug-1.0.8
06-30 08:02:22.826 5120-5120/com.speedx.s605 E/CrashReport: # LAUNCH TIME: 2017-06-30 08:00:46
06-30 08:02:22.826 5120-5120/com.speedx.s605 E/CrashReport: # CRASH TYPE: JAVA_CRASH
06-30 08:02:22.826 5120-5120/com.speedx.s605 E/CrashReport: # CRASH TIME: 2017-06-30 08:02:22
06-30 08:02:22.826 5120-5120/com.speedx.s605 E/CrashReport: # CRASH PROCESS: com.speedx.s605
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: # CRASH THREAD: main
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: # REPORT ID: 61a911cb-6642-45c0-8f24-42dfbef73e59
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: # CRASH DEVICE: coretek2601_wp_l ROOTED
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: # RUNTIME AVAIL RAM:302571520 ROM:1079816192 SD:4954914816
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: # RUNTIME TOTAL RAM:491769856 ROM:1445314560 SD:5227413504
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: # CRASH STACK: 
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: java.lang.Error: out of range destination coordinates for image copy
                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:176)
                                                                at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:426)
                                                                at android.view.View.draw(View.java:15231)
                                                                at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14167)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
                                                                at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
                                                                at android.view.View.updateDisplayListIfDirty(View.java:14127)
                                                                at android.view.View.getDisplayList(View.java:14189)
                                                                at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
                                                                at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                            	at android.view.Choreographer.d
06-30 08:02:22.829 5120-5120/com.speedx.s605 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
06-30 08:02:22.862 5120-5120/com.speedx.s605 D/CrashReport: [Database] deleted t_lr data 1
06-30 08:02:22.910 5120-5120/com.speedx.s605 D/CrashReport: [Database] insert t_lr success.

**Comment by chenqingfeid** [comment]
Repaired，thanks!
