### ISSUE TITLE
Adding CustomLayer results in GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9444]
On master, when running the custom layer activity in the test app on a Samsung S6 Edge/Samsung J3/emulator and toggling the custom layer to be shown:

> java.lang.Error: vertexArray->bindVertexArray(value): Error GL_INVALID_OPERATION at /home/tvn/Mapbox/mapbox-gl-native/src/mbgl/gl/value.cpp:347 at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method) at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:158) at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:416) at android.view.View.draw(View.java:18318)

**Comment by tobrun** [comment]
duplicate of #8448
