### ISSUE TITLE
Android crash on style change

### ISSUE THREAD

**Issue by thomas-huet** [mapbox/mapbox-gl-native#945]
Test of e07e9807325aee0cf74382d2326928d563ceab38 on android:
The application crashes when I try to select another style

```
F/libc    (27698): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 27743 (ox.mapboxgl.app)
I/DEBUG   (  180): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  180): Build fingerprint: 'google/razor/flo:5.0.2/LRX22G/1649326:user/release-keys'
I/DEBUG   (  180): Revision: '0'
I/DEBUG   (  180): ABI: 'arm'
I/DEBUG   (  180): pid: 27698, tid: 27743, name: ox.mapboxgl.app  >>> com.mapbox.mapboxgl.app <<<
I/DEBUG   (  180): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
I/DEBUG   (  180):     r0 0000000c  r1 9ffa2d4c  r2 00000000  r3 0000000c
I/DEBUG   (  180):     r4 a3551040  r5 0000000c  r6 00000000  r7 a3df8750
I/DEBUG   (  180):     r8 a3549308  r9 a3df8768  sl 00000000  fp a3df875c
I/DEBUG   (  180):     ip a3df7198  sp 9ffa2d38  lr a3b6aea0  pc a3cf12cc  cpsr a00e0010
I/DEBUG   (  180): 
I/DEBUG   (  180): backtrace:
I/DEBUG   (  180):     #00 pc 002b42cc  /data/app/com.mapbox.mapboxgl.app-2/lib/arm/libmapbox-gl.so
I/DEBUG   (  180):     #01 pc 0012de9c  /data/app/com.mapbox.mapboxgl.app-2/lib/arm/libmapbox-gl.so (uv__zip_error+28)
I/DEBUG   (  180):     #02 pc 002a2f88  /data/app/com.mapbox.mapboxgl.app-2/lib/arm/libmapbox-gl.so
I/DEBUG   (  180):     #03 pc 002a48ec  /data/app/com.mapbox.mapboxgl.app-2/lib/arm/libmapbox-gl.so
I/DEBUG   (  180):     #04 pc 000162e3  /system/lib/libc.so (__pthread_start(void*)+30)
I/DEBUG   (  180):     #05 pc 000142d3  /system/lib/libc.so (__start_thread+6)
W/debuggerd(  180): type=1400 audit(0.0:116): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=7753 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
W/debuggerd(  180): type=1400 audit(0.0:117): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=7753 scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file
I/DEBUG   (  180): 
I/DEBUG   (  180): Tombstone written to: /data/tombstones/tombstone_09
W/ActivityManager(  535):   Force finishing activity com.mapbox.mapboxgl.app/.MainActivity
I/BootReceiver(  535): Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
W/InputDispatcher(  535): channel '3fd65f73 com.mapbox.mapboxgl.app/com.mapbox.mapboxgl.app.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  535): channel '3fd65f73 com.mapbox.mapboxgl.app/com.mapbox.mapboxgl.app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
V/GmsNetworkLocationProvi(31979): onSetRequest: ProviderRequestUnbundled, reportLocation is true and interval is 86400000
V/GmsNetworkLocationProvi(31979): SET-REQUEST
V/GmsNetworkLocationProvi(31979): in Handler: ProviderRequestUnbundled, reportLocation is true and interval is 86400000
E/SharedPreferencesImpl(  535): Couldn't create directory for SharedPreferences file shared_prefs/log_files.xml
I/WindowState(  535): WIN DEATH: Window{1a559a24 u0 SurfaceView}
I/WindowState(  535): WIN DEATH: Window{3fd65f73 u0 com.mapbox.mapboxgl.app/com.mapbox.mapboxgl.app.MainActivity}
W/InputDispatcher(  535): Attempted to unregister already unregistered input channel '3fd65f73 com.mapbox.mapboxgl.app/com.mapbox.mapboxgl.app.MainActivity (server)'
I/Zygote  (  195): Process 27698 exited due to signal (11)
W/ActivityManager(  535): Exception thrown during pause
W/ActivityManager(  535): android.os.DeadObjectException
W/ActivityManager(  535): 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  535): 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  535): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:701)
W/ActivityManager(  535): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:852)
W/ActivityManager(  535): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2754)
W/ActivityManager(  535): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2611)
W/ActivityManager(  535): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2453)
W/ActivityManager(  535): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11511)
W/ActivityManager(  535): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11408)
W/ActivityManager(  535): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12087)
W/ActivityManager(  535): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11603)
W/ActivityManager(  535): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
E/lowmemorykiller(  174): Error opening /proc/27698/oom_score_adj; errno=2
I/ActivityManager(  535): Process com.mapbox.mapboxgl.app (pid 27698) has died

```

**Comment by ljbade** [comment]
@kkaefer I thought we had fixed the uv zip problems?

**Comment by ljbade** [comment]
Related to https://github.com/mapbox/mapbox-gl-native/issues/863?

**Comment by thomas-huet** [comment]
No more crashes when switching styles.
