### ISSUE TITLE
Crash on map click from AnnotationManager

### ISSUE THREAD

**Issue by cvance** [mapbox/mapbox-gl-native#9584]
**Platform:** Android 7.0
**Mapbox SDK version:** 5.1.1

### Steps to trigger behavior

 1. Single tap on map anywhere

### Actual behavior

App crashes with following stacktrace:

`java.lang.NumberFormatException: For input string: ""
                                                       at java.lang.Long.parseLong(Long.java:455)
                                                       at java.lang.Long.valueOf(Long.java:542)
                                                       at com.mapbox.mapboxsdk.maps.AnnotationManager$ShapeAnnotationHitResolver.execute(AnnotationManager.java:729)
                                                       at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:651)
                                                       at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:318)
                                                       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by tobrun** [comment]
Thank you for the report, haven't seen this crash with regular testing using the testapp and our base styles. In this case a query for features was done but the feature returned didn't include an id. I assumed id was required but the geojson spec doesn't enforce this:

>If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number.

Will add a fix, to be included with next patch release.

**Comment by tobrun** [comment]
I'm a bit curious about the setup you have in place for reproducing this issue. For querying the map we only use layers that where added through addPolygon/addPolyline. 
```java
mapboxMap.queryRenderedFeatures(shapeHit.tapPoint, shapeHit.layerIds)
```

I'm going to harden the integration though the crash in OP shouldn't happen in normal use-cases.

**Comment by tobrun** [comment]
@cvance feel free to test out the 5.1.2-SNAPSHOT with the fix.

**Comment by cvance** [comment]
Will do! Thanks!

**Comment by cvance** [comment]
Looks good to me! Thanks once again for the quick response and fix!
