### ISSUE TITLE
Null pointer exception on  

### ISSUE THREAD

**Issue by jiyeh** [mapbox/mapbox-gl-native#9603]
**Platform:** Android 5.1, 6.0
**Mapbox SDK version:** 5.1.0

We are experiencing this NPE crash on v5.1.0.

### Here is the stack trace:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
       at com.mapbox.services.android.telemetry.MapboxTelemetry.getBatteryLevel(MapboxTelemetry.java:244)
       at com.mapbox.services.android.telemetry.MapboxTelemetry.pushEvent(MapboxTelemetry.java:474)
       at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:190)
       at ninjavan.swiftninja.views.slidingtab.layouts.MapTab.onCreateView(MapTab.java:193)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17915)
       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2731)
       at android.view.View.measure(View.java:17915)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2413)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1415)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1639)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1293)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6599)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

**Comment by tobrun** [comment]
Thank you for the report, I opened a ticket in the downstream repo to fix this.
