### ISSUE TITLE
Fatal Exception: java.lang.Error: program failed to link

### ISSUE THREAD

**Issue by henriquemelissopoulos** [mapbox/mapbox-gl-native#9635]
**Platform:** Android
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior
Open an activity with a MapView, but only one user had this problem so far, his device is a Sony Experia M - C2004 with Android 4.2.2. I already tested on several other devices with this same app build but I couldn't replicate this issue.

I'm talking to the user who have these crashs and I think I'll test a build without proguard with him.

### Expected behavior
Show the map.

### Actual behavior
Crash with the following report:

```
Fatal Exception: java.lang.Error: program failed to link
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Unknown Source)
       at com.mapbox.mapboxsdk.maps.NativeMapView.render(Unknown Source)
       at com.mapbox.mapboxsdk.maps.MapView.onDraw(Unknown Source)
       at android.view.View.draw(View.java:13806)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:12736)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2911)
       at android.view.View.getDisplayList(View.java:12674)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2911)
       at android.view.View.getDisplayList(View.java:12674)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2911)
       at android.view.View.getDisplayList(View.java:12674)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2911)
       at android.view.View.getDisplayList(View.java:12674)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2911)
       at android.view.View.getDisplayList(View.java:12674)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2911)
       at android.view.View.getDisplayList(View.java:12674)
       at android.view.View.getDisplayList(View.java:12780)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1210)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2177)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2049)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4372)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5085)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tobrun** [comment]
Thank you for the detailed report!

> I'm talking to the user who have these crashs and I think I'll test a build without proguard with him.

Would you be able to test with 5.1.1? This patch update contained a couple of fixes related to this.

**Comment by philemonmerlet** [comment]
Hello, we have the same problem (exactly same trace) with mapbox 5.1.3. The device is a Samsung Galaxy Ace 3 running Android 4.2.2.
Should I open a new issue ?

**Comment by mrfaa** [comment]
Experienced also the error:
```
Fatal Exception: java.lang.Error program failed to link
com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender (NativeMapView.java)
com.mapbox.mapboxsdk.maps.NativeMapView.render (NativeMapView.java:179)
```

com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3@aar
Galaxy Ace3

**Comment by mrfaa** [comment]
Friendly ping @jfirebaugh @tobrun any progress on this issue?

**Comment by nehm39** [comment]
We have the same crash on Xperia L with Android 4.2.2.
Can we receive a fix for this?

**Comment by levyschiavetti** [comment]
Still getting this crash, mostly in Sony devices apparently 
do we have a fix for this?

**Comment by j05u3** [comment]
I also experience this crash:
`compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar'){
        transitive=true
    }`

http://crashes.to/s/0174eb5a998

**Comment by Romamo** [comment]
Still crashing on Sony Xperia L C2105 4.2.2
Platform: Android
Mapbox SDK version: 6.4.0

08-17 11:33:47.047 12226-12226/com.demo D/libEGL: loaded /system/lib/egl/libEGL_adreno200.so
    loaded /system/lib/egl/libGLESv1_CM_adreno200.so
08-17 11:33:47.107 12226-12226/com.demo D/libEGL: loaded /system/lib/egl/libGLESv2_adreno200.so
08-17 11:33:47.117 12226-12226/com.demo I/Adreno200-EGL: <qeglDrvAPI_eglInitialize:265>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_2.5.04.02.02.040.400_msm8960_JB_2.5_CL3744273_release_AU (CL3744273)
    Build Date: 06/30/13 Sun
    Local Branch: 
    Remote Branch: quic/jb_2.5
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_JB_2.5.04.02.02.040.400 +  NOTHING
08-17 11:33:47.267 12226-12226/com.demo D/OpenGLRenderer: Enabling debug mode 0
08-17 11:33:47.327 12226-12226/com.demo I/dalvikvm: Could not find method android.view.View.setTooltipText, referenced from method android.support.v7.widget.TooltipCompat.setTooltipText
08-17 11:33:47.327 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 24382: Landroid/view/View;.setTooltipText (Ljava/lang/CharSequence;)V
08-17 11:33:47.327 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.327 12226-12226/com.demo I/dalvikvm: Could not find method android.view.ViewConfiguration.getScaledHorizontalScrollFactor, referenced from method android.support.v4.view.ViewConfigurationCompat.getScaledHorizontalScrollFactor
08-17 11:33:47.327 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 24406: Landroid/view/ViewConfiguration;.getScaledHorizontalScrollFactor ()F
08-17 11:33:47.327 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.327 12226-12226/com.demo I/dalvikvm: Could not find method android.view.ViewConfiguration.getScaledHoverSlop, referenced from method android.support.v4.view.ViewConfigurationCompat.getScaledHoverSlop
08-17 11:33:47.327 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 24407: Landroid/view/ViewConfiguration;.getScaledHoverSlop ()I
08-17 11:33:47.327 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.327 12226-12226/com.demo I/dalvikvm: Could not find method android.view.ViewConfiguration.getScaledVerticalScrollFactor, referenced from method android.support.v4.view.ViewConfigurationCompat.getScaledVerticalScrollFactor
08-17 11:33:47.327 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 24412: Landroid/view/ViewConfiguration;.getScaledVerticalScrollFactor ()F
08-17 11:33:47.327 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.327 12226-12226/com.demo I/dalvikvm: Could not find method android.view.ViewConfiguration.shouldShowMenuShortcutsWhenKeyboardPresent, referenced from method android.support.v4.view.ViewConfigurationCompat.shouldShowMenuShortcutsWhenKeyboardPresent
08-17 11:33:47.327 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 24415: Landroid/view/ViewConfiguration;.shouldShowMenuShortcutsWhenKeyboardPresent ()Z
08-17 11:33:47.327 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.638 12226-12333/com.demo I/mbgl: {Thread-8246}[General]: GPU Identifier: Adreno (TM) 305
08-17 11:33:47.638 12226-12333/com.demo W/mbgl: {Thread-8246}[OpenGL]: Not using Vertex Array Objects
08-17 11:33:47.878 12226-12226/com.demo I/dalvikvm: Could not find method android.content.res.Resources.getColor, referenced from method com.mapbox.mapboxsdk.utils.ColorUtils.getColorCompat
08-17 11:33:47.878 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 1667: Landroid/content/res/Resources;.getColor (ILandroid/content/res/Resources$Theme;)I
08-17 11:33:47.878 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x000e
08-17 11:33:47.888 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.applyTheme, referenced from method android.support.v4.graphics.drawable.DrawableCompat.applyTheme
08-17 11:33:47.888 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2920: Landroid/graphics/drawable/Drawable;.applyTheme (Landroid/content/res/Resources$Theme;)V
08-17 11:33:47.888 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.888 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.canApplyTheme, referenced from method android.support.v4.graphics.drawable.DrawableCompat.canApplyTheme
08-17 11:33:47.888 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2921: Landroid/graphics/drawable/Drawable;.canApplyTheme ()Z
08-17 11:33:47.888 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.888 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.InsetDrawable.getDrawable, referenced from method android.support.v4.graphics.drawable.DrawableCompat.clearColorFilter
08-17 11:33:47.888 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 3011: Landroid/graphics/drawable/InsetDrawable;.getDrawable ()Landroid/graphics/drawable/Drawable;
08-17 11:33:47.888 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x001a
08-17 11:33:47.888 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.DrawableContainer$DrawableContainerState.getChild, referenced from method android.support.v4.graphics.drawable.DrawableCompat.clearColorFilter
08-17 11:33:47.888 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2982: Landroid/graphics/drawable/DrawableContainer$DrawableContainerState;.getChild (I)Landroid/graphics/drawable/Drawable;
08-17 11:33:47.898 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0048
08-17 11:33:47.898 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.getAlpha, referenced from method android.support.v4.graphics.drawable.DrawableCompat.getAlpha
08-17 11:33:47.898 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2928: Landroid/graphics/drawable/Drawable;.getAlpha ()I
08-17 11:33:47.898 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.898 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.getColorFilter, referenced from method android.support.v4.graphics.drawable.DrawableCompat.getColorFilter
08-17 11:33:47.898 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2932: Landroid/graphics/drawable/Drawable;.getColorFilter ()Landroid/graphics/ColorFilter;
08-17 11:33:47.898 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.898 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.inflate, referenced from method android.support.v4.graphics.drawable.DrawableCompat.inflate
08-17 11:33:47.898 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2949: Landroid/graphics/drawable/Drawable;.inflate (Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;Landroid/util/AttributeSet;Landroid/content/res/Resources$Theme;)V
08-17 11:33:47.908 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.908 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.isAutoMirrored, referenced from method android.support.v4.graphics.drawable.DrawableCompat.isAutoMirrored
08-17 11:33:47.908 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2951: Landroid/graphics/drawable/Drawable;.isAutoMirrored ()Z
08-17 11:33:47.908 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.908 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setAutoMirrored, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setAutoMirrored
08-17 11:33:47.908 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2963: Landroid/graphics/drawable/Drawable;.setAutoMirrored (Z)V
08-17 11:33:47.908 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.918 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setHotspot, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setHotspot
08-17 11:33:47.918 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2972: Landroid/graphics/drawable/Drawable;.setHotspot (FF)V
08-17 11:33:47.918 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.918 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setHotspotBounds, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setHotspotBounds
08-17 11:33:47.918 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2973: Landroid/graphics/drawable/Drawable;.setHotspotBounds (IIII)V
08-17 11:33:47.918 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.918 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setLayoutDirection, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setLayoutDirection
08-17 11:33:47.918 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2974: Landroid/graphics/drawable/Drawable;.setLayoutDirection (I)Z
08-17 11:33:47.918 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.918 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setTint, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setTint
08-17 11:33:47.918 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2977: Landroid/graphics/drawable/Drawable;.setTint (I)V
08-17 11:33:47.918 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.918 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setTintList, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setTintList
08-17 11:33:47.918 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2978: Landroid/graphics/drawable/Drawable;.setTintList (Landroid/content/res/ColorStateList;)V
08-17 11:33:47.918 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.918 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setTintMode, referenced from method android.support.v4.graphics.drawable.DrawableCompat.setTintMode
08-17 11:33:47.918 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2979: Landroid/graphics/drawable/Drawable;.setTintMode (Landroid/graphics/PorterDuff$Mode;)V
08-17 11:33:47.918 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
08-17 11:33:47.928 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.isAutoMirrored, referenced from method android.support.v4.graphics.drawable.WrappedDrawableApi14.isAutoMirrored
08-17 11:33:47.928 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2951: Landroid/graphics/drawable/Drawable;.isAutoMirrored ()Z
08-17 11:33:47.928 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
08-17 11:33:47.928 12226-12226/com.demo I/dalvikvm: Could not find method android.graphics.drawable.Drawable.setAutoMirrored, referenced from method android.support.v4.graphics.drawable.WrappedDrawableApi14.setAutoMirrored
08-17 11:33:47.928 12226-12226/com.demo W/dalvikvm: VFY: unable to resolve virtual method 2963: Landroid/graphics/drawable/Drawable;.setAutoMirrored (Z)V
08-17 11:33:47.928 12226-12226/com.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
08-17 11:33:48.038 12226-12305/com.demo W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
08-17 11:33:48.048 12226-12305/com.demo W/dalvikvm: VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
08-17 11:33:48.048 12226-12305/com.demo I/dalvikvm: Could not find method java.nio.file.Files.newOutputStream, referenced from method okio.Okio.sink
08-17 11:33:48.048 12226-12305/com.demo W/dalvikvm: VFY: unable to resolve static method 44564: Ljava/nio/file/Files;.newOutputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/OutputStream;
08-17 11:33:48.048 12226-12305/com.demo D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a
08-17 11:33:48.048 12226-12305/com.demo W/dalvikvm: VFY: unable to find class referenced in signature (Ljava/nio/file/Path;)
    VFY: unable to find class referenced in signature ([Ljava/nio/file/OpenOption;)
08-17 11:33:48.048 12226-12305/com.demo I/dalvikvm: Could not find method java.nio.file.Files.newInputStream, referenced from method okio.Okio.source
08-17 11:33:48.048 12226-12305/com.demo W/dalvikvm: VFY: unable to resolve static method 44563: Ljava/nio/file/Files;.newInputStream (Ljava/nio/file/Path;[Ljava/nio/file/OpenOption;)Ljava/io/InputStream;
08-17 11:33:48.048 12226-12305/com.demo D/dalvikvm: VFY: replacing opcode 0x71 at 0x000a
08-17 11:33:56.507 12226-12333/com.demo E/mbgl: {Thread-8246}[Shader]: Program failed to link: --From Vertex Shader:
    Error: Symbol u_is_text defined with different precision in vertex and fragment shaders.
    --From Fragment Shader:
    Error: Symbol u_is_text defined with different precision in vertex and fragment shaders.
08-17 11:33:56.607 12226-12333/com.demo W/dalvikvm: threadid=19: thread exiting with uncaught exception (group=0x41891ae0)
08-17 11:33:56.617 12226-12333/com.demo E/AndroidRuntime: FATAL EXCEPTION: GLThread 8246
    java.lang.Error: program failed to link
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
        at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by msh91** [comment]
Still Crashing, here is the report:
Devices: 
Sony 79% :  XPERIA L, XPERIA M dual, XPERIA XA
Samsung 14% : Galaxy A3(2016), Galaxy Grand Prime, G620F, Core 2
Huawei 4% : P8 Lite

OS:
Android 4: 90%
Android 7: 6%
Android 5: 2%


`Fatal Exception: java.lang.Error: program failed to link
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(MapRenderer.java)
       at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
       at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

**Comment by msh91** [comment]
> Still Crashing, here is the report:
> Devices:
> Sony 79% : XPERIA L, XPERIA M dual, XPERIA XA
> Samsung 14% : Galaxy A3(2016), Galaxy Grand Prime, G620F, Core 2
> Huawei 4% : P8 Lite
> 
> OS:
> Android 4: 90%
> Android 7: 6%
> Android 5: 2%
> 
> `Fatal Exception: java.lang.Error: program failed to link at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(MapRenderer.java) at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74) at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57) at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516) at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

Mapbox version : 6.4.0

**Comment by msh91** [comment]
Still crashing
Devices: Xperia M, Xperia L c2105
Mapbox: 6.7.0

Crash report:
`{Thread-943}[Shader]: Program failed to link: --From Vertex Shader:
    Error: Symbol u_is_text defined with different precision in vertex and fragment shaders.
    --From Fragment Shader:
    Error: Symbol u_is_text defined with different precision in vertex and fragment shaders.
E/AndroidRuntime: FATAL EXCEPTION: GLThread 943
    java.lang.Error: program failed to link
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
        at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:58)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`
