### ISSUE TITLE
Error when click on map with features

### ISSUE THREAD

**Issue by rodrigoyleila** [mapbox/mapbox-gl-native#9652]
**EVENT START**
        mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
            @Override
            public void onMapClick(@NonNull LatLng point) {
                Log.i(TAG, "punto mapa " + point  );
                markerclick(point);
                Log.i(TAG, "punto mapa " + point  );
            }
        });
**EVENT END**

**FUNCTION CLICK START**
    public void markerclick(@NonNull LatLng point) 
{
        try 
{
            Feature feature = null;
            final PointF pixel = mapboxMap.getProjection().toScreenLocation(point);
            List<Feature> features = mapboxMap.queryRenderedFeatures(pixel);
            mapboxMap.removeImage("marker-seleccionado");
            if (features.size() == 1)
            {
                feature = features.get(0);
                mapboxMap.addImage("marker-seleccionado", BitmapFactory.decodeResource(funciones._actividad.getResources(), pins.getResourceId(feature.getProperty("c_img").getAsInt(), 0)));
            }
            final SymbolLayer camada_seleccionada = (SymbolLayer) mapboxMap.getLayer("selected-marker-layer");
            List<Feature> selectedFeature = mapboxMap.queryRenderedFeatures(pixel, "selected-marker-layer");
            if (selectedFeature.size() > 0 && markerSelected) {
                return;
            }
            if (features.isEmpty())
            {
                if (markerSelected)
                {
                    deselectMarker(camada_seleccionada);
                }
                return;
            }

            if(feature!= null)
            {
                FeatureCollection featureCollection = FeatureCollection.fromFeatures(
                        new Feature[]{Feature.fromGeometry(feature.getGeometry())});
                GeoJsonSource source = mapboxMap.getSourceAs("selected-marker");
                if (source != null) {
                    source.setGeoJson(featureCollection);
                }
                selectMarker(camada_seleccionada, feature.getProperties(), (Position) feature.getGeometry().getCoordinates());

            }

            if (markerSelected) {
                deselectMarker(camada_seleccionada);
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
**FUNCTION CLICK END**

**FUNCTION THAT GENERATE GSON MARKERS - START**

    private String add_puntos_sin_mover() {

        M_Propiedad consultas = new M_Propiedad(funciones);
        String sql_propiedades = consultas.sql_propiedades_inmuebles_residentes(
                null
                , where_tp_prop
                , where_status_inmueble
                , where_visita_inmueble
                , where_tp_residente
                , where_idioma_residente

        );

        try {
            crear_camada_marker_seleccionado();
            JSONObject gson = funciones._CRUD.retorna_GeoJson(sql_propiedades);
            if(gson != null && gson.length() > 0)
            {
                String string_gson = gson.toString();
                String GeoJsonSource        = "residentes";
                String clusters             = "cluster";
                String contador             = "count";
                String name_img_marker;
                String unclustered_points;

                GeoJsonSource gsonvalues = new GeoJsonSource(GeoJsonSource,
                        string_gson,
                        new GeoJsonOptions()
                                .withCluster(true)
                                .withClusterMaxZoom(O_Constantes.setMaxClusteringZoomLevel)
                                .withClusterRadius(O_Constantes.radiusMarkerClusterer)
                );

                mapboxMap.addSource(gsonvalues);

                for(int indice_markers=0; indice_markers<=14;indice_markers++)
                {
                    //Creating a marker layer for single data points
                    if(string_gson.contains("\"c_img\":\""+indice_markers+"\""))
                    {
                        unclustered_points  = "unclustered-points_" + indice_markers;
                        name_img_marker     = "marker_residentes_" + indice_markers;
                        mapboxMap.addImage(name_img_marker, BitmapFactory.decodeResource(funciones._actividad.getResources(), pins.getResourceId(indice_markers,0)));

                        SymbolLayer unclustered = new SymbolLayer(unclustered_points, GeoJsonSource);

                        unclustered.setProperties(
                                iconImage(name_img_marker)
                        );

                        unclustered.setFilter(
                                eq("c_img", ""+indice_markers)
                        );

                        mapboxMap.addLayer(unclustered);

                    }
                }
                int[][] layers = new int[][]{
                        new int[]{100, ContextCompat.getColor(funciones._actividad, R.color.deslizar_1)},
                        new int[]{50, ContextCompat.getColor(funciones._actividad, R.color.deslizar_2)},
                        new int[]{0, ContextCompat.getColor(funciones._actividad, R.color.deslizar_3)}
                };

                for (int i = 0; i < layers.length; i++)
                {
                    //Add clusters' circles
                    CircleLayer circles = new CircleLayer(clusters + "-" + i, GeoJsonSource);
                    circles.setProperties(
                            circleColor(layers[i][1]),
                            circleRadius(15f)
                    );

                    // Add a filter to the cluster layer that hides the circles based on "point_count"
                    circles.setFilter(
                            i == 0
                                    ? gte("point_count", layers[i][0]) :
                                    all(gte("point_count", layers[i][0]), lt("point_count", layers[i - 1][0]))
                    );
                    mapboxMap.addLayer(circles);
                }

                //Add the count labels
                SymbolLayer count = new SymbolLayer(contador, GeoJsonSource);
                count.setProperties(
                        textField("{point_count}"),
                        textSize(12f),
                        textColor(Color.WHITE)
                );
                mapboxMap.addLayer(count);

                return O_Constantes.b_true;
            }
            return O_Constantes.b_false;

        } catch (Exception e) {
            e.printStackTrace();
            return O_Constantes.b_false;
        }
    }
**FUNCTION THAT GENERATE GSON MARKERS - END**

**ERRORS BEGIN**

07-31 08:06:57.105 31741-31741/com.mapsjw.territorio E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.mapsjw.territorio, PID: 31741
                                                                       java.lang.NumberFormatException: For input string: ""
                                                                           at java.lang.Long.parseLong(Long.java:602)
                                                                           at java.lang.Long.valueOf(Long.java:804)
                                                                           at com.mapbox.mapboxsdk.maps.AnnotationManager$ShapeAnnotationHitResolver.execute(AnnotationManager.java:729)
                                                                           at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:651)
                                                                           at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:318)
                                                                           at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-31 08:06:57.107 31741-31741/com.mapsjw.territorio E/ACRA: ACRA caught a NumberFormatException for com.mapsjw.territorio
                                                             java.lang.NumberFormatException: For input string: ""
                                                                 at java.lang.Long.parseLong(Long.java:602)
                                                                 at java.lang.Long.valueOf(Long.java:804)
                                                                 at com.mapbox.mapboxsdk.maps.AnnotationManager$ShapeAnnotationHitResolver.execute(AnnotationManager.java:729)
                                                                 at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:651)
                                                                 at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:318)
                                                                 at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**ERROS END**

**Platform:ANDROID 8.0 DEVELOPER PREVIEW 4**
**Mapbox SDK version:5.1.1**

_On Mapbox SDK version 5.1.0 works my code_

**Comment by tobrun** [comment]
Thanks for the report! This has been fixed with https://github.com/mapbox/mapbox-gl-native/pull/9606, feel free to test out our 5.1.2-SNAPSHOT with this fix. We are aiming at releasing 5.1.2 this week. Closing as this issue has already been resolved.

**Comment by rodrigoyleila** [comment]
Thank you!
