### ISSUE TITLE
std::exception

### ISSUE THREAD

**Issue by jetadore** [mapbox/mapbox-gl-native#9680]
**Platform:** android
**Mapbox SDK version:** 5.2.0-SNAPSHOT

### Steps to trigger behavior

 1. Dynamic Add/Remove Marker in Multi Thread 
 2. then throw Exception in native and app exit
```
13038-14570 W/System.err: java.lang.Error: std::exception
13038-14570 W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddMarkers(Native Method)
13038-14570 W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.addMarker(NativeMapView.java:418)
13038-14570 W/System.err:     at com.mapbox.mapboxsdk.maps.MarkerContainer.addViewBy(MarkerContainer.java:148)
13038-14570 W/System.err:     at com.mapbox.mapboxsdk.maps.AnnotationManager.addMarker(AnnotationManager.java:202)
13038-14570 W/System.err:     at com.mapbox.mapboxsdk.maps.MapboxMap.addMarker(MapboxMap.java:1196)
```

**Comment by tobrun** [comment]
@jetadore all invocations on MapboxMap should occur on the main thread.
