### ISSUE TITLE
Crash on map click of a symbol layer

### ISSUE THREAD

**Issue by sun2008mt** [mapbox/mapbox-gl-native#9693]
**Platform:Android 6.0
**Mapbox SDK version:5.1.1

### Steps to trigger behavior

 1.Single tap on a symbol layer (using addImage() method to add icon sources)
 2. It's OK on version 5.1.0.

### Expected behavior
OnMapClickListener() can listen to the event

### Actual behavior
OnMapClickListener() can't listen to the event. After tapping app crashes directly with following stacktrace:
java.lang.NumberFormatException: Invalid long: ""
                                                                         at java.lang.Long.invalidLong(Long.java:124)
                                                                         at java.lang.Long.parseLong(Long.java:345)
                                                                         at java.lang.Long.parseLong(Long.java:321)
                                                                         at java.lang.Long.valueOf(Long.java:511)
                                                                         at com.mapbox.mapboxsdk.maps.AnnotationManager$ShapeAnnotationHitResolver.execute(AnnotationManager.java:729)
                                                                         at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:651)
                                                                         at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:318)
                                                                         at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5524)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by tobrun** [comment]
This is fixed with 5.1.2 that was released yesterday. Closing as resolved.
