### ISSUE TITLE
Android App crashes:  call to OpenGL ES API with no current context + eglSwapBuffers() failed

### ISSUE THREAD

**Issue by uburoiubu** [mapbox/mapbox-gl-native#9737]
Is there any solution to this? App crashes systematically. And the debugging is not that helpful.

```
08-09 14:42:57.260 27784-27784/work.phobos.flagman E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
08-09 14:42:57.260 27784-27784/work.phobos.flagman E/mbgl: {.phobos.flagman}[OpenGL]: eglSwapBuffers() returned error 12294
08-09 14:42:57.851 27784-27784/work.phobos.flagman E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: work.phobos.flagman, PID: 27784
                                                                     java.lang.Error: eglSwapBuffers() failed
                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
                                                                         at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:179)
                                                                         at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:407)
                                                                         at android.view.View.draw(View.java:16536)
                                                                         at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15466)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3697)
                                                                         at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3676)
                                                                         at android.view.View.updateDisplayListIfDirty(View.java:15426)
                                                                         at android.view.View.getDisplayList(View.java:15488)
                                                                         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:309)
                                                                         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:315)
                                                                         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:354)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:2956)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2753)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2339)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:576)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6934)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by tobrun** [comment]
Thank you for reaching out, this has already been ticketed in #6647. Closing as a duplicate.
