### ISSUE TITLE
Crash on Android 4.4.4

### ISSUE THREAD

**Issue by MilkBiscuit** [mapbox/mapbox-gl-native#9879]
**Platform:** Android 4.4.4 Genymotion simulator 
**Mapbox SDK version:** 5.1.2

### Steps to trigger behavior

 1. Try to show MapFragment which is a child of com.mapbox.mapboxsdk.maps.SupportMapFragment 

### Actual behavior
1. Crash

`08-28 23:09:07.616 6596-6596/com.agrimap.mobile.android E/FusionEngine: Unable to register for network updates.
java.lang.IllegalArgumentException: provider doesn't exist: network
    at android.os.Parcel.readException(Parcel.java:1469)
    at android.os.Parcel.readException(Parcel.java:1419)
    at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
    at android.location.LocationManager.requestLocationUpdates(LocationManager.java:860)
    at android.location.LocationManager.requestLocationUpdates(LocationManager.java:454)
    at com.mapzen.android.lost.internal.FusionEngine.enableNetwork(FusionEngine.java:109)
    at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java:73)
    at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java:36)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:50)
    at com.mapbox.mapboxsdk.location.LocationSource.requestLocationUpdates(LocationSource.java:123)
    at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$GpsLocationListener.onConnected(MyLocationView.java:776)
    at com.mapbox.mapboxsdk.location.LocationSource.activate(LocationSource.java:57)
    at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:543)
    at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(MyLocationView.java:487)
    at com.mapbox.mapboxsdk.maps.TrackingSettings.setMyLocationEnabled(TrackingSettings.java:380)
    at com.mapbox.mapboxsdk.maps.TrackingSettings.setMyLocationEnabled(TrackingSettings.java:369)
    at com.mapbox.mapboxsdk.maps.TrackingSettings.initialise(TrackingSettings.java:52)
    at com.mapbox.mapboxsdk.maps.MapboxMap.initialise(MapboxMap.java:96)
    at com.mapbox.mapboxsdk.maps.MapView.initialise(MapView.java:168)
    at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:93)
    at com.mapbox.mapboxsdk.maps.SupportMapFragment.onCreateView(SupportMapFragment.java:66)
    at com.agrimap.mobile.android.paddock.ui.MapFragment.onCreateView(MapFragment.java:189)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
    at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2270)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1381)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
    at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
    at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2034)
    at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
    at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
    at android.view.View.measure(View.java:16497)
	at android.widget.LinearLayout.measureVertical(Linea
08-28 23:09:07.632 6596-6596/com.agrimap.mobile.android E/mbgl: {.mobile.android}[OpenGL]: eglChooseConfig(NULL) returned error 12288`

**Comment by MilkBiscuit** [comment]
Works on Android 5.1,  6.0, 7.0
Only crashes on Android 4.4.4

Might be the same issue with https://github.com/mapbox/mapbox-gl-native/issues/9878  , but crash log looks different.

**Comment by tobrun** [comment]
Thank you for the report @MilkBiscuit. This crash is related using an older version of the LOST location dependency which isn't handling if the device doesn't have a network provider. Note that non-virtual machine devices do have this provider enabled so I'm not seeing this as a big issue. This is going to be fixed with https://github.com/mapbox/mapbox-gl-native/issues/9581.
