### ISSUE TITLE
Crash when tapping on marker twice.

### ISSUE THREAD

**Issue by tonyc10** [mapbox/mapbox-gl-native#9924]
I have map with two Markers, added to the Mapbox map with the following code:

```
        // start and end pins
        val pinA = IconFactory.getInstance(this).fromResource(R.drawable.pin_a)
        val pinB = IconFactory.getInstance(this).fromResource(R.drawable.pin_b)

        map.addMarker(MarkerOptions().setPosition(pointA()).setIcon(pinA))
        map.addMarker(MarkerOptions().setPosition(pointB()).setIcon(pinB))
```
The markers look fine, and I expect no action or Info window when they are clicked.  However, whenever a Marker is clicked twice, the app crashes, with the following Stack trace:

UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.mapboxsdk.annotations.Marker.isInfoWindowShown()' on a null object reference
                                                                             at com.mapbox.mapboxsdk.maps.AnnotationManager.deselectMarker(AnnotationManager.java:384)
                                                                             at com.mapbox.mapboxsdk.maps.AnnotationManager.toggleMarkerSelectionState(AnnotationManager.java:718)
                                                                             at com.mapbox.mapboxsdk.maps.AnnotationManager.isClickHandledForMarker(AnnotationManager.java:705)
                                                                             at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:661)
                                                                             at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:318)
                                                                             at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)

Any workaround would be greatly appreciated.  
I have tried adding empty title and snippet, adding an onMarkerClickedListener, and saving the Marker references as class variables -- but none of them prevents the crash.

In fact, I also get an IllegalArgumentException in Kotlin for passing a null value (the marker) to onMarkerClick() which is specified as non-null.

Any help is appreciated!

**Platform:**
Android 7.1 . Nexus 5x.

**Mapbox SDK version:**
mapbox-android-sdk:5.1.2

**Comment by tobrun** [comment]
@tonyc10 
I haven't been able to reproduce this issue with the code from `5.1.3`:

![ezgif com-video-to-gif 34](https://user-images.githubusercontent.com/2151639/30273475-682f1d04-96f9-11e7-9fc7-2ddddd6d2ce2.gif)

Do you have any more information on how to reproduce the crash?
