### ISSUE TITLE
Fragment not attached to Activity error on OfflineDownloadManager

### ISSUE THREAD

**Issue by Mickey-Livesgood** [mapbox/mapbox-gl-native#9958]
I have a "download manager" activity in my app.
This activity has two fragments, the first for downloading regions, and the second for viewing and deleting already downloaded regions.
I was using OfflineManagerActivity.java in the Mapbox Demo as a reference.
The fragments are basically a ListView with the ability to click on an item and download/delete (and in the case of download - display a progress bar).
Right now, the download region (kyoto) is hardcoded until I am able to finish that part of the code (later it will get the data from the ListView adapter).

However, sometimee going launching the DownloadManager activity, or clicking on a ListView item and starting download, and even once randomly when I was on the MainActivity (a bit after finishing download) the app crashes and I get the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                   Process: com.livesgoodapps.alpha, PID: 15652
                                   java.lang.IllegalStateException: Fragment DownloadedFragment{2ab00a1b} not attached to Activity
                                        at android.support.v4.app.Fragment.getResources(Fragment.java:687)
                                        at android.support.v4.app.Fragment.getString(Fragment.java:709)
                                        at com.livesgoodapps.alpha.DownloadedFragment$3$1$1.onDelete(DownloadedFragment.java:118)
                                        at com.mapbox.mapboxsdk.offline.OfflineRegion$3$1.run(OfflineRegion.java:367)
                                        at android.os.Handler.handleCallback(Handler.java:739)
                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                        at android.os.Looper.loop(Looper.java:135)
                                        at android.app.ActivityThread.main(ActivityThread.java:5349)
                                        at java.lang.reflect.Method.invoke(Native Method)
                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

This usually happens after I download a region and

This is the code for the "Download" Fragment:
```

public class DownloadFragment extends Fragment {

    private ListView downloadListView;
    private OfflineManager offlineManager;
    private ProgressBar progressBar;
    private MapView mapView;
    private MapboxMap map;
    private OfflineRegion offlineRegion;

    // cities definitions
    private OfflineTilePyramidRegionDefinition kyotoDefinition;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.download_list, container, false);

        // set up list
        downloadListView = (ListView) rootView.findViewById(R.id.download_list_view);
        DownloadAdapter downloadAdapter = new DownloadAdapter(getContext(),new String[]{"test 1","test 2","test 3"});
        downloadListView.setAdapter(downloadAdapter);

        progressBar = (ProgressBar) rootView.findViewById(R.id.progress_bar);

        // Set up the OfflineManager
        offlineManager = OfflineManager.getInstance(getActivity());

        // Update definitions
        defineOfflineRegions();

        // Set up the MapView
        mapView = (MapView) rootView.findViewById(R.id.download_mapview);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                map = mapboxMap;
            }
        });

        downloadListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                downloadRegionDialog("test");
            }
        });





        return rootView;
    }


    private void downloadRegion(final String regionName) {
        // Define offline region parameters, including bounds,
        // min/max zoom, and metadata

        // Start the progressBar
        startProgress();

        // Create the offline region and launch the download
        offlineManager.createOfflineRegion(kyotoDefinition, Data.kyotoMetadata, new OfflineManager.CreateOfflineRegionCallback() {
            @Override
            public void onCreate(OfflineRegion offlineRegion) {
                Log.d(TAG, "Offline region created: " + regionName);
                DownloadFragment.this.offlineRegion = offlineRegion;
                launchDownload();
            }

            @Override
            public void onError(String error) {
                Log.e(TAG, "Error: " + error);
            }
        });
    }

    private void launchDownload() {
        // Set up an observer to handle download progress and
        // notify the user when the region is finished downloading
        offlineRegion.setObserver(new OfflineRegion.OfflineRegionObserver() {
            @Override
            public void onStatusChanged(OfflineRegionStatus status) {
                // Compute a percentage
                double percentage = status.getRequiredResourceCount() >= 0
                        ? (100.0 * status.getCompletedResourceCount() / status.getRequiredResourceCount()) :
                        0.0;

                if (status.isComplete()) {
                    // Download complete
                    Toast.makeText(getActivity(),"Download Completed",Toast.LENGTH_SHORT).show();
                    return;
                } else if (status.isRequiredResourceCountPrecise()) {
                    // Switch to determinate state
                    setPercentage((int) Math.round(percentage));
                }

                // Log what is being currently downloaded
                Log.d(TAG, String.format("%s/%s resources; %s bytes downloaded.",
                        String.valueOf(status.getCompletedResourceCount()),
                        String.valueOf(status.getRequiredResourceCount()),
                        String.valueOf(status.getCompletedResourceSize())));
            }

            @Override
            public void onError(OfflineRegionError error) {
                Log.e(TAG, "onError reason: " + error.getReason());
                Log.e(TAG, "onError message: " + error.getMessage());
            }

            @Override
            public void mapboxTileCountLimitExceeded(long limit) {
                Log.e(TAG, "Mapbox tile count limit exceeded: " + limit);
                Toast.makeText(getActivity(),"Download limit exceeded", Toast.LENGTH_SHORT).show();
            }
        });

        // Change the region state
        offlineRegion.setDownloadState(OfflineRegion.STATE_ACTIVE);
    }

    // Progress bar methods
    private void startProgress() {
        // Start and show the progress bar
        progressBar.setIndeterminate(true);
        progressBar.setVisibility(View.VISIBLE);
    }

    private void defineOfflineRegions() {

        kyotoDefinition = generateDefinition(Data.kyotoBounds);


    }

    private void setPercentage(final int percentage) {
        progressBar.setIndeterminate(false);
        progressBar.setProgress(percentage);
    }


    private OfflineTilePyramidRegionDefinition generateDefinition(LatLngBounds bounds) {
        return new OfflineTilePyramidRegionDefinition(Data.styleURL, bounds, 10, 18, getActivity().getResources().getDisplayMetrics().density);
    }

    private void downloadRegionDialog(final String regionName) {
        // Set up download interaction. Display a dialog
        // when the user clicks download button and require
        // a user-provided region name
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());

        // Build the dialog box
        builder.setTitle(getString(R.string.download_dialog_title))
                .setPositiveButton(getString(R.string.download_dialog_positive_button), new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        downloadRegion(regionName);
                    }
                })
                .setNegativeButton(getString(R.string.download_dialog_negative_button), new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.cancel();
                    }
                });

        // Display the dialog
        builder.show();
    }

}
```

And this is the "Downloaded" Fragment:

```
public class DownloadedFragment extends Fragment {

    private ListView downloadListView;
    private OfflineManager offlineManager;
    private ProgressBar progressBar;
    private MapView mapView;
    private MapboxMap map;
    private OfflineRegion offlineRegion;
    private DownloadedAdapter downloadedAdapter;


    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.download_list, container, false);

        // set up list
        downloadListView = (ListView) rootView.findViewById(R.id.download_list_view);

        // progress bar
        progressBar = (ProgressBar) rootView.findViewById(R.id.progress_bar);
        progressBar.setVisibility(View.INVISIBLE);

        // Set up the MapView
        mapView = (MapView) rootView.findViewById(R.id.download_mapview);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                map = mapboxMap;
            }
        });

        // Set up the OfflineManager
        offlineManager = OfflineManager.getInstance(getActivity());

        // fill up the list
        downloadedRegionList();

        downloadListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

            }
        });

        return rootView;
    }



    private void downloadedRegionList() {
        // Build a region list

        // Query the DB asynchronously
        offlineManager.listOfflineRegions(new OfflineManager.ListOfflineRegionsCallback() {
            @Override
            public void onList(final OfflineRegion[] offlineRegions) {
                // Check result. If no regions have been
                // downloaded yet, notify user and return
                if (offlineRegions == null || offlineRegions.length == 0) {
                    Toast.makeText(getApplicationContext(), getString(R.string.toast_no_regions_yet), Toast.LENGTH_SHORT).show();
                    return;
                }

                // Add all of the region names to a list
                ArrayList<String> offlineRegionsNames = new ArrayList<>();
                for (OfflineRegion offlineRegion : offlineRegions) {
                    offlineRegionsNames.add(getRegionName(offlineRegion));
                }
                String[] regionsArray = offlineRegionsNames.toArray(new String[offlineRegionsNames.size()]);
                //final CharSequence[] items = offlineRegionsNames.toArray(new CharSequence[offlineRegionsNames.size()]);

                // set up the list
                downloadedAdapter = new DownloadedAdapter(getContext(),regionsArray);
                downloadListView.setAdapter(downloadedAdapter);


                // set on click delete
                downloadListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        // Begin the deletion process
                        offlineRegions[position].delete(new OfflineRegion.OfflineRegionDeleteCallback() {
                            @Override
                            public void onDelete() {
                                Toast.makeText(getApplicationContext(), getString(R.string.toast_region_deleted),
                                        Toast.LENGTH_LONG).show();
                            }

                            @Override
                            public void onError(String error) {
                                Log.e(TAG, "Error: " + error);
                            }
                });
            }

        });
    }

            @Override
            public void onError(String error) {
                Log.e(TAG, "Error: " + error);
            }


            private String getRegionName(OfflineRegion offlineRegion) {
            // Get the region name from the offline region metadata
            String regionName;

            try {
                byte[] metadata = offlineRegion.getMetadata();
                String json = new String(metadata, Data.JSON_CHARSET);
                JSONObject jsonObject = new JSONObject(json);
                regionName = jsonObject.getString(Data.JSON_FIELD_REGION_NAME);
            } catch (Exception exception) {
                Log.e(TAG, "Failed to decode metadata: " + exception.getMessage());
                regionName = getString(R.string.region_name);
            }
            return regionName;
        }
    });
    }
    }

```

Sorry for long code here...

Would love some help on this issue. I believe it somehow connected to the download thread but I'm not sure why this is happening.
Thanks!

**Comment by tobrun** [comment]
The issue stems from using an component that has a lifecycle that doesn't match the duration of your download. The advised way of doing an offline download is through a foreground Service (this also allows you to show progress in a notification). If you make that service bind-able you can also show progress in your activity/fragment directly (an example of this UX is shown in Google Play while you are downloading an app).

Alternatively you can also get away by using a headless retained fragment. Fwiw we are working on an offline plugin that will make integration of offline maps way more easy https://github.com/mapbox/mapbox-plugins-android/pull/72. We are aiming to have a SNAPSHOT available for testing asap. Going to close this as this isn't an issue with the SDK code but the way the download is managed in your code.
