### ISSUE TITLE
Unknown pbf field type exception

### ISSUE THREAD

**Issue by YShein** [mapbox/mapbox-gl-native#9969]
Hello, i received this issue from fabric. 

Fatal Exception: java.lang.Error: unknown pbf field type exception
       at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(NativeMapView.java)
       at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:179)
       at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:407)
       at android.view.View.draw(View.java:15239)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at android.view.View.updateDisplayListIfDirty(View.java:14175)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.updateDisplayListIfDirty(View.java:14170)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.View.draw(View.java:14967)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3411)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
       at android.view.View.draw(View.java:15242)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2655)
       at android.view.View.updateDisplayListIfDirty(View.java:14175)
       at android.view.View.getDisplayList(View.java:14197)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2547)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2363)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1993)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1072)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5959)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5438)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Platform: kyocera Brigadier, android 5.0
Mapbox SDK version: 5.1.1

**Comment by kkaefer** [comment]
Can you please provide more background on what you were doing with the SDK? Did you load in a custom style/source? Under what circumstance did this bug occur?

**Comment by YShein** [comment]
@kkaefer I am using custom style. I set it in onMapReady. 
I don't have any steps to reproduce, sorry

**Comment by mikemorris** [comment]
This error is often associated with attempting to parse uncompressed vector tiles when gzipped vector tiles are expected, or vice versa. Are you using a custom or offline tile source @YShein?

**Comment by YShein** [comment]
We are using airmap tile source.

**Comment by jfirebaugh** [comment]
This is an issue with your tiles, or with how they are being served. As @mikemorris said, the most common cause is serving gzip-compressed tiles without a `Content-Encoding: gzip` response header.

**Comment by jackcjp** [comment]
Try this: data = zlib.unzipSync(data);
